In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

/home/christine/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [3]:
from selenium.webdriver.chrome.service import Service
s = Service(r"/usr/bin/chromedriver")

# Observations

In [99]:
import json
import copy
driver = webdriver.Chrome(service=s)
driver.get("https://flatheadavalanche.org/avalanche-forecast/#/archive")
html = driver.page_source

In [100]:
import json
import copy
import time
weather_df = pd.DataFrame()
forms = []

In [101]:
year = 2024

In [ ]:
n = 0
while(True):
    driver.implicitly_wait(20)
    html = driver.page_source
    soup = BeautifulSoup(html, 'html.parser')
    new_form, new_weather = parse_zone_forecast_html(html)
    if new_form in forms:
        break
    else:
        forms.append(copy.deepcopy(new_form))
        weather_df = pd.concat([weather_df, new_weather])
    button = driver.find_element(By.CSS_SELECTOR, '.nac-html-button.nac-btn.nac-btn-light.nac-btn-lg.has-tooltip')
    button.click()
    time.sleep(20)
    n+=1
    print(len(forms))
    print(new_form)
    print('\n')
    pd.DataFrame(forms).to_csv(f'/home/christine/Jupyter/snow/data/fac_forecast_{int(year-1)}_{int(year)}.csv')
    weather_df.to_csv(f'/home/christine/Jupyter/snow/data/fac_weather_{int(year-1)}_{int(year)}.csv')

1
{'author': 'Mark Dundas', 'date': '2024-03-17', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 1, 'likelihood': 'possible', 'size': ['Large (D2)', '', 'Very Large (D3)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': 'Avoid traveling in avalanche terrain today. The likelihood of spontaneous large and very large avalanches makes steep terrain and avalanche runouts very dangerous. Heat and radiation are destabilizing hard slabs perched on deeply buried weak layers. These layers are widespread but variable in strength, making it impossible to determine which slopes will fail and when they will fail.  Multiple large hard slab avalanches occurred Friday and Saturday in Glacier Park and the Flathead Range and likely failed on buried weak layers above an early February crust. Debris from these slides can run the full length of avalanche paths, making surviving one of these events nearly impossible.\xa0 \xa0'}, {'problem_type': ' Cornice Fall', 'problem_number': 3, 'likelihood': 'likely', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': 'Impressive southwest winds built large cornices along alpine ridgelines in late February/early March. Intense warming this weekend may weaken these features. A failing cornice can send large blocks of snow trundling downhill, potentially triggering a destructive avalanche.\xa0 The nature of this problem is highly unpredictable and should warrant your respect. Give these whales a wide berth above and below a corniced ridgeline to reduce your risk. Don’t get surprised by a cornice breaking further back than expected. '}, {'problem_type': ' Wet Loose', 'problem_number': 2, 'likelihood': 'very likely', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'south', 'southwest', 'west', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'south', 'southwest', 'west', 'northwest'], 'lower': ['north', 'northeast', 'east', 'southeast', 'south', 'southwest', 'west', 'northwest']}, 'discussion': 'Today will be unseasonably warm, leading to another day of wet snow instabilities. Over the past three days, rollerballs and loose snow slides have occurred on sunny aspects. This problem has expanded to include the northern aspects, where previously dry snow is becoming wet.\xa0 Mushy snow that does not support your weight or machine is a sign you could trigger a loose slide. Although the debris is relatively small, these slides can pack a punch in chutes or gullies, where escape may be difficult. Be aware of the terrain above you and where an avalanche could carry you.\xa0 These small avalanches can trigger\xa0a much larger\xa0avalanche\xa0lower on the slope. Continued warm temperatures combined with a poor overnight freeze allow meltwater to drain to weak layers deeper in the snowpack, making wet slab avalanches possible.\xa0'}], 'bottom_line': 'An Avalanche Warning is in effect in all zones of our advisory area. Very dangerous avalanche conditions exist today and will likely continue during a period of prolonged warming. Avoid traveling in avalanche terrain today.', 'discussion': 'We are continuing an Avalanche Warning for the Swan Range, the Whitefish Range, the Flathead Range, and portions of Glacier National Park through 0600 tomorrow (Monday). If conditions dictate, we may extend this warning to Tuesday. As of Sunday mid-morning, temperatures at many mid- and upper-elevation stations had been above freezing for 48 hours, reaching 50F at two upper-elevation stations yesterday.\nThe abnormally warm temperatures triggered deep hard slab avalanches on shaded slopes and thinner slabs on sunny aspects. Friday, the BNSF Avalanche Safety Team reported 3 large slab avalanches observed from Highway 2. Cam observed a D2.5 hard slab avalanche on a northwest aspect of Great Northern, and outside our forecast region, Rob viewed several large slab avalanches on sunny aspects of the Swan Crest near Condon. Saturday, blase observed multiple slab avalanches in the eastern portion of the advisory area, while Rob and I noted slides in the mountains around Lake McDonald. WMR patrol closed all their avalanche terrain as the day warmed. \nOur multi-day warming raises the risk of wet slab avalanches. Melting surface snow produces water that drains into the snowpack and may eventually reach the ground unless an impediment like a thick crust or weak layer is encountered. Here, the meltwater pools and increases the chance of releasing a wet slab avalanche. The meltwater production occurs faster on sunny slopes, where there are more crusts to interrupt the draining process. The general rule of thumb regarding this process is that three nights without a freeze are needed for meltwater production to drain into the snowpack. If forecasted temperatures materialize, we may begin seeing wet slab activity in the next day or two, although timing these is difficult.\xa0\nPlanning an early exit and choosing low-angle terrain free of overhead hazards are ways to manage your risk in the face of uncertainty. If you observe avalanche activity, submit an observation to let us know what you are seeing. '}


2
{'author': 'Sarah Williams', 'date': '2024-03-16', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 1, 'likelihood': 'possible', 'size': ['Large (D2)', '', 'Very Large (D3)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': 'Avoid traveling in avalanche terrain today. The likelihood of spontaneous large and very large avalanches makes steep terrain and avalanche runouts very dangerous today. Heat and radiation are destabilizing hard slabs perched on deeply buried weak layers. These layers are widespread but variable in strength, making it difficult to impossible to determine which slopes will fail and when. Debris from these slides can run the full length of avalanche paths. You are unlikely to survive getting hit by one of these beasts. The usual tests and terrain management practices are woefully inadequate in these conditions.'}, {'problem_type': ' Cornice Fall', 'problem_number': 3, 'likelihood': 'likely', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': 'Impressive southwest winds built large cornices along alpine ridgelines in late February/early March. Intense warming this weekend is weakening these features. A failing cornice can send large blocks of snow trundling downhill. These can be dangerous in themselves. They can also trigger destructive avalanches that fail on deeply buried weak layers.\xa0 The nature of this problem is highly unpredictable and should warrant your respect. Give these whales a wide berth above and below a corniced ridgeline to reduce your risk. Don’t get surprised by a cornice breaking further back than expected. '}, {'problem_type': ' Wet Loose', 'problem_number': 2, 'likelihood': 'very likely', 'size': ['Small (D1)', '', 'Large (D2)', '', 'Very Large (D3)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'south', 'southwest', 'west', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'south', 'southwest', 'west', 'northwest'], 'lower': ['north', 'northeast', 'east', 'southeast', 'south', 'southwest', 'west', 'northwest']}, 'discussion': 'Overnight temperatures stayed above freezing at many mid- and upper-elevation stations, and today’s temperatures will climb higher than the past few days. Wet snow avalanche hazards will become more widespread and destructive, and they may include shaded aspects that have previously held dry snow.\xa0 Pinwheels or rollerballs indicate the snow surface is softening, and loose snow avalanches may soon follow. Avoid exposing yourself to this problem in terrain with overhead hazards. Avoid traveling above terrain traps, where debris can pile up deep, and in long-running gullies, where escape may be difficult.'}], 'bottom_line': 'An Avalanche Warning is in effect in all zones of our advisory area. Very dangerous avalanche conditions exist today, and will likely continue during a period of prolonged warming. Avoid traveling in avalanche terrain today.', 'discussion': 'Ready or not, the heat is on for this weekend. We have issued an Avalanche Warning for the Swan Range, the Whitefish Range, the Flathead Range, and parts of Glacier National Park from 6 am today through 6 am tomorrow (Sunday). Remote weather stations have recorded above-freezing temperatures since yesterday, creating a lack of refreezing overnight. Heat and radiation destabilize thick, hard slabs, weaken cornices, and create widespread areas of wet surface snow.\nWe are most concerned about hard slab avalanches failing on buried weak layers. This Persistent Slab problem is unpredictable, and the consequences of getting caught in this type of slide are deadly. Observations from yesterday (Friday) included the BNSF Avalanche Safety Team’s report of 3 large slab avalanches observed from Highway 2. FAC Forecaster Cam observed a D2.5 hard slab avalanche on a northwest aspect of Great Northern. Outside of our forecast region, Rob, FAC Forecaster, viewed several large slab avalanches on the west, southwest, and south aspects of the Swan Crest.\xa0 These slides likely failed in the late afternoon yesterday.\xa0\nNatural and triggered avalanches involving wet surface snow are very likely on both sunny and shady slopes. We expect widespread wet loose activity today. Additionally, this heat wave will weaken ridgeline cornices and increase the likelihood of them unexpectedly breaking and subsequently triggering large to very large avalanches on the slopes below.\xa0 Planning an early exit and choosing low-angle terrain are ways to manage your risk in the face of uncertainty. If you observe avalanche activity, let us know what you are seeing by submitting an observation. '}

3
{'author': 'Rob Millspaugh', 'date': '2024-03-15', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 1, 'likelihood': 'possible', 'size': ['Large (D2)', '', 'Very Large (D3)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': "Warming temperatures will stress buried weak layers and could result in very large avalanches that break 2-4 feet below the surface. Several faceted crusts have been documented on NW-N-SE aspects above 5000'.\xa0 These layers are not always reactive in stability tests and can give the impression of being benign or stable. The deepest layers consist of rounding facets near a stout crust formed in early February. During a wind-loading event two weeks ago, this layer produced a cycle of very large avalanches in the Flathead Range. Give steep, shaded slopes a wide margin.\xa0 Recognize that small surface slides or cornice falls have the potential to trigger more destructive avalanches on buried weak layers.\xa0"}, {'problem_type': ' Cornice Fall', 'problem_number': 3, 'likelihood': 'possible', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': "Since mid-February, prevailing southwesterly winds have built large, overhanging cornices on slopes facing NW-N-E-SE. These giants will weaken during today's sun and warmth and can fail naturally or when approached by a rider. They often break much further back than you would expect. Whether you're on it or below it, a tumbling chuck of cornice is enough to ruin your day.\xa0 Cornice fall can also trigger large and destructive avalanches on buried weak layers, as described above in the Persistent Slab problem. Do not linger on or under slopes with cornice looming overhead. Give them a wide berth as you navigate ridgelines.\xa0"}, {'problem_type': ' Wet Loose', 'problem_number': 2, 'likelihood': 'likely', 'size': ['Small (D1)', '', 'Large (D2)', '', 'Very Large (D3)'], 'aspect_elevation': {'upper': ['east', 'southeast', 'south', 'southwest', 'west', 'northwest'], 'middle': ['east', 'southeast', 'south', 'southwest', 'west', 'northwest'], 'lower': ['east', 'southeast', 'south', 'southwest', 'west', 'northwest']}, 'discussion': 'Today starts a bit warmer and is expected to be clearer than yesterday.\xa0 A series of crusts may delay the onset or limit the extent of wet loose activity on solar aspects. Slopes sheltered from the sun may still have 4-12 inches of dry snow that will rapidly transition to wet. Rollerballs and snow falling from the trees are early signs of impending wet loose activity.  Small point releases can entrain significant amounts of snow and travel further than expected, especially when sliding on one of several crusts in the snowpack. While slow-moving, an avalanche of this nature will be hard to escape and could easily push you over cliffs or into trees. Limit your risk by choosing slopes that are more shaded and/or less steep, free from overhead hazards.'}], 'bottom_line': 'Danger will rise today due to rapid warming and intense sunshine. Large avalanches may occur naturally and run long distances. Move off of and out from under steep slopes during the heat of the day.\xa0', 'discussion': "Yesterday's wet loose action was more fizzle than sizzle. Today should bring on the heat in earnest, though crusts from previous warming could still limit the extent of today’s activity. Our last prolonged warming occurred late January into early February and resulted in a widespread avalanche cycle on a buried weak layer. Very large hard slabs failed early during the warming, followed by a cycle of wet slabs. That same event yielded the stout 2/3 crust.\nSince then, a layer of facets near the 2/3 crust has produced sporadic action in our advisory area and beyond. It has also caused fatalities North, West, and South of our region. As we enter a period of prolonged warming, the stage is set for increased activity on buried weak layers, in addition to typical springtime problems like wet loose and cornice fall.\nAvalanche Canada is painted red today, and all zones are expected to reach HIGH avalanche danger this weekend. Large human-triggered avalanches occurred near Fernie this week. Areas North have received more snow recently, and buried weak layers have been generally more reactive from the onset. Still, the slew of accidents and fatalities across the northwest US and Canada are a good reason to default to conservative terrain choices. Today, make it less about riding big terrain and more about laying in that base tan."}


4
{'author': 'Guy Zoellner', 'date': '2024-03-14', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 2, 'likelihood': 'possible', 'size': ['Large (D2)', '', 'Very Large (D3)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': 'NW-N-SE aspects above 6,000’ still harbor a weak layer of facets above a crust.\xa0 This combo is identifiable by digging down 2-4 feet until you find a thick and supportable crust. It is not always reactive in stability tests and can give the impression of being benign or stable.\xa0 It is, however, a low-frequency/high-consequence scenario. Natural and human-triggered avalanches have been reported on this layer within the last week. A common theme is that every time this weak layer is tested by a dramatic change to the snowpack (i.e. warming or loading), it has produced D2-D3 avalanches. Shallow, rocky, or convex parts of the slope are places to avoid.\xa0 Enjoy good snow on more gentle terrain or ribs between bigger slopes. Cornices have developed over the last several weeks. Any of these monsters that warm, sag and fall onto the slope below could be a likely trigger for a hard slab avalanche.\xa0 Move quickly out of paths that have large cornices looming above them.'}, {'problem_type': ' Wet Loose', 'problem_number': 1, 'likelihood': 'likely', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['southeast', 'south', 'southwest', 'west'], 'middle': ['southeast', 'south', 'southwest', 'west'], 'lower': ['southeast', 'south', 'southwest', 'west']}, 'discussion': 'What skied well yesterday (Wednesday) will become a problem today. The 4-12 inches of dry snow that rests above a crust on W-S-SE aspects will become wet and slide as the sun warms the snow surface. Steep slopes that are directly exposed to the sun will be the first to manifest this problem. Rollerballs or snow falling out of the trees are your first clue that the surface snow is changing. Small point releases can entrain large amounts of snow and travel further than you expect, especially when sliding on one of several crusts in the snowpack. While slow-moving, an avalanche of this nature will be hard to escape and could easily push you over cliffs or into trees. Limit your risk by choosing slopes that are more shaded and/or less steep.'}], 'bottom_line': 'Warm temperatures and direct sun will create dangerous avalanche conditions today. Rollerballs and snow falling out of trees are your clue that a wet loose avalanche cycle is starting. You can still trigger large avalanches on shaded slopes. Ridgelines and gentle terrain will provide the safest conditions and best opportunities for stunning views today.', 'discussion': 'It’s all about trade-offs. Just when the forecast area seemed to be filled in and skiing/riding great, the clouds part and give way to warming temperatures and changing problems.\xa0\nThe tricky part about the next few days is going to be managing wet snow and the lingering danger of persistent weak layers. As the snow on the sunny slopes transitions to wet, you will be forced onto more polar aspects. This shaded terrain still harbors several faceted crusts. Hard slabs failing on persistent weak layers have been well documented in the Whitefish Range and the Flathead Range over the last few weeks. We haven’t received any reports of natural or triggered avalanches in the Swan Range on these layers. Tuesday, an avalanche that failed on a buried weak layer, likely formed in early February, claimed the life of a backcountry skier near Lost Trail Pass south of Missoula.\nWith the sunset of the winter season just around the corner, we will have to hunt out the last powder stashes. As these get more affected by the warm weather, we’ll be driven to the precise slopes that harbor the recipe for large avalanches. Keep this in mind as FOMO begins to influence our decision-making.\nAs we transition into springtime travel, recall the cast of spring problems. Cornices that have grown over the last several weeks will begin to weaken due to sun and warm temperatures.\xa0 Limit your time underneath these hazards and stay well back from the edge while on ridgelines.'}

5
{'author': 'Jeff Metsky', 'date': '2024-03-13', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 1, 'likelihood': 'possible', 'size': ['Large (D2)', '', 'Very Large (D3)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': "It is easy to fall into a sense of complacency with a Persistent Slab problem. Although we haven’t seen a natural persistent slab avalanche cycle recently, it is important to maintain conservative terrain choices, even when the instability appears unreactive. The potential to trigger a large to very large avalanche is possible if you find a thinner part of the slab on top of the February 3rd crust/facet combo. Signs of instability are inconsistent, creating a problem that may be difficult to manage. You may or may not see recent avalanches during your travels, or cracking/collapsing before triggering a slope. In addition, it could be the 1st, 2nd, or 10th person on the slope that triggers an avalanche that fails on the buried weak layer.\xa0 The February 3 crust/facet combo is buried 2 to 4 feet below the snow surface. Another facet/crust exist about 1 foot below the surface and was the culprit for a few human-triggered avalanches last week.\xa0 The safest way to manage this Persistent Slab problem is to choose slopes with lower slope angles and ones that aren't in the runout of large avalanche paths.\xa0"}, {'problem_type': ' Wind Slab', 'problem_number': 2, 'likelihood': 'possible', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': 'Southwesterly winds have been strong enough to drift snow into thin slabs near and below ridgelines at mid and upper elevations on NW-N-E-SE aspects. Though shallow, these slabs could be reactive as they will have formed over a variety of weak surfaces. Signs of Wind Slabs include textured surfaces or hollow-sounding snow under your board or snowmachine. Look to identify and avoid terrain features where wind slabs may form. Examples include steep slopes (>35 degrees) with overhanging cornices, deposition zones with convex rollovers, and smooth wind pillows. These slabs may be small but have the potential to knock you off your feet and send you downslope into more consequential terrain. The worst-case scenario would be for a small wind slab to step down to a Very Large and dangerous Persistent Slab.\xa0'}], 'bottom_line': 'Recent snow and strong winds thickened slabs above weak layers that caused very large natural avalanches last week. You may not get feedback like cracking or collapsing before triggering a destructive avalanche. Today, sticking to slopes 30 degrees or less will help to minimize your risk.', 'discussion': 'Yesterday, (Tuesday) freezing levels reached roughly 6000 feet. Cooler temps overnight should keep the wet snow problem off the list for one more day. Recent wind speeds were strong enough to transport new and recent snow across the forecast area.\xa0\xa0\nYou may not see signs of instability or recent avalanches but still trigger a potentially destructive avalanche. Conditions become more complex as you climb in elevation. If you choose to travel on NW-N-E-SE aspects, consider the overlapping problems at mid and upper elevations. These are the places where conservative terrain choices: (ex. <35 degrees, deep snowpack, planar slopes) will help you make it home to ride another day.\nDigging a snowpit or probing the snow to identify weak layers below you are helpful, but realize this is only one data point on a slope, and your results can be different only a few feet away. How these buried layers will react to the weight of a rider or machine is difficult to predict. Yesterday, (Tuesday) Guy and I visited the site of a human-triggered avalanche in the Southern Whitefish Range (obs). The rider triggered a large avalanche (D2.5) on the February 3 crust. Judging by a set of tracks near the crown, it appeared that the rider hit a thin part of the slab, which likely triggered the avalanche. Fortunately, no one was caught or carried in this avalanche.\xa0 Identifying thin spots on a slope is nearly impossible at times.\xa0\nAs we move into a period of drier and warmer temperatures over the next couple of days, the potential for wet snow avalanches will increase at all elevations. Shallow wet loose avalanches may run quickly and farther than you expect on top of recently formed crusts. Consider adjusting travel times as activity will increase in the afternoon hours.\xa0'}


6
{'author': 'Cam Johnson', 'date': '2024-03-12', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 1, 'likelihood': 'possible', 'size': ['Large (D2)', '', 'Very Large (D3)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': 'New snow and wind are loading the same slopes that produced Large (D2) and Very Large (D3) naturals last week. A small avalanche may step down to weak layers buried 2 to 4+ feet deep, causing an unsurvivable slide. The safest option for riding is to give steep slopes a wide margin for error today. Choose simple terrain away from the runouts of large avalanche paths.\xa0 Another faceted crust buried 1 to 2 feet down is the culprit for human-triggered avalanches in the Whitefish Range, and is found in the Flathead and Swan Ranges. Avalanche activity on this layer is more focused on south and east aspects.\xa0'}, {'problem_type': ' Wind Slab', 'problem_number': 2, 'likelihood': 'likely', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': '\xa0Give wind-loaded terrain a wide margin today in areas favored by recent snowfall. Slabs will be thicker and more dangerous along ridge crests and where winds funnel through terrain features. Visual clues of a Wind Slab are dune-shaped drifts and textured surfaces. Shooting cracks are indicators the slab is ripe for triggering in steep terrain. It may be possible to trigger a slab avalanche in terrain sheltered from the wind that received more than 8 inches of recent snow. Recent snow may rest on recently formed weak layers. Avalanches failing at the new/old snow interface may break wider than you expect.\xa0\xa0'}], 'bottom_line': 'Give avalanche-prone terrain a wide margin for error today, especially as you climb in elevation. Avalanches in the new snow may trigger a thicker, more dangerous avalanche. Safe options for riding are on slopes 30 degrees or less. Avoid dawdling in the runouts of large avalanche paths.\xa0', 'discussion': 'Storm totals are starting to tally up at remote weather stations. In the past 48 hours, Noisy Basin in the Swan Range picked up .7 inches of Snow Water Equivalent (SWE), Stahl in the northern Whitefish Range picked up 1.2 inches of SWE, and Flattop in central Glacier National Park picked up 1.4 inches SWE. Tunnel Ridge in the Flathead Range gained 10 inches of settled snow since the start of the storm. The driver is the southwest winds that accompanied this precipitation. Winds turned out gusts 40 to 50 mph at remote weather stations. A few more inches and increased winds will thicken recently formed slabs.\nThere are a couple of different faceted crusts to keep an eye on. The first one you will see in the snowpack is 1 to 2 feet below the surface. Reported avalanche activity on this layer is more common in the Whitefish Range. The second layer is the one responsible for producing the largest avalanches. It is faceted snow above the early February crust buried 2 to 4+ feet deep. The Flathead Range and Glacier National Park are the hotspots for reported avalanche activity failing at this interface.\nWeak snow above the early February crust has a bad reputation throughout the northwest. It extends north into Canada, south to Missoula, and west to Washington. Unfortunately, this interface is the culprit of close calls, accidents, and fatalities. This history continues to be the topic of conversation within the forecast team.\xa0'}

7
{'author': 'Sarah Williams', 'date': '2024-03-11', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 1, 'likelihood': 'possible', 'size': ['Large (D2)', '', 'Very Large (D3)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': "In late February, an intense wind-loading event triggered multiple large to very large hard slab avalanches in the Flathead Range, Glacier Park, and the Whitefish Range. All appeared to fail on a layer of weak, faceted snow 2-4 feet below the surface. This weak layer is best preserved and most problematic on shady slopes; however, in some locations, sunny aspects contain a mix of crusts and faceted layers capable of producing a destructive slide. You're most likely to trigger one of these beasts in steep, rocky terrain similar to the photo to the right/below. Signs of instability, such as cracking or collapsing, may not be present before the slope you are on slides. Choosing lower-angle terrain without convexities is the easiest way to manage this problem. "}, {'problem_type': ' Wind Slab', 'problem_number': 2, 'likelihood': 'possible', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': 'Today’s elevated southwest winds and new snow are building slabs of wind-drifted snow near ridgelines and cross-loaded terrain features like gullies and ribs. These slabs are likely to be small but may be able to knock you off your feet and send you downslope. As you gain elevation, you can expect to find thicker and larger slabs. Pay attention to the blowing snow and the density of the snow you travel through. Look for clues that the wind has been at work, such as drifts, dunes, rippled snow surfaces, and snow pillows. Cracks shooting away from your machine or boards indicate you have found an unstable slab directing you to sheltered or lower-angle terrain. '}], 'bottom_line': 'Triggering a large avalanche remains a possibility—primarily in wind-affected terrain. In these areas, a 2-4 foot dense slab may exist atop buried weak layers. To reduce your risk, avoid slopes with evidence of wind such as fresh drifts or a stiffer snow surface that supports your sled or skis.\n\xa0', 'discussion': "Overnight, a warm and windy storm brought snow to favored locations. Precipitation at SNOTEL sites varied from 0.5 inches at Noisy Basin and Stryker Ridge to 0.7 inches at Stahl Peak and 0.8” at Flattop in central Glacier Park. Tunnel Ridge leads in new snow depth with 8 inches of settled snow. Light snow continues today; however, the primary driving force of the avalanche hazard will be the moderate to strong southwest winds.\nFresh wind slabs will continue building throughout the day as elevated southwest winds buffet our area. Recorded wind gusts in the past 24 hours include 60 mph at Hornet, 94 mph at Tunnel, and 53 mph at Aeneas Ridge.\nAmong the few observations we received on Sunday, skiers and riders mainly mentioned the distinct snow/rain line at 4000 feet. Low elevations in our forecast area saw decreases in the snowpack as the warm storm continued overnight.\nThe Flathead Range continues to have a majority of large-to-very-large avalanche activity. Saturday’s good visibility brought more observations of these impressive crowns (photo, photo). However, since March 4th, we have had reports of 4 human-triggered slides in the Whitefish Range. Additionally, we have received word of an observation of large hard slab activity in Hay Creek in the Whitefish Range. If you're out and about and notice any large crowns, let us know so we can continue documenting the distribution of this problem.\xa0"}


8
{'author': 'Mark Dundas', 'date': '2024-03-10', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 1, 'likelihood': 'possible', 'size': ['Large (D2)', '', 'Very Large (D3)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': "In late February, an intense wind-loading event triggered multiple large to very large hard slab avalanches in the Flathead Range, central Glacier Park, and southern Glacier Park. All appeared to fail on a layer of weak, faceted snow 2-4 feet below the surface. This weak layer is best preserved and most problematic on shady slopes; however, in locations east of Essex, sunny aspects contain a mix of crusts and faceted layers capable of producing a destructive slide. The persistent slab problem is magnified in the mountains between Essex and Marias Pass, where the snowpack is generally thinner and weaker.\xa0 You're most likely to trigger one of these beasts in steep, rocky terrain similar to the photo to the right/below. Signs of instability, such as cracking or collapsing, may not be present before the slope you are on slides. Choosing lower-angle terrain without convexities is the easiest way to manage this problem.\xa0"}, {'problem_type': ' Wind Slab', 'problem_number': 2, 'likelihood': 'possible', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': [], 'lower': []}, 'discussion': "Southwest winds increased on Saturday and will stay elevated into Monday morning. As riders noted yesterday, plenty of dry snow from last week's storms remains available for transport, with more on the way later today. As you gain elevation, you will find thicker and larger slabs downwind of ridgelines and saddles and on the sidewalls of gullies. Today's blowing snow and cornice formation point toward slopes with developing slabs. Look for clues that the wind has been at work, such as drifts, dunes, rippled snow surfaces, and snow pillows. Cracks shooting away from your boards or machine indicate you have found an unstable slab directing you to sheltered or lower-angle terrain.\xa0"}], 'bottom_line': "Triggering a 2-4 foot thick avalanche on a buried weak layer remains possible in the Flathead Range and Glacier Park. You will most likely affect this layer on shaded slopes harboring a shallow snowpack. Blustery conditions will continue forming thin slabs of wind-drifted snow that could be reactive to a rider's weight.\xa0\xa0\n\xa0", 'discussion': "Yesterday (Saturday), temperatures reached 40F+ at many mid-elevation weather stations and 50F+ at low-elevations. Despite the mild conditions, high clouds and breezy conditions mostly kept the wet loose problem in check. One party did report triggering a small wet slide near the bottom of the Skook Chutes, while another noted rollerballs (photo). With cooler temperatures on tap for today, we have removed this problem from the list. However, you could probably trigger a small wet loose at low elevations where the temperature has remained above freezing since late morning yesterday.\xa0\nWinds increased yesterday afternoon, and last week's snow began transporting (photo). Winds cranked up overnight with a gust of 92 at Tunnel Ridge and into the 50s in several other locations. An approaching cold front will elevate the wind speeds and bring snow to help fuel the wind slab problem.\nSarah and Rob visited the site of two skier-triggered slides in the Chicken Bones area east of WMR from March 4 and 6. These occurred in an area cross-loaded by last week's strong winds and appeared to fail on a faceted weak layer below a melt-freeze crust 21 cm from the surface.\xa0\nIn the Whitefish Range, several slides failed on buried weak layers last week (photo) and are clustered in a small area on the southeast side of this zone at mid-elevations. The crowns seem thinner than slides in the Flathead Range, so Jeff and Sarah will investigate one of these today and try to solve this puzzle.\nThe Flathead Range, interior Glacier Park, and southern Glacier Park are the epicenters of large-to-very-large avalanche activity. Good visibility allowed for more observations of crowns in this area yesterday (photo, photo).\nA huge thank you to the 10 parties that submitted observations yesterday (Saturday). Riders found dry snow on shaded aspects and decent riding conditions on sunny aspects at mid and upper elevations, with generally stable snowpack tests noted by The Patrol Fund Level 1 class (observation, observation)."}

9
{'author': 'Mark Dundas', 'date': '2024-03-09', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 1, 'likelihood': 'possible', 'size': ['Large (D2)', '', 'Very Large (D3)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': "In late February, multiple large avalanches occurred in the Flathead Range and southern Glacier Park on a layer of weak, faceted snow 2-4 feet below the surface. This weak layer is best preserved and most problematic on shady slopes; however, some sunny aspects contain a mix of crusts and faceted layers capable of producing a destructive slide. This problem is magnified in the mountains between Essex and Marias Pass, where the snowpack is thinner and weaker. Today's warming temperatures may make the slab above the weak snow more reactive to triggering.\xa0 You're most likely to trigger one of these beasts in steep, rocky, wind-swept terrain. Signs of instability, such as cracking or collapsing, may not be present before the slope you are on avalanches. Choosing lower-angle terrain without convexities is the easiest way to manage this problem.\xa0"}, {'problem_type': ' Wet Loose', 'problem_number': 2, 'likelihood': 'likely', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['southeast', 'south', 'southwest', 'west'], 'middle': ['southeast', 'south', 'southwest', 'west'], 'lower': ['southeast', 'south', 'southwest', 'west']}, 'discussion': "Today's intense March sun and warming temperatures will increase the threat of wet loose avalanches, especially on steep, rocky, wind-sheltered terrain. These slides could entrain substantial snow and travel long distances on the underlying crust. Rollerballs, pinwheels, and snow falling from trees indicate warming and are precursors to loose snow slides.\xa0 \xa0\xa0 Though these slides will generally be small, tangling with one in long-running gullies, chutes, or large faces may make escape difficult. If you travel on or below steep sunny slopes, stay ahead of the sun and plan your exit strategy to avoid these areas in the afternoon. The shady side of the compass still holds dry, loose snow, which will keep you away from this problem and offer a higher-quality product.\xa0 \xa0"}], 'bottom_line': "Riders can trigger a large, destructive avalanche on a buried weak layer, especially on slopes with a thin snowpack or exposed rocks. Today's warming and sunshine may initiate loose snow slides as the surface softens. Rollerballs and mushy surface snow indicate you've worn out your welcome and need to move to a shadier aspect or stick to lower-angle terrain free of overhead hazards.\xa0", 'discussion': "Yesterday (Friday), cool morning temperatures, occasional high clouds, and light winds mostly kept the wet loose problem at bay. This morning, temperatures are 10-15 degrees warmer than yesterday, which may expedite the warming of the surface snow. The unknown is the amount of cloud cover that will make or break a wet loose cycle today. Generally, 6-12 inches of surface snow rests on a slick rain crust below around 5800 feet, with similar amounts above resting on old, harder snow. Yesterday's warming and solar input likely left a thin surface crust at low and mid-elevation sunny aspects. Wet loose activity will be delayed until the crust breaks down. An approaching cold front this afternoon will bring cloud cover and minimize this problem.\xa0\nClear skies continue to allow observers unimpeded mountain views following recent snowfall and blustery winds. In the Swan Range, there has not been a documented avalanche on the early February buried weak layer, and we have trimmed the distribution of the Persistent Slab problem by removing the middle elevation band and dropped the likelihood of triggering at the upper elevations to unlikely. In the Whitefish Range, slides failing on buried weak layers are clustered in a small area on the southeast side of this zone at mid-elevations. These are located on the south and southeast aspects, and we have not had a chance to verify what layer they are failing on, as the crowns seem thinner than slides in the Flathead Range. The epicenter of large to very large avalanche activity is the Flathead Range, interior Glacier Park, and southern Glacier Park.\xa0\nObservations yesterday (Friday) noted no instabilities but found quality snow in sheltered locations in the Swan Range. An observer on Snowshed Mountain remotely triggered a cornice while kicking a separate section of cornice, but otherwise found no instabilities. A party in Rescue Creek found two faceted layers in the upper half of the pack, but they had no propagation in large column tests. Blase and I took a short walk up Rescue after our team meeting and enjoyed viewing impressive crowns and piles of debris from the February 28 and 29 loading events (photo, photo, photo). A party in central Glacier Park noted a whopper of a slide that failed on the early February crust (photo, photo).\xa0"}


10
{'author': 'Rob Millspaugh', 'date': '2024-03-08', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 1, 'likelihood': 'possible', 'size': ['Large (D2)', '', 'Very Large (D3)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': "Yesterday (Thursday), a snowmobiler triggered a large avalanche on a buried weak layer at 5500' in the southern Whitefish Range. Otherwise, most avalanche activity has occurred in the Flathead Range on slopes near and above 6500 feet that face NW-NE-E-SE. Carefully assess terrain on slopes that fit this description. Slabs can break 2 to 4 feet deep on facets formed in early February. The resulting avalanche will be difficult to escape. The most conservative option is to stick to lower-angled slopes in areas where the problem exists. Avoid convex rollovers and rocky, wind-effected slopes if you enter steeper terrain. Today's warming temperatures and solar radiation may stress weak layers buried in the snowpack.\xa0 Give steep terrain a wider margin during the heat of the day."}, {'problem_type': ' Wet Loose', 'problem_number': 2, 'likelihood': 'possible', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['south', 'southwest', 'west'], 'middle': ['south', 'southwest', 'west'], 'lower': ['south', 'southwest', 'west']}, 'discussion': "A Wet Loose problem may develop today due to intense solar radiation and warming temperatures. Steep, rocky areas hit by the sun are typically the first place to slide. Expect this problem to develop most quickly where warm temperatures meet dry snow. Middle elevations may see the most activity, but upper elevations can't be ruled out. Move to lower-angle terrain or shaded aspects, IF you see signs of warming, like rollerballs and pinwheels scuttling down the hill.\xa0"}], 'bottom_line': 'A snowmobiler triggered a large avalanche yesterday (Thursday) on a weak layer buried 2-4 feet deep. Warming temperatures can increase the potential for natural and human-triggered avalanches. Give steep slopes a wide margin, particularly during the heat of the day.\xa0', 'discussion': "This week I traveled to the Northern and Southern ends of the advisory area. In both outings, my party found seemingly benign conditions; limited effects from wind and sun, and unremarkable findings in our test pits. After wrapping up in one pit my partner commented, “If it wasn’t for all the action, we’d be riding everything.”\nThe action they were referring to consists of:\n\nA handful of near-misses and accidents in the Marion Lake area during the President’s Day weekend\nA skier-triggered hard slab on Slippery Bill Mountain in the Flathead Range on 2/26\nA cycle of very large avalanches in the Flathead Range during the wind-loading event 2/28-2/29\nFatalities north and west of our advisory area\n\nYou can add Thursday's snowmobile-triggered avalanche in the Whitefish Range to this list. These slides all involved buried weak layers from early February. In some cases, the weak structure has been subtle and has fooled several parties including professionals. Stability tests have been a pretty mixed bag, although BNSF Avalanche Safety was able to reproduce propagating results in John F Stevens Canyon.\xa0 In this situation I'm placing more emphasis on behavior than appearance.\xa0 These buried weak layers may not look like much, but the above rap sheet has me wanting to steer clear.\xa0 \xa0\nWe removed the windslab problem as observations indicate tapering wind-loading and slabs trending toward unreactive. Continue to exercise caution where you find signs of wind-loading, like a scalloped surface or dune-shaped features. Recognize that previous wind-loading occurred on slopes harboring buried weak layers. Three human-triggered avalanches have occurred in the southern Whitefish Range since Monday. One of these (the previously mentioned snowmobile-triggered slide) stepped down to a buried weak layer and resulted in a larger avalanche.\xa0"}

11
{'author': 'Cam Johnson', 'date': '2024-03-07', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Wet Loose', 'problem_number': 3, 'likelihood': 'possible', 'size': ['Small (D1)', ''], 'aspect_elevation': {'upper': ['south', 'southwest', 'west'], 'middle': ['south', 'southwest', 'west'], 'lower': ['south', 'southwest', 'west']}, 'discussion': 'Solar radiation may cause a loose snow avalanche problem. This will likely start as a dry avalanche problem and transition to a wet avalanche problem late in the day. Rollerballs or pinwheels rolling down the hill are signs of an impending Wet Loose problem. Steep, rocky areas hit by the sun are typically the first place to slide. Move to lower-angle terrain or shaded aspects IF you see signs of warming.'}, {'problem_type': ' Persistent Slab', 'problem_number': 1, 'likelihood': 'possible', 'size': ['Large (D2)', '', 'Very Large (D3)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': 'A weak layer of facets near the early February Crust is the culprit of many natural and human-triggered avalanches in the last few weeks. The hotspot of avalanche activity occurred on slopes near and above 6500 feet that face NW-NE-E-SE. Continue to exercise caution on slopes that fit that description. If triggered, slabs can break 2 to 4 feet deep and will be difficult to escape. The most conservative option is to stick to lower-angled slopes in areas where the problem exists. Avoid convex rollovers if you decide to enter steeper terrain. Warming temperatures and solar radiation may stress weak layers buried in the snowpack. There is a layered cake of crusts and facets on solar aspects that have yet to cause a problem. The safest option is to give steep terrain a wide margin for error, especially during the heat of the day.'}, {'problem_type': ' Wind Slab', 'problem_number': 2, 'likelihood': 'possible', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': 'Two recent human-triggered avalanches involving wind-drifted snow have occurred in the southern Whitefish Range. Wind Slabs range from thin to thick and new to old. The more sensitive of the two is a slab that is roughly a foot thick. Drifted snow should be fairly easy to identify by its dune-shaped appearance. Be wary of cross-loaded terrain features further downslope. Wind Slabs have formed on slopes that harbor weak layers buried deep in the snowpack. A small Wind Slab can step down to a more dangerous Persistent Slab avalanche. Avoid this problem by sticking to slopes less than 30 degrees, or by choosing terrain sheltered from the wind.'}], 'bottom_line': 'Another human-triggered slab avalanche occurred in the southern Whitefish Range. Loose snow avalanches may become possible to trigger during the heat of the day on sunny aspects. Triggering an avalanche 2 to 4 feet thick is a low probability, high consequence scenario. Keep it simple by selecting lower-angled slopes.', 'discussion': 'The southern Whitefish Range has been the focal point for recent human-triggered slab avalanches. Avalanches are failing up to a foot thick on slopes that face east and southeast. FAC will visit these sites soon to gather more snowpack information.\xa0\nThe effects of solar radiation are growing as we work our way towards spring. Freezing levels are forecasted to climb to roughly 4500 feet. This will likely increase the chances of triggering loose snow avalanches. Thankfully, loose snow avalanche problems caused by solar radiation are typically easy to manage. Signs like rollerballs, snow falling out of trees, and gloppy snow are indicators of wet snow.\xa0\nWarming temperatures and solar radiation can increase the likelihood of triggering a slab avalanche. These environmental factors lead to rapid settlement and increased creep rates in the snowpack. This stresses weak layers and can cause them to fail. We have a few different facet/crusts on solar aspects, and a facet/crust responsible for several near-misses and accidents. The safest bet is to give steep terrain a wide margin for error.'}


12
{'author': 'Cam Johnson', 'date': '2024-03-06', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 1, 'likelihood': 'possible', 'size': ['Large (D2)', '', 'Very Large (D3)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': 'A weak layer of facets near the early February Crust is the culprit of many large natural and human-triggered avalanches in the last few weeks. Exercise caution on shaded slopes near and above 6500 feet in elevation. If triggered, slabs can break 2 to 4 feet deep and will be difficult to escape. The most conservative option is to stick to lower-angled slopes in areas where the problem exists. Avoid steep rollovers and rocky outcroppings if you choose to enter steeper terrain on shaded slopes.\xa0'}, {'problem_type': ' Wind Slab', 'problem_number': 2, 'likelihood': 'possible', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': 'Winds transported snow into fresh slabs on leeward-facing aspects. Wind slabs range from thin to thick and new to old. The more sensitive of the two will be thin slabs that formed in the last 24 hours. Drifted snow should be easy to identify by its dune shape or textured appearance. Wind Slabs formed on slopes that harbor weak layers buried deep in the snowpack. It is possible that triggering a small Wind Slab could step down to a dangerous Persistent Slab avalanche. Avoid this problem by sticking to slopes less than 30 degrees, or by choosing aspects that face south or west.'}], 'bottom_line': 'The primary concern is avalanches failing 2 to 4 feet deep on a persistent weak layer. Winds drifted snow into thicker, denser slabs above 5000 feet. Manage both problems by selecting lower-angled slopes on aspects that face NW-N-NE-SE.\nExpect a Wet Loose avalanche problem IF the sun stays out longer than anticipated. Rollerballs and gloppy snow are signs of an impending Wet Loose avalanche cycle. Move to shaded slopes if you see this beginning.\xa0', 'discussion': 'Avalanche activity in the last week has ranged from small to large (D1-D2), with a few very large (D3) avalanches. Most reported avalanches were Storm/Wind Slabs on slopes above 5000 feet. The larger avalanches are Persistent Slab avalanches failing 2 to 4 feet deep on a layer of facets above a hard crust buried in early February. Avalanche activity on this layer is most common above 6500 feet on aspects that face N-NE-SE.\nInstabilities in the new and drifted snow should be relatively short-lived. Winds were transporting snow yesterday. Expect to see signs of cracking with the possibility of triggering smaller slabs on leeward-facing aspects. These new thin slabs rest over thick, hard slabs from the past week of moderate to strong winds. Although those are gaining strength, I’d still be wary of jumping onto steep slopes that face NW-NE-SE.\nPersistent weak layers buried near the early February Crust remain untrustworthy. Snowpit tests continue to show mixed results of propagating and non-propagating. In some areas, this layer is buried at a depth where a human is less likely to trigger. On the flip side, if triggered, the resulting avalanche may be unsurvivable. Common trigger points are convex rollovers and thin parts of the slab. Unfortunately, it is sometimes impossible to identify where those thin parts are. Rocky outcroppings or areas scoured by the wind are the usual suspects.\nThe weather forecast suggests periods of clear skies. IF the sun stays out for longer than anticipated, or if you travel to the Whitefish Range which is supposed to see fewer clouds, then expect a loose snow avalanche problem on aspects getting hit by the warm sun. Sluffs, rollerballs, and gloppy snow are signs of a Wet Loose avalanche problem. Move to lower-angle slopes or slopes shaded by the sun if you see this problem beginning.\xa0\n\xa0'}

13
{'author': 'blase reardon', 'date': '2024-03-05', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Wind Slab', 'problem_number': 3, 'likelihood': 'possible', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': 'Today\'s third hazard lies in between the other two - apparent if you\'re looking, with the potential to bury or injure a person. The region has seen bouts of moderate to strong winds the past week that have built multiple generations of wind slabs. If winds pick up today as forecast, we may see another, as the low-density snow from Monday gets drifted. Patches of dense but soft snow near ridges will be the most sensitive to the weight of a person or snow machine. They may be covering older hard slabs of wind-packed snow that are harder for a person to trigger, but produce larger, more dangerous avalanches. These can step down and release very dangerous avalanches that break on the weak facets above the crust.\xa0 Look for dunes, drifts, and whale-shaped piles of hard snow below ridge crests and on the downwind sides of terrain features of rocks and gully walls. More subtle are drifts cross-loaded onto steep slopes, as shown by this unintentionally-triggered slide Monday east of Whitefish Mountain Resort. Hard, hollow-feeling snow isn\'t "bomber," it\'s a slab.\xa0'}, {'problem_type': ' Persistent Slab', 'problem_number': 1, 'likelihood': 'possible', 'size': ['Large (D2)', '', 'Very Large (D3)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': "The most serious hazard today is the one to account for when choosing destinations, routes, and places to play. The lowest risk choices don't require travel under steep, shady start zones or riding up or down convex slopes where snow depths are likely to be variable. The potential for triggering avalanches from below lingers, and thin spots in the snow cover are potential trigger points for releasing hard slabs that would be very difficult to escape. A thin layer of weak, faceted snow is buried 2 to 4 feet deep, a few inches above a stout ice layer and/ or melt-freeze crust. While this layer is subtle in snowpits, the avalanches releasing on it are anything but. Multiple large to very large avalanches failed on this layer during the end of February storm and avalanche cycle. Many occurred on very steep, leeward slopes below ridges, where wind-transported snow built thicker, harder slabs over the facets. This upper elevation terrain remains the place where you're most likely to trigger an avalanche on the faceted layer.\xa0 At mid elevations, we've had almost no reports of avalanches, whumpfing collapses, or snowpit tests that show instability in the past week. However, fatal avalanche accidents to the west and north of our region likely involved this layer and occurred near 6500 feet, the boundary between our mid and upper elevations. That tells me that it's important to minimize exposure to this hazard in terrain approaching that elevation, to leave a margin for safety.\xa0 So pick destinations that offer options to ride sunny slopes where the weak layer is less common, especially because the riding on these slopes will deteriorate with the sun and warming temperatures headed our way. In shady terrain, stick to lower angled slopes that are planar or concave in profile. Park or stop well out of the runouts of steep start zones, even on what look like small slopes.\xa0 \xa0"}, {'problem_type': ' Dry Loose', 'problem_number': 2, 'likelihood': 'possible', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['southeast', 'south', 'southwest', 'west'], 'middle': ['southeast', 'south', 'southwest', 'west'], 'lower': []}, 'discussion': "The most obvious hazard today will be the easiest to avoid. If the sun comes out this afternoon, expect sluffs of fresh snow to run on very steep slopes, triggered by snow falling off trees or rocks. Most will be harmless. The exceptions will be: If you're in or below this terrain and you see rollerballs fanning downslope, move on. If you want to ride steep, confined slopes, get down and out from under them before the sun hits."}], 'bottom_line': "Choose your destinations and play spots with an eye to avoiding today's trifecta of avalanche hazards. The most serious is triggering large, serious avalanches that break on weak snow buried 2 to 4 feet deep. Secondary hazards today include the potential for sluffing in the new snow, particularly if the sun comes out, and the possibility of triggering dense slabs of drifted snow. Careful attention to terrain will help you find a Goldilocks band of quality, low-risk riding.", 'discussion': "Problems, problems, problems. We've listed three avalanche hazards today. Recent obs describe a rain crust that extends to about 5000 feet and sometimes 5300 feet. Others, a sun crust on solar aspects, particularly southwest.\nThe Goldilocks band is above that rain crust, in shaded, wind-sheltered terrain that's not too steep and free of the lingering danger of triggering slides that break deep in the snowpack. Whew. It's half-caff semi-dry cappucino with oat milk. But being specific is the key to low risk, fun riding today. Check the problem descriptions for ideas how to maximize your your riding and safety today.\nThe general trend is decreasing danger, as weak layers slowly strengthen and adjust to the load delivered by this past weekend's storm. A ridge building in at the end of this week will interrupt that trend on sunny slopes. Clear skies and direct sun may produce a wet snow avalanche cycle on sunny slopes. Shaded slopes, however, will continue to stabilize so long as temperatures remain below freezing overnight. It's hard to say yet whether the ridge will bring a diurnal melt-freeze cycle strong enough to produce supportable crusts and corn on sunny slopes early in the day. Stay tuned.\xa0"}


14
{'author': 'Sarah Williams', 'date': '2024-03-04', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 1, 'likelihood': 'possible', 'size': ['Large (D2)', '', 'Very Large (D3)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': "A layer of weak, faceted snow buried 2-4 feet was the failure layer in multiple large avalanches during Wednesday and Thursday's snowfall and intense wind events. This layer is several inches above the hard, early February ice and crust on shady, mid- and upper-elevation slopes. This weak snow has been challenging to identify in snowpits and does not always produce concerning results in stability tests.\xa0 This week's cool temperatures will slow the strengthening of this weak layer. You may not experience any signs of instability like collapsing or cracking before triggering a slide.\xa0 Choose terrain free of convexities to increase your safety margin. Steer around thin areas, such as those scoured or peppered with rocks, in favor of a deeper, more consistent snowpack. Cracking beneath your boards or machine indicates an unstable slab, and a sign to move to lower-angle terrain.\xa0"}, {'problem_type': ' Wind Slab', 'problem_number': 2, 'likelihood': 'possible', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': [], 'lower': []}, 'discussion': "This problem consists of two distinct generations of wind-drifted snow. The older slabs formed during Wednesday and Thursday's strong to extreme southwest winds. It consists of hard slabs that may be several feet thick. These features may be masked by recent snowfall, sound hollow like a drum, support you and your machine, and offer no signs of instability until they fail. You are more likely to trigger them from thinner spots in the slabs. Triggering a hard slab avalanche poses the risk of the slide stepping down to a deeper buried weak layer. More recent slabs formed over the weekend in the new snow. These should be easier to identify by soft, fresh drifts, dunes, rippled snow surfaces, and snow pillows. You may notice cracking beneath your boards or machine, indicating you have found an unstable slab. Let this direct you to lower-angle terrain.\xa0 Today's snowfall will replenish fetches and be available for transport, especially above 6,500 feet. Blowing snow and cornices point in the direction of danger."}], 'bottom_line': 'Buried weak layers remain a concern. If triggered, these avalanches are likely very large and unsurvivable. Keep in mind that as you gain elevation, ridgetop terrain is affected by winds and may be reactive to the weight of your sled or boards.', 'discussion': 'Reports of natural avalanches have continued to come in from the past week. Many of these avalanches are large to very large and have the characteristics of a persistent slab problem. Crowns and fracture lines are several feet thick; many of these slides are more than 100 feet wide. These slides likely failed during the intense wind-loading event on Wednesday night or Thursday morning. They likely failed on a layer of weak faceted snow above the early February crust. We expect to continue to catalog similar avalanches when we have clearing skies and visibility.\xa0\nIncremental snow accumulations and light winds are expected today. As many observers reported on Sunday, there have been few signs of instability during their tours. Two observers in the northern Whitefish Range had no propagating results in their snowpack tests but were alarmed to see a large avalanche with a crown of 3 feet (Red Meadow observation, Link observation). In the Flathead Range, multiple crowns of very large avalanches have been observed (photo 1, photo 2, photo 3), with all of these slides starting at upper elevations.\nObservers completing a snow survey in Glacier National Park submitted photos of debris that impacted the Going-To-the-Sun-Road from the Red Rock Slide path (photo 1, photo 2). The debris appears to be wet loose from the Leap Day rain event. Red Rock is just upstream from Avalanche Creek and is a dramatic path that drops steeply for 3484 feet off the shoulder of Mt Cannon (photo). This path hits the road yearly and occasionally dams up the adjacent McDonald Creek.'}

15
{'author': 'Mark Dundas', 'date': '2024-03-03', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 2, 'likelihood': 'possible', 'size': ['Large (D2)', '', 'Very Large (D3)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': "During Wednesday and Thursday's snowfall and intense wind events, a layer of weak, faceted snow buried 2-4 feet was the failure layer in multiple large avalanches. This layer is several inches above the hard, early February ice and crust on shady, mid- and upper-elevation slopes. This weak snow has been challenging to identify in snowpits\xa0and does not always produce concerning results in\xa0stability tests.\xa0 This week's cool temperatures will slow the strengthening of this weak layer. You may not experience any signs of instability like collapsing or cracking before triggering a slide.\xa0 Choose terrain free of convexities to increase your safety margin. Steer around thin areas, such as those scoured or peppered with rocks, in favor of a deeper, more consistent snowpack. Cracking beneath your boards or machine indicates an unstable slab directing you to lower-angle terrain.\xa0"}, {'problem_type': ' Wind Slab', 'problem_number': 1, 'likelihood': 'possible', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': "Wednesday and Thursday's gale-force southwest winds drifted substantial snow into thick, hard slabs. A wind shift to a north and east direction Friday and Saturday may have built thin slabs in locations favored by atypical winds. A return to southwesterly flow is transporting Saturday's low-density snowfall.\xa0 Recently formed hard slabs may be masked by yesterday's snow. They may sound hollow like a drum, support you and your machine, and offer no signs of instability until they fail. Features formed over the past 48 hours should provide more straightforward clues, such as drifts, dunes, rippled snow surfaces, and snow pillows. Cracks shooting away from you indicate you have found an unstable slab directing you to sheltered or lower-angle terrain.\xa0 On Saturday, riders in the Whitefish Range found thin reactive slabs in sheltered locations. This instability probably formed due to intense precipitation intensity and should be short-lived. However, look for slopes holding cohesive snow in the trees.\xa0 Saturday's low-density snow may sluff on steep slopes in sheltered locations, primarily where this snow rests on a slick recently formed rain crust or a thick layer of cohesionless powder.\xa0 \xa0"}], 'bottom_line': "Recently formed hard slabs may be masked by yesterday's snow. You're most likely to trigger a slide in terrain that the wind has loaded. You can reduce your risk of triggering slides today by avoiding steep, rocky, wind-affected slopes.", 'discussion': "Most locations experienced a brief, intense shot of precipitation Saturday. Widespread snow totals are generally 3-6 inches, with the northern Whitefish Range and the Flathead Range favored and the Swan Range a distant third.\xa0 Fortunately, temperatures have cooled since last week's valley floor 50F readings, with the snow line now below 1000 feet. Cold arctic air is spilling over the Continental Divide on the far eastern edge of our advisory area with -3F at Marias Pass this morning.\xa0\nSaturday, experienced backcountry groups found enjoyable riding in sheltered locations. A party in the northern Whitefish Range experienced up to 16 inches of dry, unconsolidated snow with no instabilities observed. A group in the southern Whitefish Range found the new storm snow touchy and noted multiple (10+) thin D1-size slabs in sheltered locations. They wisely maintained wide margins, only exposed themselves to nonconsequential terrain, and intentionally stuck to low-angle and low-consequence slopes throughout the tour. A group in the Flathead Range noted calm conditions in a drainage sheltered from the east winds. They had 3 inches of afternoon snowfall with some sluffing in the new snow, and 5300 feet seems to be the transition point from good skiing to more spicy.\nFAC staff traveled to Cascadilla Creek to look closer at a very large avalanche on Nyack Mountain. Unfortunately, our visibility window was limited to a short period when we were still well down the valley from the slide. However, we did get enough of a view in the flat light to recognize this slide is very large, with a crown exceeding 1000 feet wide. This slide failed during the intense wind-loading event on Wednesday night or Thursday morning. It likely failed on a layer of weak faceted snow above the early February crust. We did note that rain had affected the low and middle elevations of this drainage, leaving behind a widespread surface crust (photo) and well-developed runnels (photo), which made skiing challenging.\xa0\n\xa0"}


16
{'author': 'Rob Millspaugh', 'date': '2024-03-02', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 2, 'likelihood': 'possible', 'size': ['Large (D2)', '', 'Very Large (D3)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': "Slides can break 2-4 feet deep on a layer of weak, faceted snow in steep, shaded terrain at upper and middle elevations. This layer is found several inches above a stout crust formed in early February. It has been difficult to identify in snowpits and does not always produce concerning results in stability tests. This week, snow and strong winds overloaded buried weak layers, resulting in large destructive avalanches, most notably in the Flathead Range and southern Glacier Park. Natural avalanches ran on this layer Thursday in John F. Stevens Canyon. Human-triggered avalanches during the President's\xa0 Day weekend resulted in several accidents and near-misses in the Marion Lake area. The structure has been reported across the region and was the cause of a fatality in the Canadian reaches of the North Fork of the Flathead River on Feb. 24. \xa0Slabs can break well above you, wrap around terrain features, and will be difficult, if not impossible, to escape. They can also be triggered remotely or sympathetically from below or adjacent slopes.\xa0"}, {'problem_type': ' Wind Slab', 'problem_number': 1, 'likelihood': 'possible', 'size': ['Small (D1)', '', 'Large (D2)', '', 'Very Large (D3)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': "Today, winds could shift to easterly and transport new and recent snow onto atypical slopes. This could result in thin and sensitive drifts on slopes that are usually sheltered or windward.\xa0 These slabs should remain small and relatively harmless. Consider moving to lower-angle terrain if today's snowfall overproduces and you find 8 or more inches of new or wind-drifted snow. During the previous 5 days, moderate to strong southwesterly winds drifted snow onto leeward slopes along ridgelines and cross-loaded gullies.\xa0 Winds peaked Thursday afternoon and have been tapering off since. Slabs range from soft to hard. Soft slabs may crack around your feet or machine to warn you of their instability.\xa0 Hard slabs will not do this until it's too late. For the best and safest riding, seek out sheltered slopes. Scalloped snow surfaces and dune-shaped drifts are visual indicators of wind-affected snow. However, today's snowfall may cover these features and make it more difficult to identify wind slabs. If your skis, board, or machine start to ride on top of a stiff, hollow-sounding surface, you've likely found a wind slab. Remember that even a small slide can step down to a deeper weak layer, resulting in a larger, more destructive avalanche, as described in the Persistent Slab problem below."}], 'bottom_line': 'Recent wind and snow have stressed weak layers buried deep in the snowpack. Decrease your risk by limiting travel on and below steep, wind-drifted slopes. Avalanches can break well above you, wider than expected, and will be difficult to escape.\n\xa0', 'discussion': 'The snow surface took a beating this week from moderate to strong southwesterly winds. Yesterday (Friday), Blase and Sarah were East of WMR, where they noted improved weather and stability but generally worse riding conditions than the previous day’s. Although the winds have relented, and natural avalanche activity is unlikely today, it is still possible for a rider to trigger a deadly avalanche, particularly on upper-elevation leeward slopes. \xa0\nNorth of the advisory area, a Special Public Avalanche Warning is in effect for most of British Columbia’s and Alberta’s forecast regions. This warning concerns recent loading on “prominent weak layers established during drought conditions in February.” That should sound familiar since a similar structure has been found across our region.\nWe received less snow than our neighbors to the north, but we had plenty of wind to make up for it. Thursday, BNSF Avalanche Safety reported a handful of large to very large natural avalanches in John F Stevens Canyon. These slides likely ran sometime late on Wednesday, occurred on wind-loaded slopes, and several may have failed on buried weak layers. Friday, we received similar reports of several very large avalanches in the Middle Fork drainages. These recent slides indicate that the persistent weak layer has not fully healed and still demands caution.'}

17
{'author': 'Rob Millspaugh', 'date': '2024-03-01', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 2, 'likelihood': 'possible', 'size': ['Large (D2)', '', 'Very Large (D3)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': "Steep, shaded slopes at mid and upper elevations remain particularly dangerous. In this terrain, slides can break 2-4 feet deep on a layer of weak, faceted snow. This layer is often located several inches above a stout crust formed in early February. It has been difficult to identify in snowpits and has yielded mixed results in stability tests. The Flathead Range has seen the most activity on this layer. Large natural avalanches ran on this layer as recently as\xa0 Thursday in John F. Stevens Canyon. Human-triggered avalanches during the President's\xa0 Day weekend resulted in several accidents and near-misses in the Marion Lake area. The structure has been reported across the region and was the cause of a fatality in the Canadian reaches of the North Fork of the Flathead River on Feb. 24. Wind will continue to drift recent snow onto this weak structure. This added stress may result in natural avalanches or could increase the chance of human triggering. Slabs can break well above you, wrap around terrain features, and will be difficult if not impossible to escape. They can also be triggered remotely or sympathetically, from below or from adjacent slopes.\xa0"}, {'problem_type': ' Wind Slab', 'problem_number': 1, 'likelihood': 'likely', 'size': ['Small (D1)', '', 'Large (D2)', '', 'Very Large (D3)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': "Over the past 5 days, moderate to strong southwesterly winds have drifted snow onto leeward slopes along ridgelines and cross-loaded gullies. Winds peaked yesterday (Thursday) afternoon but are still sufficient to continue building slabs today. Both older and freshly-formed slabs remain sensitive to the weight of a rider.\xa0 Scalloped snow surfaces and dune-shaped features are visual indicators of wind-drifted snow. Slabs may range from soft to hard. Soft slabs may crack around your feet or machine to warn you of their instability.\xa0 Hard slabs will not do this until it's too late. If your skis, board, or machine start to ride on top of a stiff, hollow-sounding surface you've likely found a hard slab. For the best and safest riding, seek out sheltered slopes.\xa0 Recognize that isolated wind-sheltered slopes may still harbor lingering instability in the storm snow. Opt for low-angle terrain where you find 8 or more inches of recent snow.\xa0 Keep in mind that even a small slide can step down to a deeper weak layer and result in a larger, more destructive avalanche as described in the Persistent Slab problem below."}], 'bottom_line': 'Conditions remain dangerous due to continued wind transport, recent snow, and weak layers buried deep in the snowpack. To minimize your risk, limit your travel on and below steep, wind-drifted slopes. Avalanches can break wider and run longer than expected.\nThe upper McDonald Valley received significantly more snow and the avalanche danger may be higher in central Glacier National Park. ', 'discussion': 'Yesterday (Thursday) was pretty wild: intense, buffeting wind and natural cornice fall on the ridge top, and 50*F with sticky snow down low. Somewhere in between, though, there’s good honest riding in wind-sheltered terrain.\nToday should be one step closer to normal. Most stations are reporting seasonable temperatures, decreasing winds, and a trace of precipitation overnight. The one notable exception is in central Glacier National Park, where Flattop Mountain picked up another 1.3 inches of SWE in the last 24 hours. That totals 2.5 inches of water and 14+ inches of snow in 48 hours for that location. Slabs in the upper McDonald Valley will be thicker.\xa0\nThough the weather moderated some, the danger remains elevated. Winds are still sufficient to build slabs and add stress to buried weak layers. Yesterday (Thursday), BNSF Avalanche Safety reported a handful of large to very large hard slabs on wind-loaded slopes in John F Stevens Canyon. Several likely failed on the uncooperative facet layer near the early-February Crust. This layer continues to give mixed results in pit tests. It may not look like much, but for the time being, it still deserves some respect. When in doubt, opt for simple, low-angle terrain.'}


18
{'author': 'Jeff Metsky', 'date': '2024-02-29', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 3, 'likelihood': 'possible', 'size': ['Large (D2)', '', 'Very Large (D3)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': "To reduce your risk of getting overrun by dangerous avalanches that break well below the recent snow, stay off and out from under steep, shaded start zones at mid and upper elevations. In this terrain, slides can break on weak, faceted snow a few inches above the stout crust and ice deposited in early February. This layer is now buried 2 to 4 feet deep in most of the Flathead zone. Prior to this week's storms, it was most sensitive to a person's weight on shaded, northerly aspects above 6,500 feet in the Flathead Range. Avalanches that broke on this layer resulted in several accidents and near-misses over the holiday weekend, and it was the weak layer in a fatality associated\xa0 just north of the border, in the upper North Fork of the Flathead River on Feb. 24. For the past three days, new and drifted snow has been actively loading the slopes where it was most sensitive. Slabs that involve the recent snow can step down to the weak layer above the crust, resulting in slides that break much wider, involve much more debris, and can be difficult to impossible to escape. They may can also be triggered remotely or sympathetically, from below or from adjacent slopes. Because many avalanche paths in the Flathead Range run into low elevations, travel on ridge crests or in dense timber is the only way to minimize your exposure to this hazard.\xa0"}, {'problem_type': ' Storm Slab', 'problem_number': 2, 'likelihood': 'likely', 'size': ['Small (D1)', '', 'Large (D2)', ''], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'south', 'southwest', 'west', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'south', 'southwest', 'west', 'northwest'], 'lower': []}, 'discussion': 'Adding warming temperatures and windy conditions to the mix is the perfect recipe for developing a storm slab problem. Expect these slabs to increase in thickness as you gain elevation. Slabs can also be thicker below ridgelines, in cross-loaded gullies, and mid-slope convexities.\xa0 On steep slopes sheltered from the wind, a person or snowmachine can trigger soft slabs 6 to 12 inches thick that break within the new snow, or at the old/new snow interface. Look for signs of instability like shooting cracks that may travel long distances. Avalanches that start up high will entrain a lot of snow and may run long distances in areas that have been protected from recent winds.'}, {'problem_type': ' Wind Slab', 'problem_number': 1, 'likelihood': 'very likely', 'size': ['', 'Large (D2)', '', 'Very Large (D3)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': 'Moderate to strong winds have transported snow onto leeward aspects along ridgelines and cross-loaded gullies over the past 72 hours. This snow transport will continue today. Expect to find slabs 1 to 3 feet or so thick in most leeward terrain. These will be reactive to the weight of a rider or snowmachine. For the best riding, seek out sheltered, low-angle slopes. Steer clear of areas with hollow-sounding snow or areas sculpted by recent winds.'}], 'bottom_line': 'Heavy snow and strong winds have created very dangerous avalanche conditions. Continued snowfall and the possibility of rain-on-snow will keep the danger elevated through the day. Natural and triggered avalanches have the potential to break across terrain features and run longer than expected. Avoid traveling in avalanche terrain.', 'discussion': 'Happy Leap Day! If you get to celebrate a real birthday for the first time in 4 years, enjoy. For the rest of us, we get an additional day to play in the snow. Unfortunately, as the snow totals stack up, the terrain for safe recreation becomes more limited.\nHeavy snowfall combined with 3 days of southwest winds have left a variety of avalanche\xa0 problems for backcountry users to navigate. The answer to a complex weather pattern and multiple avalanche problems is terrain management. Seek out simple terrain that is under 30 degrees and not exposed to avalanches from above.\nTemperatures have risen 10 to 15* F since snow began a few days ago. New and recent snow have developed into an upside-down slab. Think: stronger and warmer,\xa0 well-bonded snow over weak, cold, dry snow. Continued warming temperatures today (Thursday) will bring the rain/ snow line to 5000 feet and possibly 5500 feet. Rain on new snow rapidly destabilizes it, by adding heat and mass to slabs and rapid strain to buried weak layers, like our old frenemy from early February (the stout/crust facet combo). Finally, drifting snow on leeward aspects has formed reactive slabs along ridgelines and steep rollovers. If/when precipitation switches to rain, expect the avalanche danger to spike across all zones. If you find areas with 8 inches or more of recent snow, expect avalanches to be easily triggered by the weight of a rider or snowmachine.\nThe safest bet for today is to avoid traveling under avalanche paths or near connected terrain, as you could trigger avalanches from a distance or below.'}

19
{'author': 'Guy Zoellner', 'date': '2024-02-28', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 2, 'likelihood': 'possible', 'size': ['Large (D2)', '', 'Very Large (D3)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': 'Don’t lose sight of the weak faceted snow that sits atop (or several inches above) the early February crust. This layer will be buried 3-4 feet below the surface. An inch of water throughout the day combined with active wind-loading may be enough weight to awaken this weak layer. Shaded, northerly aspects above 6,500’ are the most suspect. Yesterday (Tuesday) I found the weak layer in the northern Swan Range. A fatality associated with these facets just north of the border, near Fernie, implies its presence in all three of our forecast zones.\xa0 Winds will actively load the same slopes today where this facet/crust combo exists. I would give shaded upper elevation slopes lots of room today as any avalanche that breaks on this weak layer will likely be large to very large and entrain a significant amount of snow. Avalanches on this layer may break further than you expect, run long distances, and be difficult to escape.'}, {'problem_type': ' Wind Slab', 'problem_number': 1, 'likelihood': 'very likely', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'northwest'], 'middle': ['north', 'northeast', 'east', 'northwest'], 'lower': []}, 'discussion': 'Strong southwesterly winds will transport recent snow into fresh slabs on the leeward side of ridgelines, saddles, and in cross-loaded gullies. Up to a foot of expected snow and moderate to high winds will result in obvious dunes and drifts. Cracking in the snow underneath you or your machine is providing bulls-eye data that you’re on top of recently drifted snow and should steer you toward more sheltered terrain.\xa0 Snow will be actively transported today and reactive slabs of recently drifted snow will form quickly.\xa0 Expect the surface to change as the day progresses and plan accordingly. Don’t hem yourself in by only having one egress route out of the terrain you are in.\xa0 Steep, sheltered terrain that receives 8 inches or more of snow today could present a storm slab problem.\xa0 Any sluffing indicates a potential loose snow problem. Maintain awareness of what is below you and steer clear of steep convexities above consequential terrain(like cliffs, trees or gullies).'}], 'bottom_line': 'An Avalanche Watch is in effect until 18:00 this evening. Dangerous avalanche conditions will develop as winds and snowfall increase today and tonight. Fresh slabs will build on leeward terrain, and add stress to a weak layer buried 3-4 feet. Any avalanche today could entrain a large volume of snow, making escape difficult. Wind-sheltered, low-angle terrain will still provide enjoyable conditions.\xa0\nThe danger may not rise to HIGH until sundown or tonight.', 'discussion': "Storm days are the best. The raw power and artistry of Mother Nature doing her thing are always fun to watch. The sculpting of the wind on recent snow will leave us with a new masterpiece in the mountains. Danger will rise throughout the day.\xa0 If the forecast verifies, we will reach HIGH sometime this evening.\xa0 We've listed upper elevations at HIGH in all zones in case things come in a little earlier or spicier than anticipated.\xa0\nThere are several things to remember as we take in the fresh slate over the next few days.\n1). There is uncertainty about the timing of the storm today and snowfall amounts.\xa0 Keep in mind that the hazard will INCREASE throughout the day.\xa0 IF storm totals for wind and snowfall deliver as predicted then the danger rating will rise to HIGH.\n2). Don’t forget the buried weak layer. We haven’t received any reports lately of the facet/crust being reactive in stability tests. And we haven’t heard of an avalanche in our forecast area associated with this layer for a week. But people keep finding the structure present, and it is going to get a rapid load over the next 24 hours.\xa0\xa0\n3). There is plenty of snow available for transport and all three ranges are forecasted to see Southwest winds in the 30’s and an additional 10-20 inches of snowfall. Fresh wind-slabs will be easy to find over the next several days. Give these slabs a few days before venturing across them to find better snow in the sheltered terrain.\n4). There is a chance of freezing levels reaching 5,000 feet.\xa0 If you start to see rollerballs in the lower elevations or snow falling out of the trees then seek out lower angle terrain.\xa0\xa0\nStorm days such as this are great times to get wheelies on the snowmobile locked in, or explore low angle old growth spruce powder turns. There is plenty of fun terrain to be had without entering up on slopes that are dealing with fresh loading."}


20
{'author': 'blase reardon', 'date': '2024-02-27', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 2, 'likelihood': 'possible', 'size': ['', 'Large (D2)', ''], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': 'Ride to reduce your chances of triggering large avalanches that break on old, weak snow. The new and drifted snow of the past few days have thickened and stiffened the slab sitting on thin, persistent weak layers buried 1 to 3 feet above the snow surface and inches above a very hard crust from early February. Propagation in some snowpack tests before the storm indicates that these layers are not yet dormant. The additional load may have reactivated them. Minimize your time on and under steep slopes, particularly those that are convex in profile and that may be scoured by recent winds. Thin spots in the slabs are likely trigger points and are more common in slopes with these characteristics. You can trigger these slabs from below or from adjacent slopes, so keep an eye on your riding partners. Park well out of runouts so if a partner is surprised, you can keep eyes on them and minimize your search time.\xa0'}, {'problem_type': ' Wind Slab', 'problem_number': 1, 'likelihood': 'likely', 'size': ['', 'Large (D2)', ''], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'south', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'south', 'northwest'], 'lower': []}, 'discussion': "Powerful winds have raked the Flathead Range, McDonald Valley, and Marias Pass the past two days, drifting snow into hard slabs that can react unpredictably to the weight of a rider or snowmachine. Be alert for smooth, pillowy snow surfaces. These may feel or sound hollow or drum-like. Avoid steep terrain where you find these dense slabs. They can release well above a rider and break much wider than expected. The hard chunks of debris can deliver a serious pummeling to a person caught and carried. With continued loading today, natural avalanches remain possible in upper elevations. The debris from these slides can run into middle and low elevations. Avoid the runouts of steep, wind-laoded start zones. These slabs will be more widespread than usual, thanks to both the strong wind speeds and shifting wind directions. The location rose for this problem highlights the terrain where they'll be most widespread. You may find isolated slabs on typically windward slopes, much further below ridges than usual, or cross-loaded onto odd sides of gullies and other terrain features. Sticking to wind-sheltered terain where the snow is soft is a great strategy for minimizing your risk and maximizing your riding quality."}], 'bottom_line': 'Strong winds have drifted recent snow into dense, unstable slabs that, because of variable wind directions, exist on a variety of aspects and elevations. Avoid the runouts of steep start zones well above you, particularly if you see blowing snow at upper elevations. You can still trigger large to very large slabs that break 2 to 3 feet deep, on thin layers of weak snow buried just above a stout, obvious crust. Be very suspicious of steep, shaded slopes at mid and upper elevations.\xa0', 'discussion': "New snow and powerful winds have left dense slabs of drifted snow across the forecast region the past few days. Storm totals (since Saturday morning) have varied, with the northern and eastern parts of the forecast region favored. I'm estimating 12 to 15 inches of storm snow in the northern Whitefish Range, 18 to 20 inches in the upper McDonald Valley in Glacier National Park, and a foot or more in the Flathead Range near Tunnel Ridge. The storm was stingy around Whitefish Mountain Resort and the in the Swan Range, where storm totals look to be 4 to 7 inches.\xa0\nThe winds, however, were much more equitable. Most stations recorded hourly averages of 25 to 45 mph Sunday, with gusts of 40 to 80 mph - and over 100 mph at Tunnel Ridge. Wind speeds dropped to the single digits Monday when arctic air arrived. They look to veer back to the west and southwest today, and pick up again.\nThe storm's legacy today is dense slabs of drifted snow that are widespread in typically leeward terrain - NW to NE to SE - and isolated in usually windward terrain. The slabs are mostly composed of snow that fell during the storm, because sun crusts were present on windward slopes prior to the storm.\xa0 So the slabs will be thicker and larger in areas that got more snow, like the northern Whitefish Range, upper McDonald Valley, John F. Stevens Canyon, and the Flathead Range. You'll find them most common at upper elevations. Be on the lookout for dense slabs of drifted snow in unusual spots as well - well below ridges, on usually scoured sides of gullies, etc. The main danger with these hard slabs is that they break unpredictably, so you can get well onto a slab before it releases.\xa0\nThese dense slabs of drifted snow are adding to the load above tricky weak layers now buried 1 to 3 feet below the snow surface and just a few inches above an obvious and very stout crust. These layers were the culprits in a series of accidents and near-misses in the Flathead Range over the holiday weekend. We've had no reports of triggerd slides on these layers in other ranges, though they are present and sometimes propagate in snowpack tests. These layers haven't given much warning prior to releasing\xa0 - no audible collapes and no cracking. I remain very leery of steep, shaded terrain in the Flathead Range. Elsewhere, snowpack tests might be more reliable. Sticking to slopes that are less than 35 degrees and aren't below steeper terrain is the most straightforward way of managing this hazard."}

21
{'author': 'Sarah Williams', 'date': '2024-02-26', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 2, 'likelihood': 'possible', 'size': ['', 'Large (D2)', '', 'Very Large (D3)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': "Sunday's precipitation and wind transport have added weight to the snowpack, stressing weak layers buried 1 to 3 feet below the surface. These layers are found above the very hard, early February ice and crust layer. You can find this weak snow on shady, middle and upper-elevation slopes and isolated sunny slopes.\xa0 Recent mild temperatures have initiated the strengthening of the weak layer, but this process is notoriously slow. You may not experience any signs of instability like collapsing or cracking before triggering a slide.\xa0 Choose terrain free of convexities to increase your safety margin. Steer around thin areas, such as those scoured or peppered with rocks, in favor of a deeper, more consistent snowpack. Cracking beneath your boards or machine indicates an instability directing you to lower-angle terrain.\xa0"}, {'problem_type': ' Wind Slab', 'problem_number': 1, 'likelihood': 'likely', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': "Impressively strong westerly winds will continue to transport Sunday's snowfall into fresh slabs downwind of ridgelines, saddles, and on sidewalls of cross-loaded gullies. These slabs will increase in size and thickness as you gain elevation. Drifts, dunes, and rippled snow surfaces confirm that the wind has been working. Today's blowing snow will be an obvious sign that slabs are forming. In isolated locations favored by snowfall, you may find thin storm slabs on slopes sheltered by wind. They can be identified by cracking at the surface in consolidated, dense snow.\xa0 Whether in sheltered or wind-affected terrain, cracking beneath your machine or boards indicates instability, directing you to lower-angle slopes free of overhead hazards.\xa0 Triggering a small surface slab may initiate a much larger avalanche on a buried weak layer described in our persistent slab problem below. \xa0 \xa0"}], 'bottom_line': 'Strong winds will transport new snow building fresh slabs. Triggering a large avalanche is very likely—primarily in wind-affected terrain. To reduce your risk, avoid slopes with evidence of wind, such as fresh drifts or a stiffer snow surface that supports your skis or sled.', 'discussion': 'We issued an Avalanche Warning for the Flathead Range/Glacier National Park zone on Sunday night, with the start of a powerful storm favoring this area. This zone will remain at high avalanche danger, as we expect natural avalanches to be likely and human-triggered avalanches to be very likely. Traveling in avalanche terrain today, specifically on leeward slopes at upper elevations, is not recommended.\xa0\nStrong winds are the driving force for avalanches in all areas of the forecast region. We’ve listed Wind Slabs as our primary problem. Ridgetop winds are cranking in the Flathead, with Tunnel Ridge recording 104 mph gusts at 4 am. Other regional stations include 78 mph gusts at Hornet and 66 mph at Aeneas Ridge and Snowslip.\xa0\nWarm temperatures associated with the start of this storm have brought impressive SWE totals. Flattop recorded 1.9 inches of water in less than 24 hours, while Stryker recorded 1 inch. The Swan Range missed out in this storm, only picking up 0.3 inches.\nWe expanded the distribution of the lurking Persistent Slab problem to include middle elevations where we’ve observed the facet/crust structure. Impressive wind drifting with the current storm is loading slopes harboring this layer.\xa0 This additional weight could be the tipping point for slabs to fail.\xa0\nTraveling today in the mountains will require monitoring winds and snow. If you are able to keep your hat on, let us know what you see by submitting an observation.'}


22
{'author': 'Mark Dundas', 'date': '2024-02-25', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 2, 'likelihood': 'likely', 'size': ['Small (D1)', '', 'Large (D2)', ''], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': [], 'lower': []}, 'discussion': 'The incoming storm will add weight and stress to weak layers buried 1 to 2 feet below the surface. These layers are found above the very hard, early February ice and crust layer. This weak snow is better developed on shady, upper-elevation slopes but is also found on isolated sunny and mid-elevation slopes.\xa0 Recent mild temperatures have initiated the strengthening of the weak layer, but this process is notoriously slow. You may not experience any signs of instability like collapsing or cracking before triggering a slide.\xa0 Choose terrain free of convexities to increase your safety margin. Steer around thin areas, such as those scoured or peppered with rocks, in favor of a deeper, more consistent snowpack. Cracking beneath your boards or machine indicates an unstable slab directing you to lower-angle terrain.\xa0'}, {'problem_type': ' Storm Slab', 'problem_number': 1, 'likelihood': 'very likely', 'size': ['Small (D1)', '', 'Large (D2)', ''], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'south', 'southwest', 'west', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'south', 'southwest', 'west', 'northwest'], 'lower': []}, 'discussion': "Strong westerly winds will transport today's snowfall into fresh slabs downwind of ridgelines, saddles, and on sidewalls of cross-loaded gullies. These slabs will increase in size and thickness as you gain elevation and the day progresses. Drifts, dunes, and rippled snow surfaces confirm that the wind has been working. Today's blowing snow will be an obvious sign that slabs are forming. As snow totals increase, storm slabs may develop in locations sheltered from the wind. These will be thinner but may become more widespread than the above-mentioned wind slabs. They can be identified by cracking at the surface in consolidated, dense snow.\xa0 Whether you are in sheltered or wind-affected terrain, cracking beneath your machine or boards indicates instability, directing you to lower-angle slopes free of overhead hazards.\xa0 Triggering a small surface slab may initiate a much larger avalanche on a buried weak layer described in our persistent slab problem below. \xa0 \xa0"}], 'bottom_line': "Today's incoming storm will develop dangerous avalanche conditions in areas favored by snowfall and wind. Expect the danger to rise as snow totals increase throughout the day and overnight. Fresh slabs will form initially on wind-drifted slopes and in sheltered locations later in the day. Cracking beneath your boards or machine directs you to seek out lower-angle terrain.\nThe danger may not reach HIGH until sundown or overnight.", 'discussion': "A robust Pacific storm system will move into the area today (Sunday), with heavy snow and blustery winds creating dangerous avalanche conditions. Snowfall and windy conditions will continue overnight and into Monday, with a Winter Storm Warning in effect from noon Sunday until 0800 Monday.\xa0\nSnowfall yesterday and overnight favored the Flathead Range and John F. Stevens Canyon areas, with 5-7 inches. Most other locations were skunked.\nToday's rising danger is related to the incoming snowfall. This morning, most Swan and Whitefish Range slopes will have a generally stable snowpack. The danger will increase after several inches of new snow accumulates. The danger in the Flathead Range and southern Glacier Park is slightly elevated due to recent snow, and the danger will rise sooner in this zone.\nToday's storm will favor the Flathead Range, southern Glacier Park, and interior Glacier. The avalanche danger may reach HIGH later today or overnight in these locations. Forecasted totals for other areas are less. The northern Whitefish Range will receive more than the slopes near the WMR ski area.\xa0 The Swan Range may only receive totals similar to the southern Whitefish Range. We anticipate the danger reaching CONSIDERABLE in these locations.\xa0\nMonitor changing conditions and snow totals throughout the day. With the impressive wind speeds, higher quality riding will be found in terrain sheltered from the wind.\xa0\n\xa0\n\xa0"}

23
{'author': 'Mark Dundas', 'date': '2024-02-24', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 1, 'likelihood': 'possible', 'size': ['Small (D1)', '', 'Large (D2)', ''], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': [], 'lower': []}, 'discussion': 'It is still possible to trigger\xa0a\xa0slab that breaks 1 to 2 feet deep on thin layers\xa0of weak snow above the very hard, early February ice and crust layer. These\xa0layers\xa0are better developed on shady, upper-elevation slopes but are also found on isolated sunny and mid-elevation slopes.\xa0 Recent mild temperatures are helping to strengthen the weak layer, but this process is notoriously slow. You may not experience any signs of instability like collapsing or cracking before triggering a slide.\xa0 Choose terrain free of convexities to increase your safety margin. Steer around thin areas, such as those scoured or peppered with rocks, in favor of a deeper, more consistent snowpack. Cracking beneath your boards or machine indicates an unstable slab directing you to lower-angle terrain.\xa0'}, {'problem_type': ' Wind Slab', 'problem_number': 2, 'likelihood': 'possible', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': 'West and southwesterly winds developed Friday, increased overnight, and will remain elevated today (Saturday). In most windward locations, only several inches of snow are available for transport, which will limit drifting. However, expect to find thin, fresh slabs reactive to the weight of a rider downwind of ridgelines, saddles, and on sidewalls of cross-loaded gullies. These slabs will increase in size and thickness as you gain elevation. Drifts, dunes, and rippled snow surfaces confirm that the wind has been working. Blowing snow and cornices point in the direction of slab formation. Cracking beneath your machine or boards indicates instability, directing you to safer, sheltered terrain.\xa0 Wind slabs will form on the same slopes that harbor our persistent slab problem. Triggering a small wind-drifted feature may initiate a much larger avalanche.\xa0 \xa0 \xa0'}], 'bottom_line': 'Triggering a large avalanche remains a possibility—primarily in wind-affected terrain. In these areas, a slab may exist atop a buried weak layer. To reduce your risk, avoid slopes with evidence of wind, such as fresh drifts or a stiffer snow surface that supports your sled or skis.\nA strong storm will impact the area beginning Sunday, creating dangerous avalanche conditions.\xa0', 'discussion': "A robust Pacific storm system will move into the area on Sunday, with heavy snow and blustery winds creating dangerous avalanche conditions. If the forecast verifies, we may reach CONSIDERABLE danger on Sunday and perhaps HIGH on Monday. Unsettled weather continues throughout the work week, keeping the hazard elevated and new snow avalanche problems on the list.\xa0\nToday (Saturday), we will primarily experience the effects of wind, with the chance of light snow showers developing this afternoon. Due to moderate sustained west and southwest winds, we added wind slab to the problem list. Overnight wind speeds were impressive, with gale force gusts (greater than 38 mph) at many upper elevation stations, with 88 mph recorded at Tunnel Ridge. Despite the limited snow available for transport, riders noted wind-drifted snow filling in their skin track along with small reactive cornices in southern Glacier Park.\nThe last recorded avalanche on a buried weak layer occurred on Monday, 5 days ago. This week's relatively mild temperatures are helping to strengthen this layer found 1 to 2 feet below the surface. Today's wind loading will initially test this weak snow, but the heart punch begins tomorrow with the heavy snow and drifting.\xa0\xa0\nIn the southern Whitefish Range, three groups from the Patrol Fund Level 2 avalanche course submitted observations from just east and west of the ski area (Observation 1, Observation 2, Observation 3). Numerous snowpit tests resulted in non-propagating results except for an ECTP 28 down 37 cm on a south aspect. They looked but could not locate the buried surface hoar (photo) that Rob noted Thursday.\xa0\nFriends Fest is Here! Today, February 24th, is the last day—Hot Dog Days at the Canyon Creek trailhead and the top of Flower Point chair at WMR. Don't miss the Ultimate Après with Backcountry Partner Speed Dating and the Big A$$ Raffle. More info at flatheadavalanche.org/event/friendsfest"}


24
{'author': 'Rob Millspaugh', 'date': '2024-02-23', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 1, 'likelihood': 'possible', 'size': ['Small (D1)', '', 'Large (D2)', ''], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': [], 'lower': []}, 'discussion': 'Triggering a slab that breaks on a weak layer one to two feet deep remains a hazard. The weak layer consists of faceted snow and sometimes surface hoar a few inches above a very hard crust or ice layer formed in early February. This layer is not distinct on some slopes, though the crust and ice are apparent. The hazard exists primarily at upper elevations on steep, shaded slopes, and resulted in two recent accidents and two near misses. You can find this hazard on isolated slopes elsewhere, including middle elevations and solar aspects. Reduce your risk through careful terrain selection during your climb, traverse, or descent. Evaluate slope angles, slope shapes, potential trigger points, and the consequences of a slide.\xa0 Good options include slopes that are less than 35 degrees in steepness, concave (bowl-shaped) or planar in shape, and not peppered with rocks and trees or punctuated by cliff bands, gullies, or abrupt benches.\xa0'}], 'bottom_line': 'On upper-elevation, shaded slopes, you can trigger slabs that break one to two feet deep without obvious signs of instability. Decrease your risk by choosing terrain with a consistent slope angle and free from hazards like cliffs, gullies, and exposed rocks and trees. Travel one at a time and watch your partner from a safe location.', 'discussion': "Once bitten, twice shy: that’s my attitude toward the current persistent slab problem. With two accidents and two near misses in the last week, I feel a bit shier than I usually might at Moderate danger.\xa0\nBesides these incidents, the weak structure has not given obvious signs of instability, like cracking or collapsing. Furthermore, this structure has been challenging to identify in pit profiles and tests, although more recent observations are finding propagation in ECTs. The weak layer presents as a layer of rounding facets and patchy surface hoar 1-2 feet below the surface and a few inches above the stout and well-documented crust from early February. In some cases, it is barely softer than the overlying slab. It has fooled experienced parties, including FAC forecasters.\nDuring my brief tour outside of WMR yesterday (Thursday), I had the luxury of finding an obvious layer of buried surface hoar roughly one foot deep, which propagated with moderate force. This prominent layer appears to be the exception and not the norm. Elsewhere, I'm placing less emphasis on my interpretation of the snowpack and more on spatial variability and uncertainty. The recent incidents and close calls are good reasons to reevaluate and consider increasing your margins by dialing back to less aggressive terrain.\xa0\nWith minimal new snow, we've elected to drop the wind slab problem. Winds at Aeneas Ridge in the Swan Range, Hornet in the Whitefish Range, and along the continental divide have remained adequate for transport and may increase throughout the day. If you are in one of these areas and notice the hallmarks of wind-effected snow, like a scalloped surface or dune-shaped features, consider moving to less steep or more sheltered terrain. Warm temperatures and sunshine in today's forecast mean there is potential for some small wet loose activity; however, this again will be limited by scant snow on crusty solar aspects. Pay attention to the weather and the snow surface throughout the day. If you're on a southerly slope with more than 8 inches of loose snow transitioning to wet, it's probably time to find less steep or less sunny terrain.\nFriends Fest is Here! February 21st-24th: Check out Workshop Night (Tonight) with State of the Snowpack and USGS, Hot Dog Days, Ultimate Après with Backcountry Partner Speed Dating, and the Big A$$ Raffle. More info at flatheadavalanche.org/event/friendsfest\n\xa0"}

25
{'author': 'blase reardon', 'date': '2024-02-22', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 1, 'likelihood': 'possible', 'size': ['Small (D1)', '', 'Large (D2)', ''], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': [], 'lower': []}, 'discussion': "Triggering a slab that breaks one to two feet deep remains a lingering and serious hazard on steep, upper-elevation, shaded slopes. It's an isolated hazard elsewhere. The slabs sit on a layer of weak, faceted snow and sometimes surface hoar a few inches above a very hard crust or ice layer. The weak layer is not that distinct on some slopes, though the crust and ice are obvious. The most reliable way of reducing your exposure to this hazard is to be very picky about the terrain you climb, traverse, or descend. Evaluate slope angles, slope shapes, and runouts. Your risk is lowest on slopes that are less than 35 degrees that are concave (bowl-shaped) or planar, and aren't above trees, rocks, benches, or gullies.\xa0"}, {'problem_type': ' Wind Slab', 'problem_number': 2, 'likelihood': 'possible', 'size': ['Small (D1)', ''], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'northwest'], 'middle': [], 'lower': []}, 'discussion': 'In upper-elevation terrain that collects wind-blown snow, you can trigger small slabs that can be dangerous if they carry you into a gully, trees, or rocks, or over a cliff. That includes the lee sides of ridges and chutes, slopes below cornices, and slopes downwind of saddles. Most of these slabs have formed over the past two days; the slabs could continue developing in areas that receive more than a few inches of snow today. Before climbing or descending this terrain, look for signs of wind-affected snow at the surface - smooth, pillowy drifts or dunes? Check the runout of the slope - free of things that can magnify the consequences of getting caught and carried down?\xa0 If the answer to either question is yes, step back and consider alternatives on wind-sheltered, low-angle slopes.'}], 'bottom_line': 'The best riding with the lowest risk of triggering a slab avalanche exists on shaded, mid-elevation slopes. In this terrain, stick to slopes less than 35 degrees that have runouts free of terrain traps. Elsewhere, a sun crust may make for less quality riding. And on upper-elevation, shaded slopes, you can trigger slabs that break one to two feet deep with little prior signs of instability.', 'discussion': "An innocuous-looking layer of facets and surface hoar continues to pose a danger across the region. It's been the weak layer in at least two accidents - one mine - and two near-misses in the past week.\xa0\nWhile this structure exists across the region, we can narrow down the terrain where you're most likely to get into trouble, based on accident sites and recent observations. The most likely suspects:\n\nFace north to northeast at upper elevations\nAre in the Flathead Range\nAre more than 35 degrees in steepness and aren't adjacent to steeper slopes\nAre convex in profile\n\nAgain, that's the most likely terrain. One unintentionally-triggered slide occurred on a north-northwest facing slope, and another was triggered from a spot that was 33 or 34 degrees. People have reported the structure on mid-elevation slopes in all ranges, where it's propagated in snowpack tests. During the storms that loaded the weak layer, remotely-triggered slides broke on this layer in the Swan Range. A few naturals have also released on southeast-facing slopes. Several of the unintentionally-triggered slides also appear to have released where the slab was thinner, possibly because winds scoured away some of the slab.\nI'm focusing on these characteristics because terrain-based decisions are the most reliable way of avoiding surprises and trouble. The slab above the facets and surface hoar is relatively soft and the weak layer is spatially variable. In those conditions, snowpack tests tend to be less accurate predictors of instability. And none of the parties involved in the past week's incidents reported collapsing or cracking prior to the slides.\xa0\nA secondary, short-lived hazard today is triggering small wind slabs. These aren't widespread, and most are shallow and small. And they're definitely more predictable. Nonetheless, they can be dangerous in steep, consequential terrain, like couloirs and chutes and steep faces. Check for this hazard with thorough assessments before committing to steep, consequential terrain.\xa0"}


26
{'author': 'Guy Zoellner', 'date': '2024-02-21', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 1, 'likelihood': 'possible', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': [], 'lower': []}, 'discussion': 'A weak layer of facets has been the culprit in a series of accidents and near-misses the past four days. This layer is buried 12 to 24 inches deep, and sits 1 to 6 inches above a very hard crust. Moderate temperatures are helping this weak layer to sinter and gain strength. The rate will vary by slope, so you may find the structure present and unreactive in stability tests at one site, yet move several yards away and get a completely different result. This layer remained sensitive to the weight of a rider two days ago (Monday) in the Flathead Range.\xa0 Give steep shaded slopes above 6,500 feet plenty of room today. Choose slopes with runouts clear of trees and gullies. If you find yourself feeling the snow getting warmer and stiffening this afternoon, dial back your terrain selection and retreat to lower slope angles.\xa0'}, {'problem_type': ' Wind Slab', 'problem_number': 2, 'likelihood': 'possible', 'size': ['Small (D1)', ''], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'northwest'], 'middle': [], 'lower': []}, 'discussion': 'Fresh snow and overnight winds have drifted snow near ridgelines.\xa0 Thin windslabs may sit atop several feet of old snow that has buried a weak layer.\xa0 If these break they can propagate much further across the slope than you expect.\xa0 Manage this by keeping to slopes that are planar and runouts that are clear of terrain traps. '}], 'bottom_line': 'Avalanches may still fail at a weak layer buried a few inches above a very hard crust. Overnight winds and a few inches of snow have formed thin pockets of wind drifted snow below ridgelines. Low angle slopes that are protected from the wind will be the most enjoyable today.\xa0\xa0\n\xa0', 'discussion': "Patience is the name of the game with today’s problems.\xa0 A Persistent Slab avalanche\xa0 structure exists across the forecast region. The primary concern is a layer of weak, faceted snow buried 12 to 24 inches below the surface and a few inches above the early February crust/ ice layer. The layer appears most developed in the Flathead Range, where slabs have been\xa0 reactive to the weight of skiers multiple times over the last 4 days (here and here). Several of these slides have been triggered from spots where the slab is thinner. The same facet and crust combo has been reported in the Whitefish and Swan Ranges. However, we’re not getting any reports of triggered avalanches in these 2 ranges. In the Flathead Range incidents, the parties observed no collapsing or cracking prior to triggering the slides. The take home message is that this weak layer may provide very little feedback, until it is breaking underneath you or your machine.\xa0\xa0\nTemperatures hovering around freezing and cloudy skies this morning mean conditions ought to be ripe for traveling on your favorite ridgeline today or riding from one drainage to the next.\xa0 If the sun does break through, or if the temperature exceeds the forecast, beware of loose snow avalanches.\xa0 Clues will be rollerballs and sticky skins. The Flathead Range has seen most south aspects get cooked lately. The Northern Whitefish and Swan ranges still harbor soft snow that hasn't been affected by the sun. This slight warming could also speed settlement and consolidation of the slab above the facets. Find small test slopes and terrain free of hazards below before commiting to a line if you feel this happening.\xa0\xa0We have yet to see the facet/crust combo in the Whitefish and Swan Ranges tested like in the Flathead Range.\xa0\n\xa0"}

27
{'author': 'Cam Johnson', 'date': '2024-02-20', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 1, 'likelihood': 'possible', 'size': ['Small (D1)', '', 'Large (D2)', ''], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': [], 'lower': []}, 'discussion': 'Recent avalanches are a glaring red flag. In the past three days, there have been two accidents and two near-misses, all in the Flathead Range. Additionally, south of the advisory area near Seeley Lake, a rider triggered a large avalanche failing on this same layer. We’ve received no reports of triggered avalanches in the Whitefish Range, though we aren’t ruling the problem out in that zone. Signs of whumpfing, collapsing, and shooting cracks are all signs of instability but are not common with this weak layer. Avalanches are breaking 1 to 2 feet deep, on weak facets a few inches above a hard crust. The best tactic is avoidance. Slopes that face north and east are proving most sensitive. Avalanches have failed on slopes with angles in the low 30-degree range.'}, {'problem_type': ' Wind Slab', 'problem_number': 2, 'likelihood': 'possible', 'size': ['Small (D1)', ''], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': 'Winds will drift new snow into fresh slabs sensitive to the weight of the rider. Slabs of drifted snow should be small unless snow accumulations exceed forecast totals. Pay attention to the amount of freshly fallen snow and signs of instability. Cracking around your boards or machine is a sign of an unstable slab.\xa0 Slabs of wind-drifted snow are adding weight to a poor snowpack structure. A small avalanche may easily step down to a weak layer buried 1 to 2 feet below the surface. If this occurs, slabs will break wider than you may expect and be difficult to escape.'}], 'bottom_line': 'Large human-triggered avalanches occurred within the last 24 hours. Stick to lower angled slopes on shaded aspects above 6500 feet. New snow and southwest winds will form thin slabs of drifted snow. Windward aspects are safer options for riding.\xa0', 'discussion': 'Today, southwest winds will drift the couple of inches of new snow that falls. Expect thin and small slabs to form on leeward-facing aspects. A sun crust will limit the amount of snow available for transport, so drifting should be fairly minimal. The aspects being drifted are the same aspects where people have triggered large avalanches failing on a persistent weak layer 1 to 2 feet below the surface.\nReported human-triggered avalanches are confined to shaded aspects above 6500 feet in the Flathead Range. I suggest dialing slope angles back wherever you feel a hard crust buried more than a foot below the surface. Signs of instability and snowpack tests are not providing negative feedback, which may dupe a person into thinking the slope is stable. Here is an example.\nYesterday, Blase and I visited the crown of a recent human-triggered avalanche. This avalanche failed on facets a few inches above the early February crust. During our descent, we unintentionally triggered a neighboring slope. The start of this slope had a planar/concave shape with slope angles in the low 30s. The slope was relatively short and sparsely vegetated. Prior to the slide, we observed no signs of unstable snow on neighboring slopes and no alarming results in tests. The one red flag was the nearby avalanche.\xa0 The first rider on the slope triggered the slide just below the ridgeline and could not escape the moving debris. The rider was caught, carried, and lost some equipment.\xa0\nExperienced teams and veteran forecasters are getting surprised. This is not a problem to try to outsmart. Keep it simple.\xa0\nUpcoming event: Flathead\xa0Avalanche\xa0Friends Fest, February 21-24.\xa0We have four days of events on tap for you:\xa0Beacons\xa0& Brews, Name That Tune/Name That Avalanche, Workshop Night with State of the Snowpack and USGS, Hot Dog Days, and the Ultimate Après with Backcountry Partner Speed Dating and the Big A$$ Raffle. More info at\xa0flatheadavalanche.org/event/friendsfest'}


28
{'author': 'Sarah Williams', 'date': '2024-02-19', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 1, 'likelihood': 'possible', 'size': ['Small (D1)', '', 'Large (D2)', ''], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': [], 'lower': []}, 'discussion': "Saturday's avalanche activity verified that it is still possible to trigger\xa0a\xa0slab\xa0that breaks 18 to 24 inches deep on thin\xa0layers of weak snow above the very hard, early February ice and crust layer. Notably, these layers\xa0are better developed on shady, upper-elevation slopes but are also found on isolated sunny and mid-elevation slopes.\xa0 The weekend's warm temperatures and recent winds have stiffened the snow surface, forming a slab in many locations. You may not get warning signs of unstable snow, such as cracking beneath your boards or machine. Choose terrain free of convexities to limit the chance of triggering a slide. Steer around thin areas, such as those scoured or peppered with rocks, in favor of a deeper, more consistent snowpack.\xa0"}], 'bottom_line': 'A lurking weak layer in the snowpack has resulted in recent large avalanches. Traveling in the mountains today requires the knowledge that there is still a possibility of triggering a 1-2 foot thick slab avalanche. Choose terrain free of convexities to limit your chance of triggering a slide.\xa0', 'discussion': "On Saturday, three separate skier-triggered avalanches in the Marion Lake area were symptoms of a Persistent Slab problem.\xa0 These slides resulted in one incident which required a helicopter evacuation, as well as two close calls. As we investigated the characteristics of these avalanches, some themes emerged.\nTemperature:\xa0Friday’s solar input began the initial warming of cold surface snow, which accelerated with Saturday's warmer temperatures. This transition from a loose surface to a consolidated slab was the missing ingredient for the Persistent Slab problem. An impressive temperature change is a hallmark of increasing instability within the snow. Regarding the three avalanches occurring on February 17th, all three slides occurred in the afternoon, around or slightly after the day’s peak warming.\nTerrain: Skiers triggered slides on steep, northerly upper-elevation slopes with convex rollovers in all three avalanches.\xa0 These slopes have been the target of FAC’s messaging about the current Persistent Slab problem. The snowpack’s structure of weak faceted snow above a stout crust has been unpredictable, and multiple people have skied similar or adjacent slopes before triggering an avalanche. The lack of obvious signs of instability increases the need to pay attention to terrain features. Thin parts of the snowpack and convexities increase the probability of propagating an avalanche.\nCommunity: All three parties involved in Saturday’s events were transparent and forthcoming with details of each incident. For the skier caught and carried, it was extremely fortunate to have ski partners who acted quickly and thoughtfully. Two Bear Air and ALERT Air Ambulance were invaluable resources that evacuated and transported the victim to the hospital for overnight care.\xa0\nPracticing safe travel habits can stack the odds in your favor. These habits include communicating and being aware of your partner’s intended travel.\xa0 Get in the habit of identifying potential avalanche paths and positioning yourself in a safe spot within the terrain. Unpredictable avalanches, such as the current Persistent Slab problem, should garner your respect. If you head out into the mountains today, be mindful of changing conditions, the slope aspects you ride, and where you and your partners are positioned in the environment.\nUpcoming event: Flathead\xa0Avalanche\xa0Friends Fest, February 21-24.\xa0We have four days of events on tap for you:\xa0Beacons\xa0& Brews, Name That Tune/Name That Avalanche, Workshop Night with State of the Snowpack and USGS, Hot Dog Days, and the Ultimate Après with Backcountry Partner Speed Dating and the Big A$$ Raffle. More info at\xa0flatheadavalanche.org/event/friendsfest"}

29
{'author': 'Mark Dundas', 'date': '2024-02-18', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 1, 'likelihood': 'possible', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'northwest'], 'middle': [], 'lower': []}, 'discussion': "A slide on Saturday confirms it is still possible to trigger\xa0a\xa0slab\xa0that breaks 18 to 24 inches deep on thin\xa0layers\xa0of weak snow above the very hard, early February ice and crust layer. These\xa0layers\xa0are better developed on shady, upper-elevation slopes but are also found on isolated sunny and mid-elevation slopes.\xa0 Saturday's warming and recent winds have stiffened the snow surface, forming a slab in many locations. The slab was the missing ingredient, which may be why observations have noted few avalanches on this layer until yesterday. Choose terrain free of convexities to limit the chance of triggering a slide. Steer around thin areas, such as those scoured or peppered with rocks, in favor of a deeper, more consistent snowpack. Cracking beneath your boards or machine indicates an unstable slab directing you to lower-angle terrain.\xa0"}], 'bottom_line': 'Skier-triggered slides on Saturday confirm that releasing a 1-2 foot thick slab avalanche on a buried weak layer remains possible. Pay attention to changing snow surface conditions throughout your tour. Treat upper-elevation shaded slopes with respect, as these slopes can catch you off guard and are suspect of sliding in surprising ways.', 'discussion': 'Following a week of well below-average temperatures, yesterday\'s sunshine resulted in southerly slopes feeling like spring. However, air temperatures remained cool with just one mid or upper-elevation station, Hornet (6500\'), warming above freezing.\xa0\xa0\nAs expected, the strong mid-February sun affected the cold, dry snow surface on steep southerly aspects. Most observations noted loose snow slides that ran on Friday or Saturday (Observation), with one party witnessing a D2 dry loose slide in action (Observation). At the same time, another group watched a small dry loose trigger a storm slab, resulting in a D2 slide (Observation).\xa0\nOn Saturday, two parties in the Marion Lake area above Essex unintentionally triggered large slab avalanches. Our limited knowledge of one incident where a member was injured is found here. A skier triggered a slide that caught another member of the party below. The victim was carried through small trees and came to rest, partially buried and injured. Two Bear Air extracted the individual, who was treated for serious but non-life-threatening injuries. Another party had skied a nearby slope earlier in the day. An Extended Column Test they conducted before skiing scored ECTN; it broke but did not propagate on an interface between storm layers within 2 feet of the surface. We believe the slide was on an east aspect above the head of the lake, but we are not sure of the elevation. We will update our website with more information as it becomes available.\nA thorough observation by the other party is here. This observation contains a wealth of information, and we appreciate this group for sharing this information in the name of public safety. This avalanche fractured with the third skier on the slope at the skier\'s skis and ran full track through a convoluted avalanche path. The slide was on a north aspect at 7100\' and failed as a hard slab on a layer of facets above the early February crust. The party noted, "The avalanche caught us completely off guard, given our other observations throughout the day on similar aspects and at similar elevations." They also shared this pearl of wisdom, "Please keep heads up out there and don\'t get lulled into a false sense of security because you aren\'t finding the problem everywhere - that\'s the sneaky part about persistent weak layers."\nThe bluebird weather allowed for views of avalanche activity associated with the late-January and early February warming and atmospheric river along with the February 11 and 12 storm cycle. Check out these observations for more details (Observation 1, Observation 2, Observation 3).\nUpcoming event: Flathead\xa0Avalanche\xa0Friends Fest, February 21-24.\xa0We have four days of events on tap for you:\xa0Beacons\xa0& Brews, Name That Tune/Name That Avalanche, Workshop Night with State of the Snowpack and USGS, Hot Dog Days, and the Ultimate Après with Backcountry Partner Speed Dating and the Big A$$ Raffle. More info at\xa0flatheadavalanche.org/event/friendsfest'}


30
{'author': 'Mark Dundas', 'date': '2024-02-17', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 2, 'likelihood': 'possible', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'northwest'], 'middle': [], 'lower': []}, 'discussion': "It is still possible to\xa0trigger\xa0a\xa0slab\xa0that breaks 18 to 24 inches deep on thin\xa0layers\xa0of weak snow above the very hard, early February ice and crust layer. These\xa0layers\xa0are better developed on shady, upper-elevation slopes but are also found on isolated sunny and mid-elevation slopes.\xa0 The surface snow in many locations remains soft and unconsolidated. Exceptions to this are where the wind has stiffened the surface or today's warming consolidates the snow into a denser slab. Cracking beneath your boards or machine indicates an unstable slab directing you to lower-angle terrain.\xa0"}, {'problem_type': ' Dry Loose', 'problem_number': 1, 'likelihood': 'likely', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'south', 'southwest', 'west', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'south', 'southwest', 'west', 'northwest'], 'lower': []}, 'discussion': "Cold weather has preserved the recent 1-2 feet of surface snow on many slopes. Today's sunshine and slightly warmer temperatures may initiate loose snow slides on steep slopes that face the sun. Riders may trigger sluffs on steep, shaded terrain. Both of these can potentially entrain substantial snow in large, continuous terrain.\xa0\xa0 Snow falling from tree branches, sluffing from rock outcroppings, and small rollerballs are precursors to a loose slide. Either move to a different aspect or choose lower-angle slopes. Manage your sluff and limit time spent above terrain traps and in long-running gullies."}], 'bottom_line': 'Natural loose snow avalanches may occur on steep slopes that face the sun or are initiated by riders on shady aspects. It remains possible to trigger a 1-2 foot thick slab avalanche on a buried weak layer where the surface snow is consolidated. Pay attention to changing snow surface conditions throughout the day.\xa0', 'discussion': "A Bluebird Saturday is on tap to reward the hard-working mid-week employees. Another cool day is expected, although warmer than yesterday. This morning, temperatures at mid and upper elevations are generally several degrees warmer except in the eastern part of the advisory area, where Marias Pass is +29 F and Shed 7 +16 F from yesterday.\nA day of sun and warmer temperatures may initiate natural loose snow avalanches on sunny slopes, especially this afternoon. In most locations, the tree branches still hold substantial snow, as I observed above Essex yesterday. Today's warming may shed this snow, initiating rollerballs or loose slides upon impact with the surface snow.\xa0 Rock outcroppings facing the sun will heat and possibly shed their snow cover. These slides will gain mass as they move downhill, perhaps running fast and far in the unconsolidated surface snow. Loose slides in the 1-2 feet of soft surface snow can be triggered by riders on shaded slopes, as this group experienced in Cascadilla yesterday.\xa0\nToday's warming may consolidate the surface snow, forming a denser slab on top of potentially weak layers. Note where your boards or machines do not sink as deeply into the snow surface and steer around these areas in favor of softer snow or lower-angle terrain for a more enjoyable and safer experience.\xa0\nWinds have shifted to the southwest after a few days of north and easterly flow. We removed wind slab from the problem list, but in isolated locations, riders may still be able to trigger a slide in the dense wind-drifted snow on atypical aspects. An experienced rider identified and avoided these in the southern Whitefish Range in favor of soft boot top powder.\xa0\nUpcoming event: Flathead\xa0Avalanche\xa0Friends Fest, February 21-24.\xa0We have four days of events on tap for you:\xa0Beacons\xa0& Brews, Name That Tune/Name That Avalanche, Workshop Night with State of the Snowpack and USGS, Hot Dog Days, and the Ultimate Après with Backcountry Partner Speed Dating and the Big A$$ Raffle. More info at\xa0flatheadavalanche.org/event/friendsfest"}

31
{'author': 'Rob Millspaugh', 'date': '2024-02-16', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 2, 'likelihood': 'possible', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'northwest'], 'middle': [], 'lower': []}, 'discussion': 'It is still possible to trigger a slab that breaks 18 to 24 inches deep on thin layers of weak snow above the very hard, early February ice and crust layer. These layers are better developed on shady, upper-elevation slopes but are also found on isolated sunny and mid-elevation slopes.\xa0 Opt for planar slopes (with constant slope angle) rather than those with break-overs where the slope abruptly steepens. Limit the consequences of any slides by choosing slopes free of gullies, rocks, and trees. Whumpfing collapses and shooting cracks are clear signs of unstable structures. When in doubt, you can further reduce your risk by defaulting to less steep terrain.\xa0'}, {'problem_type': ' Wind Slab', 'problem_number': 1, 'likelihood': 'possible', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['southeast', 'south', 'southwest', 'west'], 'middle': [], 'lower': []}, 'discussion': "You can find slabs of wind-drifted snow on slopes that are usually windward due to recent northeast winds. Most will be small and tough to trigger, though they can have big consequences in extreme terrain or terrain traps. Decreasing windspeeds should limit any growth today.\xa0 Identify wind-affected snow from surface clues like a rippled surface or pillowy, dune-shaped features.\xa0 Expect to find these along ridgelines, gullies, and other prominent terrain features. Cracking around your boards or machines indicates that wind-blown snow is sensitive to human triggering. Pick lines that aren't above cliffs, rocks, gullies, and trees, so you're less likely to be buried or injured if surprised by a slide."}], 'bottom_line': 'Safely enjoy today’s sunshine by recognizing—and steering away from— wind-drifted snow along alpine ridges. Use small and inconsequential slopes to test recent snow before committing to steep terrain. Reduce the consequences of a slide by limiting travel above hazards like gullies and cliffs. \xa0', 'discussion': 'Dry conditions today should keep us on a trend toward stability.\xa0 Snowfall from early this week continues to settle on top of the remarkably stout and well-documented crust from early February.\xa0 However, weak faceted snow and patchy surface hoar on or near this crust remain a concern, particularly on shaded slopes above 6500\' (where we\'ve had limited recent observations). The last reported activity on these layers was Tuesday (Flathead Range, here). Wednesday, several parties felt comfortable transitioning to a "stepping out" mindset by riding slopes greater than 30 degrees in steepness though they still avoided likely trigger points and terrain traps. With great riding conditions and forecasted blue skies, I expect folks will be getting after it today and tomorrow.\xa0 If you\'re one of those folks, consider starting small before committing to larger and steeper slopes.\xa0 Also, let us know what you find during your travels: we received no observations from yesterday. Even reports of benign conditions are useful.\nOur Canadian neighbors are reporting a similar but more active snowpack.\xa0 On Wednesday, A skier near Fernie triggered a large (D2) slab avalanche on a southeast aspect at 6400\'.\xa0 Also on Wednesday, explosives mitigation near Fernie produced many large (D2) avalanches in the alpine on nearly all aspects.\nUpcoming event: Flathead\xa0Avalanche\xa0Friends Fest, February 21-24.\xa0We have four days of events on tap for you: Beacons\xa0& Brews, Name That Tune/Name That Avalanche, Workshop Night with State of the Snowpack and USGS, Hot Dog Days, and the Ultimate Après with Backcountry Partner Speed Dating and the Big A$$ Raffle. More info at\xa0flatheadavalanche.org/event/friendsfest'}


32
{'author': 'blase reardon', 'date': '2024-02-15', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 2, 'likelihood': 'possible', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'northwest'], 'middle': [], 'lower': []}, 'discussion': "Planar slopes with runouts clear of terrain traps will be your safest bet today. In this terrain, you are less likely to trigger slabs 18 to 24 inches thick that release on thin layers of weak snow above the very hard, early-February ice and crust layer. These layers are most developed on shady, upper elevation slopes; they're isolated on sunny and mid elevation slopes.\xa0 Pick slopes with a roughly constant angle all the way up or down, rather than those with breaks where the slope abruptly steepens. Surprises and misjudgments will result in less serious consquences on slopes that are free of gullies, rocks, and trees. Regardless of the aspect or elevation, whumpfing collapses and shooting cracks are clear signs of unstable structures.\xa0"}, {'problem_type': ' Wind Slab', 'problem_number': 1, 'likelihood': 'possible', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['southeast', 'south', 'southwest', 'west'], 'middle': [], 'lower': []}, 'discussion': "Look for - and dodge around - dense slabs of drifted snow. You'll find these on slopes that are usually windward, because winds have been blowing from the northeast. Most will be small and tough to trigger, though they can have surprisingly big consequences on steep slopes above terrain traps. Cracking around your boards or machines indicates you've found a spot where the wind-blown snow isn't well bonded to softer, lower-density snow below. Look up and down the full length of your chosen line for uneven, pillowy snow surfaces that can show whether a slope has been top-loaded or cross loaded. Pick lines that aren't above cliffs, rocks, gullies, and trees, so you're less likely to be buried or injured if you're surprised."}], 'bottom_line': 'The likelihood and consequences of triggering avalanches increase today as you climb higher in elevation. Look for - and avoid - freshly formed slabs near ridges and other terrain that catch wind-blown snow. Stick to planar slopes with runouts free of things that can increase your chances of injury or burial in the event of a misjudgment or surprise.', 'discussion': "An artic intrusion has brought winds out of the north, northeast, and east over the past 36 hours. While speeds were light Wednesday, they picked up overnight, with gusts exceeding 50 mph at several stations. These gusty winds may have transported recently-fallen snow, forming drifts and slabs on atypical aspects. These will be larger and more widespread at upper elevations and will likely grow today as the gusty winds continue. I expect wind speeds to diminish by tomorrow morning, with light winds forecast for Friday.\nWe're several days out from the most recent snowfall, and observations indicate that avalanches involving new snow are unlikely. We have no reports of triggered slides breaking on density changes in the recent snow since Tuesday (Flathead Range, here). With up to 4 inches of settlement in the new snow, sluffs of loose snow are unlikely and isolated. So we've dropped the Storm Snow avalanche problem that's been our primary hazard.\xa0\nOur concerns now turn to the potential for triggering slabs up to two feet thick that break on thin layers of old, weak snow. These layers might be composed of small rounding facets, decomposing surface hoar, or both, depending on location. These layers are above the knife-hard ice or melt-freeze crust left by the late January warming and rain. It was buried the first few days in February - the 1st in the Swan Range. the 3rd in most other locations. At some sites, you'll find these layers right above the that ice/ crust complex. In others, it's two to 6 inches higher, at the snow surface buried a week later.\xa0\nWhile this structure is widespread, observations aren't indicating the recently-formed slab is senstive to the weight of a person. We've received only scattered reports of whumpfing collapses (southern Whitefish Range, here and here) and almost no reports of propagation in extended column tests. The caveat, though is that most obs since the storm are from mid elevations. I suspect the weak layers are better developed at upper elevations, particularly on slopes scoured by a previous bout of northeast winds (Feb. 3-4).\xa0\nA stepping out mindset is appropriate today. For my partner and I Wednesday, that meant riding slopes steeper than 30 degrees but avoiding terrain with likely trigger points or higher potential consequences. We were prepared to step back to more conservative terrain if we found signs of instability or a snow structure that was likely to propagate a collapse. We were rewarded with great riding under blue skies and no surprises.\xa0"}

33
{'author': 'Cam Johnson', 'date': '2024-02-14', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Storm Slab', 'problem_number': 1, 'likelihood': 'likely', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'south', 'southwest', 'west', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'south', 'southwest', 'west', 'northwest'], 'lower': []}, 'discussion': '1 to 3 feet of recent snow rests above soft, weak snow. Natural avalanches and remotely-triggered avalanches were reported above 6500 feet on north-east-southeast facing aspects. Shooting cracks and whumpfing collapses have also occurred recently. This is bullseye information for us to utilize today. Whumpfing collapses, shooting cracks, and recent avalanches are all signs of unstable snow. Today, expect to observe these warning signals more commonly on shaded aspects where slabs rest over weak layers. Slabs can be triggered from a distance and propagate surprisingly far distances. Keep an eye out for wind-drifted snow in atypical locations. Look for dune-shaped drifts and wind-textured surfaces. Although remote weather stations reported light wind speeds, easterly winds are notorious for drifting snow where they gain momentum as they channel through terrain features.'}], 'bottom_line': 'Small to large avalanches failed on slopes above 6500 feet in the past 48 hours. Shooting cracks, recent avalanches, and audible collapses should point you to lower-angle terrain. Avalanches may be triggered from afar and wrap around terrain features. Give the snowpack time to adjust before riding in steep, consequential terrain.\xa0', 'discussion': 'We have kept the danger rating elevated in the Swan and Flathead Ranges.\xa0 Although we suspect natural avalanche activity to be over, human-triggered avalanches may still be likely. Conditions will be more dangerous near the crests of the Flathead Range and Swan Range where more snow fell. This recent snow landed on weak layers that may be slow to gain strength.\xa0\nRecent storm totals vary throughout the forecast region. Below are Snow Water Equivalent (SWE) totals starting February 8th:\nNoisy Basin in the Swan Range: 4.8 inches\nStahl in the northern Whitefish Range: 2.5 inches\nWhitefish Mountain Resort in the southern Whitefish Range: 1.6 inches\nFlattop in Central Glacier National Park: 2 inches *The Flathead Range, especially along the crest in the Middle Fork Corridor, likely received more precipitation.\nSouthwesterly winds during the storm were generally unimpressive. Blase did find wind-thickened slabs along the crest of the Swan Range on Monday. I’d suspect to find similar conditions along other exposed ridgelines. Winds flipped directions to the east yesterday. Easterly winds can wreak havoc on lower and middle-elevation slopes. Winds commonly channel through valleys, leaving some areas scoured and drifted, with other valleys untouched. Easterly winds are going to ramp up to transportable speeds this evening. If you are out late or planning an evening ride, pay close attention to wind-drifting snow. Slabs will become more sensitive to the weight of a rider.\nRecent snow landed on a variety of weak surfaces that vary by aspect. Near-surface facets and surface hoar exist on shaded slopes. We suspect these will be the most sensitive and dangerous slopes at the moment. These are the same slopes that remotely triggered avalanches have failed on.\nA crust/facet/crust combination exists on various solar aspects. This structure has been reported in all three ranges. It is more difficult to predict when these aspects will become active. The upper crust allows the weak layer to withstand a larger load before collapsing. This structure can produce very large avalanches IF it receives a substantial loading event.\nKeep an eye on the sun and the surface snow IF temperatures become warmer than forecasted. Rollerballs, pinwheels, and point releases out of steep, rocky terrain indicate an impending Wet Loose cycle. Cold air should limit this problem today.\nUpcoming event: Flathead\xa0Avalanche\xa0Friends Fest, February 21-24.\xa0We have four days of events on tap for you: Beacons\xa0& Brews, Name That Tune/Name That Avalanche, Workshop Night with State of the Snowpack and USGS, Hot Dog Days, and the Ultimate Après with Backcountry Partner Speed Dating and the Big A$$ Raffle. More info at\xa0flatheadavalanche.org/event/friendsfest'}


34
{'author': 'Guy Zoellner', 'date': '2024-02-13', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Storm Slab', 'problem_number': 1, 'likelihood': 'likely', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'south', 'southwest', 'west', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'south', 'southwest', 'west', 'northwest'], 'lower': []}, 'discussion': 'Freshly fallen and wind-drifted snow will remain sensitive to a skier or snowmachiner. Yesterday (Tuesday), remotely triggered avalanches large enough to bury and injure a person occurred in the Swan Range (observation). Winds formed harder and thicker slabs along ridgelines.\xa0 Cracking in the snow around you or whumpfing sounds are clues you’ve found unstable snow.\xa0 Retreat to lower-angle slopes if you notice these signs. Remember, all of the new snow in the last 48 hours has fallen on a faceted crust from early February.\xa0 Any slab that fails on this layer will likely extend much further than expected.\xa0 '}], 'bottom_line': 'New snow and recently drifted snow have developed dangerous avalanche conditions.\xa0 Soft slabs 1-2 feet thick will be reactive to the weight of a skier or snowmachine.\xa0 Lower your risk by giving steep slopes plenty of room.\xa0 Avalanches that fail today could be larger than you anticipate.', 'discussion': "Skunked, kind of.\xa0 While we all were hoping to wake up this morning and find weather stations reporting another foot of snow overnight, the faucet was turned off. \xa0 24-hour snowfall totals in the Whitefish range reported 3-9 inches, the Flathead range saw 4-7 inches and Noisey Basin received 6 inches.\xa0 These numbers account for recent snowpack settlement, so storm totals are likely much greater.\xa0 The storm put down an impressive total of 2.7 inches of water at Noisy Basin and 1.7 inches at Stahl Peak.\xa0\nThe problem today encapsulates many things.\xa0 Winds have thickened slabs and drifted snow along ridgelines.\xa0 Over a foot of snow has fallen in the last 48 hours in sheltered terrain.\xa0 This new snow fell on facets above a very thick crust from early February.\xa0 There is complexity today as the snowpack adjusts to the recent loading.\nConfidence is high that all aspects and elevations in the forecast area were affected by unseasonably warm weather in late January.\xa0 Several inches of light snow then fell making travel difficult and sluffing snow a problem.\xa0 This problematic soft snow faceted above the crust.\xa0\xa0Now, today, it's buried by 1 to 2 feet of recent snow.\xa0 Avalanches that fail at this interface may extend around terrain features and be triggered from further away."}


35
{'author': 'Cam Johnson', 'date': '2024-02-12', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Storm Slab', 'problem_number': 1, 'likelihood': 'likely', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'south', 'southwest', 'west', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'south', 'southwest', 'west', 'northwest'], 'lower': []}, 'discussion': 'New and recent snow will form slabs sensitive to the weight of a rider, and natural avalanches are possible. Winds will drift snow into thicker and harder slabs along ridge crests. Any triggered avalanches will become larger and more dangerous throughout the day. Pay close attention to your surroundings. Signs of recent avalanches, shooting cracks, or whumpfs should direct you toward lower-angle terrain free of overhead hazards. NOTE: New snow is landing on weak surfaces. This may cause avalanches to propagate wider distances or be triggered remotely. Today is a day to have a "Stepping Back" mindset.'}], 'bottom_line': 'Dangerous avalanche conditions are developing at upper elevations. New snow and wind will form slabs large enough to bury and injure a person. Stick to lower angle slopes if you see 8 or more inches fall throughout the day or see signs of shooting cracks and recent avalanches. Avoid areas of wind-drifting snow and be wary of traveling in the runouts of large avalanche paths.', 'discussion': "Conditions are changing! As conditions change, so should our travel habits. Plan to dial back to more conservative terrain choices throughout the day. New and recent snow is piling up and landing on a weak layer of near-surface facets above a slick crust. This may cause avalanches to break wider distances and in unexpected ways.\nToday’s avalanche forecast relies on today’s precipitation forecast. There is high confidence that the forecast area will receive anywhere from .5 to 1 inch of Snow Water Equivalent (SWE) by Tuesday Morning. This can translate into upwards of 1 to 2 feet of snow. Although the liquid water amounts may not be overly impressive, snowfall rates of 1 inch or more an hour can rapidly increase the avalanche danger. Forecasted snowfall rates like this make it even more important to pay close attention to changing conditions. The avalanche danger WILL rise throughout the day with continued snowfall.\nPrecipitation amounts vary throughout the forecast area and within each forecast region. The Swan Range will see the higher end of precipitation totals. Models show precipitation favoring terrain west of Flathead Lake, so expect the avalanche danger to increase rapidly the further south you travel. The Flathead Range should catch any spillover from the Swan Range. I’d expect to see snowfall totals of 6 to 12 inches in the Flathead Range. The crest of the range will likely wring out the remaining moisture, so expect less snow in southern and central Glacier National Park. The Northern Whitefish Range picked up close to an inch of water yesterday (Sunday) and may be favored with today's snow as well. Areas like Ten Lakes, Red Meadow Pass, and Gibraltar Ridge will see elevated avalanche danger.\xa0"}

36
{'author': 'Sarah Williams', 'date': '2024-02-11', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Wind Slab', 'problem_number': 1, 'likelihood': 'possible', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': 'Saturday, observers noted increasing southwest winds, snow transport, and surface cracking in wind-affected slopes. The wind continued overnight, drifting the 8-12 inches of recent low-density surface snow. Thin, fresh slabs are forming on a layer of lower-density snow, adding to the instability. These features will be larger, thicker, and more widespread at upper elevations while only found in the most wind-prone locations at middle elevations. Look for them downwind of ridgelines and saddles and on the sidewalls of gullies.\xa0 Look for rippled surfaces, hollow-sounding stiff snow, and cracks shooting out from your boards or machine. Blowing snow and cornices point toward the direction of loading. Terrain sheltered from the wind will offer a safer and better riding experience.'}], 'bottom_line': 'Recent snow and increasing southwest winds will form fresh slabs above 5000 feet. Look for blowing snow, dune-shaped drifts, or textured surface snow as visual clues. You can reduce your risk of triggering a slide by avoiding steep, rocky, wind-affected terrain. ', 'discussion': 'As of 5 AM, weather stations report an uptick in southwesterly winds that will redistribute the recent unconsolidated snow. To account for these winds, we’ve transitioned our primary avalanche problem from Storm Slab to Wind Slab. Above 6500 feet, the snow available for transport will develop larger and more widespread slabs, while middle elevations will likely have less snow and wind, making for more isolated hazards.\xa0\nWe dropped our Loose Dry problem today, however keep in mind that fast-running sluffs in steep terrain can still catch you off guard.\xa0 Before committing to a steep line, consider the terrain below you and the consequences of taking a ride into places you don’t want to go.\nObservers from Saturday reported 3 to 12 inches of cohesionless snow over a stout and supportable crust formed in early February. Varying depths across the region favored upper elevations, and many observations described sluff management as their primary hazard. On steep slopes, observers were challenged by sluffing and sliding on the slick crust. For one party in the northern Whitefish Range, a rider was caught and carried 75 feet, but was thankfully not buried and escaped uninjured. Other observers in the southern Whitefish Range (Example 1, Example 2, Example 3) confirmed a loose, dry problem that was straightforward to manage.\nIn the Skyland area, riders reported isolated cracking, wind gusts transporting snow, and warming southern aspects from solar input. This contrasted conditions in the Swan Range, where skies were mostly cloudy, and skiers and riders reported powder turns above 5200 feet. As we enter the workweek, the avalanche danger is expected to rise due to new snow overnight, with accumulations estimated to be 6 to 8 inches or more in favored locations.\nUpcoming event: Flathead\xa0Avalanche\xa0Friends Fest, February 21-24.\xa0Beacons\xa0& Brews, Name That Tune/Name That Avalanche, Workshop Night, Hot Dog Days, and Ultimate Après.\xa0 Check out 4 days of events:\xa0flatheadavalanche.org/event/friendsfest'}


37
{'author': 'Rob Millspaugh', 'date': '2024-02-10', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Dry Loose', 'problem_number': 2, 'likelihood': 'likely', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'south', 'southwest', 'west', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'south', 'southwest', 'west', 'northwest'], 'lower': []}, 'discussion': 'Riders continue to trigger sluffs on steep slopes holding 4-8+ inches of unconsolidated snow above a firm crust. Sluffs will be largest in terrain protected from the sun and wind, where this week’s snowfall remains dry and incohesive.\xa0 Sunshine this morning could trigger natural sluffs on southerly slopes.\xa0 Limit your time spent in confined, long-running gullies where you’ll have difficulty escaping a sluff. Choose descent routes free of terrain traps where moving snow could rake you through exposed hazards or pile up deeply.\xa0 If the sun hangs around longer than anticipated, expect surface snow to transition and run as wet loose, particularly at middle elevations. Rollerballs are a clear sign that the wet snow is primed to slide.\xa0'}, {'problem_type': ' Storm Slab', 'problem_number': 1, 'likelihood': 'possible', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'south', 'southwest', 'west', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'south', 'southwest', 'west', 'northwest'], 'lower': []}, 'discussion': 'The Swan and Flathead Ranges recorded up to a foot of snow in the last 48 hours. This snow fell on a crust on southerly aspects and weak snow on northerlies, adding to the instability. You may find slabs both where the wind has drifted the snow and in sheltered locations. Slabs will be thicker and stiffer at upper elevations downwind of ridgelines and saddles and on the sidewalls of gullies.\xa0 Cracking beneath you or your machine indicates a sensitive slab directing you to lower-angle terrain. Utilize hand pits and small test slopes to assess how the new snow is bonding to the older snow surface.'}], 'bottom_line': 'You can still trigger a slab avalanche in both sheltered and wind-affected terrain. Loose snow sluffs are likely in steep terrain and may run naturally on sunny slopes. Limit your risk by reducing the time you spend traveling above terrain traps like gullies, cliffs, or exposed rocks and trees.', 'discussion': 'As I review the weather and observations this morning, a theme emerges:\xa0 Winter is (kind of) back! Recent snowfall and seasonable temperatures have greatly improved the riding throughout the advisory area. However, in most cases, there is a prerequisite brush thrashing (obs 1, obs 2 , obs 3).\nThis was also the case during a FAC visit to Anna Creek on the East Side of the Swan Range. Throughout our travels, we noted generally unconsolidated snow resting on an impressively stout melt-freeze crust. We were able to kick off fast-running sluffs in extreme terrain on shaded slopes and found a cohesive slab in wind-stiffened snow at the entrance to a couloir. Both of these hazards were easily managed at the time, however, we acknowledged the potential for the faceting surface snow to become problematic once buried. Southeast aspects were particularly interesting as they harbored a crust/facet combination from warming Tuesday/Wednesday this week. Blase and Jeff noted this same structure East of WMR. This structure will be able to support a greater load and may result in larger avalanches once it reaches its limit.\xa0\nUpcoming event: Flathead\xa0Avalanche\xa0Friends Fest, February 21-24.\xa0Beacons\xa0& Brews, Name That Tune/Name That Avalanche, Workshop Night, Hot Dog Days, and Ultimate Après.\xa0 Check out 4 days of events:\xa0flatheadavalanche.org/event/friendsfest'}


38
{'author': 'Mark Dundas', 'date': '2024-02-09', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Dry Loose', 'problem_number': 2, 'likelihood': 'likely', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'south', 'southwest', 'west', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'south', 'southwest', 'west', 'northwest'], 'lower': []}, 'discussion': 'Yesterday, riders triggered sluffing on steep, northerly aspects holding 4-8 inches of weak snow. Snowfall overnight will increase the size of these slides and expand this problem onto southerly slopes, where the snow readily slides on a crust. Natural sluffing may occur on steep slopes with loose surface snow, with rider-triggered slides likely.\xa0 Utilize techniques to manage your sluff. Limit time spent in long-running gullies where getting caught in a sluff may make escape difficult. Choose descent routes free of terrain traps where the snow piles up deep.'}, {'problem_type': ' Storm Slab', 'problem_number': 1, 'likelihood': 'possible', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'south', 'southwest', 'west', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'south', 'southwest', 'west', 'northwest'], 'lower': []}, 'discussion': 'Overnight,\xa0 up to 6+ inches of snow was recorded in the Flathead Range and southern Glacier Park. Snow fell on a crust on southerly aspects and weak snow on northerlies, adding to the instability. Expect to find slabs both where the wind has drifted the snow and in sheltered locations. Slabs will be thicker and larger at upper elevations downwind of ridgelines and saddles and on the sidewalls of gullies.\xa0 Cracking beneath you or your machine indicates a sensitive slab directing you to lower-angle terrain. Utilize hand pits and small test slopes to assess how the new snow is bonding to the older snow surface.'}], 'bottom_line': "Fresh snowfall and wind have increased the avalanche danger. Riders may encounter slabs reactive to their weight in both wind-affected and sheltered areas. Expect to trigger loose snow slides on many steep slopes. Enjoy today's powder on lower-angle terrain so you can do the same tomorrow.\nThe hazard is highest in the Swan Range, where more snow fell.", 'discussion': 'Snowfall Thursday and overnight into Friday morning favored the Swan Range, with over 1 inch of SWE and 7+ inches at Noisy Basin. As of 0500, most other mountain locations had picked up 3-6+ inches with 0.7 inches of SWE at Stryker Ridge in the Whitefish Range. Winds shifted back to the southwest yesterday and are generally light with moderate gusts. The wind is forecast to blow from the north or northeast as a low develops east of the Divide today. Temperatures, thankfully, have fallen back to a cool, seasonable range.\nThe new snow and wind have bumped the avalanche danger following two days of LOW danger.\xa0 The hazard is highest in the Swan Range, where more snow accumulates, and the winds are stronger. The Flathead Range and southern Glacier Park have also done well, with the Whitefish Range lagging. Snowfall should taper off through the day, but fresh slabs will continue forming in wind-affected terrain at upper elevations.\nThe storm was accompanied by intense periods of precipitation. The Noisy Basin SNOTEL recorded 0.5 inches of SWE (4+ inches) in a two-hour period overnight. Snowfall rates greater than 1 inch per hour generally create instability and possible natural avalanche activity. We have rolled a storm and wind slab problem together to mitigate uncertainty. Storm slabs are problem #1 in the Swan and Flathead zones, while loose dry is the #1 problem in the Whitefish Range.\nYesterday (Thursday), Rob, Cam, and Guy explored the terrain around the Anna Creek cabin on the east side of the Swan. They reported having to manage their sluff on steep, northerly aspects where 6-8 inches of faceted, loose surface snow moved downhill easily. Blase and Jeff encountered similar conditions on their tour east of the WMR ski area.\xa0\nUpcoming event: Flathead\xa0Avalanche\xa0Friends Fest, February 21-24.\xa0Beacons\xa0& Brews, Name That Tune/Name That Avalanche, Workshop Night, Hot Dog Days, and Ultimate Après.\xa0 Check out 4 days of events:\xa0flatheadavalanche.org/event/friendsfest'}

39
{'author': 'Mark Dundas', 'date': '2024-02-08', 'zone': 'Flathead Range & Glacier NP', 'problems': [], 'bottom_line': 'Recent benign weather has resulted in a generally stable snowpack. On isolated, steep, northerly slopes, you could still trigger a thin, loose slide that may knock you off your feet or encounter a small slab of wind-drifted snow reactive to your weight. Snow returns overnight into Friday with an increasing hazard.\xa0', 'discussion': "Due to the recent weather and snowpack conditions, we are not listing any avalanche problems today. This is unusual, especially for early February. A summary of the impact of the past few days on the snowpack is listed below.\nTuesday and Wednesday's dry, sunny weather initiated small, wet loose avalanches on solar aspects in the snowfall from earlier in the week and over the weekend (Observation 1, Observation 2). This melting formed a crust on many sunny aspects (Observation). Today's cloudy and cooler conditions will limit the crust's ability to break down and shut down any potential for wet loose slides.\nOn shaded slopes, thin, dry loose slides occurred naturally and were triggered by riders over the past few days (Observation 1, Observation 2). There remains a chance that you could trigger a small sluff in steep, northerly terrain. These should be easy to manage but could become a problem in technical terrain if a rider is knocked off their machine or boards.\xa0\nShifting winds earlier in the week initially transported the new snow into thin slabs on various aspects. The winds have quieted down the past 48 hours, and we feel slabs have gained strength and are generally unreactive to triggering by a rider. Look for signs of wind-affected snow at upper elevations, such as dunes or drifts beneath ridgelines and in gullies. Cracking in this snow indicates instability, directing you to sheltered or lower-angle terrain.\xa0\nSnow will develop later today and into Friday. We expect several inches at all mountain locations, with the Swan Range favored. The avalanche danger will rise overnight, with new snow avalanche problems such as wind slabs and dry loose returning tomorrow.\nAlthough the riding conditions are less than ideal in the Flathead, at least we are not dealing with a nasty persistent slab problem that southwest Montana and the Gallatin National Forest Avalanche Center have. The lower half of their snowpack is faceted (sugar) snow. It has been reactive to nearly every load placed onto it by small storms, resulting in a multi-day elevated avalanche hazard.\nUpcoming event: Flathead\xa0Avalanche\xa0Friends Fest, February 21-24.\xa0Beacons\xa0& Brews, Name That Tune/Name That Avalanche, Workshop Night, Hot Dog Days, and Ultimate Après.\xa0 Check out 4 days of events:\xa0flatheadavalanche.org/event/friendsfest"}


40
{'author': 'Cam Johnson', 'date': '2024-02-07', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Wind Slab', 'problem_number': 2, 'likelihood': 'unlikely', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'northwest'], 'middle': [], 'lower': []}, 'discussion': 'Expect to find slabs up to 1 foot thick on wind-loaded terrain features at upper elevations. These terrain features include slopes below exposed ridgelines and on the sidewalls of gullies. Slabs of drifted snow should be stubborn or unreactive to triggering, however, that does not suggest putting the blinders on. Continue to keep an eye out for textured surfaces and dune-shaped drifts. Signs of cracking around your board or machine should steer you to areas sheltered from the wind. Varying wind directions over the last few days formed slabs of drifted snow on most aspects at upper elevations. The painted distribution identifies the most recently formed slabs. Slabs that formed on south and west aspects this past weekend should be unreactive to trigger.'}, {'problem_type': ' Dry Loose', 'problem_number': 1, 'likelihood': 'possible', 'size': ['Small (D1)', ''], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'northwest'], 'middle': ['north', 'northeast', 'east', 'northwest'], 'lower': []}, 'discussion': 'Manage your sluff with defensive riding strategies if you travel into very steep, northerly-facing terrain that is sheltered from the wind. One defensive riding strategy that comes to mind is to cut across the top of the slope and allow your sluff to run before continuing your descent. Dry Loose avalanches will generally be harmless in size, yet could prove consequential if knocked off your feet above cliff bands or other terrain traps. It is best practice to expose only one rider at a time to steep terrain. A report of a freezing rain crust came in this morning. A thin surface crust will eliminate the chances of triggering a Dry Loose avalanche.\xa0'}], 'bottom_line': 'Today’s avalanche problems are generally small and easy to manage. Expect to trigger Dry Loose avalanches in very steep, northerly-facing terrain. Slabs of drifted snow exist downwind of exposed ridgelines above 6500 feet. Steer around pillowy-looking surfaces and dune-shaped drifts.', 'discussion': 'Most days an avalanche forecast is only as good as a weather forecast. Yesterday was one of those days. Cloud cover opened to clear skies and freezing levels climbed higher than expected, resulting in a round of natural loose wet avalanches on sunbaked slopes. So far, reported avalanche sizes were primarily small (D1), with a couple of large (D2) slides in longer running paths. Expect to find a sun crust on south and west aspects.\nReports of rider-triggered Dry Loose avalanches continue to trickle in, hence the reason for bringing it back to the problem list. This problem is primarily listed for those of you looking to ride in very steep terrain. Since solar aspects were cooked by the sun yesterday, I’d expect this problem to be confined to shaded slopes at middle and upper elevations. Any triggered avalanche should be predictable and easy to manage with slope cuts or other defensive riding strategies.\nWind speeds over the last 24 hours were calm and variable. Slabs of drifted snow will be two to three days old and difficult to trigger. Tuck in below or ride around wind-drifted slabs if your travels take you high into the alpine or into consequential terrain.\nWe removed Persistent Slab as a listed hazard on Monday. You can still find soft facets around a hard crust on many middle and upper-elevation slopes. Recent warm temperatures allowed these facets to gain strength. A supportable crust near the surface also adds strength to the snowpack by reducing the chances of collapsing the weak layer. If your travels take you to the highest elevations in the forecast area, it is still worth digging to look for this structure, especially if you don’t find a supportable crust beneath your feet or machine.'}

In [82]:
stations = {'Flathead Range & Glacier NP':'Shed 7','Swan':'Aeneas Ridge','Whitefish':'WMR Summit'}

def get_weather_table(soup, zone, date):
    forecast_table = soup.find('table', {'class': 'nac-html-table nac-table'})

    # Initialize an empty list to hold all rows of data
    data = []

    # Extract the header row
    headers = [header.get_text(strip=True) for header in forecast_table.find_all('th')]

    # Iterate through each row in the table body
    for row in forecast_table.find('tbody').find_all('tr'):
        cols = row.find_all('td')
        # Extract text from each cell in the row and add to the row data
        row_data = [col.get_text(strip=True) for col in cols]
        data.append(row_data)

    # Create a DataFrame using the extracted data and the headers
    df = pd.DataFrame(data, columns=headers)

    # Adjust the DataFrame to have proper headers
    new_header = ['Metric', 'Last 24 Hours', 'Today', 'Tonight', 'Tomorrow']
    df.columns = new_header
    df['range'] = zone
    df['station'] = stations.get(zone)
    df['date'] = date
    return df

def get_author_date_zone(soup):
    author = soup.find('h6', string='Author').find_next_sibling(text=True).strip()
    zone_element = soup.find('h2', class_='nac-zone-title')
    zone = zone_element.text.strip()
    issued_date = soup.find('h6', string='Issued').find_next_sibling(text=True).strip()
    issued_date = datetime.strptime(issued_date, "%A, %B %d, %Y - %I:%M%p")
    date_formatted = issued_date.strftime('%Y-%m-%d')
    return {'author' : author, 'zone': zone, 'date': date_formatted}

def get_forecast(soup):
    today_forecast_container = soup.find('div', class_='nac-dangerToday')

    forecast = {'upper': '', 'middle': '', 'lower': ''}
    elevation_blocks = today_forecast_container.find_all('div', class_='nac-elevationBlock')
    for block in elevation_blocks:
        elevation_label = block.find('span', class_='nac-elevationLabel').text.strip().lower()
        danger_label = block.find('span', class_='nac-dangerLabel').text.strip().split(' - ')[1]

        if 'upper' in elevation_label:
            forecast['upper'] = danger_label
        elif 'mid' in elevation_label:
            forecast['middle'] = danger_label
        elif 'low' in elevation_label:
            forecast['lower'] = danger_label
        return forecast

def get_bottom_line(soup):
    return soup.find('div', class_ = 'nac-bottomLine-text nac-tinymce').text

def get_discussion(soup):
    return soup.find('h2', text='Forecast Discussion').find_next_sibling().text

def parse_problems(soup):
    parsed_json_list = []
    
    # Find all problem blocks
    problem_blocks = soup.find_all('h3', class_='nac-html-h3')
    problem_blocks = list(set([p for p in problem_blocks if 'Problem' in p.text]))
    
    for problem_h3 in problem_blocks:
        problem_type_text = problem_h3.get_text(strip=True)
        problem_number, problem_type = problem_type_text.split(':')
        problem_number = int(problem_number.replace("Problem #", "").strip())

        # Assuming the structure is consistent for each problem block
        problem_block = problem_h3.find_next_sibling('div', class_='nac-infoGraphics nac-row')
        
        # Likelihood
        likelihood_label = problem_block.find('h5', text=' Likelihood ').find_next_sibling('div')
        likelihood = likelihood_label.find('div', class_='nac-label nac-active').get_text(strip=True).lower()

        # Size
        size_label = problem_block.find('h5', text=' Size ').find_next_sibling('div')
        size = [label.get_text(strip=True) for label in size_label.find_all('div', class_='nac-label nac-active')]

        # Aspect/Elevation
        aspect_elevation = {'upper': [], 'middle': [], 'lower': []}
        svg_paths = problem_block.find('div', class_='nac-rose').find_all('path', {'data-id': True})
        for path in svg_paths:
            aspect, elevation = path['data-id'].split()
            if 'rgb(200, 202, 206)' in path['style']:  # Check if the path is shaded
                aspect_elevation[elevation.lower()].append(aspect)

        # Discussion
        discussion_block = problem_h3.find_next_sibling('div', class_='nac-tinymce')
        if discussion_block:  # Check if the discussion block exists
            discussion_paragraphs = discussion_block.select('p')
            discussion = ' '.join(p.get_text() for p in discussion_paragraphs)
        else:
            discussion = ""

        # Combine into JSON structure
        parsed_json = {
            'problem_type': problem_type,
            'problem_number': problem_number,
            'likelihood': likelihood,
            'size': size,
            'aspect_elevation': aspect_elevation,
            'discussion': discussion,}
        

        parsed_json_list.append(parsed_json)
    return parsed_json_list

def parse_zone_forecast_html(html):
    soup = BeautifulSoup(html, 'html.parser')
    
    author_date_zone_info = get_author_date_zone(soup)
    
    problems = parse_problems(soup)
    
    bottom_line = get_bottom_line(soup)
    
    discussion = get_discussion(soup)
    
    weather_df = get_weather_table(soup, author_date_zone_info['zone'], author_date_zone_info['date'])

    # Assemble everything into a structured dictionary
    forecast_info = {
        'author': author_date_zone_info['author'],
        'date': author_date_zone_info['date'],
        'zone': author_date_zone_info['zone'],
        'problems': problems,
        'bottom_line': bottom_line,
        'discussion': discussion,
        # Assuming you want to handle the DataFrame separately as it might not be directly serializable or
        # you might want to process it differently (e.g., convert to JSON, CSV, etc.).
        # 'weather_data': weather_df
    }
    return forecast_info, weather_df
f, w = parse_zone_forecast_html(html)    

    # Return the structured forecast information and the weather DataFrame
    ## intended outputs:  {'author': author, 'date':date, 'zone':zone, 'problems':[problem_list], 'bottom_line':bottom_line, 'discussion':discussion}
    ## AND weather_df from get_weather_table with date and zone passed in

{'author': 'Guy Zoellner', 'date': '2024-03-14', 'zone': 'Flathead Range & Glacier NP', 'problems': [{'problem_type': ' Persistent Slab', 'problem_number': 2, 'likelihood': 'possible', 'size': ['Large (D2)', '', 'Very Large (D3)'], 'aspect_elevation': {'upper': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'middle': ['north', 'northeast', 'east', 'southeast', 'northwest'], 'lower': []}, 'discussion': 'NW-N-SE aspects above 6,000’ still harbor a weak layer of facets above a crust.\xa0 This combo is identifiable by digging down 2-4 feet until you find a thick and supportable crust. It is not always reactive in stability tests and can give the impression of being benign or stable.\xa0 It is, however, a low-frequency/high-consequence scenario. Natural and human-triggered avalanches have been reported on this layer within the last week. A common theme is that every time this weak layer is tested by a dramatic change to the snowpack (i.e. warming or loading), it has produced D2-D3 avalanches. Shallow, rocky, or convex parts of the slope are places to avoid.\xa0 Enjoy good snow on more gentle terrain or ribs between bigger slopes. Cornices have developed over the last several weeks. Any of these monsters that warm, sag and fall onto the slope below could be a likely trigger for a hard slab avalanche.\xa0 Move quickly out of paths that have large cornices looming above them.'}, {'problem_type': ' Wet Loose', 'problem_number': 1, 'likelihood': 'likely', 'size': ['Small (D1)', '', 'Large (D2)'], 'aspect_elevation': {'upper': ['southeast', 'south', 'southwest', 'west'], 'middle': ['southeast', 'south', 'southwest', 'west'], 'lower': ['southeast', 'south', 'southwest', 'west']}, 'discussion': 'What skied well yesterday (Wednesday) will become a problem today. The 4-12 inches of dry snow that rests above a crust on W-S-SE aspects will become wet and slide as the sun warms the snow surface. Steep slopes that are directly exposed to the sun will be the first to manifest this problem. Rollerballs or snow falling out of the trees are your first clue that the surface snow is changing. Small point releases can entrain large amounts of snow and travel further than you expect, especially when sliding on one of several crusts in the snowpack. While slow-moving, an avalanche of this nature will be hard to escape and could easily push you over cliffs or into trees. Limit your risk by choosing slopes that are more shaded and/or less steep.'}], 'bottom_line': 'Warm temperatures and direct sun will create dangerous avalanche conditions today. Rollerballs and snow falling out of trees are your clue that a wet loose avalanche cycle is starting. You can still trigger large avalanches on shaded slopes. Ridgelines and gentle terrain will provide the safest conditions and best opportunities for stunning views today.', 'discussion': 'It’s all about trade-offs. Just when the forecast area seemed to be filled in and skiing/riding great, the clouds part and give way to warming temperatures and changing problems.\xa0\nThe tricky part about the next few days is going to be managing wet snow and the lingering danger of persistent weak layers. As the snow on the sunny slopes transitions to wet, you will be forced onto more polar aspects. This shaded terrain still harbors several faceted crusts. Hard slabs failing on persistent weak layers have been well documented in the Whitefish Range and the Flathead Range over the last few weeks. We haven’t received any reports of natural or triggered avalanches in the Swan Range on these layers. Tuesday, an avalanche that failed on a buried weak layer, likely formed in early February, claimed the life of a backcountry skier near Lost Trail Pass south of Missoula.\nWith the sunset of the winter season just around the corner, we will have to hunt out the last powder stashes. As these get more affected by the warm weather, we’ll be driven to the precise slopes that harbor the recipe for large avalanches. Keep this in mind as FOMO begins to influence our decision-making.\nAs we transition into springtime travel, recall the cast of spring problems. Cornices that have grown over the last several weeks will begin to weaken due to sun and warm temperatures.\xa0 Limit your time underneath these hazards and stay well back from the edge while on ridgelines.'}

,Metric,Last 24 Hours,Today,Tonight,Tomorrow,range,station,date
0,Cloud Cover,Partly Cloudy,Partly Cloudy,Mostly Clear,Partly Cloudy,Flathead Range & Glacier NP,None,2024-03-14
1,Temperatures,Low: 23° F | High: 28 ° F,27 to 34 ° F,16 to 20 ° F,38 to 46 ° F,Flathead Range & Glacier NP,None,2024-03-14
2,Wind Direction,Southwest,West,West,West,Flathead Range & Glacier NP,None,2024-03-14
3,Wind Speed,3G8mph,8,7,6,Flathead Range & Glacier NP,None,2024-03-14
4,Snowfall,"0""","0""","0""","0""",Flathead Range & Glacier NP,None,2024-03-14
5,Snow Line,"3000""",3000',3500',4500',Flathead Range & Glacier NP,None,2024-03-14

In [ ]:
import json
import copy
driver = webdriver.Chrome(service=s)

years = [2023,2024]
for year in years:
    driver.get(f"https://flatheadavalanche.org/observations/read-observations/#/view/observations?startDate=%22{int(year-1)}-10-01%22&endDate=%22{int(year)}-06-01%22&season={int(year)}")

    # Wait for the table to load
    WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, ".nac-card.nac-observation-card.nac-card-hover"))
    )

    rows = driver.find_elements(By.CSS_SELECTOR, ".nac-card.nac-observation-card.nac-card-hover")
    rows[0].click()
    forms = []
    n=0
    while(True):
        driver.implicitly_wait(20)
        html = driver.page_source
        soup = BeautifulSoup(html, 'html.parser')
        new_form = get_obs_fields(soup)
        if new_form in forms:
            break
        else:
            forms.append(copy.deepcopy(new_form))
        next_arrow = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, ".nac-btn.nac-btn-primary.nac-next"))
        )
        next_button = driver.find_element(By.CSS_SELECTOR, "a.nac-btn-primary.nac-next")
        next_button.click()
        time.sleep(20)
        n+=1
        print(len(forms))
        print(len(set([json.dumps(elem) for elem in forms])))
        print(new_form)
        print('\n')
    pd.DataFrame(forms).to_csv(f'/home/christine/Jupyter/snow/data/fac_obs_{int(year-1)}_{int(year)}.csv')

1
1
{'Latitude': '48.402214', 'Longitude': '-114.13365'}


2
2
{'location': 'Whitefish Range', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Clear (No clouds)', 'Temperature (F)': '45', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'None', 'Wind Loading': 'None', 'Weather Summary': 'Wet. Hot.', 'Observation Date': 'Apr 28, 2023', 'Submission Date': 'Apr 28, 2023', 'Observer type': 'public', 'Observation Summary': 'Got creative out in the whitefish range today.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered', 'Instability Comments': 'Numerous recent avalanches on the north face of moose peak. We dropped into the north face at noon today. Snow was past prime at this hour, but not terrible considering the lack of freeze last night. First of 3 skiers triggered a wet loose slide on their first couple of turns. This slide ran 400 feet or so before loosing energy as it traveled into older debris on the slope. Size 2.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


3
3
{'location': 'Middle Fork', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Up rescue, out Skiumah', 'Cloud Cover': 'Clear (No clouds)', 'Temperature (F)': '50', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Observation Date': 'Apr 28, 2023', 'Submission Date': 'Apr 29, 2023', 'Observer type': 'public', 'Observation Summary': 'Good corn skiing thanks to what seemed like ..the last freeze up for awhile?  Rescue trail fully skiiable down to old 2.. skiumah trail… not so much.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': 'one manageable  d1 wet slab and a couple medium small pinwheels around noon', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


4
4
{'location': 'Middle Fork', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Clear (No clouds)', 'Temperature (F)': '35', 'New or Recent Snowfall (cm)': '2"', 'Rain/Snow Line': "4500'", 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Observation Date': 'Apr 23, 2023', 'Submission Date': 'Apr 26, 2023', 'Observer type': 'forecaster', 'Observation Summary': "I visited the Middle Fork Sunday and noted a breakable surface crust at all elevations early morning.\n\nAbove 5500 feet, we found 4-6 inches of moist snow below the surface resting on a thick supportable crust.\nThe light winds through the day transported a thin\xa0layer\xa0of dry surface snow on northerly aspects, and we encountered up to 16 inches of dry wind-blown snow in an upper elevation north-facing chute.\nBy mid-morning, a loud, rumbling Wet Loose\xa0avalanche\xa0cycle began on steep southerly slopes receiving direct sun. These\xa0slides\xa0mainly were D1.5 with several\xa0D2\xa0and continued through our 2:00 exit.\nWe stuck to northerly slopes and noted large fields of recent rollerballs and Loose Wet slides, which looked like a groomer had been at work removing all of last week's snow. We initiated rollerballs and small Wet Loose\xa0slides\xa0on our descent. The riding was fun, but a workout in the heavy snow that needed more time before developing into a\xa0corn\xa0consistency.", 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': 'Wet Loose avalanches and rollerballs developed throughout the day.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


5
5
{'location': 'GTSR - Granite Park', 'Zone / Region': 'Other', 'Activity': 'Skiing/Snowboarding', 'Route': 'Up from the Loop to Granite Park Chalet then back the way we came.', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '38', 'New or Recent Snowfall (cm)': '20-40 cm', 'Rain/Snow Line': "3500'", 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': "Variable cloud cover (OVC to BKN) with temperatures climbing to 38*F at 6700' at 1pm and widespread green housing observed.", 'Observation Date': 'Apr 20, 2023', 'Submission Date': 'Apr 20, 2023', 'Observer type': 'public', 'Observation Summary': 'We found 6-16" of fresh storm snow, variable cloud cover, and increasing temperatures during our brief tour today. We observed many small dry loose (and wet loose) avalanches within the new snow on steep slopes on all aspects and observed localized cracking within the new snow while skinning and skiing on short steep slopes. We intentionally triggered 3 small wet loose avalanches. We expect the avalanche hazard to increase over the weekend with additional snowfall Friday, clearing skies Saturday, and warming temperatures Sunday, but instability will be confined to the recent storm snow.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered  Cracking Observed (isolated)', 'Instability Comments': 'Instability limited to new snow atop the old surface melt freeze crust. Localized cracking in the new snow on steep slopes and a storm slab "upside down" structure to the new snow by midday on all aspects below 6700\'.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


6
6
{'location': 'Tranquil Basin', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': "8''", 'Rain/Snow Line': 'Valley Floor', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': 'Snow continued throughout the day partially filling in our skin track between laps.', 'Observation Date': 'Apr 19, 2023', 'Submission Date': 'Apr 19, 2023', 'Observer type': 'public', 'Observation Summary': "2-8'' of new snow between valley and 7500 feet. Surface snow is wet to 5500 feet. Above 6000 feet snow felt nice and dry. Snow near ridge varied from  scoured surfaces to dense windslab. Pockets of windslab were reactive on test slopes to ski cut propagating 5-10 feet by 4-6inches. Dry loose in steep terrain above 6000 feet and wet loose below 5500 feet both initiated from ski turns.", 'SIGNS OF INSTABILITY': 'Avalanches Observed  Cracking Observed (isolated)', 'Instability Comments': "Reactive pockets of isolated windslab 4-6'' deep on west aspect near ridgeline. Harmless wet loose and dry loose initiate from ski turns.", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


7
7
{'location': 'Huckleberry Lookout', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '30', 'New or Recent Snowfall (cm)': '2"', 'Rain/Snow Line': "4000'", 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Observation Date': 'Apr 18, 2023', 'Submission Date': 'Apr 18, 2023', 'Observer type': 'forecaster', 'Observation Summary': "We took advantage of the open Camas Road to enjoy a day in the Apgar Range. This road closes yearly on December 31 and reopens to vehicle traffic in early to mid-April.\xa0\n\nCool overnight temperatures left a surface crust supportable to skis at low and mid-elevations throughout the day. However, this crust was not nearly as strong as what we enjoyed last week and over the past weekend in the Flathead Range.\xa0\nLight snowfall overnight and through the day totaled only 2 inches by day's end.\nThe new snow was moist, and each turn on our steep descent initiated numerous rollerballs, but the riding quality remained good.\nThe south-facing Huckleberry Lookout hiking trail is beginning to melt out and resulting in a slow exit.\nThe Apgar Range receives significant wind and often has impressive cornice growth along the Crest and the numerous sub-ridges. The cornices we observed today were relatively small, which we assumed was due to this season's below-average snowfall.", 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


8
8
{'location': 'Autumn Creek Trail', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'XC Skiing/Snowshoeing', 'Observation Date': 'Apr 14, 2023', 'Submission Date': 'Apr 14, 2023', 'Observer type': 'public', 'Observation Summary': 'Debris over the Autumn Creek west trail from the bowl below Elk.  Covered the ski trail', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

9
9
{'location': 'Northern Swan, East of Crater Mountain', 'Zone / Region': 'Swan Range', 'Activity': 'Other', 'Route': 'Remote observation', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '40', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': 'Several days of above freezing temps at or near this elevation.', 'Observation Date': 'Apr 11, 2023', 'Submission Date': 'Apr 11, 2023', 'Observer type': 'public', 'Observation Summary': "Glide crack has catastrophically failed.  This crack appeared roughly a week ago above a larger crack first observed late Feb.  Other nearby glide cracks (Aeneas, Strawberry, Peter's Ridge) are currently obscured.", 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': 'A glide crack has catastrophically failed.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


10
10
{'location': 'Repeater Ridge', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '3” at the top of Repeater Ridge', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': 'Rain low down with snow above ~6000 feet yielding to sunny conditions in the early afternoon.', 'Observation Date': 'Apr 8, 2023', 'Submission Date': 'Apr 8, 2023', 'Observer type': 'public', 'Observation Summary': 'Day began with rain at the Isaac Walton Inn parking lot which slowly turned to groppel on the ascent. We made it to the top of Repeater Ridge and dug two snow pits on the Northern aspect which showed failure, but no propagation on the persistent week layer about 12 inches down. With this in mind we skied a north facing, lower angle shot without any problems. Feeling emboldened by our findings, we decided to step out and ski a steeper north facing line off Repeater Ridge (~40 degrees). Our first two skiers descended without incident, but our third skier triggered a slab avalanche that luckily they were able to ski out of to safety. This avalanche failed on the buried weak layer that was previously noted, had a crown depth of about 12”, width of ~100 feet and travelled about 150 feet. After this incident, we skied back down the South aspect towards Marion Lake which exhibited typical spring afternoon conditions with rollerballs and heavy snow. Lots of lessons learned today!', 'SIGNS OF INSTABILITY': 'Collapsing Observed (isolated)', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


11
11
{'location': 'GTSR - Garden Wall WX', 'Zone / Region': 'Other', 'Activity': 'Skiing/Snowboarding', 'Route': 'Up from the GTSR at Little Granite to the Garden Wall weather station then back the way we came.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '35', 'New or Recent Snowfall (cm)': '5 cm', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'None', 'Wind Loading': 'Previous', 'Weather Summary': "Temperatures climbed from the upper twenties to mid-30s above 6k' and mid-40s at lower elevations.", 'Observation Date': 'Apr 7, 2023', 'Submission Date': 'Apr 7, 2023', 'Observer type': 'public', 'Observation Summary': "Today was a generally a calm day in the mountains with overcast conditions that evolved into broken clouds with considerable solar heating between 230pm and 4pm. Temperatures climbed quickly in direct sunlight and broke down strong surface refreezes by noon below 6k'. Above 6k' we found variable snow conditions that included hot pow, windboard, and thin melt freeze crusts. Roller balls began to naturally occur between noon and 1pm with a spike in activity during the afternoon clearing and warm up.", 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'No obvious signs of instability observed today. Also observed an old partially filled in large crown on the north aspect of Heavens Peak (pictured) and glide cracks forming on Heavens Peak.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


12
12
{'location': 'Soup', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Nil', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'None', 'Wind Loading': 'None', 'Weather Summary': 'A couple moments of a intense sun through the breaks.', 'Observation Date': 'Apr 7, 2023 (10:00 - 3:00)', 'Submission Date': 'Apr 7, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Went to the Swan to see how Northerly aspects were holding up:\n\nThe top 2" of snow has transitioned to moist on NW-N-E up to 6900 feet (upper extent of my travels).\nBelow this depth the snowpack remains dry.\nRollerballs and pinwheels ran naturally in rocky terrain or where trees were shedding snow. \xa0They were easy to trigger on steep slopes.\nDid not see any recent Loose Wet avalanches in the immediate area. \xa0\nSkinning was gloppy and skiing was sticky.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Rollerballs and pinwheels', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


13
13
{'location': 'Jewel Basin- Black Lake Ski', 'Zone / Region': 'Swan Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Snowmobilied up to Wind blown section of road. Skinned from there up to camp misery and opted to ski over down to black lake. Traveld primarily on shaded W facing terrain and E facing terrain.', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '>30', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'None', 'Wind Loading': 'Light', 'Weather Summary': 'Overcast, but still warm even though the sun was not shining anywhere we were this afternoon. Precip started to move in ~7pm, as rain...', 'Observation Date': 'Apr 7, 2023', 'Submission Date': 'Apr 7, 2023', 'Observer type': 'public', 'Observation Summary': 'At 4pm, there was over 5" of slushy snow up to 6500\' and higher on certain orientations. Observed wind slabs that had been consolidated, but were not reactive. Quite a few glide cracks, looked like. Cornices reactive to human jumping.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': 'Unsure when wet slabs occured. No reactivity to note seen through out the day besides slight snails from skis.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


14
14
{'location': 'Glop City', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'None', 'Observation Date': 'Apr 7, 2023', 'Submission Date': 'Apr 7, 2023', 'Observer type': 'public', 'Observation Summary': 'A poor refreeze, glopping, and audible whumfing collapses led to an early turnaround. Whumfing was heard twice, both on east-facing slopes between 6000-7000ft. A poor refreeze (if any?) down low made for sticky travel conditions and roller balls/pinwheels on solar aspects before 10am, and the same on polar aspects after 10am. Ski out was variable and sticky at times.', 'SIGNS OF INSTABILITY': 'Collapsing Observed (isolated)', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


15
15
{'location': 'Flathead range', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Obscured (Sky not visible due to fog or non-cloud layer)', 'Temperature (F)': '35', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': '12345', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': 'Warm.. too warm. Still praying for snow', 'Observation Date': 'Apr 6, 2023', 'Submission Date': 'Apr 7, 2023', 'Observer type': 'public', 'Observation Summary': 'Snow from last weekend was too sticky to get above middle elevations.. should have hot  waxed my skins…', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

16
16
{'location': 'GTSR 54-1 and 54-3', 'Zone / Region': 'Other', 'Activity': 'Skiing/Snowboarding', 'Route': 'Up the GTSR then up the shoulder of 54-1/Red Rock then back down before another quick tour up 54-3 to snag a pit profile.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Trace', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Overcast all day with increasing winds midday and intermittent S-1 precipitation throughout the day.', 'Observation Date': 'Apr 5, 2023', 'Submission Date': 'Apr 5, 2023', 'Observer type': 'public', 'Observation Summary': "We mostly toured on northerly aspects today and found variable surface conditions including breakable crusts, firm wind-affect, loose facets, and consolidated fresh snow. The recently buried crust/facet interface is prevalent wherever we looked although not very reactive in instability tests. Travel conditions are sub-optimal and generally challenging currently as we're still stuck down low and touring through thick alder for the most part on the GTSR", 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'No obvious signs of instability noted today.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


17
17
{'location': "southern GNP, 6996'", 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': '25-35', 'New or Recent Snowfall (cm)': '4 to 6 inches', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Periods of intense sunshine mixed with scattered clouds. Calm winds.', 'Observation Date': 'Apr 4, 2023', 'Submission Date': 'Apr 4, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Traveled to southern Glacier National Park for my final field day of the season.\n\nWe enjoyed mostly sunny skies, good visibility, and calm winds. No recent avalanche activity was observed. No cracking, collapses, or other signs of instability.\nOn solar aspects, there were 4 to 6 inches of new snow resting above a faceting crust, up to just under 7000 feet. The surface snow exposed to the sun was becoming moist at all elevations by early afternoon.\nShaded aspects were strikingly cold, as we observed our sweaty hats freeze while digging our north-facing snow pit.\nWe skied a northern aspect, that had 12 inches of dry soft snow which transitioned to moist snow about 5700 feet. No signs of instability while skiing.\nIn both snow pits, the new snow was unconsolidated and we did not get propagating results. We dug on a sunny, east-facing slope and a shaded north-facing slope around 6800 feet. ECTX and no fracture in our compression test.\nWe observed one glide crack opening on a steep, southeasterly slope at upper elevations.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Skier triggered roller balls on sunny aspects.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


18
18
{'location': 'JFS Canyon Snowslip Mtn', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': '•\tClimbed the ridge above the Burnout, Shed 4D, Shed 5, and Shed 7 avalanche paths to a high point at 6800’ elevation in Shed 7 West.', 'Cloud Cover': 'Not Observed', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': '•\tClear skies in the morning, then building clouds and mostly overcast by late afternoon. Intermittent snow showers with trace accumulations.•\tWinds were light to moderate from the east or northeast with minimal blowing and drifting snow. •\tOvernight lows dropped to the single digits °F with the clear skies. But temperatures warmed quickly and reached to mid-30s °F on the Canyon floor and mid-20s°F above 6000’ by mid-afternoon.', 'Observation Date': 'Apr 3, 2023', 'Submission Date': 'Apr 3, 2023', 'Observer type': 'public', 'Observation Summary': '•\tNo recent avalanche activity observed.•\tSnowfall totals from the Apr 1st/2nd storm have settled out to 2-3” on the Canyon floor, 5-6” at 5000’, and 6-10” at 6000’ and above.•\tMinimal wind loading today, but the newest crop of wind slabs formed over the weekend were 1-2’ thick and found on easterly and northerly aspects above 6000’.•\tExperienced 3 audible collapses/whumpfs. All occurred above 6500’ and on north-facing slopes. Hand pits revealed a 2-3” thick layer of facets right under the most recent snow as the layer of concern.•\tOn other slopes where the pre-storm surface is a stout melt-freeze crust, the recent snow appears to be bonding well and no signs of instability were observed.•\tSnowpack surface was becoming moist at all elevations on slopes exposed to the intermittent sunshine by mid-afternoon.', 'SIGNS OF INSTABILITY': 'Collapsing Observed (isolated)', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


19
19
{'location': 'Tranquil Basin', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'low 20s', 'New or Recent Snowfall (cm)': 'T', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Broken clouds, with strong sun when windows were open. Calm to light winds until early afternoon, then winds got gusty when convective cell moved through. A few flurries.', 'Observation Date': 'Apr 3, 2023 (10:30 - 16:30)', 'Submission Date': 'Apr 3, 2023', 'Observer type': 'forecaster', 'Observation Summary': '3-10" of new and drifted snow between canyon floor and 7500 feet. Sitting on last week\'s snow surfaces, which were mostly melt-freeze crusts on steeper, sun-exposed slopes and old snow on sheltered slopes. 1 audible collapse, 2 recent natural avalanches, and no shooting cracks or propagating test results. Snow felt cakey and a little dense on open, west facing slopes at upper elevation but we found no distinct wind slabs.\xa0\n1 glide ctack opening on a steep, southeasterly slope at upper elevations.\xa0\nToday\'s sunny breaks were strong enough to thicken the surface snow on the most open mid elevation slopes. May be a slight crust in the morning.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Cracking Observed (isolated)  Collapsing Observed (isolated)', 'Instability Comments': 'Isolated short, radial cracks around skis while breaking trail. Crust breaking on soft snow below. 1 audible collapse at ~6600 feet as later skiers approached regroup point. Not loud.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


20
20
{'location': 'Mt. Cannon', 'Zone / Region': 'Other', 'Activity': 'Skiing/Snowboarding', 'Route': "Up GTSR from Avalanche TH then up Red Rock/54-1 shoulder to 4500' then down 54-1 avalanche path back to the road.", 'Cloud Cover': 'Few (Mostly Clear, up to 2/8 covered)', 'Temperature (F)': '-1', 'New or Recent Snowfall (cm)': 'T - 10 cm', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Pleasant weather for a quick tour and some road plowing!', 'Observation Date': 'Apr 3, 2023', 'Submission Date': 'Apr 3, 2023', 'Observer type': 'public', 'Observation Summary': 'Today was the first day up the road of the 2023 GTSR Spring Opening Avalanche Program. During our quick tour we observed locked-up surface conditions, few clouds, temperatures rising to ~0*C, and calm winds. We also observed recent wolf, fox, and bear tracks.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': "Wide propagating fresh avalanche crowns along the E and SE aspects of Heavens Peak above 8k' that appear to be similar depth and distribution to persistent slab avalanches triggered in the Flathead Range over the weekend.", 'Latitude': '48.402214', 'Longitude': '-114.13365'}

21
21
{'location': 'Crystal Creek', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '10 inches', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Moderate', 'Weather Summary': 'Wind was variable today from the west light to strong with intense busts of snow.', 'Observation Date': 'Apr 2, 2023', 'Submission Date': 'Apr 2, 2023', 'Observer type': 'public', 'Observation Summary': "-HN24: 3-10'' resting on supportable melt freeze crust-Snow felt cohesionless and test slopes did not fail on skin up-Cornices were reactive to stomps and failed - Cornice drops did not initiate slab activity (several moderate sized cornices were dropped onto steep terrain)", 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered  Cracking Observed (isolated)', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


22
22
{'location': 'Diamond peak', 'Zone / Region': 'Whitefish Range', 'Activity': 'Snowmobiling/Snowbiking', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '3"', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Moderate', 'Observation Date': 'Apr 2, 2023', 'Submission Date': 'Apr 2, 2023', 'Observer type': 'public', 'Observation Summary': 'Slab avalanche from wind loading on east face at about 6,700 ft.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered  Cracking Observed (isolated)', 'Instability Comments': 'Instability found near ridge lines. Plenty of signs of wind loading on and just below ridge particularly on east facing slopes', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


23
23
{'location': 'Swan', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'FAC', 'Activity': 'Snowmobiling/Snowbiking', 'Observation Date': 'Apr 2, 2023', 'Submission Date': 'Apr 4, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Remotely triggered a slab on a wind-drifted feature. Other riders reported similar activity. Slabs were small and not running far distances.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


24
24
{'location': 'Southern Whitefish Range', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'multi-drainage/multi-aspect tour adjacent to WMR.', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Yes', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Previous', 'Observation Date': 'Apr 2, 2023', 'Submission Date': 'Apr 5, 2023', 'Observer type': 'public', 'Observation Summary': 'Dust on crust/ Slide-for-Life conditions on southern aspects. Northern aspects are better but supportable crust still exists. We found that there was not quite enough new snow to be concerned about sluff management even on the steepest slopes. Spring snow flurries persisted throughout the day with short bouts of sunshine.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': 'widespread loose-wet debris from the previous warming period on multiple aspects at mid-elevations. Several glide-cracks on southern aspects.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


25
25
{'location': 'Wahoo Cr.', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': "Up Wahoo to ~6500' then back on down.", 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '28', 'New or Recent Snowfall (cm)': '10-30 cm', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': 'Variable spring weather with blustery winds observed from E, S and W throughout our outing.', 'Observation Date': 'Apr 2, 2023', 'Submission Date': 'Apr 2, 2023', 'Observer type': 'public', 'Observation Summary': 'We observed touchy and easily triggered wind slabs that stepped down to deeper buried weak layers at mid and upper elevations while touring today. We also found good powder skiing in wind-sheltered lower angle slopes and variable surface conditions throughout (classic spring).', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered  Caught in Avalanche  Cracking Observed (isolated)  Collapsing Observed (isolated)', 'Instability Comments': "Observed localized collapses from 4800' on up on N, NW, and NE aspects and localized cracking (up to 2m) in wind loaded terrain features. No recent avalanches observed until we both intentionally and unintentionally triggered avalanches (described in avalanche section).", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


26
26
{'location': 'Ten Lakes WSA', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Toured in Ten Lakes area today and found better than expected conditions.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Below freezing', 'New or Recent Snowfall (cm)': '2-3cm', 'Rain/Snow Line': 'N/A', 'Snow Available For Transport': 'None', 'Wind Loading': 'None', 'Weather Summary': 'Intermittent snow showers with OVC skies shifting to BRK by the end of the tour. Temps stayed below freezing throughout the day. Light winds at Below and Near Treeline locations.', 'Observation Date': 'Apr 2, 2023', 'Submission Date': 'Apr 2, 2023', 'Observer type': 'public', 'Observation Summary': 'Light winds with no drifting snow or wind slab formation. Temps were between -6 and -1C throughout the day. OVC skies with light intermittent snowfall. In standard Upper WF Range fashion, exit had moderately deep frozen moose tracks intermixed with alder and refrozen snowmobile tracks.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': 'Found stable conditions on all aspects. No signs of cracking or collapsing. Traveled on slopes up to 35 degrees.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


27
27
{'location': 'Flathead Range', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '10', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Light winds with moderate gusts today.', 'Observation Date': 'Apr 2, 2023', 'Submission Date': 'Apr 2, 2023', 'Observer type': 'forecaster', 'Observation Summary': "An April Fools' persistent weak layer strikes again! Today we observed many signs of unstable snow.\xa0\n\nWhile traveling a ridgeline we experienced 5 audible collapses. These collapses occurred on a north-facing ridgeline above 5500 feet.\xa0\nWe experienced localized and shooting cracks.\xa0\nWe intentionally and unintentionally triggered small and large avalanches above 6500 feet. Triggered avalanches were on west, north, and east-facing slopes.\xa0\xa0\n\nThe avalanche we unintentionally triggered was triggered from a 32-degree ridge. The collapse occurred while taking one step off of the ridge. This avalanche propagated 600 feet wide and wrapped around multiple aspects.\xa0\nThe crown height of this slab averaged one foot thick. The thickest section was just shy of three feet.\xa0\n\n\nObserved natural avalanche activity on east and south-facing slopes across the canyon. These avalanches appeared large (D2).\xa0\n\nAvalanches failed on a layer of near-surface facets that formed during our extended period of high pressure.\xa0\nphotos video soon.", 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered  Caught in Avalanche  Cracking Observed (isolated)  Collapsing Observed (isolated)', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


28
28
{'location': 'Essex', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Apr 2, 2023', 'Submission Date': 'Apr 2, 2023', 'Observer type': 'public', 'Observation Summary': '3” in Essex and 8-10” at my high point of 7000. New snow was a little upside down. Light snow with moderate wind in the morning gave way to sun breaks by mid day and on my exit solar aspects were getting wet. While skiing I stuck to north facing trees, had several audible collapses including one with shooting cracks where I turned around. Defensive skiing with ski cuts yielded lots of soft storm slabs, the biggest was about 100’ wide and ran 600-800’.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered  Cracking Observed  Collapsing Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

29
29
{'location': 'Essex Creek', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'From Izaak Walton skinned up NE aspect, South of Essex Creek. Skied down within close proximity of our skin track.', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '20-36', 'New or Recent Snowfall (cm)': '30cm', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': 'Convective snow showers, broken clouds and partial sunshine back and forth all day.', 'Observation Date': 'Apr 2, 2023', 'Submission Date': 'Apr 2, 2023', 'Observer type': 'public', 'Observation Summary': 'Initial observations in our snow pit were centered around the 30cm of new snow resting on a weak, sugary layer. ECT was performed on NE aspect around 7200ft which resulted in an ECTP13. Failure occurred at the new | old snow convergence roughly 30cm down.', 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)  Collapsing Observed (isolated)', 'Instability Comments': 'During our ascent we noticed frequent collapsing above 6000ft. We had several occurrences of cracking which ran about 20ft. No signs of recent avalanches were found.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


30
30
{'location': 'Northern Flathead', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Apr 1, 2023', 'Submission Date': 'Apr 1, 2023', 'Observer type': 'public', 'Observation Summary': 'Afternoon tour to allow the storm to stack up . Found 4” of new at my high point of 6500’. Winds were gusting and swirling. No slab formation yet. Moderate speed sluff ran about 1200’ on my north facing descent.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


31
31
{'location': 'Sixmile', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '1 inch', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': 'Some flurries around noon. Wind picked up around 1300 hrs.  Gusting moderate from the SW at mid and upper elevations.', 'Observation Date': 'Mar 31, 2023 (11:00 - 5:00)', 'Submission Date': 'Mar 31, 2023', 'Observer type': 'forecaster', 'Observation Summary': "Returned to Sixmile to recover my rutschblock cord out of last week's pit:\n\nSkiff of snow at the trailhead increasing to an angry inch at upper elevations.\nOn E->S, new snow rested on a meltfreeze crust of varying thickness and supportability. \xa0All were edgeable, fortunately. \xa0Crust was most rebust and skiable on steep and sparsely treed southerly slopes. Elsewhere it was less consistent and require defensive skiing.\nOn N->NE, I found up to 6 inches of well preserved dry powder.\nI avoided west-facing slopes as they were getting hammered by wind.\nWind transport was surprising considering the limited recent snow.\nIsolated and thin pockets of soft slab were trending toward reactive on leeward terrain along upper elevation ridges.", 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)', 'Instability Comments': 'Isolated and thin soft slabs were stubborn, trending towards reactive.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


32
32
{'location': 'Elk Mountain', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': "SW aspect to max elevation of ~6000'", 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '32', 'New or Recent Snowfall (cm)': '0.5 inches', 'Rain/Snow Line': 'valley bottom', 'Snow Available For Transport': 'None', 'Wind Loading': 'Not Observed', 'Weather Summary': "Snow in the trees above ~6300' from some previous snow event.  Winds calm to light from the S.  S-1 snowfall pretty much all morning.", 'Observation Date': 'Mar 30, 2023', 'Submission Date': 'Mar 30, 2023', 'Observer type': 'public', 'Observation Summary': "Quick, easy travel with cool temps and a firm MF crust.  Temps were stable right around freezing until our exit around 1:30.  Steady S-1 snowfall on an edge agreeable crust made for an enjoyable backcountry groomer experience.  We were happy it didn't warm up today.Low cloud ceiling obscured most of the surrounding higher elevation terrain.", 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'No signs of instability observed.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


33
33
{'location': 'Nyack Mountain', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '1 cm', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Overnight cloud cover meant for a milder morning. Overcast to obscured skies most of the day, with cloud bases about 7000 ft. A few brief breaks, several well timed for us, but little direct sunlight. Frequent flurries, with 1 cm new snow (large crystals). Winds calm to light.', 'Observation Date': 'Mar 30, 2023 (8:00 - 16:00)', 'Submission Date': 'Mar 30, 2023', 'Observer type': 'forecaster', 'Observation Summary': "Checked out snow surfaces as this warming weather ends and more snowfall *may* arrive. And those surfaces were...variable. A wide variety of melt-freeze crusts and wind packed snow interspersed with soft, and sometimes moist snow. MF crusts softened today but remained supportable at low elevations. Breakable at upper elevations on westerly slopes. That said, we found reliable skiing on most other slopes. Today's light snow bonded readily with these surfaces. Snow on some shady mid and upper elevation slopes showed signs of faceting\nIn a steep, upper elevation, northerly bowl, we were surprised to find the mid-January crust only a foot below the snow surface. The snowpack in this area was < 150 cm in places. A good reminder that conditions are not uniform and persistent weak layers still exist close enough to the surface for a person to affect. We found no slab above the Jan. structure, and no shears in hand pits. To minimize the chances of stumbling into a trigger point, we used old debris piles for our ascent route in rocky terrain.\nCorniuces continue to loom at ridgelines, and new glide cracks are opening on SE slopes.\xa0\nSki crampons useful for low elevation trails.", 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


34
34
{'location': 'Cascadilla', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': '32-33', 'New or Recent Snowfall (cm)': '0.25', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Winds were calm.  Sun and clouds scattered the skies. Air temperatures stayed below freezing in the shade.', 'Observation Date': 'Mar 28, 2023', 'Submission Date': 'Mar 28, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Today was a short tour in the Flathead Range to get a handle on diurnal melt-freeze conditions.\n\nWe traveled on a supportable crust that varied in depth from 1 to 3 inches, with a dusting of new snow. \nMore freeze than melt, as the crust did not soften up by our 3 pm exit. \nWe did observe recent loose wet debris piles on steep, southerly aspects, which suggested that recent afternoon temperatures and solar radiation initiated these sunny slopes to slide.\nLooming in the backdrop of our day, we could still see the fracture line of a very large persistent slab avalanche that failed on March 2nd.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Recent wet loose avalanche activity on solar slopes, but we can only guess when they occurred.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

35
35
{'location': 'Lost Johnny.', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'Below Freezing', 'New or Recent Snowfall (cm)': '6 inches', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Observation Date': 'Mar 26, 2023', 'Submission Date': 'Mar 26, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Headed into the northern Swan to confirm Low Danger. Validated.\xa0\n\nObserved no signs of instability. No collapsing, no cracking, and no recent avalanches.\n6 inches of settled snow rests on a variety of firm surfaces.\xa0\nSki cuts on steep leeward slopes along the crest of the Swan produced no avalanches other than very minimal sluffing.\xa0\nWe observed no evidence of recent wind-drifted snow in this drainage of the Swan.\xa0\nIntermittent periods of solar radiation warmed the surface enough to glop up under skis.\xa0\n\nWith no signs of instability, we chose to ski steep terrain one at a time.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


36
36
{'location': 'Furlong', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '32', 'New or Recent Snowfall (cm)': '1-2 inches', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Observation Date': 'Mar 25, 2023', 'Submission Date': 'Mar 25, 2023', 'Observer type': 'public', 'Observation Summary': '1-2 inches of new snow on the ground, with temps at 32 degrees at the valley floor at the start of our walk. Calm weather all day, with overcast skies, little to no wind, and very light snowfall. No signs of instability, but did notice old wet avalanche debris on south aspects. North facing aspect off the top of Furlong offered fun skiing with dry snow and no noticeable crust until about 5800ft.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': 'Old wet slides, but not from today.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


37
37
{'location': 'Peter’s ridge', 'Zone / Region': 'Swan Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Snowmobiled to the summer trailhead and toured up the ridge, skied NW bowl', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'None', 'Weather Summary': 'Perfectly calm, very light snow throughout the day', 'Observation Date': 'Mar 25, 2023', 'Submission Date': 'Mar 25, 2023', 'Observer type': 'public', 'Observation Summary': 'New snow was easily sluffing on steep slopes that needed to be managed. We saw a lot of glide cracks and old crowns', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Lots of glide cracks, old crowns and debris.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


38
38
{'location': 'Cascadilla', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'North east of nyack via cascadilla creek', 'Cloud Cover': 'Not Observed', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '3in', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Moderate', 'Observation Date': 'Mar 25, 2023', 'Submission Date': 'Mar 25, 2023', 'Observer type': 'public', 'Observation Summary': 'Isolated shooting cracks on small slabs on northwest aspect', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Cracking Observed (isolated)', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


39
39
{'location': 'Marion', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Skiing north-facing aspects in the Marion Lake area.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Observation Date': 'Mar 25, 2023', 'Submission Date': 'Mar 25, 2023', 'Observer type': 'public', 'Observation Summary': "Dug a pit and performed ECT on a north-facing aspect at 6600' with no results (ECTX). Skied steep (>40*) north facing aspects with no signs of instability, had to manage sluff. South facing aspects held 1-2' of dust on a stout sun crust. Overcast with a high (>7500') cloud ceiling most of the day. Intermittent snow flurries in the morning. No signs of wind transport at upper elevations.", 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


40
40
{'location': 'Swans', 'Zone / Region': 'Swan Range', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '6', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'None', 'Observation Date': 'Mar 25, 2023', 'Submission Date': 'Mar 25, 2023', 'Observer type': 'public', 'Observation Summary': 'Pow n glide cracks', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': 'Glide cracks galore', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


41
41
{'location': 'Rescue/ Nyack', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '3-5"', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Overcast, with cloud bases hovering about 7600 ft. and occasional bluish sucker holes. Mostly calm, except for some light, downslope winds late morning.  S-1 flurries off and on during the day, with little accumulation.', 'Observation Date': 'Mar 25, 2023 (9:30 - 16:00)', 'Submission Date': 'Mar 25, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Took advantage of the uninspiring conditions to look for solitude in the Rescue Creek area. Also surveyed new snow amounts, and extent and distribution of wind drifting. Found a little of each - two other parties, 3-5" of fresh snow that was crossloaded into soft drifts less than 8" thick at mid elevations, from downslope westerly winds. These were unreactive. Less scouring and drifting at upper elevations. Elsewhere, new snow was mostly sitting on recent melt-freeze crusts or old wind board. The exceptions were in sun- and wind-sheltered areas.\xa0\xa0\nSurprisingly good skiing, especially above 5500 ft. Quietest turns on northerly slopes and low-angle slopes.\nSki crampons useful on the icy trail into the basin, and on steep, wind- and sun-hardened slopes at upper elevations. No wet snow, no glopping.', 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)', 'Instability Comments': 'Some short (< 1m) cracks around skis. New snow and recent Melt-freeze crust breaking on low density snow below.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


42
42
{'location': 'Cascadilla and Rescue', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Up Cascadilla, down Crystal creek, over Nyack and down North face, up and down Penrose and back to Cascadilla.', 'Observation Date': 'Mar 24, 2023', 'Submission Date': 'Mar 25, 2023', 'Observer type': 'public', 'Observation Summary': 'I found mostly stable conditions during the beginning of the storm.  By the end of the day, up to 3" of new snow had fallen at upper elevations.  Winds were strong along windlines and intermittently gusty below the ridges, which was enough to redistribute some of the snow into very shallow slabs.  I was able to ski cut small avalanches in the most sensitive east facing starting zones, and new snow was sluffing on all steep slopes, but generally there was not enough new snow to be of consequence.', 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

43
43
{'location': 'Paola/Rescue', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Other', 'Route': 'Flying over the Middlefork Drainages. Pilot: Mitch Fontenot', 'Observation Date': 'Mar 23, 2023', 'Submission Date': 'Mar 23, 2023', 'Observer type': 'public', 'Observation Summary': 'Lots of wet loose activity on South Aspects, large debris piles', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


44
44
{'location': 'Rescue Creek', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'None', 'Wind Loading': 'None', 'Weather Summary': 'Sun in the morning. Around 3 pm clouds rolled in.  Winds were light, with a few moderate gusts.', 'Observation Date': 'Mar 23, 2023', 'Submission Date': 'Mar 23, 2023', 'Observer type': 'forecaster', 'Observation Summary': "Today was a quiet avalanche activity day in Rescue Creek.\n\nNo avalanche activity was observed throughout the day. We didn't even see a roller ball. All previous wet loose avalanche activity was from previous days this week or earlier.\nSurface crust made fast travel conditions and was supportable until we transitioned to a northerly aspect of about 5700 feet.\nWe dug at a pit on a north aspect around 6000 feet, and we got no propagating results.\nSpring diurnal weather patterns were clear, as several cycles of wet avalanche activity covered steep slopes. Many of the slides originated from rocky outcroppings.\nNorth aspects skied well above 5800 feet. Below that elevation, the north aspects were punchy wind-stiffen snow.\xa0 When we moved to a southerly aspect, the 1 to 2-inch surface crust was firm until around 5000 feet. The transition to wet snow was abrupt, and with the afternoon clouds, the descent was a race to stay ahead of the quickly refreezing snow.\nCheers to the snowshoers that summited Mount Penrose and descended avalanche debris. An impressive showing of snowshoe skills.\nAdditionally, we noted the low-flying plane over Rescue Basin, and we thank those flying for their observation and photos.", 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'All avalanche activity was from earlier in the week.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


45
45
{'location': 'Elk Mountain', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Ascended and descended the ESE face of Elk Mountain', 'Cloud Cover': 'Clear (No clouds)', 'Temperature (F)': '32+', 'New or Recent Snowfall (cm)': 'None', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'None', 'Wind Loading': 'Not Observed', 'Weather Summary': 'Splitter day', 'Observation Date': 'Mar 22, 2023', 'Submission Date': 'Mar 23, 2023', 'Observer type': 'public', 'Observation Summary': 'Older avalanches (several days) were observed on surrounding slopes but no recent signs of wet loose from the recent warm weather we have had interestingly enough.Like stated earlier pockets of wind slab up to ~10cm thick were present.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Generally stable conditions for the day. Obviously quite warm in the later afternoon and was able to ski the face in before worry of wet loose was a problem. There was some obvious pockets of wind slab on the skin up but these were easily avoidable.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


46
46
{'location': 'Shed 7/Snowslip', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Up Shed 7 path to East shoulder, dug pits and skied back along the same route.', 'Cloud Cover': 'Clear (No clouds)', 'Temperature (F)': '0', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'None', 'Wind Loading': 'None', 'Weather Summary': 'Clear and calm. Temps at TH were 11*F at 915am and 40*F at 230pm.', 'Observation Date': 'Mar 22, 2023', 'Submission Date': 'Mar 22, 2023', 'Observer type': 'public', 'Observation Summary': "Generally stable conditions today and beautiful weather. Meltfreeze crust snow surface was very firm and supportable throughout the tour on solar aspects but began to moisten/soften by 2pm, especially below 5k'.", 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': 'No obvious signs of instability observed today (avalanche observed was old).', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


47
47
{'location': 'Central Whitefish Range', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Clear (No clouds)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Beauty of a day.', 'Observation Date': 'Mar 22, 2023', 'Submission Date': 'Mar 22, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'We went to the central Whitefish Range to suss out buried weak layers at upper elevations. We did find ourselves an avalanche and also found ourselves a lot of stable conditions. Just depends on where you look.\xa0\n\nWe intentionally trundled a cornice down a north-facing slope at upper elevations. The cornice triggered a Hard Slab that failed 2 feet thick. This failed into old snow roughly 1 foot above the ground. (This was thoughtfully executed and over a slope where we confirmed no other parties were.)\nWe observed no other signs of instability. We found generally safe avalanche conditions on solar aspects until our departure time of 2 pm.\xa0\nPrevious sled tracks reached into many steep east-facing start zones with no triggered avalanches.\xa0\nWe rode across old debris piles that came very close to reaching their historical trim lines. These avalanches failed sometime during late February or early March.\n\nWe steered away from complex upper elevation start zones on shaded aspects. We did ride in steep terrain on other aspects.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


48
48
{'location': 'Snowshed', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Up and down the north facing tree route of snowshed', 'Observation Date': 'Mar 22, 2023', 'Submission Date': 'Mar 22, 2023', 'Observer type': 'public', 'Observation Summary': 'Climbed up to the snowshed ridge. Was treated to clear skies, great views, and t-shirt weather. Snow above 6000ft was creamy and dreamy. Below that, not so much. Saw one surprisingly sized wet slide in the trees on a north facing slope. Plenty of signs of small point releases as well. Was 15 degrees when I started in the morning, and 44 when I stopped at lunchtime.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


49
49
{'location': 'Sixmile', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Clear (No clouds)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Not a cloud.  Steady light wind from the East\nGusting to Moderate kept things cool.', 'Observation Date': 'Mar 22, 2023 (9:30 - 16:30)', 'Submission Date': 'Mar 22, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Out to check on todays thaw:\n\nLow elevation snow in direct sunlight was softening by 1100 hrs.\nMid elevation southerlies softening by 1300 hrs but were cooled by easterly winds.\nThe surface at upper elevation S aspect consisted of a thin crust, above 3 inches moist snow on top of dry snow.\nFound dry surface snow on N through NE at upper elevations.\nPit at 7000 feet\xa0NE aspect had several weak layers in the top 3 feet but did not propagate in large column test.\nNo new natural loose wet or roller ball activity.\n\nStarted heading down around 1530 hrs to avoid overcooked snow on Southern egress. Upper elevation was still a little stiff, \xa0mid elevation had perfect corn. \xa0Low elevations were sticky and punchy.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Thin and small pockets of hard slab cracked easily along a ridge at 7000 feet.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

50
50
{'location': 'Red Crow Mountain', 'Zone / Region': 'Other', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Clear (No clouds)', 'Temperature (F)': '30+', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': 'Sunny, clear, warm', 'Observation Date': 'Mar 22, 2023', 'Submission Date': 'Mar 22, 2023', 'Observer type': 'public', 'Observation Summary': 'Went out to summit Red Crow in Glacier.  Observed the previous mentioned avalanche from the rude goats. Most interesting part of the day was the summit cornice that was starting to rip away and had skin tracks on it from previous groups.  Good reminder how far back cornices can peel away.  Otherwise snow felt in a freeze thaw spring cycle except north faces.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': 'Some wet slides from previous days and the avalanche from the red Crow crew over the weekend.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


51
51
{'location': 'Northern Flathead', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Mar 21, 2023', 'Submission Date': 'Mar 21, 2023', 'Observer type': 'public', 'Observation Summary': 'Attempted another higher alpine face today but sadly found this north/north west face had previously slid and the bowl/apron had been hammered with wind leaving l the bowl and apron full wind board or scoured. Stark contrast to JFS canyon two days ago. Two other fun observations from the day: older skin and ski tracks covered by recent wet slides and shout out to the snowshoers from Alabama who were all over the basin with reckless abandon!', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


52
52
{'location': 'Six Mile', 'Zone / Region': 'Swan Range', 'Activity': 'Skiing/Snowboarding', 'Route': "Late start from 4000' turned out to not be problematic leaving trailhead at 10:30 - travelled to 7400 feet - returned to car by 13:30.", 'Cloud Cover': 'Clear (No clouds)', 'Temperature (F)': '(26-40)', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Observation Date': 'Mar 21, 2023', 'Submission Date': 'Mar 21, 2023', 'Observer type': 'public', 'Observation Summary': "-Snow was mostly supportable on solar aspects all the way to 7400 feet on ascent. -Dry snow still exists on northerly aspect above 5500 feet. -Great corn skiing in middle elevation band roughly (5000-7000'). -Snow below middle elevation band felt isothermic by 1pm on descent. -Snow approaching summit was in some places not fully edgeable. -Full value views from the top, cool wind kept the surface snow above 7000 feet locked up. -Saw tracks from large mammal could not identify due to freeze thaw cycle metamorphosis of surface snow (bring bear spray!)", 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


53
53
{'location': 'Flathead', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Mar 21, 2023', 'Submission Date': 'Mar 22, 2023', 'Observer type': 'forecaster', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


54
54
{'location': 'Checkerboard/6437', 'Zone / Region': 'Swan Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Up switchback, then north to top of Peak 6437. Descended through Checkerboard, passed by Jewel Basin Yurt and used Jewel Basin Road for out.', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': "Warm day, blustery winds at top of Switchback and 6437 but no signs of blowing snow, most transport at ridgelines or peaks and in very minimal amounts. Sun crust on affected aspects was 2-3in thick. Sun affect on the snow was minimal from slight overcast conditions, tour up switchback was great until it wasn't. Can definitely see freeze/thaw cycle above treeline.", 'Observation Date': 'Mar 20, 2023', 'Submission Date': 'Mar 21, 2023', 'Observer type': 'public', 'Observation Summary': 'Multiple wet loose slides, at least 1 glide crack beginning to open up.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Cracking Observed (isolated)', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


55
55
{'location': 'Skyland', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'zero', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'None', 'Wind Loading': 'None', 'Weather Summary': 'Overcast skies all day, but the visibility was excellent for viewing surrounding terrain. Winds were calm, expect a few moderate gusts of northerly winds.', 'Observation Date': 'Mar 20, 2023', 'Submission Date': 'Mar 20, 2023', 'Observer type': 'forecaster', 'Observation Summary': "We took the sleds to the Skyland area for a look at the snowpack close to the Continental Divide.\n\nGood visibility provided a 360 degree view of the surrounding terrain and we were surprised that we did not see any wet avalanche activity.\nAny snow that was recently touched by the sun was today’s refrozen surface crust that extended up to 7150 feet. Crust depths decreased as we climbed in elevation from 4 inches to a 1 inch crust at the ridgeline.\nThe cooler temperatures from overcast skies locked up the area, except for the true northern aspects that were sheltered and shaded, holding soft dry snow above 5800 feet. Soft snow at upper elevations was 6 inches above a crust.\nInstability observed today was limited to old rollerballs that remain frozen hazards.\nRecent northerly winds eroded and minimized cornices formed from prevailing SW winds. These Arctic winds also cross-loaded mid-elevation slopes.\nWatch those scratchers, the hardened roads of Skyland's bumps can be tough on a sled's parts.", 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Older roller balls observed.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


56
56
{'location': 'John F Stevens', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Mar 19, 2023', 'Submission Date': 'Mar 19, 2023', 'Observer type': 'public', 'Observation Summary': 'Pleasantly surprised to found solar aspects at elevation skiing quite well, very corn like. Polar aspect still finding powder. Noticed on open east aspects surface hoar forming. Active wet slides on steep and rocky faces in the afternoon', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


57
57
{'location': 'Flathead Range', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Clear (No clouds)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'None', 'Weather Summary': 'Clear and calm.', 'Observation Date': 'Mar 19, 2023', 'Submission Date': 'Mar 19, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Took a leisurely walk up above Marion to dig around on south aspects and get some views of the surrounding alpine terrain.\n\nObserved one crown that looked relatively newer in the Dickey drainage. This crown failed just below ridgeline. It looked more recent than other nearby slab avalanche activity.\xa0\nWet loose activity appeared a couple of days old. All D1-D1.5 in size.\xa0\nSurface conditions on south aspects softened by the time I arrived at noon. Surface snow was still semi-supportable to ski at around 3 pm.\xa0 Just starting to get manky.\xa0\nNorth aspects at upper elevation still held dry surface snow.\xa0\nMeltwater reached the January crust/facet layer on southerly aspects at 6000 feet.\xa0 Facets below the January crust are just starting to become moist.\nI only found a few inches of wet snow above a crust on a southerly aspect near 7000 feet. This was however on a slope with roughly a 30-degree angle. I suspect steeper slopes that receive a more direct sun angle have more wet snow.\xa0\n\nThere was still plenty of time for the sun to do its work after I left.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

58
58
{'location': 'Dickey', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Skinned and skied N facing terrain up to 7200’.', 'Cloud Cover': 'Not Observed', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': 'Sunshine, sunshine, sunshiiiiine. Not a wisp of breeze.', 'Observation Date': 'Mar 19, 2023', 'Submission Date': 'Mar 19, 2023', 'Observer type': 'public', 'Observation Summary': 'We spied lots of wet loose coming down south aspects across the drainage, and I could just see the toe of debris of what looked to be a large wet slide down into the Marion side that looked to have slid today. We could also see an old large crown across the valley in rocky terrain. Polar aspects up high still held dry powder as of early afternoon. Below 5500’ we found a couple cm’s on a friable crust, except in the open sunny patches where the sun was warming that crust into a nice spring slush.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


59
59
{'location': 'Autumn Creek', 'Zone / Region': 'Other', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': '35', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': '3000', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Observation Date': 'Mar 18, 2023', 'Submission Date': 'Mar 18, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'I heard rumors of large avalanches impacting the Autumn Creek trail, so we went to take a closer look.\n\nWe viewed three large crowns of Persistent Slab avalanches that failed in late February. These were on east-to-southeast aspects between 6600 - 7000 feet.\nAll were in steep, rocky terrain with non-uniform snow depths due to the frequent wind. These characteristics are similar to the Persistent Slab we investigated on 3-17 immediately south of these three.\nTwo debris piles traveled a long distance and impacted the Autumn Creek trail.\nThe destructive size of the slides varied between D2.5 to D3.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


60
60
{'location': 'tunnel', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Mar 18, 2023', 'Submission Date': 'Mar 18, 2023', 'Observer type': 'public', 'Observation Summary': "First day out after a work stretch. Found several cm's of new snow on top of crust on more northerly/sheltered aspects. Any sort of direct sun resulted in near instant glopping. We observed a couple glide cracks opening on solar aspects in the park and a handful of point releases on Grant and surrounding terrain but no deep slab crowns like Mark saw. Counted seven cars parked at the rescue and cascadilla spots, so we look forward to their observations!", 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


61
61
{'location': 'JFS Canyon Snowslip Mtn', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Not Observed', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': 'Clear skies with light winds from the southwest.  Air temps in the mid-30s °F.', 'Observation Date': 'Mar 18, 2023', 'Submission Date': 'Mar 18, 2023', 'Observer type': 'public', 'Observation Summary': '•\tNo recent avalanche activity observed.•\tNo snow profile or stability tests conducted.•\tNo audible failures or obvious signs of instability.•\tNo wind loading observed.  Previous wind loading was not recent.•\tAbove 5200’ elevation on solar aspects, the upper 6” was becoming moist.  •\tAbove 5200’ elevation on non-solar aspects, surface snow had recrystallized.•\tBetween 5200’ and 6000’ elevation on non-solar aspects, a stout crust remained intact below surface snow. •\tBy late afternoon, below 5200’ elevation on solar aspects snowpack exhibited signs of being isothermal and cohesionless to the ground. Did not conduct a snowpack temperature profile.•\tOn non-solar aspects below 5200’ elevation, surface snow had developed a melt-freeze crust with moist snow beneath it. (~1500 timestamp).  •\tClear skies with light winds from the southwest.  Air temps in the mid-30s °F.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


62
62
{'location': 'Rescue/SkiumahN', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Mar 18, 2023', 'Submission Date': 'Mar 19, 2023', 'Observer type': 'public', 'Observation Summary': 'The flip flop conditions in the parking lot and all the avalanche activity suggest this is a bit of a proto-spring? Timing matters more than usual. Our tour up Rescue, over Penrose, and out Skiumah featured plenty of avalanche activity. Solar aspects in Rescue were generally crusty at lower elevations, with varying degrees of wind affected/slabby snow in polar aspects as we ascended to the Nyack/Penrose col. Lots of wet loose debris that seemed gouging fairly deep into deeper, dryer layers for how far it had traveled. Upper areas on the descent to Skiumah saw light wind loading in the bottom of the  chute, with firmer wind surfaces to both sides. Lower down, we skied consistent soft slab debris for over 1500ft. Multiple large slides (D2-D3) have run in the amphitheater above the lake. Skies were clear. Moderate winds on the summit, but light to none elsewhere. Temps cold in the valleys and summit but above freezing below 5k ft on our descent.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


63
63
{'location': 'Red Crow Mountain, GNP', 'Zone / Region': 'Other', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Not Observed', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Moderate', 'Weather Summary': 'Winds were pretty strong this morning with visible active loading, but generally tapered throughout the day.  Sun was strong but temps stayed cold with winds and snow surfaces remained cold throughout the day.', 'Observation Date': 'Mar 18, 2023', 'Submission Date': 'Mar 21, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Outside of the advisory area but wanted to share as it caught us off guard. We felt fortunate for our timing.\xa0 Additionally we had considered that slope generally benign and discussed using some of it for our approach.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


64
64
{'location': 'Elk Mountain', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Clear (No clouds)', 'Temperature (F)': '30', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': "2000'", 'Snow Available For Transport': 'None', 'Wind Loading': 'None', 'Observation Date': 'Mar 17, 2023', 'Submission Date': 'Mar 17, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'The BNSF snow safety team spotted a hard slab avalanche on Elk Mountain Thursday, March 16. We decided to take a closer look at this slide.\n\nThe avalanche occurred at 6600 feet on a wind-loaded east aspect. The failure layer was 10 cm thick, large-grained facets near the ground. These facets formed in November.\nThe crown varied between 1.5 - 6.5 feet thick and was 150 feet wide. We believe the avalanche initiated where the crown tapered into rocks.\nThe top part of the debris field consisted of large chunks of hard slab debris.\nSurprisingly, we found 2-6" of dry snow in shaded aspects at low and mid-elevations. Areas exposed to the sun softened this afternoon and skied a little like corn.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

65
65
{'location': 'Rescue/Wahoo', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Up Rescue creek, down wahoo.', 'Observation Date': 'Mar 16, 2023', 'Submission Date': 'Mar 16, 2023', 'Observer type': 'public', 'Observation Summary': 'Toured up Rescue Creek drainage this morning and down Wahoo. Breakable crust all the way up to 6000 feet and most of the way down on NW and NE slopes. Small wind slabs and wind affected snow. Lots of evidence of recent slides on the SE and E facing slopes of the Rescue drainage.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Cracking Observed (isolated)', 'Instability Comments': 'Isolated cracking on windslabs.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


66
66
{'location': 'GNP East face Elk Mountain', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Driving', 'Observation Date': 'Mar 16, 2023', 'Submission Date': 'Mar 16, 2023', 'Observer type': 'public', 'Observation Summary': "Noticed this newer crown on the east face of Elk Mtn from the Hwy. today. There was some new powder snow on the debris, so it's not brand new , but pretty sure it wasn't there on Monday afternoon (13th). Maybe ran from recent wind loading or the Mar. 13/14th rain event?", 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


67
67
{'location': 'Ridge Between Crystal Creek and Stanton Lake', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'From the highway headed up the ridge, skied down the ridge to return to vehicle.', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Mixture of sunny, light to moderate winds, broken clouds, S-1.', 'Observation Date': 'Mar 15, 2023', 'Submission Date': 'Mar 15, 2023', 'Observer type': 'public', 'Observation Summary': 'Crust found at all E elevations traveled in (3800-6400), but the amount of new snow totals above crust increased with elevation. Thickness of crust varied from .5 to 2". Observed freshly transported snow on N to E facing slopes.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


68
68
{'location': 'Swan Lake', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '6 inches', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': '1" of new snow at the highway increasing to 8" at upper elevation. Sun broked out for only a couple minutes. Westerly winds light and gusting to moderate in the afternoon.  Short-lived squalls of S1-2 with rapidly diminished visibility.', 'Observation Date': 'Mar 15, 2023 (10:00 - 15:00)', 'Submission Date': 'Mar 15, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'We poked around in the Swan Lake area to check on new snow and wind-loading:\n\nWe found touchy pockets of wind-drifted snow at upper elevations\nThese pockets were located on specific terrain feautres (along ridges, gullies and midslope convexities).\nSlabs were\xa0 4-6 inches thick.\nWe intentionally triggered a D1.5 soft slab below a ridge line.\nWith light-moderate blowing snow, this problem will continue to develope.\nOur pit at 6600\' NE aspect had a propagating result with moderate force in the top 16".\nNo action from solar today but we found several wet-loose debris piles from warming on Monday.\xa0\n\nWe rode one at a time on short slopes of\xa0 35+ degrees.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered  Cracking Observed (isolated)', 'Instability Comments': 'We initiated shooting cracks and intentionally triggered a small avalanche in wind-drifted snow.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


69
69
{'location': 'JFS Canyon - Burnout/Shed  Wx station', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'upper 20s', 'New or Recent Snowfall (cm)': '3-6"', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Previous', 'Weather Summary': 'Broken skies w S-1 snow showers and light winds til mid-day/ early afternoon. Then clouds lowered and snowfall intensity increased to S1-2. Winds remained light.', 'Observation Date': 'Mar 15, 2023 (10:30 - 3:30)', 'Submission Date': 'Mar 15, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'In anticipation of warming and sun forecast for the end of the week, BNSF forecaster Adam Clark and I checked out low and mid elevation slopes above the railroad. We found a weak, unconsolidated snowpack below 5000 feet; steep slopes at these elevations may be susceptible to wet snow avalanches that gouge below the surface. At mid-elevations, this hazard would seem to be limited to sunny slopes, where the snowpack is weak, with one significant failure plane. On shady slopes at mmid elevations, the snowpack is well-consolidated, stronger, and more resistent to wet snow slides growing in size as they run.\xa0\nWe found 3-6" of fresh snow and few signs of recent windloading below our high point at the Shed 7 Weather station (6300 ft).', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


70
70
{'location': 'East of Big Mountain', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '25', 'New or Recent Snowfall (cm)': '1-2 inches', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Light winds with a few gusts, followed by an hour of sun, a brief shower of snow, and full spring sunshine at the parking lot by 3 pm.', 'Observation Date': 'Mar 14, 2023', 'Submission Date': 'Mar 14, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'We toured east of Whitefish Mountain Resort to take a look at how winds were affecting the surface snow and wind slab development.\n\nEvidence of strong southwest winds was masked by a layer of fresh snow, which was a nice surprise during the first part of the day.\nSouth-facing slopes had a supportable 1-inch sun crust, that was stiffened by recent winds. Frozen roller balls were observed on steep southernly slopes.\nChunky tree bombs (clumps of snow falling off trees or clumps of snow being blown off trees) made skiing a little more sporty.\nThe top 6 to 8 inches of cornices were sensitive to human weight, however, the underlying dense snow building the base of cornices was stubborn to even the most enthusiastic stomps.\nNo propagating results in our snow pit. Please see snowpack sections for details.\nThe sun made an appearance for approximately an hour, which was enough to stiffen the soft snow for a leg-burner last ski down to the groomers.', 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)', 'Instability Comments': 'Isolated cracking in surface crusts. The top 6 to 8 inches of cornice failed under human weight. Evidence of prior surface warming was observed as frozen roller balls and tree bombs, likely to have occurred on Monday (3/13/23).', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


71
71
{'location': 'Mt Marston', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Route': 'Snowmobile up the Mt. Marston road.', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '28', 'New or Recent Snowfall (cm)': '4', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': "Nice sunny day, shaded aspects stayed cool, solar aspects didn't turn into mashed potatoes.", 'Observation Date': 'Mar 14, 2023 (10:00 - 15:30)', 'Submission Date': 'Mar 14, 2023', 'Observer type': 'forecaster', 'Observation Summary': "Sled/ski of Mt. Marston. \xa0\n\nWe found a modest amount of windloading at the ridgetops, and crossloading on SE slopes. \xa0\nIt seemed like the winds must have stopped before the overnight snow as there was 4-5 inches of new on all aspects and all elevations above 5500'.\nThe warm up from sunday produced a MF crust on any slope that was able to see the sun. \xa0Shaded aspects were saved and didn't have the crust.\nWe did not see any eveidence of natural avalanches from the weekend.\nOur pit on a NE aspect still showed reactivity in a PST. \xa0The weak layer we tested was the Mid Jan crust that was down 70 cm. \xa0It was easily defined as a thin ice layer with large (2-3mm) facets below it. \xa0\nOverall I don't think it got as cooked by the sun over the weekend as Peters Ridge in the Swan Range had.", 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Things seemed pretty stable.  No natural activity or instabilities in our pits.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

72
72
{'location': 'JFS Canyon Snowslip Mtn', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Jakes avalanche path above the rail', 'Cloud Cover': 'Not Observed', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': '•\tPartly sunny in the morning, turning mostly cloudy, then fully overcast by late afternoon.•\tNo precipitation until about 1600 hours when very light rain began, and it has been steady since then.•\tDaytime high temperatures reached the high-40s °F on the Canyon floor, the mid-30s °F at 6400’, and 29 °F at 7000’.', 'Observation Date': 'Mar 13, 2023', 'Submission Date': 'Mar 13, 2023', 'Observer type': 'public', 'Observation Summary': '•\tThe avalanche in Jakes ran sometime between 1630 and 1830 hours yesterday.o\tIt was a wet loose that initiated in the recent Mar 10th/11th storm snow at the top of the path around 5000’ (photo).o\tA few hundred feet down, the debris gouged down into a layer of weak rounding facets (pit profile) which increased the destructive size to a D2.o\tAssociated debris was about 200’ wide and 1-4’ deep (photo) and terminated within 200 lineal feet of the rail, or about 80% distance to the grade.•\tObserved avalanche activity today was limited to more D1-D1.5 wet loose on steep slopes such as Shed 12, the Shed 4D Cutbank, and other steep cutbanks above the highway. No debris affecting the rail.•\tFreezing levels climbed to somewhere between 6400’ and 7000’ elevation today.•\tHigh elevation winds were strong, and plumes of drifting snow were noted off the summit of Elk Mountain and other terrain features taller than 7000’.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


73
73
{'location': 'Checkerboard', 'Zone / Region': 'Swan Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Toured up switchback trail to checkerboard summit.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '32+', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'None', 'Wind Loading': 'None', 'Observation Date': 'Mar 13, 2023', 'Submission Date': 'Mar 14, 2023', 'Observer type': 'public', 'Observation Summary': 'A wind slab still present but seemed to be in pockets, wet loose and pinwheels from previous day were all over. Hard to say the main player type for the slab observed but hesitate to say a PWL, not enough info', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


74
74
{'location': "Peter's Ridge", 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '35-40', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'winds were calm, except along the ridge. Mostly cloudy skies and warm temperatures.', 'Observation Date': 'Mar 13, 2023', 'Submission Date': 'Mar 13, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'We suspected it was a hot pow/mash potato snow kind-of-day, so we took sleds to the Swan, in search of dry snow.\n\nWe parked the sled at 4800 feet and started skinning on wet snow that quickly transitioned into a sun crust that varied in thickness from 2.5 inches at 5200 feet to 0.5 inches at 6500 feet.\nOvernight winds appeared to have redistributed the small amount of snow (snow available for transport) as a 0.5-inch to 1-inch soft snow layer over the sun crust.\nWinds were surprisingly calm for most of the day. The good visibility allowed us to spot 7 different (old) glide cracks that had been partially filled in with the recent snow.\nWe observed blowing snow along the ridgeline of upper elevations.\nWe did not get propagating test results in our snowpits on a SE aspect and a W aspect at 6400 feet.\nYesterday and today’s warm temperatures were evidenced by a variety of small loose wet debris piles, trees shedding snow, and many roller balls.\nWe skied a westerly slope that held pockets of sheltered soft snow intermixed with a sun crust that turned to manky-mash-potato snow around 5600 feet.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': "We had roller balls with every turn, where there wasn't a sun crust. We estimated that the observed loose wet debris was a result of yesterday's warming.", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


75
75
{'location': 'JFS Canyon Marias Pass', 'Zone / Region': 'Other', 'Activity': 'Driving', 'Route': 'Hwy 2 Essex to Marias Pass', 'Cloud Cover': 'Not Observed', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': '•\tPartly cloudy to mostly sunny skies by late afternoon. No precipitation with calm winds on the Canyon floor and light SW winds above 6000’.•\tDaytime high temperatures reached the low-40s °F on the Canyon floor and the high-20s above 6000’.', 'Observation Date': 'Mar 12, 2023', 'Submission Date': 'Mar 12, 2023', 'Observer type': 'public', 'Observation Summary': '4-8" of new snow starting moving this afternoon with sunshine and warming temperatures. Multiple loose snow avalanches observed, but no recent slab avalanches.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


76
76
{'location': 'WMR Sidecountry', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Day 3 of Avalanche-1 course with the Patrol Fund in the Side Country off of WMR. Banana chutes into the canyon followed by ascent up bookshelf.', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': 'Stable overcast morning weather conditions with light snowfall and minimal wind that turned into rapid warming around 1400 as clouds cleared.', 'Observation Date': 'Mar 12, 2023', 'Submission Date': 'Mar 12, 2023', 'Observer type': 'public', 'Observation Summary': 'Other notable observations from day: A glide crack was visible on the southwest aspect in WMR canyon. At 1400 rapid warming, resulted in a wet-loose slide intentionally triggered on an inconsequential test slope.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


77
77
{'location': 'Crystal Cr', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Mar 12, 2023', 'Submission Date': 'Mar 13, 2023', 'Observer type': 'public', 'Observation Summary': 'The day started cold, but once the sun arrived, even north aspects at 6K elevation felt the heat, to say nothing of the sweat pouring off our brows. Solar surfaces were moist to the touch at ridgetop elevations in the afternoon, and the new snow picked up density from those high angle rays. Winds were light with moderate gusts.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


78
78
{'location': 'Hellroaring Peak', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': '35', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Moderate', 'Observation Date': 'Mar 12, 2023', 'Submission Date': 'Mar 13, 2023', 'Observer type': 'public', 'Observation Summary': 'Made a turn on a convex rollover, small scale, where the wind had drifted snow in recent days. As I made the turn, I released a small but surprisingly deep slab (about 12-14”) that propagated around 50ft to my right and only a few feet to my left. The rollover ran into a small flat shelf so the whole slab only moved about 15-20 feet laterally but moved cohesively as one slab.', 'SIGNS OF INSTABILITY': 'Cracking Observed (widespread)', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

79
79
{'location': 'Central Whitefish Range', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Clear (No clouds)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': 'Overcast skies transitioned to clear skies by early afternoon.', 'Observation Date': 'Mar 12, 2023', 'Submission Date': 'Mar 12, 2023', 'Observer type': 'public', 'Observation Summary': 'We snowmobiled on numerous aspects from 3500 feet to 5700 feet and skied a NW aspect from approximately 6800 feet to 4800 feet. We observed a relatively shallow aspect on this NW aspect at 6800 feet (130-140 cm). Because of this shallow snowpack combined with the steep and rocky terrain, we decided to ski down the ridge to a less steep entrance to our intended line. We triggered several small dry sluffs that ran 100-200 vertical feet on slopes steeper than 35 degrees. The surface snow was very unconsolidated, and we did not observe any recent wind slab problems throughout the terrain we visited today. Surface snow became heavier at lower elevations due to increasing sunshine and warming as the day progressed. Overall, great riding and skiing.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


80
80
{'location': 'Rescue/Wahoo', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Up Rescue, down Wahoo N and NE', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '31', 'New or Recent Snowfall (cm)': '5cm', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Large Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Calm winds all day with a slight clearing trend.', 'Observation Date': 'Mar 12, 2023', 'Submission Date': 'Mar 12, 2023', 'Observer type': 'public', 'Observation Summary': 'Stunner of a day to be out with soft snow and no wind.  Sun kept trying to truly poke out and bring on a loose wet cycle, but patches of blue sky were as far as it got.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered', 'Instability Comments': 'No slab activity today but loose dries, natural and skier triggered, were running far.  No loose wet observed, even on SE aspects above Great Bear creek that stayed in a sunny hole for a few hours (although probably too far away to see if they were there).', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


81
81
{'location': 'Elk Man & MF Canyon window tour', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Typical circuit of Elk Mtn.', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': 'The clouds came, went, then came back again... A tricky day to choose the correct (low light vs dark) sunglass/ goggle lenses... Temps certainly warmed up, but not as warm as it could have been w/ more sun...', 'Observation Date': 'Mar 12, 2023', 'Submission Date': 'Mar 12, 2023', 'Observer type': 'public', 'Observation Summary': 'Observed loose D1 wet activity throughout the MF corridor. No obvious signs of instability on Elk Mtn. "Dust on wind crust" > 6,800ft, warm snow below <6,800 ft.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


82
82
{'location': 'Ten Lakes. Northern Whitefish', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'FAC', 'Activity': 'Snowmobiling/Snowbiking', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '2 Inches', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'None', 'Observation Date': 'Mar 12, 2023', 'Submission Date': 'Mar 12, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Today we went into the northern Whitefish Range to investigate a crown of a recently triggered avalanche.\n\nThis avalanche failed on an east-facing slope at 7600 feet.\xa0\nIt failed on a layer of large, weak grains (depth hoar) near the ground. (See more in video or avalanche tab)\nWe found 6 inches of new/recent snow. We observed no signs of recent wind transport.\nWe experienced mostly cloudy skies until 4 pm, which kept surface snow cold.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


83
83
{'location': 'Cascade Creek', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Up to Cascade Creek to enjoy a few north facing laps, exited on south facing terrain into Rescue Creek.', 'Cloud Cover': 'Not Observed', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': 'Mostly cloudy throughout the tour, clouds breaking up into blue by 5p. Light snowfall before noon, minimal wind.', 'Observation Date': 'Mar 12, 2023', 'Submission Date': 'Mar 12, 2023', 'Observer type': 'public', 'Observation Summary': 'Soft turns on north facing terrain, kicking off a bit of loose dry slough. Otherwise no signs of snowpack instability on north facing, shaded aspects. Late afternoon exit onto south facing terrain with small soft slabs breaking off at our skis on a few turns up top. A few tree bombs and point releases on steeper terrain noted with the warming temps, but the snow wasn’t quite catching the direct solar we were avoiding.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


84
84
{'location': 'Central Flathead', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Mar 11, 2023', 'Submission Date': 'Mar 11, 2023', 'Observer type': 'public', 'Observation Summary': '20-25 cm of new snow on top of all old skin track. Zero wind and light to moderate snowfall all day resulting in a couple cm of new. Natural and skier sluffs were common, only one small storm slab.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


85
85
{'location': 'WMR Sidecountry', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'From in bounds territory south of Flower Point - skinned south-southeast to Ghoulie Point and continued just south from the point to near "Baby\'s Butt" ski run. Observation was made on 30 degree slope, 6643\' elevation, and on a SE aspect.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '6-10 inches', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Light', 'Weather Summary': 'Lightly snowing and very little to no wind.', 'Observation Date': 'Mar 11, 2023', 'Submission Date': 'Mar 11, 2023', 'Observer type': 'public', 'Observation Summary': 'Dug a pit and performed shovel shear and ECT tests. Shovel shear produced light fractures at 30 and 60 cm, but shear quality was low. ECT test resulted in ECTN27. Fracture depth approximately 30 cm but, as indicated, no propagation.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


86
86
{'location': 'Nyack', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Nyack area.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '25', 'New or Recent Snowfall (cm)': '1', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Observation Date': 'Mar 11, 2023', 'Submission Date': 'Mar 11, 2023', 'Observer type': 'public', 'Observation Summary': 'No wind/0 mph, no sun, about one in. of new between 8-3, below freezing all day. Weird, variable crusts under the new snow on all but the most north-facing aspects.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Some natural sluffing off steep, rocky terrain, but not traveling far. No instability observed in skiable terrain.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

87
87
{'location': 'WMR Sidecountry', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Skinned from WMR Flower Point lift to Ghoulie Point and then skied a short section east of "Baby\'s Butt" run before skinning back up to the ridge extending east from Ghoulie Point.  Observation was made on 29 degree slope, 6,500\' elevation on a N aspect approximately 300 yards east of Ghoulie Point.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '15-30 cm', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Light', 'Weather Summary': 'Calm, light snow', 'Observation Date': 'Mar 11, 2023', 'Submission Date': 'Mar 11, 2023', 'Observer type': 'public', 'Observation Summary': 'Dug a pit and performed an ECT test as part of an Avi 1 class.  ECT test was ECT-N-27.  Small fracture occurred at 60 cm depth, but no propagation.  Small hand pits (southerly aspect) dug during skinning back to ridge showed 15 - 30 cm of fresh powder on top of a 2.5 cm crust.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'None', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


88
88
{'location': 'West aspect near Chicken Bones off WMR', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Traversed ridge from Ghoulie point to Chicken Bones with the Patrol Fund Avalanche-1 course. Descended the west aspect of Chicken Bones.', 'Cloud Cover': 'Obscured (Sky not visible due to fog or non-cloud layer)', 'Temperature (F)': '20-25', 'New or Recent Snowfall (cm)': '6-12 inches depending on location', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Observation Date': 'Mar 11, 2023', 'Submission Date': 'Mar 11, 2023', 'Observer type': 'public', 'Observation Summary': 'Right-side-up snowpack, no serious signs of instability observed. Dust on crust on southern aspect of Chicken Bones.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Recent loose/dry accumulation with potential for sloughing on steeper slopes.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


89
89
{'location': 'Late-morning Middle Fork', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Obscured (Sky not visible due to fog or non-cloud layer)', 'Temperature (F)': 'Low 20s', 'New or Recent Snowfall (cm)': '8"', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Snow showers (S-1 to S1) most of the day. No wind. Clouds in drainages.', 'Observation Date': 'Mar 11, 2023 (10:30 - 14:30)', 'Submission Date': 'Mar 11, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Surprising amount and quality of new snow at mid and low elevations, w no signs of instability on consequential slopes up to 40*.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


90
90
{'location': 'Essex area', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '20', 'New or Recent Snowfall (cm)': '14"', 'Rain/Snow Line': '1000', 'Snow Available For Transport': 'Large Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Cool temperatures, no wind, and mostly overcast conditions.', 'Observation Date': 'Mar 11, 2023', 'Submission Date': 'Mar 11, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Tunnel Ridge weather station recorded eight inches of new snow this morning. This was the most of all area stations. We chose a neighboring drainage to check on the new snow totals, wind loading, and the Persistent Slab problem.\n\nWe found 25cm (10 inches)\xa0 of new snow at 4000 feet and 35 cm (14 inches) above 5500 feet. This snow was extremely low-density and could be called cold smoke, champagne powder, or blower powder.\nNo evidence of recent or current wind effect along the ridgeline we walked.\nA brittle 1 cm sun crust rests below the new snow on steep southerly aspects.\nThe new snow was cohesionless, and we did not find a slab in the areas we traveled.\nSkier-triggered sluffs in the new snow frequently occurred on steep slopes. These would have been a concern on more consequential terrain features.\nWe found the mid-January crust approximately 1.5 meters below the surface on upper-elevation north aspects.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'The only signs of instability observed were skier-triggered sluffing on steep slopes and small natural sluffs which appeared to run during the storm.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


91
91
{'location': 'South Dickey', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Mar 11, 2023', 'Submission Date': 'Mar 13, 2023', 'Observer type': 'public', 'Observation Summary': "Impressively dry, light new snow greeted us from the onset. We skied north aspects, and saw some sloughing, but it wasn't moving far or fast. Temps were below freezing, but progressively warming all day. No solar effect, and no wind. No crust interface between the dry new snow and the older soft snow underneath.", 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


92
92
{'location': 'Hall Lake', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '3 inches', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': 'Wind shifted from easterly to southwesterly just after 1200 hrs. We saw less blowing snow after this shift. Snowfall fluctuated with S1-S2 at 1400 hrs.', 'Observation Date': 'Mar 10, 2023 (9:00 - 17:00)', 'Submission Date': 'Mar 10, 2023', 'Observer type': 'forecaster', 'Observation Summary': "We went to the Swan Lake area to welcome in the storm:\n\nNo obvious signs of instability\n~3 inches of new snow fell during our tour\nWe found only a couple pockets of wind-drifted snow that were wiling to produce cracks\nThese small slabs were still reluctant to slide downhill on a ~35* slope\nNew and wind-drifted snow sat atop Thursday's sun crust on aspects S through W\nOur northwest descent held roughly 1 foot of well-preserved powder\nSluffs ran easily and traveled 200 vertical feet\n\nWe felt comfortable skiing extended steep slopes.", 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Just short, thin cracks in two small pockets.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


93
93
{'location': 'Con kelly', 'Zone / Region': 'Swan Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Up SW ridge, descending N couloir', 'Cloud Cover': 'Few (Mostly Clear, up to 2/8 covered)', 'Temperature (F)': 'NO', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Previous', 'Weather Summary': 'Light winds low, moderate SW around 7000’.  No blowing snow.', 'Observation Date': 'Mar 9, 2023', 'Submission Date': 'Mar 9, 2023', 'Observer type': 'public', 'Observation Summary': 'Gorgeous day out. Small facets under thin (1-5cm) wind skin at mid elevations.  No surface hoar observed.', 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)', 'Instability Comments': 'Widespread short cracking and small (5-10cm) windslab pockets above 6500’.  Isolated pockets same depth below 6500’.  Did not observe any windslab slides, just small loose wets from earlier this week on SW at 6200’.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


94
94
{'location': 'Snowslip WX', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Up Shed 7 W shoulder and along the ridgeline to pit then back out the same way.', 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': '-9', 'New or Recent Snowfall (cm)': '10 cm', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Previous', 'Weather Summary': 'Generally scattered clouds with light winds and a good bit of sunshine.', 'Observation Date': 'Mar 9, 2023', 'Submission Date': 'Mar 9, 2023', 'Observer type': 'public', 'Observation Summary': 'Pleasant day of fieldwork getting Snowslip weather station back and communicating. Variable surface snow conditions kept us on our toes while skinning and skiing.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Cracking Observed (isolated)', 'Instability Comments': 'Very localized cracking immediately around skis in recently wind-loaded locations. No cracking in deeper/thicker wind slabs from the last week or two. Observed a small old wind slab avalanche crown in steep wind-loaded terrain nearby.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

95
95
{'location': 'Autumn West', 'Zone / Region': 'Other', 'Activity': 'Skiing/Snowboarding', 'Route': 'Northwest on Autumn creek west to east face of Elk proper.', 'Cloud Cover': 'Few (Mostly Clear, up to 2/8 covered)', 'Temperature (F)': '25', 'New or Recent Snowfall (cm)': '<1”', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Moderate', 'Weather Summary': 'Clear sunny.', 'Observation Date': 'Mar 9, 2023', 'Submission Date': 'Mar 9, 2023', 'Observer type': 'public', 'Observation Summary': 'Small slab on top of faceted snow. Later was unstable to poles and skis.', 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)  Collapsing Observed (isolated)', 'Instability Comments': 'Small wind slabs on top of faceted snow.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


96
96
{'location': 'Tunnel Ridge Weather Station', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': 'teens', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Increasing clouds through the day over the Flathead Range; skies over GNP stayed blue. Some clouds pouring over low spots on divide. Winds light at weather station, with no recent drifting. We did, however, see some occasional blowing snow on the high peaks of the Flathead Range.', 'Observation Date': 'Mar 8, 2023 (10:00 - 16:00)', 'Submission Date': 'Mar 8, 2023', 'Observer type': 'forecaster', 'Observation Summary': "Traveled to Tunnel Ridge Weather Station to swap out the wind sensor, which didn't appear to be giving good readings. That work precluded digging any holes in the snow. No signs of instability or recent avalanche activity, though we did see a at least one large, older fracture line on the high peaks of the Flathead Range.", 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


97
97
{'location': 'Hay Cr.', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'FAC', 'Activity': 'Snowmobiling/Snowbiking', 'Route': 'Up the Hay Cr road.', 'Cloud Cover': 'Clear (No clouds)', 'Temperature (F)': '20', 'New or Recent Snowfall (cm)': '4', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Bluebird!  Balmy and warm, but not above freezing. Light Southerly breeze.  Clouds building in the afternoon.', 'Observation Date': 'Mar 8, 2023 (9:00 - 3:30)', 'Submission Date': 'Mar 8, 2023', 'Observer type': 'forecaster', 'Observation Summary': "Today we ditched the skis and rode the sleds up to the Whitefish Divide via Hay Cr.\n\nThere seemed to be less wind affect than in the Swan range where I was on monday. \xa0All day we only crossed one very small sliver of windboard. \xa0The rest of the ride was in a fairly uniform 4-6 inches of new snow.\nPits were punched on NE and SE aspects. \xa0No propogation in our ECT's. \xa0We found the mid Jan. crust 70-100 cm down. \xa0\nOur SE pit had results of PST 30/100 (End) in the facets below the mid-Jan. crust. \xa0This was the same aspect/elevation of the two older avalanches we crossed. \xa0\nWe found widespread surface hoar above 5500', however, it was pretty well knocked down by the sun on any exposed slope by mid afternoon.\nObserved modest rollerball, loose dry and loose wet activity considering the intense sun.\xa0\xa0\n\nWe road one at a time on steep SE slopes, othewise the riding was great and we felt very comfortable going anywhere the sleds would allow.", 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'We did not see any instabilities in our pits, around our machines or on slopes we could see.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


98
98
{'location': 'Green Mountain', 'Zone / Region': 'Whitefish Range', 'Activity': 'Snowmobiling/Snowbiking', 'Route': 'Highline from Wolverine Lakes', 'Cloud Cover': 'Clear (No clouds)', 'Temperature (F)': '28', 'New or Recent Snowfall (cm)': 'None', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'None', 'Wind Loading': 'Light', 'Weather Summary': 'Sunny and warm. Calm to light winds.Avalanche forecast was moderate to low.', 'Observation Date': 'Mar 8, 2023', 'Submission Date': 'Mar 9, 2023', 'Observer type': 'public', 'Observation Summary': 'Avalanche slide triggered by snowmobile mid mountain, deep snowpack slab on east facing slope.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered  Cracking Observed (isolated)', 'Instability Comments': '18-24 inches deep slab', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


99
99
{'location': 'Northern Swan', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'None', 'Wind Loading': 'Previous', 'Weather Summary': 'Clear skies gave way to periods of scattered and overcast. Temps remained cold all day.', 'Observation Date': 'Mar 8, 2023', 'Submission Date': 'Mar 8, 2023', 'Observer type': 'forecaster', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


100
100
{'location': 'Tunnel Ridge', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Few (Mostly Clear, up to 2/8 covered)', 'Temperature (F)': '20', 'New or Recent Snowfall (cm)': 'Trace', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Light', 'Weather Summary': 'Afternoon convective showers with warm sunny skies were a pleasant treat from 12:00-14:00 S-1', 'Observation Date': 'Mar 7, 2023', 'Submission Date': 'Mar 7, 2023', 'Observer type': 'public', 'Observation Summary': '-Sizable cornices development on E facing ridge lines - small wind slab 4-6 inches thick fractured on test slope running a short distance. -Structural lemons on north through east aspects kept us off and out from under consequential terrain.-We enjoyed skiing steeps on westerly aspect that hosted warm powder and soft turns.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'North through east aspects harbor a myriad of PWL of various depths and strengths.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


101
101
{'location': 'Flathead Range - Cascadilla Creek', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': "Overcast skies with occasional S-1 snowfall in the AM. Broken skies, no precip, and some occasional sunshine in the PM. Winds were generally calm or light from the west. Daytime highs reached the mid to high-teens at elevations above 5000'.", 'Observation Date': 'Mar 7, 2023', 'Submission Date': 'Mar 7, 2023', 'Observer type': 'public', 'Observation Summary': "-Went up Cascadilla Creek for a close look at the previously reported very large (D3) avalanche on the east face of Nyack Mtn (photos). Continued up to the ridge crest dividing Cascadilla and Wahoo Creeks to a high point at 6700'.-Debris from this very large hard slab ran all the way down to at least 5000' elevation, possibly as low as 4600'. It was difficult to determine the exact terminus. This is a vertical fall of 2000-2500' and nearly a mile of lineal distance on the terrain.-Debris from this avalanche sympathetically triggered at least 5 additional slab avalanches, most D2 size.-Investigation of one of these smaller, debris-triggered crowns at 5100' on a NE aspect (photo) revealed the failure layer was facets right on top of the mid-Jan crust.-No obvious signs of instability on our route. No shooting cracks, collapses, or whumpfs.-Skied out on E-SE aspects and crossed underneath several old crowns from the Feb 20th/21st cycle. There was about a foot of softer snow on top of these old bed surfaces which was the mid-Jan crust.", 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

102
102
{'location': "6996'", 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '20-30', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Previous', 'Weather Summary': 'Periods of sun and clouds.  Winds were calm.', 'Observation Date': 'Mar 7, 2023', 'Submission Date': 'Mar 7, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'The morning sun made our ascent a sweat-a-thon. We expected to see more solar-related instabilities on southern slopes, but we did not. The afternoon clouds continued to roll in and partly cloudy skies kept ambient air temperatures cool.\nWe traveled on a supportable crust that we estimated to be the result of a wind/sun-crust combination, that was topped with about an inch of soft snow.\nStubborn cornices previously developed from prevailing SW winds showed signs of erosion from the more recent N and E winds.\nWe observed reverse wind scour along ridgelines (also from recent N and E winds).\nSkiing “stiff” snow on a NE aspect made for many guarded, defensive turns with intermittent pockets of soft snow. \xa0Additionally conditions we sampled during our descent included wind-hammered powder, sun-crust, wind-board, and dust-on-crust conditions.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Mini rollerballs.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


103
103
{'location': 'Nyack Mountain  northeast face', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Route': 'On ascent, stayed below (on W/SW aspect) ridgecrest because of winds.', 'Cloud Cover': 'Not Observed', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': 'Howling, cold winds from the northeast', 'Observation Date': 'Mar 6, 2023', 'Submission Date': 'Mar 6, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'One several large natural avalanches reported 3/5-6, though date of occurrence not clear. Similar to other recent events: windloaded, north-east facing slope around 7000 feet and possibly triggered by natural cornice fall, sluff, or small slab.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


104
104
{'location': 'East side of the Swan Range -Alpha Beta', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'FAC', 'Activity': 'Snowmobiling/Snowbiking', 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': '25', 'New or Recent Snowfall (cm)': '6-8" in sheltered terrain', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Previous', 'Weather Summary': 'Periods of sun with mix of high clouds. Winds were calm.', 'Observation Date': 'Mar 6, 2023', 'Submission Date': 'Mar 6, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'We took advantage of the plowed West Side Reservoir Road and took the sleds to the east side of the Swan Range.\n\n\n\nRecent northerly winds hammered the exposed northerly slopes we traveled in, along with atypical drifts at mid-elevations that were responsible for mandatory sidehilling and exciting sled conditions.\nOlder cornices formed from southwest winds were eroded from the recent northern winds along the ridgelines.\nWe got some minor cracking in very small wind drifts along with small roller balls.\nTemperatures remained cool despite periods of sun. Winds were calm.\nWe did not get propagating results in our snowpack tests on southern and northern aspects at approximately 6,500 feet.\nWe skied sheltered terrain that consisted of 8 to 12 inches of wind blown snow. The best we could describe it as “bouncy” or “springy” powder.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Isolated cracking in very small wind drifts along the ridgeline.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


105
105
{'location': 'Nyack', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Mar 6, 2023', 'Submission Date': 'Mar 6, 2023', 'Observer type': 'public', 'Observation Summary': 'Much to our amazement no wind today! Recent storm snow is settling a bit, with only a hint of soft storm slab development. As per usual polar aspects the best, everything else is variable. Did include a picture of what I believe was a wind slab induced failure, about 3 feet thick. Notable that it extended and included old growth timber and what I believe most of us would consider reasonably sheltered/safe terrain.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


106
106
{'location': 'Cascade Cr', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '-5', 'New or Recent Snowfall (cm)': '15 cm', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Cloud cover built throughout the day as easterly winds increased and temperatures gradually dropped.', 'Observation Date': 'Mar 5, 2023', 'Submission Date': 'Mar 5, 2023', 'Observer type': 'public', 'Observation Summary': 'Good snow up high with substantial boosh still to be found up to 5k’ and a rain/MF crust up to ~4500’ below 15cm of new snow… making ingress and egress sub optimal. Wind affected (and actively loading) snow reserved to ridgelines and little loose dry concern with settled powder on slopes ~35*.', 'SIGNS OF INSTABILITY': 'Collapsing Observed (isolated)', 'Instability Comments': 'Only one small collapse noted today at ~5500’ at a thinner (and potentially faceted) spot along a ridgeline.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


107
107
{'location': 'Snowshed', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Our party was able to find excellent snow above 7 grand the past 2 days. Today, because of Saturdays sunny colorado like day we made sure to be on North facing terrain and scored deep soft consistent snow all the way to the creek!', 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': 'single digits?', 'New or Recent Snowfall (cm)': 'nope', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': 'today was cold and high cloud decklight winds', 'Observation Date': 'Mar 5, 2023', 'Submission Date': 'Mar 5, 2023', 'Observer type': 'public', 'Observation Summary': 'Lots of older avalanches, big ones.Skied above 35 degrees on treed and open slopes.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': "Saw massive old avalanches on Mount Adams steeper terrain lookers left of peak 500' below the ridgeline. It was difficult to see with the eye how thick the crusts were on S facing slopes, but saw small roller balls. Definitely effected by solar.", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


108
108
{'location': 'Marion', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '20', 'New or Recent Snowfall (cm)': 'N/O', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Light', 'Observation Date': 'Mar 5, 2023', 'Submission Date': 'Mar 5, 2023', 'Observer type': 'public', 'Observation Summary': "Travelled to 7000 feet on south aspect-Observed no evidence of wind effected snow on this aspect-Variable sun crust existed too ridge top on exposed features (did not affect riding quality too much)North facing terrain-Small cornice growth was unreactive to cut-Small wind pillows unreactive to cuts as well-Scalloped and duned shaped textures were seen under 5500' (not cohesive or stiff)-Cold wind in our face on skate out of Dickey-Blower pow", 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

109
109
{'location': 'Mt. Adams', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Mar 5, 2023', 'Submission Date': 'Mar 6, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Very large natural avalanche that likely failed during the late February natural avalanche cycle. Similar to other very large natural avalanches that occurred at this time. North through east facing, upper-elevation, leeward slope, possibly triggered by natural cornice fall, sluff, or small slab.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


110
110
{'location': 'Whitefish Range', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Mar 4, 2023', 'Submission Date': 'Mar 4, 2023', 'Observer type': 'public', 'Observation Summary': 'Ski toured the Whitefish Range near Olney and experienced overall good conditions on S-W facing slopes with some thicker wet snow in sun affected areas. Small rollerballs above 5000ft. Dug two pits:ECTP8 failed around 30cm on a S/SW face ~5400ftECTN 6 failed around 30cm on SW/W face ~5700ftManaged terrain by selecting areas with relatively clean runouts and avoided wind affected and N/E aspects.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Rollerballs noticed on sun affected aspects later in the afternoon', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


111
111
{'location': 'Cascadilla', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '22', 'New or Recent Snowfall (cm)': '12', 'Rain/Snow Line': "1000'", 'Snow Available For Transport': 'Large Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Prolonged periods of the sun with light winds and cool ambient air temperatures.', 'Observation Date': 'Mar 4, 2023', 'Submission Date': 'Mar 4, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'We traveled to Cascadilla in the Middle Fork to look closely at a very large D3 hard slab avalanche on Nyack Mountain.\n\nThis slide occurred Thursday, March 2, during an intense wind storm with gale-force winds resulting in substantial wind loading.\nThe trigger was a wind slab avalanche that released 200 feet below the ridgeline.\xa0\nCrown depth was estimated at 5+ feet deep. The width of the slide is approximately 1500 feet, estimated using CalTopo.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': 'Numerous natural loose dry sluffs occurred during the recent stormy weather. These were harmless size D1. We observed triggered sluffs from skiers on steep terrain and from prolonged solar input. These were also D1 in size.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


112
112
{'location': 'Sixmile', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Few (Mostly Clear, up to 2/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '6', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Clouds building in the afternoon.  Wind mostly calm gusting to light from the South around noon and shifting to easterly.', 'Observation Date': 'Mar 4, 2023 (9:30 - 17:00)', 'Submission Date': 'Mar 4, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'We searched the many ridges of Sixmile for wind-affected snow.\n- We encountered one pocket of wind-drifted snow that was sensitive enough to crack and slide a few inches. 6800ft NE aspect.\n- We found a couple small thin soft-slabs that would not crack around our feet.\n-Cornice of of varying shapes dotted a ridge perpendicular to the previous SW winds.\xa0We could break off the most recent growth with some stomping.\n-Recent snow sat atop hard drifts formed last week. On direct southerlies the snow was stripped down to the hard surface.\n- We saw light blowing snow from Southeast winds at upper elevations.\n-Solar aspects were moist by 1100 hrs. \xa0Trees were shedding snow and causing rollerballs at 1400 hrs. \xa0A new sun crust had formed by 1600hrs.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'On isolated pocket with cracking', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


113
113
{'location': 'WMR Side Country', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Not Observed', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Large Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': 'Saturday - Warmer than forecasted and sunny all afternoon.Sunday - Ridge lines were very windy with active snow transport out of the NE. Once off the ridge and in the trees it was mostly calm.', 'Observation Date': 'Mar 4, 2023', 'Submission Date': 'Mar 5, 2023', 'Observer type': 'public', 'Observation Summary': 'Temperatures Saturday felt much warmer than predicted. The sun was warming whatever it touched but the north aspects skied great. Roller balls were gaining stem at the end of the day.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


114
114
{'location': 'Colorado', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Mar 4, 2023', 'Submission Date': 'Mar 4, 2023', 'Observer type': 'public', 'Observation Summary': '6+” of new snow on top of yesterdays skin track. No wind. Sun was doing its thing on solar slopes. Heavy then refreezing. Polar aspects still glorious. Sluffing but nothing slabbing up', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


115
115
{'location': 'red meadows', 'Zone / Region': 'Whitefish Range', 'Activity': 'Snowmobiling/Snowbiking', 'Route': 'Leaving Olney and heading to Red Meadow', 'Observation Date': 'Mar 4, 2023', 'Submission Date': 'Mar 4, 2023', 'Observer type': 'public', 'Observation Summary': 'Clients reporting two feet of fresh powder near Red Meadow and previous slide before reaching Red Meadows that groom was unable to clear.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


116
116
{'location': 'Middle fork', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Few (Mostly Clear, up to 2/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '12 inches at middle elevations', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Large Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Overcast skies in the morning became mostly sunny by late morning/early afternoon. It was a calm day in the mountains with no wind experienced at our location.', 'Observation Date': 'Mar 4, 2023', 'Submission Date': 'Mar 4, 2023', 'Observer type': 'public', 'Observation Summary': 'We climbed to roughly 6000ft where we found about 12 inches of new/recent snow. We skied a NE aspect that was sheltered from both the sun and trees, and snow was dry and unconsolidated on this sheltered slope. There was much rejoicing.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': 'Just some minor stuffing below rocks or trees in steep terrain.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


117
117
{'location': 'North of Dickey creek', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'We skied north and south aspects north of Dickey creek between roughly 5300 and 6900 feet; we kept the slope angle to ~30* or less aside from the occasional steeper rollover.', 'Cloud Cover': 'Not Observed', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'None', 'Weather Summary': 'Sunny, warm, and calm!', 'Observation Date': 'Mar 4, 2023', 'Submission Date': 'Mar 5, 2023', 'Observer type': 'public', 'Observation Summary': 'We found excellent skiing on northern aspects and conditions that deteriorated quickly from the solar blast on southern aspects. Some party members regretted their wax choices (or lack thereof) and everyone brought out the skin wax. After one south facing run we returned to the shady north where the snow remained cold and dry. In steeper terrain the heavy wet snow on S aspects may have been more of a problem, but with mild terrain choices we interacted with no obvious instabilities.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': 'The sun came out and cooked the snow on south aspects creating heavy, moist, gloppy conditions, especially at lower elevations. We did not observe any substantial roller ball action, however.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

118
118
{'location': 'Flathead Range', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Out and Back', 'Observation Date': 'Mar 3, 2023', 'Submission Date': 'Mar 3, 2023', 'Observer type': 'public', 'Observation Summary': 'Multiple crowns and wind drifting noticed. Had to take an alternate, shorter, safer route.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': 'Multiple crowns and wind drifting noticed. Had to take an alternate, shorter, safer route.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


119
119
{'location': 'JFS Canyon', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Obscured (Sky not visible due to fog or non-cloud layer)', 'Temperature (F)': 'Low teens', 'New or Recent Snowfall (cm)': '4-6"', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': 'Intermittant snow showers - S-1 to S1, increasing to S2 mid afternoon. Gusty winds veering from SW to NW. Periodic blowing snow. A few breaks in the clouds.', 'Observation Date': 'Mar 3, 2023 (10:00 - 16:00)', 'Submission Date': 'Mar 3, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Dug profiles at multiple elevations to assess sensitivity and distribution of mid-January ice/ facets structure. The variability in structure and results was notable. The ice and facets were buried deeper at mid elevation profile site than our upper elevation site. The structure was generally but not completely unreactive. At the upper profile site, the layer of most concern was large, rounding depth hoar near the ground.\xa0\nRecent and drifted snow is forming a soft slab 15-30 cm thick at the snow surface. It produced some short cracks at uptrack corners and we released one small and harmless slab at mid elevations on our descent.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered  Cracking Observed (isolated)', 'Instability Comments': 'A few short cracks on uptrack corners.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


120
120
{'location': 'Apgar LO', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Up through the bush from the Camas Road closure then up a whole lot more bush to the lookout for a snow science chemistry pit. Back down the way we ascended.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '-7', 'New or Recent Snowfall (cm)': '20 cm', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Light', 'Observation Date': 'Mar 3, 2023', 'Submission Date': 'Mar 3, 2023', 'Observer type': 'public', 'Observation Summary': "Today we observed a very manageable and predictable dry-loose avalanche problem isolated to steep north facing slopes above 5000'. We also found prolific bush that made ingress and egress challenging. We observed light gusting moderate SW winds mostly at ridgetop and intermittent S1-S2 snowfall (mostly graupel). We dug a pit at 5200' on a SE 15* slope and found lingering weak snow around and between the mid-January crust and deeper Xmas crust - see attached pit profile for more details. We tested rounding facets buried ~75cm from the surface and just above the mid-January crust and observed unstable results (PST 37/100 END)... further evidence of the lingering persistent slab problem (picture attached).", 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'No obvious signs of instability observed today on our quick tour.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


121
121
{'location': 'Dickey Creek', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': "3/3: Traveled SW from parking lot to north facing ridge at low elevations above the x-country trail.3/4: Traveled SW from parking lot to north facing ridge up to 4,800'.", 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': '24', 'New or Recent Snowfall (cm)': 'Trace', 'Rain/Snow Line': 'N/O', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': '3/3: We witnessed cloudy skies and wind, light snowfall and graupel surface.3/4: We witnessed significant warming from the sun to the snow surface. It was a beautiful day to be out in the mountains.', 'Observation Date': 'Mar 3, 2023', 'Submission Date': 'Mar 4, 2023', 'Observer type': 'public', 'Observation Summary': 'Yesterday, we found several layers of crusts mixed with faceted layers. These layers were reactive. Today, in sheltered terrain we saw pockets of very weak snow with wind deposited and new snow on top. We did not see any significant ECT results. As we traveled we performed hand pits that showed signs of this wind/new to be forming a slab.', 'SIGNS OF INSTABILITY': 'Collapsing Observed (isolated)', 'Instability Comments': 'Collapses were isolated under individual body weight as we moved through terrain.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


122
122
{'location': 'Izak Walton', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Mar 2, 2023', 'Submission Date': 'Mar 2, 2023', 'Observer type': 'public', 'Observation Summary': 'Strong winds transporting snow, scouring surface and making wind slabs. Sun crust up to 7400 on solar aspect, covered by 4-6” assuming the wind hadn’t blown it away. Sheltered polar trees were the ticket. Snowed most of the day but hard to measure any meaningful accumulation', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


123
123
{'location': 'WMR Sidecountry', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Skied S/SW aspects.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '15-20', 'New or Recent Snowfall (cm)': '8-10" recent', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': 'Snowing all day.  Wind transporting snow on shoulders and ridges in the trees, not far below these zones the snow had little to no wind effect.', 'Observation Date': 'Mar 2, 2023', 'Submission Date': 'Mar 2, 2023', 'Observer type': 'public', 'Observation Summary': 'Great skiing in low angle trees.  Snowing and wind transporting snow on shoulders/ridges all day.  Minor cracking and small slabs moving without much energy later in the day.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered  Cracking Observed', 'Instability Comments': 'Minor stuffing on steep pitches in the morning, no other signs of instability.  As new snow accumulated observed minor cracking, less than ski length.  By the afternoon on small steep slopes we were able to trigger small, very soft slabs within the storm snow.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


124
124
{'location': 'Cascadilla', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '2', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Large Amounts', 'Wind Loading': 'Intense', 'Weather Summary': 'Light snow and increasing westerly winds throughout the morning with gusts strong to extreme.', 'Observation Date': 'Mar 2, 2023 (9:30 - 12:30)', 'Submission Date': 'Mar 2, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'We optimistically committed to our goal of reaching a mid-elevation crown despite the forecast for gusty winds:\n-We were lured into the basin by decent visibility, \xa0light westerly winds and light blowing snow.- Winds increased to moderate, visibility \xa0rapidly deteriorated and we were hit by an extreme gust that stopped us in our tracks at 1100hrs.\n-We dug a pit and found mixed results in our tests as we waited to see if the gust was an anomaly.\n-It became clear that strong-extreme gusts and the resulting whiteouts were becoming the norm, so we abandoned our goal and made an early retreat.\n-Wind-drifted snow was becoming sensitive during our exit: We were able to trigger table-sized slabs 3-4 inches deep.\nMedia to follow', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Minor cracking in wind-drifted snow during our early exit.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

125
125
{'location': 'Apgar Range', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Obscured (Sky not visible due to fog or non-cloud layer)', 'Temperature (F)': '24', 'New or Recent Snowfall (cm)': '2', 'Rain/Snow Line': '1000', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': 'Moderate to strong shifting winds on the ascent up an east-facing slope. The north-south ridgeline had sustained southwest winds. Light snowfall throughout the day resulted in minor accumulation.', 'Observation Date': 'Mar 2, 2023', 'Submission Date': 'Mar 2, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'I chose the windy southern Apgar Range to monitor wind slab development and to take a closer look at the snowpack structure in an area with a skier-triggered slide ten days prior.\n\nAt 3300 feet, 6 inches of loose, dry snow rested on a rain crust. Above 5000 feet, up to 10 inches of loose, dry snow rests on older settled snow. The rain crust disappeared around 4200 feet.\nModerate to strong winds and blowing snow were observed from the valley floor to the ridgeline.\xa0\nOn and directly below ridgelines were the only spots where slabs and cornices were cohesive enough to be reactive to my weight. They were very soft elsewhere.\nSaddles on the ridgeline provided the most excitement. This is where winds funneled and cranked, resulting in cornice and slab development.\xa0\nFresh drifts throughout the tour were soft but up to 30 inches thick.\nA snowpit revealed the Christmas and mid-January crust, but snowpack tests resulted in ECTX.\nGood riding conditions in areas not scoured by the winds.', 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)', 'Instability Comments': 'Wind slabs were cohesive enough to crack beneath my skis but only traveled beyond the length of my skis in the most wind-loaded areas on the ridge.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


126
126
{'location': 'Swan Range', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '6-10', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Light winds in morning. Sustained moderate/strong on ridgeline. Wind speeds felt that they picked up in the evening.', 'Observation Date': 'Mar 1, 2023', 'Submission Date': 'Mar 1, 2023', 'Observer type': 'forecaster', 'Observation Summary': "Weather station maintenance day for Aeneas Station in the Swan Range. Thanks to Ted and Adam with the BNSF Avalanche Safety Program for helping us maintain our weather stations.\n- 6 to 10 inches of settled powder from Tuesday's storm.\n- New snow sits on a pencil-hard wind slab that is roughly a foot thick.\n- Mid-January crust is buried 185 cm at 6500 feet. This crust is in close proximity to buried surface hoar. This weak layer was the culprit of numerous avalanches during January and early February.\xa0\nLimited time for field data. Wind, temp, and RH are back in action.", 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


127
127
{'location': 'Review Ridge', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '4"', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Westerly winds gusted to moderate and clouds moved in  the afternoon.', 'Observation Date': 'Mar 1, 2023 (11:00 - 16:00)', 'Submission Date': 'Mar 1, 2023', 'Observer type': 'forecaster', 'Observation Summary': "We traveled to the northern Whitefish Range to assess the impact of last week's storm:\n-We were unable to reach our intended viewshed due to large drifts of snow blocking the road.\n-We saw no recent signs of avalanche in our limited views of start zones.\xa0\n-We found a thin and weak snowpack at low and mid elevations on aspects NE to SE\n-We got variable results in repeat tests in our snow pits.\n-Westerly winds continued to rake trees clean, blow snow along ridges, and build cornices.\n-Surface snow at low and middle elevations became moist by early afternoon.\xa0 Roller balls and very small wet loose ran from rocky, south-facing terrain.\n-Ramping winds and building clouds cooled the snow surface enough to form a breakable crust on solar aspects by late afternoon.\nWe skied through the crust happily as we avoided the thick timber, brush, and exposed talus slopes we encountered elsewhere.\xa0 We felt confident riding a short slope steeper than 35 degrees as there was barely enough to cover surface roughness.", 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)  Collapsing Observed (isolated)', 'Instability Comments': 'Cracking and collapsing on SE through NE aspects near 5000 feet.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


128
128
{'location': "Peak 6996'", 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': "Lazy day late start bluebird pow tour in southern Glacier Park from 4400' to 7000'. Descended NE exit back to car.", 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': '20-32', 'New or Recent Snowfall (cm)': '4-6"', 'Rain/Snow Line': 'N/A', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Not Observed', 'Weather Summary': 'Mostly clear skies changed to broken, then overcast by sunset. Snow in areas with solar exposure developed a sun crust when clouds rolled in. Temperatures remained below freezing. Winds were intermittent and breezy at lower and middle elevations, with occasional gusts from unexpected directions. Winds were SW-W, moderate, and sustained at ridgeline throughout the day. We observed moderate blowing snow on ridges and summits.', 'Observation Date': 'Mar 1, 2023', 'Submission Date': 'Mar 1, 2023', 'Observer type': 'public', 'Observation Summary': 'We thought we were in a different region with a bluebird pow day today! We had a lazy start and didn\'t start skinning until around 1215. Although the temperature stayed at or below freezing, the sun had warmed the roughly 4" of new snow at 4400\' enough to cause skin glopping in solar areas. By the end of the day (1730) all areas with prolonged solar exposure below roughly 5500\' had developed a sun crust as clouds rolled in and temperatures began to fall. I expect areas that developed this sun crust to have particularly active sluffing with the forecasted snowfall in the next couple days. --New snow totals were between 4" and 6" with higher totals at upper elevations. --We observed an intermittent and gusty, generally SW-W wind blowing and transporting snow at summits and ridgelines throughout the day. --Felt a few collapses, with one larger audible one while ascending a S ridge around 6300\'. --Observed wind loading and wind affected snow throughout the tour, with loading generally left over from last week\'s strong NE wind event, and cornice formation in unusual areas. --New snow was fluffy and skied phenomenally.', 'SIGNS OF INSTABILITY': 'Collapsing Observed (isolated)', 'Instability Comments': "Felt two small collapses and one audible bigger collapse while ascending a south facing ridge between 6200-6500'.", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


129
129
{'location': 'Laka-skooka-kinnimiki-leel', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': '20s', 'New or Recent Snowfall (cm)': '4-7"', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Previous', 'Weather Summary': 'Blue sky morning, with mid-day inversions, then late afternoon stratus. Winds light and variable, with hints of fresh wind transport on exposed ridgeline. Cold in the shadows, warm in the sun.', 'Observation Date': 'Mar 1, 2023 (9:30 - 18:00)', 'Submission Date': 'Mar 1, 2023', 'Observer type': 'forecaster', 'Observation Summary': "Traveled to a drainage with some of the larger slide paths in the southern Whitefish Range to look for evidence of a persistent slab avalanche problem involving the mid-January crust/ ice. The steep, rocky paths in this terrain don't appear to have produced natural avalanches during the February cycle. We did find rounding facets under the mid-January ice layer in a mid-elevation profile on a southeast facing slope. Tests resulted in no propagation or sudden failures on this layer, or storm interfaces above.\xa0\nWe triggered one wet loose sluff on a very steep convexity. No other signs of instability.", 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

130
130
{'location': 'Little Dog Mtn', 'Zone / Region': 'Other', 'Activity': 'XC Skiing/Snowshoeing', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '22’F', 'New or Recent Snowfall (cm)': '5-6”” overnight', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Previous', 'Weather Summary': 'Light snow showers all day', 'Observation Date': 'Feb 28, 2023', 'Submission Date': 'Feb 28, 2023', 'Observer type': 'public', 'Observation Summary': 'Impressive walls left by snow slide - looked more like Spring time action, but it’s been very cold,  Recent heavy snow followed by -20 to -30’F with an 8 hr window of 50+ mph winds - Today 22’F', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


131
131
{'location': 'JFS Canyon Snowshed and Snowslip Mtns.', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Highway observations and a ski tour in the Shed 7, 6, 5 area', 'Cloud Cover': 'Not Observed', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': '•\tOvercast skies with light snowfall accumulations throughout the day.•\tLight SW winds above 5500’ elevation.•\tDaytime highs reached into the upper 20s °F on the Canyon floor and into the upper-teens °F above 6000’ elevation.', 'Observation Date': 'Feb 28, 2023', 'Submission Date': 'Feb 28, 2023', 'Observer type': 'public', 'Observation Summary': '•\tNo recent avalanche activity observed.•\tA small (D1.5) slab avalanche ran in the Test Slopes on the Shed 6/7 ridge sometime during the Feb. 20th/21st storm.•\tFrom the highway we saw the crown of the large hard slab avalanche that the FAC team investigated on Sunday, Feb. 26th. This is on the east face of Snowshed Mtn. and just outside of the Railway Program Area (photo).•\tNo obvious signs of instability observed. No collapses or whoomphs. •\tNo active windloading. Signs of previous windloading evident on all aspects.•\tSubstantial previous crossloading of mid and upper elevation starting zones in the Program Area. Particularly in the starting zones of Shed 5 and Path 1163.•\tExcavated a test pit at ~6000’ elevation, SE aspect, 30° slope to investigate and test the persistent weak layers of concern that are deeply seated in the snowpack.o\tTotal snow depth was 170 cm (67”).o\tThe Feb 20th/21st pre-storm interface was at 105 cm (26” down).o\tThe mid-Jan. facets/crust interface was at 65 cm (40” down).o\tThe late-Dec. facets/crust interface was at 45 cm (49” down).o\tThe first Extended Column Test yielded no fractures (ECTX)o\tCompression Test resulted in CT22 Q2 at the Feb 20th/21st storm interface.o\tDeep Tap test performed over the mid-Jan facets/crust resulted in DT25 Q2 on facets just above the late-Dec. crust.o\tStill curious, we removed 14” off the top of our 2nd ECT column and repeated the test. We had propagation at 30 taps on the facets atop the late-Dec. crust with the block then sliding into the pit.o\tFinally, a Propagation Saw test on the facets above the late-Dec. crust resulted in 65/125 END.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


132
132
{'location': 'WMR Sidecountry', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Beaver Ponds - Kona - Big Trees', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '25', 'New or Recent Snowfall (cm)': '4-8"', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Previous', 'Weather Summary': 'Snowed lightly off and on until about 2:00 when it came down at 2"/hour for almost an hour. 3-4" of new snow during our tour on top of about 4" from the night before.', 'Observation Date': 'Feb 28, 2023', 'Submission Date': 'Mar 1, 2023', 'Observer type': 'public', 'Observation Summary': "Skied some better than expected snow on the north side of Goulie then walked up to Kona. There were wind drifts in odd places and in probing the NW side of Kona(6300') found small hard wind slabs spread out along the treed ridgeline. In a hand pit test I had a 30cm fairly hard slab shear off with moderate force on a layer of graupel.Observed multiple insignificant loose dry slides in the Skook Chutes.", 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Nothing of concern', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


133
133
{'location': 'Wahoo', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '25', 'New or Recent Snowfall (cm)': '3 inches', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Winds were calm, with intermittent squalls of snowfall that lasted about 10 minutes each. The low cloud ceiling made for poor visibility.', 'Observation Date': 'Feb 28, 2023', 'Submission Date': 'Feb 28, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Today we went avalanche hunting and mostly got skunked.\n\nSurprisingly, the drainage we toured in today did not have widespread natural avalanche debris that the neighboring drainages experienced.\nWe observed 6 soft slab avalanches (D1 to D2) on northern aspects at mid-elevations. Across the drainage, the steep southerly avalanche paths did not appear to run.\nThere was 3 inches of new snow, over 3 inches of recent snow, all on top of a crust. This crust disappears at around 5000 feet.\nThere were many very small point releases of loose, dry sluff that occurred today.\nWe did not have propagating results in our ECT. Please see snowpack tab.\nSkiing powder was worth the sporty skinning over downfall and dodging alders.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


134
134
{'location': 'Elk Calf/Flattop', 'Zone / Region': 'Other', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Clear (No clouds)', 'Temperature (F)': 'Below Freezing', 'New or Recent Snowfall (cm)': '3-6"', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': 'As advertised, winds began to pick up Wednesday afternoon bringing overcast skies and large wind transport.', 'Observation Date': 'Feb 28, 2023', 'Submission Date': 'Mar 2, 2023', 'Observer type': 'public', 'Observation Summary': 'Spent a couple days touring in the South Fork Two Medicine. Conditions were great as recent snowfall fell on supportable wind-board that was present among most terrain in the Two Med valley. Wind was calm to nil. Tuesday evening a good band of snow deposited a few quick inches before skies cleared and the mercury dropped to zero. Wednesday we found great skiing on low-angle, E facing slopes (6500-5000) under sunny skies before the onslaught of Westerly wind began to wreak havoc in the region.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


135
135
{'location': 'Snowshed', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Pin is just the area. Essex. Snowshed.', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '22', 'New or Recent Snowfall (cm)': '4-6”', 'Rain/Snow Line': '3300', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Intense', 'Weather Summary': 'The wind has been blowing in the middle fork in all directions and the snowpack reflects that. Easy to see wind loaded cornices and cross loaded ridges. The new snow didn’t move around too much yet.', 'Observation Date': 'Feb 27, 2023', 'Submission Date': 'Feb 28, 2023', 'Observer type': 'public', 'Observation Summary': 'Some cool natural activity from the last few days. We had good vis and were able to see many crowns on the surrounding peaks. Didn’t want to push it in these conditions, kept it pretty low angle. Lots of facets under the wind crust.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': 'No audible collapsing or cracking, saw some big natural crowns and old debris that was covered with the fresh snow from the last few days', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

136
136
{'location': 'Flathead Range', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Previous', 'Weather Summary': 'Overcast skies in the morning. Broken skies in the afternoon.', 'Observation Date': 'Feb 27, 2023 (9:00 - 16:00)', 'Submission Date': 'Feb 27, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Today we partnered up with the BNSF Avalanche Safety program to look for recent avalanche activity and assess the snowpack structure on a path above the rail.\n- We experience 4 audible collapses. These occurred at mid-elevations on an east-facing ridgeline.\xa0\n- We had propagating results in an extended column test on an east aspect at roughly 5400 feet. The slab above this weak layer is roughly 2 feet thick.\xa0\n- Surface snow is faceting.\n- We observed numerous crowns at mid and upper elevations (no surprise), some of which are already documented.\xa0\nWe primarily stuck to ridgelines and spaced out on the few very short steeper pitches.', 'SIGNS OF INSTABILITY': 'Collapsing Observed (isolated)', 'Instability Comments': '4 audible collapses on an east-running ridgeline between 5100-5400 feet in elevation.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


137
137
{'location': 'East of WMR', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '20', 'New or Recent Snowfall (cm)': '2 inches of recent snow', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Previous', 'Weather Summary': "Most of the day was calm winds. Light snowfall around midday, but it didn't seem to accumulate.  The afternoon had periods of sun, but temperatures remained below freezing.", 'Observation Date': 'Feb 27, 2023', 'Submission Date': 'Feb 27, 2023', 'Observer type': 'forecaster', 'Observation Summary': "Today's priority was to practice our rescue skills and thank Whitefish Mountain Resort's\xa0Ski Patrollers.\n\nAs Forest Service employees, we are required to practice our beacon skills once a month. Grey Wolf Beacon Park (at WMR) is an excellent place to accomplish this requirement.\nWe are incredibly grateful to work with the ski patrol professionals at WMR. They share their daily weather data, which improves the value of our forecasts.\nEast of WMR, we traveled to Skook peak to take a look at the various wind-affected surfaces.\nMultiple layers of building cornices (photo) were telling of the winds over the past several days. Cornices were stubborn except for the top thin layer. Those layers looked like diving boards hanging over the main cornices. Rideline surface snow was firm, unsurprisingly.\xa0\nWe did not have propagating results in our ECT test in our northwesterly snow pit at 6700 feet.\nWe skied a sheltered, northwesterly slope. We made some nice turns in the top soft snow with a little harmless stuffing.", 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Harmless sluffing in recent 2 inches of soft snow.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


138
138
{'location': 'Link Mountain', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '12', 'New or Recent Snowfall (cm)': '2 in', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'S-1 to S1 snow showers through the day, with alternating obscured and broken skies. Accumulation of 1" on sleds mid afternoon. Appears to have been 2-5" in since Sunday AM, with lots of debris scattered on trail at low elevations and drifts along groomed trail. Sunday\'s snow not as rimed/ graupel as in Flathead Range. Light but gusty SW winds today, with light drifting at ridgeline.', 'Observation Date': 'Feb 27, 2023 (9:30 - 16:30)', 'Submission Date': 'Feb 27, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Traveled to Link Mountain to de-rime the weather station. Compared to earlier this winter, it was almost nekkid. Recent natural avalanches crossed the groomed trail below Red Meadow lake. Recent bouts of winds have deposited a chaotic sea of drifts at near ridges above about 6500 feet. Even away from ridges, many slopes harbor a layer of drifted snow thats mostly supportable. It made for some harder-than-it-should-be skinning and variable skiing.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': 'Some short cracks 10-15 cm deep and < 100 cm long in drifted snow, mostly where it sat on older, very hard snow.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


139
139
{'location': 'Southern Flathead Range', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': "East and South Facing Slopes Between 3,800-6,400'", 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '21', 'New or Recent Snowfall (cm)': '2cm', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Previous', 'Weather Summary': 'Light snowfall, broken skies, and calm winds throughout most of the morning. New snow throughout the day estimated 2cm middle elevations. Sun began to peak through around 2pm, leaving a thin superficial crust on southernlies.', 'Observation Date': 'Feb 27, 2023', 'Submission Date': 'Feb 27, 2023', 'Observer type': 'public', 'Observation Summary': 'We found nice riding and good stability on South and East facing slopes, lower and middle elevations. Our south facing lap was through fairly mellow glades and our east facing lap took us into steeper terrain( 45+ degree avalanche path). 15cm of nice powder on supportable windboard 6400-5200. Faceted surface snow and minor sloughing observed in steeps 5200-4400. Punchy unsupportable windboard/crust and variable/poor skiing below 4400.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'None Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


140
140
{'location': 'Near Red Meadows', 'Zone / Region': 'Whitefish Range', 'Activity': 'Snowmobiling/Snowbiking', 'Route': 'Leaving Olney on the way to Red Meadows we observed two areas next to each other that had recently slid.  Approximately 3-4 miles past upper whitefish lake these slides obstructed the trail.', 'Observation Date': 'Feb 26, 2023', 'Submission Date': 'Feb 27, 2023', 'Observer type': 'public', 'Observation Summary': 'You can see above the overhang where the avalanche broke from.  The slide was across the groom trail obstructing the trail.  People have cut across this on snowmobiles so there is a single track trail through the slide.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


141
141
{'location': 'Apgnar Lookout', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': "Headed up toward Apgar Lookout, got to about 4800' and turned around.", 'Cloud Cover': 'Not Observed', 'Temperature (F)': '36', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Observation Date': 'Feb 26, 2023', 'Submission Date': 'Feb 26, 2023', 'Observer type': 'public', 'Observation Summary': 'We experienced some localized cracking around our skis. Most of this SW aspect we somewhat wind affected.We observed obvious recent crowns on the NW face across from the canyon near Apgar lookout.We dug a pit which showed 18" of densified new snow on drying rounded snow. There was a slightly faceted layer 6 inches down in the new snow. The interface between the new snow and the drying rounded snow was poor. We recorded an ECTN15 but after the ECT we pulled lightly behind the block that was left and it easily popped off. While we felt the newer densified snow was not consolidated enough to propagate we decided to turn around based on this information.It was quite warm at our location with only light winds.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Cracking Observed (isolated)', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

142
142
{'location': 'Essex: Snowshed Crown Profile', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '1', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': 'Gale force gusts at upper elevation ridgelines. Increasing winds throughout the day.', 'Observation Date': 'Feb 26, 2023', 'Submission Date': 'Feb 26, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Today we visited a crown to identify what the recent carnage in the Flathead Range is failing on. We suspect this slide occurred during the Feb 20/21 storm.\xa0\n- We observed a hard slab that failed on a persistent weak layer (facets below the mid-January crust). This avalanche failed on an E aspect at 7000 feet.\xa0\xa0\n- We estimated this avalanche was a D3 (very large). We found snapped trees in the debris on the smallest part of this avalanche. Visibility was obscured where this avalanche ran the furthest.\n- A large portion of this avalanche wrapped onto a 30-degree slope. That slope angle is the low end of slope steepness for "avalanche terrain." The majority of this start zone measured 35 degrees.\xa0\n- Strong winds were transporting snow into small firm slabs. The only sign of instability in the new snow was isolated cracking.\nWe traveled on bed surface and avoided steep terrain that had not slid. Unfortunately, this will likely be my approach for some time to come in the Flathead Range.\xa0\n\xa0\nSorry for the bad photos. Poor lighting.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


143
143
{'location': 'Mid-day Middle Fork', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '24', 'New or Recent Snowfall (cm)': '5 cm', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Intense', 'Weather Summary': 'Westerly and southwesterly winds most of the day, reaching into valley bottoms at times. Gale-force gusts at ridgeline, with an hourish break mid-afternoon. Snow much of the day, S-1 to S2, pushing S5 briefly. Mostly heavily rimed precip particles that were not cohesive. Hard to tell how much fell because of moderate-intense blowing snow.', 'Observation Date': 'Feb 26, 2023 (10:00 - 17:00)', 'Submission Date': 'Feb 26, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Lots of blowing snow and plenty of thin, soft slabs of drifted snow near crossloaded, mid-elevation ridgelines.\xa0 Unreactive, except for one soft slab released on a ski cut. Cornice drops did not produce slides. We did not linger in the maelstrom of winds at the main ridgeline to investigate more exposed terrain. Stuck to sheltered, north through east slopes with short pitches of 30-35*. Very good riding on soft, settled, boot-top drifted and new snow. Snow profile and tests on a northeasterly slope at 6700 ft did not produce propagation or sudden shears under the wind slab, on a layer of graupel, or near the mid-January crust (~130 cm below the surface).', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


144
144
{'location': 'Sub Shields', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Standard skin route to the top of Sub Shields (6996) and down the "Big Run"', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '30', 'New or Recent Snowfall (cm)': '1-2', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Moderate', 'Weather Summary': 'windy', 'Observation Date': 'Feb 25, 2023', 'Submission Date': 'Feb 25, 2023', 'Observer type': 'public', 'Observation Summary': 'High winds along the ridge that leads to the summit.  The cornice on the approach to the top of 6996 was very sensitive and broke off while standing five feet from the edge.  The southerly facing bowl near the top of Sub Shields was very wind affected. It appears that the wind had blown in several directions over the past few days as wind loading was occurring in areas where it normally doesn\'t.  The ski down the big run was "slabby".', 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)  Collapsing Observed (isolated)', 'Instability Comments': 'I witnessed one collapse where wind loading was occurring on a ridge.  I experienced snowpack cracking in a similar location.  These were both isolated incidents.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


145
145
{'location': 'Essex', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Not Observed', 'Temperature (F)': '30', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': 'Calm, mostly sunny.', 'Observation Date': 'Feb 25, 2023', 'Submission Date': 'Feb 25, 2023', 'Observer type': 'public', 'Observation Summary': 'Variable snow up to 6,200 ft. Trees were dripping by 4 at about 4,000 ft. even on non-solar aspects.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


146
146
{'location': 'Skookoleel', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Lower skin track (westerly) for approach to ridge on top of Skookoleel, back down low angle trees near skin track.', 'Observation Date': 'Feb 25, 2023', 'Submission Date': 'Feb 25, 2023', 'Observer type': 'public', 'Observation Summary': 'Snow was soft and mostly unaffected by wind up until about ~6400ft. Above that was the expected wind dunes, drifts, and harder pack surface. Firm wind affected surface on ridge.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Some cracking around skis on test slopes, with no obvious signs of propagation or sliding. Cracking was more prevalent as we reached higher elevation on more wind affected snow, still no propagation.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


147
147
{'location': 'Essex', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': 'Below Freezing', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Observation Date': 'Feb 25, 2023', 'Submission Date': 'Feb 25, 2023', 'Observer type': 'public', 'Observation Summary': 'Visibility improved throughout the afternoon and many recent, large to very large avalanches, were visible all along the Flathead Crest on typical leeward aspects. Name any peak along the crest in the Essex region and there were crowns present; variable elevations, but certainly in steep, alpine terrain above 6500\'. The largest avalanche crown observed was in the unnamed "Sheep Lakes" area of Sheep Creek (East of Felix)...Estimated D3 or D3.5. The width of the slide was impressive.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


148
148
{'location': 'Great Bear Crk', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '15 in the morning and 35 in the afternoon at hwy 2', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': 'Calm and overcast most of the day though clouds were moving fast along the ridge. Sun came out around 4 as the clouds blew off.', 'Observation Date': 'Feb 25, 2023', 'Submission Date': 'Feb 25, 2023', 'Observer type': 'public', 'Observation Summary': "Dug a pit at 6100' on a 30 degree SE facing slope that wasn't obviously wind affected. ECTN, a little lateral force caused the column to fail on sugary snow at 115 cm.", 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

149
149
{'location': 'Cascadilla', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '22', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': '1000', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Moderate', 'Observation Date': 'Feb 25, 2023', 'Submission Date': 'Feb 25, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'I visited the Cascadilla drainage to catalog recent avalanche activity associated with the Atmospheric River event from February 20 and 21.\xa0\n\nMost every avalanche path in this drainage slid during the storm. Three paths ran as hard slabs and produced D3 debris at the mid and upper elevations.\nTwelve mid-elevation paths produced D2 soft slab debris which terminated in the valley floor.\xa0\n10-15 smaller soft slab slides were noted in cross-loaded convex terrain features between 5000 and 5500 feet.\xa0\nAvalanche crowns ranged in elevation from around 5000 to 6600 feet and were on NW-NE-SE aspects.\nThe surface snow, which was cold-smoke quality yesterday, had warmed and densified but was still in good shape.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


150
150
{'location': 'Southern Flathead Range', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Feb 25, 2023', 'Submission Date': 'Feb 25, 2023', 'Observer type': 'public', 'Observation Summary': 'We found nice supportable powder on sheltered, mid-elevation S-SE terrain. No cracking or other sign of instabilities encountered. Sky was broken until 1330 when clouds cleared and the sun really shone through. Calm to moderate mostly SW winds kept the snow surface cool. We observed wind effect in open burned areas at middle and lower elevations. The snow was punchy, sugary, and much less supportable at lower E elevations.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


151
151
{'location': 'Delrey Rd', 'Zone / Region': 'Whitefish Range', 'Activity': 'Snowmobiling/Snowbiking', 'Route': 'From Delrey to Upper Whitefish Campground and Lower Antice.', 'Observation Date': 'Feb 24, 2023', 'Submission Date': 'Feb 24, 2023', 'Observer type': 'public', 'Observation Summary': 'My guide reported a lot of downed trees and drifts from Delrey to Upper Whitefish Campground. We did not go up striker but he would imagine that with the wind blown snow and trees there will be some slides.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


152
152
{'location': 'Goulies', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Skin up to Goulies ridge, dig pits, ski down trees above and right of Half Moon', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '8', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Intense', 'Weather Summary': 'Light winds coming from the SW, cold temperatures, very short breaks of sunshine masked by a thin layer of clouds, with predominately overcast skies, no precipitation', 'Observation Date': 'Feb 24, 2023', 'Submission Date': 'Feb 24, 2023', 'Observer type': 'public', 'Observation Summary': 'Considering the strong, Northeasterly winds the Whitefish Range experienced over the last 48hours, the SE aspects including our test site seemed relatively unaffected by the wind. Extreme wind affect resulting in pillows, wind slabs, and sastrugi was observed during our skin along Goulie Ridge. The SW aspect of which we descended back into the resort we encountered few pockets of light snow, though mostly wind affected with small reactive wind slabs.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


153
153
{'location': 'Ghoulie Pt', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Skinned just South of Ghoulie Pt to assess conditions, then skiied NW facing slope to the Bigfoot T-bar.', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Moderate', 'Weather Summary': 'Winds were light from the SW, cloud ceiling was around 7000ft then became clear after 4:00pm, no snowfall.', 'Observation Date': 'Feb 24, 2023', 'Submission Date': 'Feb 24, 2023', 'Observer type': 'public', 'Observation Summary': 'We found clear evidence of the recent NE wind event on the landscape, in the form of tree debris and wind slabs. SW facing slopes seemed to remain relatively unaffected. The ridgetops had wind slabs that varied in depth and hardness, and were limited in size because of the tree-cover along the ridge.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


154
154
{'location': 'East of WMR', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '0ish', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Previous', 'Weather Summary': 'Decreasing clouds. Light SSW winds.', 'Observation Date': 'Feb 24, 2023 (14:00 - 17:00)', 'Submission Date': 'Feb 24, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Quick explore while Mr. Cold Miser was distracted. Winds early this week played havoc with the snow near ridgelines - drifts, dunes, scouring, crusts, slabs. Surface patterns indicated these were upslope winds, mostly from the N and E. Also found evidence of upslope southerly winds at basin bottom. All hope is not lost, however. Mid slope snow remained soft on E, S, and NW facing slopes.\xa0\nDid not find much evidence of a wind slab problem on these mid elevation slopes. A ~10 cm thick, 4F+ hard wind slab failed easily in tests, but did not propagate and weak layer did not appear to be a persistent weak layer. No propagation or alarming results in the top ~75 cm of the snowpack in tests on a mid elevation, ESE-facing slope.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Surprisingly, no cracking in wind-drifted snow longer than a foot or so.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


155
155
{'location': 'The Swan', 'Zone / Region': 'Swan Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Navigated some pronounced whoopties and a wind drifted roadway in search of powder in the swan.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Intense', 'Weather Summary': '2 degrees in the AM, 14 in the PM at the car. Cloudy in the AM and clearing in the PM.', 'Observation Date': 'Feb 24, 2023', 'Submission Date': 'Feb 24, 2023', 'Observer type': 'public', 'Observation Summary': 'Wind F-ed snow on SW, NE, N, and W aspects, including in treed areas that seemed as if they should be protected. Snow remained on trees but somehow not on the ground. In some places the surface snow was knife hard wind board. We did find some good turns in some tight trees and noted that anywhere it opened up, even briefly, was hammered by the wind. Where the snow was good, it was deep.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Despite visual cues of the wind’s effects (scouring, cornices, debris everywhere, sastrugi), we saw little to no cracking, heard no whoomphs, and saw no recent avalanches.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


156
156
{'location': 'Central Whitefish Range', 'Zone / Region': 'Whitefish Range', 'Activity': 'Snowmobiling/Snowbiking', 'Cloud Cover': 'Few (Mostly Clear, up to 2/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '18-24"', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Observation Date': 'Feb 24, 2023', 'Submission Date': 'Feb 25, 2023', 'Observer type': 'public', 'Observation Summary': 'Natural avalanche observed by public, submitted by forecaster.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

157
157
{'location': 'Mt. Marston', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'FAC', 'Activity': 'Snowmobiling/Snowbiking', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '0', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Large Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Temps started just below 0 and ended just above.  Some low cloud giving way to decent visibility under broken skies. Intermittent light SW wind.', 'Observation Date': 'Feb 24, 2023 (9:30 - 13:30)', 'Submission Date': 'Feb 24, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Crept back out into the cold. \xa0Left the skis behind to simplify our plan:\n-The first 15 minutes of riding was pretty brutally cold. \xa0After the handwarmers heated up and the screaming barfies went away, it turned into a pleasant day.\n-This area received roughly a foot of snow earlier this week.\n-We found several small natural loose-dry and slab avalanches that failed during the the snowfall. \xa0\n-This area seemed to have been spared from the recent NE winds. \xa0We did find evidence of SW winds at all elevations.\xa0\n- We slope cut small test slopes without any signs of instability.\xa0\n-Our route was choked off by a long train of hard and stubborn drifts at 7000 feetRiding through or around the drifts seemed like more cost than benefit, so we\xa0bailed on our summit bid and made an early exit.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Minimal cracking around machines.  No perceived collapses in limited ofd trail travel.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


158
158
{'location': 'Flathead Range - Snowshed Mtn and Skiumah Lake', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Driving Hwy 2 and ski to Skiumah Lake', 'Observation Date': 'Feb 24, 2023', 'Submission Date': 'Feb 24, 2023', 'Observer type': 'public', 'Observation Summary': "Saw portions of two large crowns on Snowshed Mtn, D2s at least. One on the SE face above Sheep Creek at about ~7000' and another on the E face above McDonald Ck at ~6800'. Estimated these ran back on Feb. 20th/21st during the storm. This last one may have been previously reported? Crown thickness looked to be 2-4'. Could not view the rounout or debris.Skied into Skiumah Lake in the afternoon. Widespread avalanching in here during the Feb. 20th/21st storm. Multiple D2 and D3s with a few events putting debris down to the lake. Multiple crowns observed on the surrounding terrain, 2-4+ feet thick and some running several hundred feet. Two large ones up on the NNE face of Penrose and Peak 7510' (photos). Also, notable were a couple large crowns (estimated 3-4') thick on the steep slopes only a few hundred feet above the lake, around 5200' (photos).Several crowns look like they may have failed on older persistent weak layers but did not inspect any crowns close up to confirm.", 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


159
159
{'location': 'Rescue Creek', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '4', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': '0', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': 'Cold temperatures were bearable until I traveled further up this open drainage. Increasing winds and ambient air temperature resulted in chilly wind chill readings and exfoliation of any exposed skin.', 'Observation Date': 'Feb 24, 2023', 'Submission Date': 'Feb 24, 2023', 'Observer type': 'forecaster', 'Observation Summary': "I enjoyed time with the Patrol Fund Level 2 class in the morning. In the afternoon, I took a short walk up Rescue Creek to catalog recent avalanche activity and assess the near-surface conditions.\n\nMany large avalanche paths ran earlier this week during the Atmospheric River event. I spotted 4 D3-sized slides that had hard slab characteristics. Debris is estimated to have run 2000 - 2500'+. Other paths produced D1.5 - 2 of mostly soft slab debris. The lighting was poor, and I could have missed a few slides.\nA handful of thin, soft slab crowns was observed in cross-loaded convexity features.\nThe number and size of avalanches were about average for an avalanche cycle in this toilet bowl.\nThis afternoon, the southwest wind kicked into gear, moving plenty of low-density surface snow and snow off tree branches.\xa0\n8 cm of champagne powder rests on a supportable 10 cm thick crust at 4000'. At 5000', 15 cm of cold smoke rests on a 5 cm breakable crust.\xa0\nLarge swaths of this drainage escaped the effects of the northeast winds.\nGood riding conditions today. Southwest winds may affect the snow quality in this open drainage by tomorrow.", 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)', 'Instability Comments': 'Cracking was observed in soft wind slabs at low and mid-elevations. These did not propagate beyond the length of my skis.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


160
160
{'location': 'Skiumah', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Driving', 'Route': 'Hwy 2', 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Intense', 'Weather Summary': 'Wind and drifting increased in JFS canyon up to the summit.  Blowing snow obscured the sky near Marias Pass', 'Observation Date': 'Feb 23, 2023 (3:00 - 5:00)', 'Submission Date': 'Feb 23, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Out for a drive on a cold day. Visibility was good enough to spot some crowns in the Flathead Range.\n- Noted one large (D2) natural failing on a wind-loaded SE slope at upper elevations.\n-Saw several of the recently reported crowns on Nyack.\n-Wind effects were notable at all elevations particularly near the continental divide.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


161
161
{'location': 'Flathead Range - Cascadilla', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Driving', 'Route': 'View from Hwy 2', 'Observation Date': 'Feb 22, 2023', 'Submission Date': 'Feb 22, 2023', 'Observer type': 'public', 'Observation Summary': "At least 4 crowns in Cascadilla Creek from very early yesterday or the night of the 20th/21st. All were partially filled back in with recent snow. One was down on the low bench around 5300' and the others were up high (6500-7000') on the NE face Nyack Mountain. The upper ones may be the same events reported yesterday?", 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


162
162
{'location': 'Half Moon', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': "Up WMR East route, then out towards Goolie's.", 'Observation Date': 'Feb 21, 2023', 'Submission Date': 'Feb 22, 2023', 'Observer type': 'public', 'Observation Summary': 'Some very minor movement associated with small windslabs, otherwise new snow seems to have bonded pretty well on the southerly aspect we skied.  Minor differences in aspect had dramatically different snow though.  Surprisingly, lower elevation snow was more wind affected than the snow at upper elevations in halfmoon.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


163
163
{'location': 'Flathead county', 'Zone / Region': 'Other', 'Activity': 'Driving', 'Route': 'Driving backroads saw lots of wind drifts and consistent, strong winds.. obviously.  good day to be a tow truck driver..', 'Cloud Cover': 'Few (Mostly Clear, up to 2/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '3', 'Rain/Snow Line': '250', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Intense', 'Weather Summary': 'Normal February weather', 'Observation Date': 'Feb 21, 2023', 'Submission Date': 'Feb 21, 2023', 'Observer type': 'public', 'Observation Summary': 'Icy roads and mostly drivable drifts.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

164
164
{'location': 'Middle Fork', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '3 feet', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Large Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Dropping temps throughout the day. Sun was trying to poke through but never did.', 'Observation Date': 'Feb 21, 2023 (9:30 - 15:00)', 'Submission Date': 'Feb 21, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Today we went for a ridgewalk in the Flathead Range to escape the chaos of the windy valley.\n- Only a couple of inches of snow on top of a wet snowpack at low elevations. Snow heights increased rapidly with elevation. Roughly a meter (3 feet) of new and recent snow.\xa0\n- We experienced many audible collapses at middle elevations (5000-6500). One of the collapses shook snow off of trees 30 feet away.\xa0\n- We kicked and stomped small test slopes and were able to easily trigger small slides in new snow.\xa0\n- Minimal wind-drifting at middle elevations. There is a lot of snow available to transport.\xa0\n- We observed roughly 5 large avalanches at middle elevations. All but one of the crowns were mid-slope and crowns wrapped around terrain features. The bed surface had a sheen to it that looked crust-like. I anticipate these all failed on one of the faceted crusts (Christmas or Mid January).\xa0\nTrail breaking was arduous. Snow is slow. We stuck to ridgelines.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Cracking Observed (widespread)  Collapsing Observed (widespread)', 'Instability Comments': 'Loud audible collapses between 5000 and 6500 feet. We experienced 6 throughout the day.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


165
165
{'location': 'Northwest Montana Adventures', 'Zone / Region': 'Other', 'Activity': 'Snowmobiling/Snowbiking', 'Observation Date': 'Feb 21, 2023', 'Submission Date': 'Feb 23, 2023', 'Observer type': 'public', 'Observation Summary': 'Clients reporting 18-20 inches of fresh snow over the last 3 days', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


166
166
{'location': 'Snowshed Mountain', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '30-32', 'New or Recent Snowfall (cm)': '6 inches +', 'Rain/Snow Line': '3,500', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'The morning was calm with periods of sun.  At ridgelines, there were moderate gusts that transported snow. The atmospheric river did not arrive until 4pm in the Essex area.', 'Observation Date': 'Feb 20, 2023', 'Submission Date': 'Feb 20, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'We heeded the avalanche warning in the Flathead Range today and chose terrain that offered low-angle slopes and shelter from the wind.\n\nMost of the day we traveled in cohesionless powder, except at wind-exposed ridgelines and saddles.\nThe new snow contained a lot of graupel and was moist up to 7,000 feet.\nWe tried to kick off some cornices, but they were surprisingly soft and would not propagate.\nWe skied powder until about 5800 feet, at which point, the snow got progressively heavier and eventually turned to mashed potatoes and roller balls at about 4500 feet.\nWe spotted a 3-foot crown of a recent avalanche on a wind-loaded slope. It was 150 feet across and ran 300 feet on a northeast-facing slope of about 6800 feet.\xa0\nThe anticipated atmospheric river started at about 4 pm, with big clumps of snowflakes (larger than a quarter).', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Today we were in a conservative mindset, so testing for instability was limited.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


167
167
{'location': 'Southern Flathead', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Moderate', 'Weather Summary': 'S1 most of day. S5+ began around 3pm. Modrrate west winds above about 6500.', 'Observation Date': 'Feb 20, 2023', 'Submission Date': 'Feb 20, 2023', 'Observer type': 'public', 'Observation Summary': 'Enjoyable skiing on sheltered southerlies. No signs of instability.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'None observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


168
168
{'location': 'WMR- Kona', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Skied n and nne aspects.', 'Cloud Cover': 'Obscured (Sky not visible due to fog or non-cloud layer)', 'Temperature (F)': 'Below freezing', 'New or Recent Snowfall (cm)': '12+in', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Large Amounts', 'Wind Loading': 'Not Observed', 'Weather Summary': 'Snow accumulated throughout the day, often and strong “pulses”” of intensity.', 'Observation Date': 'Feb 19, 2023', 'Submission Date': 'Feb 19, 2023', 'Observer type': 'public', 'Observation Summary': 'Copious amounts of low density snow. You could describe it as “blower”, “hero”, or  “bring you snorkel” snow… We did!We avoided steeper leeward terrain with roll overs, and features that were likely wind loaded to avoid risk of exposure to wind slabs.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'No signs of instability observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


169
169
{'location': 'Fern Creek', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Ascended the ridge following the long slog through the flats of Fern Creek. Descended one of the open lines, one at a time, and then slogged back to the car.', 'Cloud Cover': 'Obscured (Sky not visible due to fog or non-cloud layer)', 'Temperature (F)': '22-36F', 'New or Recent Snowfall (cm)': '10cm', 'Rain/Snow Line': 'N/A', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': 'Warm and wet down low. Cool and breezy up high.', 'Observation Date': 'Feb 19, 2023', 'Submission Date': 'Feb 19, 2023', 'Observer type': 'public', 'Observation Summary': 'We observed light, unconsolidated storm snow in areas that were not wind-affected. Wind-affected areas had limited evidence of instability (cracking) other than the convexity one of our group members was unfortunate to hit.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered  Caught in Avalanche  Cracking Observed (isolated)', 'Instability Comments': 'We found cornices to be moderately sensitive and observed cracking and collapse with some stomping. Other than the avalanche we triggered, there were no major signs of instability.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


170
170
{'location': 'West Side Swan', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Obscured (Sky not visible due to fog or non-cloud layer)', 'Temperature (F)': 'Below Freezing', 'New or Recent Snowfall (cm)': '6 inches and 12 inches in 24hr.', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': 'Steady moderate to heavy snowfall. Precip rates appeared to be higher below 6000 feet. There were roughly 3 inches on the sled during the 4-hour tour.', 'Observation Date': 'Feb 19, 2023 (8:00 - 15:30)', 'Submission Date': 'Feb 19, 2023', 'Observer type': 'forecaster', 'Observation Summary': "Today we went to the favored Swan Range to get a taste of some deep snow and see what problems were developing.\xa0\nTwo takeaways:\n1. Don't trust wind-drifted snow. We unintentionally triggered a slab that failed 1 to 1.5 feet thick that took me off my feet. I only went a short distance due to the relatively benign terrain we were in. The slide was triggered just below a ridgeline with light wind drifting.\xa0\n2. Excellent riding in wind-protected terrain. We managed sluff by selecting slopes with slope angles less than 38 degrees. Sluffs only ran short distances in this terrain. More aggressive tactics would be needed in steeper terrain because sluff did entrain snow as it moved downslope.\xa0\n\xa0- NOTE: This slab failed on a persistent weak layer (Surface Hoar) that likely formed Wednesday or Thursday. This layer was beneath a harder windboard under the new snow. See video for more information.", 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered  Caught in Avalanche  Cracking Observed (isolated)', 'Instability Comments': 'Evidence of drifting snow. A loose-dry problem that felt on the verge of being a storm slab problem in wind-protected locations. Few loose drys did begin to fracture into small soft slabs.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

171
171
{'location': 'Flathead Range-Marion', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Standard trail up to Marion Lake, then skinned up to the ridge between Marion and Dickey. Down the middle drainage to Dickey Rd and back to IWI', 'Cloud Cover': 'Obscured (Sky not visible due to fog or non-cloud layer)', 'Temperature (F)': '~20F', 'New or Recent Snowfall (cm)': '2”?', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Intense', 'Weather Summary': 'Wind appeared to come from all directions. Lots of gusts. Snow was was definitely being transported', 'Observation Date': 'Feb 19, 2023', 'Submission Date': 'Feb 19, 2023', 'Observer type': 'public', 'Observation Summary': 'Wind slab', 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)', 'Instability Comments': 'On the ridge line we observed a clearly wind loaded slope. We intentionally ski cut the wind loaded slope to observe wind slap pop off. Slab broke away cleanly and traveled 20ft before settling in mellow terrain.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


172
172
{'location': 'JFS Canyon - Snowslip Mtn', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '3-6"', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Large Amounts', 'Wind Loading': 'Intense', 'Weather Summary': '•\tOvercast skies with light to moderate snowfall (S1 to S2).•\tDaytime high temperatures reached the low-30s °F on the Canyon floor and the low-20s °F above 6000’.', 'Observation Date': 'Feb 19, 2023', 'Submission Date': 'Feb 19, 2023', 'Observer type': 'public', 'Observation Summary': '•\tNo avalanche activity observed.•\tSince Friday, Feb. 17th through midday today, the Canyon floor picked up 3-4” of snow with 0.30” SWE. Upper elevations accumulated 5-7”.•\tSnowfall rates increased around noon today and the Canyon floor has picked up another 3-5” with 0.25-0.30” SWE since then. Another 4-6” has accumulated at elevations above 6000’.•\tModerate to strong westerly winds produced heavy wind-loading at times above 6000’.  •\tSki cuts on fresh wind slabs resulted in only minor cracking underfoot or no cracking at all.•\tDug a hasty pit near the Burnout path at 5200’ on an east aspect, snow depth was 39”. ECTP25 and ECTP20 on a layer of facets between the mid-Jan. and late-Dec. crusts about 14” down.•\tDug a second hasty pit at 5800’ on an east aspect, snow depth was 69”. Just some ECTNs in the upper 20” with no fractures on the facets (~30” down) between the above-mentioned crusts.•\tThe mid-Jan. crust was buried 30” down below the surface in Shed 7 W at about 6600” and the late-December crust was buried about 40” down.•\tCornices are growing large in Shed 7 West (photo).', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


173
173
{'location': 'Marion', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Headed up to the moderately treed area just before Marion Lake.', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '32', 'New or Recent Snowfall (cm)': "5'", 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'None', 'Weather Summary': 'It was surprisingly warm, hovering right around freezing all day, and straight up hot with the sun out. Snow tapered off around 11 AM and sun was in and out all afternoon.', 'Observation Date': 'Feb 18, 2023', 'Submission Date': 'Feb 18, 2023', 'Observer type': 'public', 'Observation Summary': 'Performed ECT at 6400\'  on a SE aspect with a result of ECTN2 failing on the interface between the variable crust and the fresh snow. There was only ~5" of fresh snow and it was loose and dry so we were not concerned. Sluffs weren\'t running at 35 degrees. Two crusts were clearly visible in the pit but everything below the upper crust was well consolidated. Crust was generally supportive but there were some areas where the crust had some lightly faceted snow underneath. Overall riding was awesome, we did 2 laps. Shoulda been there Mack.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


174
174
{'location': 'Paola', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '22', 'New or Recent Snowfall (cm)': '6"', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Large Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Winds were light and variable starting at 6000 feet.   At ridgetop (7200 feet) winds were NNW.  Snow tapered by late morning and the anticipated afternoon snowfall never arrived. We even saw the sun and some blue sky at moments.', 'Observation Date': 'Feb 18, 2023 (9:30 - 16:30)', 'Submission Date': 'Feb 18, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Hard to beat a storm day in the Middle Fork.\xa0 Our risk management began early as the forecasted daily snow totals caused us to relocate to a zone with less exposure to avalanche terrain.\xa0 The quantity of new snow didn\'t meet expectations, but the quality or riding certainly did.\n-We found roughly 6" of new snow.\xa0 Combined with this week\'s prior snowfall it amounted to ~12" above the most recent sun crust at mid and upper elevations.\n-The recent snow seemed well adhered to crust below. We could not produce sluffs or cracking.\n-The snow surface showed minimal wind effect,\xa0 however, we were wary of old windslabs hidden beneath the new snow\n-We walked atop small cornices. These broke easily and tumbled downhill without revealing any other instabilities.\n-Pit tests indicated stable results on weak layers buried in the snowpack.\nWe steered around areas where we exected previous wind-loading. We group skied terrain less than 30 degrees and allowed some distance between skiers on steeper sections.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'No obvious signs of instability', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


175
175
{'location': 'Stillwater State Forest', 'Zone / Region': 'Whitefish Range', 'Activity': 'Snowmobiling/Snowbiking', 'Route': 'Leaving olney trail head going over Stryker Loop there is some moving snow activity in a couple of the slide areas, mostly just snow balls rolling down the hill. Fitzsimmons trail and snow conditions are looking great there was a little bit of drifting over the trail in a couple areas but are cleared now.', 'Observation Date': 'Feb 17, 2023', 'Submission Date': 'Feb 17, 2023', 'Observer type': 'public', 'Observation Summary': 'I seen a couple areas on Fitzsimmons that were drifted over but are now cleared and also a small amount of snow movement in one area on fitzsimmons', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


176
176
{'location': 'Scalplock Lookout', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Trail to lookout', 'Cloud Cover': 'Few (Mostly Clear, up to 2/8 covered)', 'Temperature (F)': '25', 'New or Recent Snowfall (cm)': '2-3”', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Moderate', 'Weather Summary': 'Sunny skies with 2-3” of new lightweight snow with a surface hoar. Observed recent avalanche on distant slope SE Facing at mid/high elevation', 'Observation Date': 'Feb 16, 2023', 'Submission Date': 'Feb 16, 2023', 'Observer type': 'public', 'Observation Summary': 'SE facing avalanche near 4-5k. Wind-loading on S,E, and W aspects. Warming temps were conducive to light roller-ball action.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Collapsing Observed (isolated)', 'Instability Comments': 'Isolated audible collapsing near windswept ridgelines above 5k', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

177
177
{'location': 'Wire', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Route': 'Road to trail to ridge up to 6600 feet and back', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Nil', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Skies started mostly clear with clouds building late morning.   Sun broke through again around 1600 hrs.  Wind gusted light from SW.', 'Observation Date': 'Feb 16, 2023 (10:00 - 17:00)', 'Submission Date': 'Feb 16, 2023', 'Observer type': 'forecaster', 'Observation Summary': "Check-up in the Swan Lake area:\n-No recent avalanches or obvious signs of instability\n-Found intermittent and breakable sun crust at middle elevations\n-Saw wind-affected snow that produced minimal cracking\n-Located at least two facet/surface hoar layers in the top 3 feet of the snow pack. The buried surface hoar is well-weathered\n-Extended Column Tests did not propagate in pits on NE and SE at 6400 feet\n-Found a new crop of surface hoar that had already toppled over on slopes exposed to the wind.\n- Cloud cover kept the snow surface dry above 5000'\nDespite the above findings, I limited myself to slopes less than 30 degrees as I was without partner today", 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'No obvious signs of instability.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


178
178
{'location': 'Skiumah Creek', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Few (Mostly Clear, up to 2/8 covered)', 'Temperature (F)': '22', 'New or Recent Snowfall (cm)': '4"', 'Rain/Snow Line': "1500'", 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': 'Mostly clear morning skies gave way to overcast conditions in the afternoon. The temperature remained cool throughout the day, even when the sun was out. Moderate southwest winds affected higher ridgelines and the Skiumah valley floor.', 'Observation Date': 'Feb 16, 2023', 'Submission Date': 'Feb 16, 2023', 'Observer type': 'forecaster', 'Observation Summary': "I chose a known windy drainage in the Middle Fork to evaluate current and recent wind loading along with surveying the surface before the weather changes to a more snowy regime.\n\nSeveral inches of loose, dry snow capped the surface above 5000. This snow generally rested on a wind crust or older hard wind slab in locations open to the wind, nearly everything above 4500' in this drainage. In sheltered terrain below 5000', a thin breakable temperature crust from last weekend was beneath the new snow.\nThere was toppled-over surface hoar on the surface in many locations.\xa0\nSouthwest winds transported the recent snow at upper-elevation ridgelines and on the valley floor throughout the day.\nWind-affected snow was found on most slopes above Skiumah Lake. Slabs only cracked under skis, with no shooting cracks observed.\nSnowpits on shady mid-elevation slopes revealed a stronger structure than most recently observed pits. This is due to the large amount of wind the snowpack in this drainage is subject to.\nSnowpit tests had no propagation, and no recent avalanches were observed.", 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)', 'Instability Comments': 'Cracking in freshly formed wind slabs. Sluffing of dry, loose surface snow on steep pitches.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


179
179
{'location': 'Shed 7/Snowslip', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Up the main drainage and up the south face to pit profile location. Down similar back to the railroad and the car.', 'Cloud Cover': 'Few (Mostly Clear, up to 2/8 covered)', 'Temperature (F)': '20', 'New or Recent Snowfall (cm)': '10+cm', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Pleasant weather with few clouds, light gusting moderate SW winds (only transporting snow along ridgelines) and warming temps throughout the tour from 930am to 1pm', 'Observation Date': 'Feb 16, 2023', 'Submission Date': 'Feb 16, 2023', 'Observer type': 'public', 'Observation Summary': 'We observed a surprisingly soft surface snow atop a generally supportable crust. We did see signs of recent wind loading throughout the Shed 7 W bowl and kept our descent route to lower angle planar slopes that lacked the pockets of windslab observed near the ridgeline.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'No obvious signs of instability observed today. There were a couple of day+ old piles of cornice debris along the upper ridge of Shed 7 W but nothing of concern.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


180
180
{'location': 'Ousel Peak', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Feb 16, 2023', 'Submission Date': 'Feb 17, 2023', 'Observer type': 'public', 'Observation Summary': 'Scrappy trail access down low, obviously. Lots of wind up high mid afternoon, varying from West to North, blasting the upper reaches of the ridge I climbed. 5 mm surface hoar was fairly prevalent in wind protected areas. Generally low snowpack in this particular zone. Hasty pits revealed Xmas crust down 50-80 cm’s. NW descent route from 7000 to 5200 harbored varied conditions. Cross loaded wind features up high were locked in place, despite lots of stomping. Once below 6400 ft skiing conditions were OK, with 1-3” fresh snow on a variety of near surface breakable crusts. Surface snow sluffed fast on steeper pitches. Most consistent skiing was below 6000 with a more northerly aspect. General faceting of surface snow was occurring in the lower fully shaded elevations.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


181
181
{'location': 'Swan Range, north and east of Peters Ridge (Brown Ridge Area)', 'Zone / Region': 'Swan Range', 'Activity': 'Other', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '30 degrees (Creston)', 'New or Recent Snowfall (cm)': 'About 1 inch at 3200 feet Feb. 13', 'Rain/Snow Line': 'Unk.', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': 'Overcast to clear and cold.', 'Observation Date': 'Feb 15, 2023', 'Submission Date': 'Feb 15, 2023', 'Observer type': 'public', 'Observation Summary': 'See photos.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': 'Photo Swan1 was first observed Feb. 9, and is current as of this date.  Swan2 is a brown frown about a quarter mile north of Swan1, and was first observed Feb. 14.  Swan3 is a brown frown about 3/4 mile south of Swan1 and was first observed this date.  Swan4 is a brown frown about 2-3 miles south of Swan3.  All are observed and photographed through a telescope from about 5 miles away and with a cell phone.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


182
182
{'location': 'Late Middle Fork', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '25', 'New or Recent Snowfall (cm)': '4', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Broken clouds with some very small sucker holes.  The ceiling was high enough all day to give grande views of the terrain we were in.', 'Observation Date': 'Feb 15, 2023 (9:00 - 14:30)', 'Submission Date': 'Feb 15, 2023', 'Observer type': 'forecaster', 'Observation Summary': "Took a break from the machines and used human powered devices to ascend and descend some of the fine mountains in the Flathead Range.\n-There is a nasty crust from the warm up last friday that exists up to 5000'. \xa0Beyond that elevation the crust seemed to be confined to the southern aspects. \xa0On the solar aspects it was prevelant to the ridgetops at 7K.\n-We found old windslabs at the ridgelines. \xa0From a distance we could see several E facing slopes that were well cross-loaded. \xa0\n-There was 4-6 inches \xa0of dry snow from overnight. \xa0This snow had not been moved at all by the wind by the time we left.\n-We did not find any surface hoar.\n-Skiing was great. \xa0We felt plenty comfortable skiing bigger terrain.", 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'No instabilities observed in our pits or while skinning.  We did notice one 6 inch wind-slab that had released, and steep slopes were certainly prone to some minor loose-dry while skiing.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

183
183
{'location': 'North Swans', 'Zone / Region': 'Other', 'Activity': 'Skiing/Snowboarding', 'Route': 'We gained a S ridge and followed that north to the high point and skied a S/SW aspect down to the summer trail.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '20', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Unknown', 'Weather Summary': 'It was hard to tell how much recent snow had fallen due to the wind. We stayed off the N side so I’m not sure how loaded that was. There were still 3-4” of fresh snow on the S facing bowl.', 'Observation Date': 'Feb 15, 2023', 'Submission Date': 'Feb 15, 2023', 'Observer type': 'public', 'Observation Summary': 'The crust was present and firm on our S facing approach up to 5k or so. Higher elevations in protected areas actually held several inches of soft snow on top of the crust. Once topping out at the summit there was obvious signs of wind transport but the southerly aspect still held snow even in less treed areas. The crust was untouchable until about 5200’ and minor sloughing was noted. We probed around 5200’ and found 175cm depth. Obviously the lower we got the crustier the snow got.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Other than minor sloughing, no signs of instability in our tour. There were at least 2, maybe 3, glide cracks towards Peters Ridge. Unfortunately with an iPhone and overcast skies I wasn’t able to get a worthwhile photo.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


184
184
{'location': 'JFS Canyon - Devils Hump', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': '•\tBroken skies with occasional very light snowfall. Minimal accumulation throughout the day.•\tDaytime high temperatures reached the high-20s to low-30s °F on the Canyon floor and the mid-teens above 6000’.', 'Observation Date': 'Feb 15, 2023', 'Submission Date': 'Feb 15, 2023', 'Observer type': 'public', 'Observation Summary': '•\tNo avalanche activity observed.•\tAbout 1” of new snow on the Canyon floor and 4-6” above 6000’.•\tNo signs of instability observed. Ski cut a couple fresh wind slabs with only minor cracking underfoot or no cracking at all.•\tLight to moderate SW winds above 6000’ elevation were occasionally loading leeward slopes just below ridgelines. But minimal wind loading over the course of the day.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


185
185
{'location': 'Red Meadow', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Skied NW and W aspects, we felt comfortable skiing slopes up to ~ 35 degrees', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '1-2"', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Previous', 'Observation Date': 'Feb 14, 2023', 'Submission Date': 'Feb 14, 2023', 'Observer type': 'public', 'Observation Summary': 'We observed some Isolated cracking in the top 1-2" of new snow. There was significant previous wind loading along ridges at upper elevations with moderate to large cornices hanging over east facing aspects. Minimal sluffing of new snow on steeper pitches.', 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


186
186
{'location': 'Southern GNP', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Running Rabbit Traverse', 'Cloud Cover': 'Few (Mostly Clear, up to 2/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '2"', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Light', 'Observation Date': 'Feb 14, 2023', 'Submission Date': 'Feb 14, 2023', 'Observer type': 'public', 'Observation Summary': 'Bluebird skies and general light winds. Minimal snow transport noted. Skied a mix of powder and 2-3" of dust on crust on mostly south and west facing aspects.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered  Cracking Observed (isolated)', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


187
187
{'location': 'Sun Elk', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Wet slide in southeast face of true Elk summit.', 'Cloud Cover': 'Few (Mostly Clear, up to 2/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '5 inches', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Observation Date': 'Feb 14, 2023', 'Submission Date': 'Feb 16, 2023', 'Observer type': 'public', 'Observation Summary': 'Long slide. Approximately 500 meters long.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


188
188
{'location': 'Marion Lake', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '32 to 38', 'New or Recent Snowfall (cm)': '1 to 2 inches', 'Rain/Snow Line': "4000'", 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Previous', 'Weather Summary': 'Rain in the morning at the trailhead, followed by brief periods of graupel and snow. Broken clouds with pockets of blue sky in the afternoon.', 'Observation Date': 'Feb 13, 2023', 'Submission Date': 'Feb 13, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Today was a comical test of contingency plans. Good thing we had a plan B and C.\xa0\n\nRain at the trailhead was not ideal, with sloppy, wet conditions. We decided to reevaluate and drove further East to the Essex area in the hopes that the summer trail would be supportable despite the rain at lower elevations.\nAt 5600 feet, the dusting of new snow transitioned to about an 1 inch of snow. The snow was moist until about 5800 feet. The day’s total accumulations at 6000 feet was 2 inches.\nWe visited the recent avalanche on Essex Mountain, estimated to have run on 2/11/23. We wanted to take a look at the bed surface layer of the avalanche, as a possible failure of a persistent weak layer or a wind slab avalanche.\nTurns out, this avalanche was a great example of a cross-loaded slope sliding on a 10 cm pencil-hard crust. We estimated that the crust that was buried 85cm from the surface was formed around Dec. 25 (as we have referred to it as the Christmas crust).\nThis was a hard slab that differed in slab depth, commonly seen in cross-loaded slopes.\nUnsurprisingly the ski out was fast, as the wind-buffed surface was Mother Nature’s groomer.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


189
189
{'location': 'JFS Canyon - Running Rabbit Mtn', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Not Observed', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': '•\tBroken or overcast skies with light rain or rain/snow mix on the Canyon floor and light snowfall above 5000’ elevation.•\t2” of new snow today above 5000’ feet and a 0.25” water on the Canyon floor by the time precipitation ended around 1600 hours.•\tModerate westerly winds with strong gusts at mid/upper elevations with winds subsiding around 1600 hours.•\tCanyon floor temperatures were in the low-40s °F in the morning and cooled as the day progressed, finally dropping below freezing around 1700.', 'Observation Date': 'Feb 13, 2023', 'Submission Date': 'Feb 13, 2023', 'Observer type': 'public', 'Observation Summary': '•\tNo avalanche activity observed.•\tPoor snowpack structure persists between 5000’ and my high point at 5500’ elevation with weak facets below the mid-Jan. crust and a building slab on top. This slab is now 1-2’ thick.•\tNo signs of instability observed. Ski cut a couple fresh wind slabs with only minor cracking underfoot or no cracking at all.•\tModerate to strong W-SW winds, predominantly above 5000’ elevation, were actively loading leeward slopes (photo) until late afternoon when the winds began to calm down.•\tDug a snow pit and conducted a full profile at 5300’ elevation on a SE aspect, 35° slope (see pit profile). Found a poor snowpack structure with a layer of facets below the mid-Jan crust about 16” below the surface. Unstable result with the first Extended Column Test, ECTP24 on said facet layer, but then ECTN25 with the second test on the same layer.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

190
190
{'location': 'Nyack area', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '30s', 'New or Recent Snowfall (cm)': '4-6 inches', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Observation Date': 'Feb 12, 2023', 'Submission Date': 'Feb 12, 2023', 'Observer type': 'public', 'Observation Summary': 'We skied a north facing aspect in a sheltered zone with sparse trees starting near the Nyack area in the Flathead Range. We noticed no instability, some old windloading near the ridge, but otherwise soft snow. The zone was sheltered from the sun and did not seem terribly impacted by wind from recent weather events. Calm day, no wind and mostly overcast skies aside from brief sun in the morning.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


191
191
{'location': 'Marion Lake, Essex Mtn', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Traveled through and observed slopes across the compass from 3,900-8,000 ft', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Below freezing', 'New or Recent Snowfall (cm)': 'none', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Intense', 'Weather Summary': 'We observed wind gusts moving snow along ridge lines.', 'Observation Date': 'Feb 12, 2023', 'Submission Date': 'Feb 12, 2023', 'Observer type': 'public', 'Observation Summary': '2x natural avalanches, variable surface snow conditions, no other obvious signs of instability. Cloud deck was above neighboring peaks. No other natural avalanches observed.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': "Observed 2 natural avalanches. Both appeared to be recent, possibly 2/11/23? <br><br>Both appeared to be wind slabs. #1 lower elevation @ Marion lake = cross loaded?. #2 @ higher elevation= top loading? <br><br>Both were in rocky, steep (40'+) terrain. <br><br>No other obvious signs of instability observed.", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


192
192
{'location': 'Northern Flathead Range', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Route': 'Day off wander at mid-elevations in the northern Flathead Range. Did not travel above 6700 ft, .', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Previous', 'Weather Summary': 'Overcast with hints of blue sky. Some wind gusts midday at mid-elevations, from both west and east. Otherwise light winds in this elevation band. We could hear strong winds near uppe elevation ridgelines, though we saw no blowing snow. Warm below about 4000 ft.', 'Observation Date': 'Feb 12, 2023 (9:00 - 16:30)', 'Submission Date': 'Feb 12, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Widespread wind effects above 4500 ft. Some scouring, but most slopes < 6500 ft had 15-30 cm of dense, wind-packed snow (aka wind slabs) at the surface. Ranged from 4F hard to 1F hard. These were unreactive; we experienced no cracking or collapsing while skinning or skiing slopes up to about 38*.\xa0 Snow/ rime melted or blown out of most trees below about 6500 ft; trees above still white. Spotty melt-freeze crusts onSW and S slopes below about 6500 ft, possibly higher.\xa0\nThe wind-effected snow skied better than expected, though still grabby at times. We found soft, low-density snow on gladed NW-N facing slopes, or improbably given the NW winds, in a NW facing basin.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'A glide crack is opening on a steep, upper-elevation, east facing slope on Mt. Penrose. The slope is bedrock in the summer.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


193
193
{'location': 'N. Whitefish', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'FAC', 'Activity': 'Snowmobiling/Snowbiking', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Below Freezing', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Previous', 'Weather Summary': 'Overcast and calm wind. We never reached upper elevations or ridgetops.', 'Observation Date': 'Feb 12, 2023', 'Submission Date': 'Feb 12, 2023', 'Observer type': 'forecaster', 'Observation Summary': "Today we rode around in the N. Whitefish Range to see what's going on up there. We found generally safe avalanche conditions at middle elevation. We didn't get above 6400 feet.\n- We observed no recent natural avalanches, no shooting cracks, and no collapses.\n- We found wind-drifted snow at middle elevations. Slabs were hard, thin, and unreactive to sled cuts. We observed evidence of drifting snow at upper elevations.\xa0\n- We got propagating results in extended column tests. These failed on a layer of stellar dendrites that fell last week. These were decomposing and we had no other signs of instability on this layer.\n- A poor basal snowpack structure exists in the N. Whitefish.\xa0\nWe rode in steeper terrain and did short high marks in wind-protected areas given the lack of instability.", 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


194
194
{'location': 'Whitefish range', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Skied E, NE, N, and S aspects near WMR.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Observation Date': 'Feb 12, 2023', 'Submission Date': 'Feb 12, 2023', 'Observer type': 'public', 'Observation Summary': 'Light to moderate wind gusts, though pretty calm between gusts. We had cloud cover all day. No cracking was noted, no avalanches observed.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Light sluffing of the surface powder or crust.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


195
195
{'location': 'Early middle fork', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Skinned up W and N aspects from 3500-6200’. Skied N facing terrain.', 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': 'It seemed to stay below freezing except on the valley floor all day, but the solar aspects definitely were catching some rays much of the day.', 'Observation Date': 'Feb 11, 2023', 'Submission Date': 'Feb 11, 2023', 'Observer type': 'public', 'Observation Summary': 'Visible snow being transported on ridge tops. Consistent high winds were noted on ridgetops all day and at all elevations at various points through the day.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Cracking Observed (isolated)  Collapsing Observed (isolated)', 'Instability Comments': 'We experienced a large collapse while skinning up at 5200’, and several shooting cracks in the same zone. The collapse was an isolated wind slab in sheltered terrain, occurring about 6” deep in the snowpack, failing on facets sitting on a firm crust.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


196
196
{'location': 'East of WMR', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Route': "round-the-compass, to sample a wide range of aspects and elevations prior to this week's storm. Only missed NW.", 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Few-scattered clouds, calm to light winds, warming temps and some strong solar radiation input', 'Observation Date': 'Feb 11, 2023 (8:30 - 16:00)', 'Submission Date': 'Feb 11, 2023', 'Observer type': 'forecaster', 'Observation Summary': "Hand pits, slope cuts, and snow profiles (W, 5100'; NE, 6100') showed no troubling failure planes in the near-surface snow.\xa0 Weakest near-surface snow in between ice/ crusts on SE. The surface snow was dry on the shady half of the compass in the morning, spongy on high SE and SW. Below about 6000 ft, that shrank to the shadiest third by mid afternoon. Expect some robust crusts tomorrow. On steep, northerly slopes, the surface snow sluffed easily but did not entrain additional snow.\xa0\nImages soon", 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

197
197
{'location': 'Essex area', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Few (Mostly Clear, up to 2/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'None', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': 'Wind blowing from NW throughout the day. Mostly sunny, with southern aspects receiving moderate sunlight. Minimal wind transport at middle elevation bands where we were traveling, but noted active wind loading on higher peaks of Flathead Range.', 'Observation Date': 'Feb 11, 2023', 'Submission Date': 'Feb 11, 2023', 'Observer type': 'public', 'Observation Summary': 'From our vantage on a shaded northerly aspect, we noted a small number of roller balls on a sunny southern aspect on the opposite side of the drainage. Winds out of the NW with minimal transport in our sheltered trees, but noticeable snow transport on the higher peaks of the Flathead Range.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'No notable instabilities save some isolated cracking around our skies.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


198
198
{'location': 'Snowshed Mountain', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '24', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': "2500'", 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Moderate winds with strong gusts at mid and upper elevations. Partly cloudy conditions limited full warming potential.', 'Observation Date': 'Feb 11, 2023', 'Submission Date': 'Feb 12, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'We traveled to an upper-elevation location to observe the effects of recent windy weather and the current state of our Persistent Slab problem.\n\nRecent winds scoured windward aspects and left a thin breakable slab on cross-loaded slopes above 6000 feet. Top-loaded locations held soft and hard slabs. Slabs cracked beneath a skier, and occasional shooting cracks were observed. Cornices were stiff and difficult to trigger.\xa0\nThere are up to 12 inches of loose, dry snow in sheltered locations.\nSnowpits at mid and upper elevations reveal the mid-January crust down 35 - 65 cm. No propagation was noted in stability tests.\nThe snow structure at mid-elevations is much weaker than at upper elevations.\nThe riding quality remained good on easterly aspects down to 4300 feet.', 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)', 'Instability Comments': 'Cracking in recently formed wind slabs.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


199
199
{'location': 'Essex Mtn', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'North & East facing lines off Essex Mountain', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '20-25 cm', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': "We witnessed wind loading and snow being transported at higher elevations, like 8,000' +. We climbed to just under 7k and did not experience anything more than a couple moderate gusts all day.", 'Observation Date': 'Feb 10, 2023', 'Submission Date': 'Feb 10, 2023', 'Observer type': 'public', 'Observation Summary': "Way better pow skiing was had than we expected. Couldn't stop. We were glad to be on a shady aspect despite the clouds rolling in about 11- the sun this morning was stroooong.", 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Minor cracking, but almost entirely between kickturns so to be expected. No shooting cracks or collapses.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


200
200
{'location': 'Tunnel Ridge', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Feb 9, 2023', 'Submission Date': 'Feb 10, 2023', 'Observer type': 'public', 'Observation Summary': 'Re-build of the Tunnel Ridge weather station (wind site).', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


201
201
{'location': 'Sub-Shields', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Skinned up SE ridge of sub-Shields and skied the S bowl.', 'Cloud Cover': 'Few (Mostly Clear, up to 2/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Moderate', 'Weather Summary': 'Beautiful sunny day with light to moderate wind from NE and SW. Lenticular clouds hanging out around peaks.', 'Observation Date': 'Feb 9, 2023', 'Submission Date': 'Feb 9, 2023', 'Observer type': 'public', 'Observation Summary': 'One of our group members heard a small whumpf while breaking trailing in the low angle S bowl at around 6500 feet. We dug a quick hand pit and found a layer of facets above a crust buried roughly a foot and a half deep. There was a 4 finger plus slab on top of the facets and we were noticing light to moderate NE winds with moderate gusts. We also felt wind coming from the SW and witnessed lots of swirling snow.', 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)  Collapsing Observed (isolated)', 'Instability Comments': "Stomped on small cornices and windslabs facing NE. Some were more reactive than others, one broke just by skinning next to it. Lot's of shooting cracks while walking and stomping on them.", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


202
202
{'location': 'Brown Creek', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'FAC', 'Activity': 'Other', 'Observation Date': 'Feb 9, 2023', 'Submission Date': 'Feb 10, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'This is the Brown’s Creek basin just north of Peters Ridge; the usual spot for these glide cracks that can be seen clear from Bigfork.\n\xa0\nThe left one had been visible for about two weeks, but I’ve never had a camera handy to send you a photo.\xa0\n\xa0\nThe right one caught me totally by surprise as I had seen no crack there as of yesterday 5pm.\n\xa0\nI was out and about enough today to scan from this area all the way down to Broken Leg Mountain, and I see no other glide cracks in the usual places - yet.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


203
203
{'location': 'Strawberry Mountain area', 'Zone / Region': 'Swan Range', 'Activity': 'Other', 'Cloud Cover': 'Clear (No clouds)', 'Temperature (F)': '26f (Creston)', 'New or Recent Snowfall (cm)': 'very light', 'Rain/Snow Line': 'unk.', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': 'Today is CAVU (clear and visibility unrestricted).  The past week has been warmish.', 'Observation Date': 'Feb 9, 2023', 'Submission Date': 'Feb 9, 2023', 'Observer type': 'public', 'Observation Summary': '"Brown frown" that started out small and grew over time.  This morning I observed that a large avalanche had occurred immediately south of the brown frown.  My observation point is approximately 5 miles west of location of avalanche area, and photo is taken with a phone through a telescope.', 'SIGNS OF INSTABILITY': 'Cracking Observed (widespread)', 'Instability Comments': 'See photo', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


204
204
{'location': 'Ghoulies East of WMR', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Toured up to ghoulie point and traveled east of there', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': 'Light winds out of SWMostly cloudy with breaks of sun', 'Observation Date': 'Feb 8, 2023', 'Submission Date': 'Feb 8, 2023', 'Observer type': 'public', 'Observation Summary': 'SE Facing @ 6512 (Upper)Ghoulies side country Total snowpack: 210cmECTN11 @ 195cmECTN29 @ 177cm', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

205
205
{'location': 'Ghoulie Point', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Left Whitefish Mountain Resort into side country, skinned up Ghoulie Point then traversed to the saddle', 'Observation Date': 'Feb 8, 2023', 'Submission Date': 'Feb 8, 2023', 'Observer type': 'public', 'Observation Summary': 'Ghoulie Point. Elv.6400ft. Aspect: Eastern facing wind-affected slope. Slope Angle: 20-25 Degrees. Performed 4 ECT tests. No propagation on tests 1-3. Propagation on test 4 with hard force. Multiple weak layers in new storm layers from last night, not quite forming a slab yet.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


206
206
{'location': 'Essex area', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': "Ascended and descended a N/NE aspect from 3800' to 7000'. Also skied an E facing run from 7000' to 6300'.", 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '27-33', 'New or Recent Snowfall (cm)': '3-8"', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': 'We were thrilled that the winds relatively light and much calmer with gusts more sporadic than forecasted. Winds were generally from the west, with intermittent gusts to moderate and periods of calm/light wind. When the wind was blowing and during gusts, we did observe plenty of blowing snow on the surface. During our ascent in the morning the upper level clouds were moving west to east quite quickly, and there was some observable blowing snow at ridgeline. The sun poked out intermittently throughout the day, and light (S1 or less) snow/graupel occasionally fell. Temperature was 33 degrees at the car at 9am.', 'Observation Date': 'Feb 8, 2023', 'Submission Date': 'Feb 8, 2023', 'Observer type': 'public', 'Observation Summary': 'We went out hunting sheltered pow turns, and were rewarded. It was a "look-but-don\'t-touch" kind of day, as the 30-35 degree entries into the zones we hoped to ski were very wind loaded, with wind slabs on test slopes proving easily reactive. We skied a mellow (15-30 degree) east facing run in a sheltered area and enjoyed soft turns. We skied down the N/NE ridge we ascended. We descended steeper (35-45 degree) terrain below 5000\', as we had not observed wind loading or instability at that elevation. The new snow sluffed fairly fast on the recent crust, but was easily manageable. We estimate a widespread 8" of new snow above 5000\' fell in this zone. Below 5000\' and in the parking area below 4000\' there was about 3" of new snow. Graupel was common on the surface and widespread throughout the new snow.We observed what looked to be an avalanche failing on a steep SE facing chute around 6000\' off of Essex Mountain, likely from loading within the last 24hrs. Tough to see much from a distance, but it looked to have failed on the old/new snow interface. D1/R2.', 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)', 'Instability Comments': 'New wind slabs of varying size proved pretty reactive on test slopes. Cracking on these slabs was widespread. Some cracking around ski tracks as well. We observed wind slabs on slopes N, NE, E, and SE.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


207
207
{'location': 'Swan Range South of Swan Lake', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Route': 'Road to north-facing bowl. Skin and ride NE aspect.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '6-10"', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Bursts of graupel', 'Observation Date': 'Feb 8, 2023 (10:00 - 14:30)', 'Submission Date': 'Feb 8, 2023', 'Observer type': 'forecaster', 'Observation Summary': "Into the Swan! Let's see what this storm left for us:\n-We found exceptional riding with 4-10 inches of recent snow.\xa0\xa0\n-We noticed a handful of small, natural soft slab avalanches that failed in wind drifted snow during the last week.\xa0\n-We stomped though wind drifted snow with minimal cracking.\xa0\n-Cornice were growing and we were able to chunk off the top 30cm with some jumping.\xa0\n-We found buried surface hoar 55-90cm deep in our testpits.\n-An extended column test at 7200 feet, NE aspect produced a propagating result with moderate force.\nWe backed away from riding a steep, treed bowl.", 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Cracking was confined to the top 10 cm.  Was able to break some chunks off of cornice ~30 cm thick.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


208
208
{'location': 'Middle Fork Corridor', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Below Freezing', 'New or Recent Snowfall (cm)': '6', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Previous', 'Weather Summary': 'We could hear the winds overhead most the day, but not as windy as expected. Full trees in motion at low elevations, light winds at mid and upper elevations.', 'Observation Date': 'Feb 8, 2023 (9:00 - 16:00)', 'Submission Date': 'Feb 8, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Today we were Flathead bound to observe snow totals and see how sensitive freshly formed wind slabs are. We also wanted to assess buried weak layers in the upper snowpack.\n- We initiated many shooting cracks and triggered a few very small slabs. We skied a windward aspect and found isolated pockets throughout our descent.\xa0\n- Freshly formed drifts were thicker, but stubborn on more wind-loaded aspects.\xa0\n- We found weak faceted snow roughly 40 cm and 50 cm down from the surface. This similar structure was found in a number of neighboring drainages. We had nonpropagating results in extended column tests. See snow profile for more info.\nWe chose to ski steep terrain on windward aspects below 6500 feet. This did require attention to surface texture since winds drifted snow further down the slope than anticipated.\xa0\nprofile and photos soon.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered  Cracking Observed (widespread)', 'Instability Comments': 'We triggered small and inconsequential wind slabs. Lots of shootin cracks in pockety wind slabs at middle elevations.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


209
209
{'location': 'Whitefish Range', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Upper whitefish lake zone, Up and down an east facing aspect from 4500’-7000’', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '4-6”', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Observation Date': 'Feb 8, 2023', 'Submission Date': 'Feb 9, 2023', 'Observer type': 'public', 'Observation Summary': 'Some patchy sun through the day. Growing  cornices on the divide. Fun skiing in the sheltered terrain.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Some wind board crumbling on hard turns, and isolated cracks in the storm snow that did not result in shooting cracks or any propagation (yet).', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


210
210
{'location': 'Whitefish Mountain Sidecountry', 'Zone / Region': 'Other', 'Activity': 'Skiing/Snowboarding', 'Route': 'Goolies point', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '21-28', 'New or Recent Snowfall (cm)': '6in', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'None', 'Observation Date': 'Feb 8, 2023', 'Submission Date': 'Feb 8, 2023', 'Observer type': 'public', 'Observation Summary': 'Snow pit tests were conducted around 2pm in Whitefish Mountain Resort side country on a 29° southeast facing slope of Old Man’s bowl at approximately 6700ft of elevation.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

211
211
{'location': 'Northern Swan', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Below Freezing', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': '3000', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Previous', 'Weather Summary': 'Generally light winds. Precipitation started to pick up during our exit at around 1500.', 'Observation Date': 'Feb 7, 2023 (7:00 - 15:30)', 'Submission Date': 'Feb 7, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'We bumped our way up the west side road and overheated the machines every 10 minutes. Once we got there, we toured up to assess a month-old layer of buried surface hoar and look for signs of recent avalanche activity.\n- We observed recent natural avalanches on steep north-facing slopes. These were likely wind slabs. Crown depths appeared to average 1 to 2 feet thick.\n- We dug a pit on a north aspect at 6900 feet and found a buried surface hoar. We did not get this layer to propagate in extended column tests. A propagation saw resulted in an unstable result (PST40/100End). Although considered unstable, this weak layer has gained strength.\xa0\n- We found hard slabs of drifted snow above 7000 feet. These were hollow feeling and roughly a foot thick.\xa0\nWith recent avalanche activity, we chose to ski on slopes sheltered from the wind and less than 35 degrees.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': 'Observed 5 crowns and/or debris piles from avalanches from the past few days.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


212
212
{'location': 'Jewel Basin/Mt Aeneas', 'Zone / Region': 'Swan Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Skinned up from shooting range on J-Basin Rd up to summit of Aeneas, skied NW Face to picnic lake, skinned up Noisy Notch to top of Crown Bowl, skied bowl, skinned up to Checkerboard Summit, skied Checkerboard and back to truck.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': 'Once on the ridge leading to Aeneas summit there was fairly consistent 25-35 mph winds with active windloading observed. Temps were warm down low (high 30s) and cooled off significantly around 5500ft, unknown temp.', 'Observation Date': 'Feb 7, 2023', 'Submission Date': 'Feb 9, 2023', 'Observer type': 'public', 'Observation Summary': 'Obvious signs of recent and active wind loading with an evident  windslab on pockets of our tour.', 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)', 'Instability Comments': 'Cracking was initiated on purpose with a test slope above the skin track. Was a pocket of windslab roughly 10cm thick.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


213
213
{'location': 'JFS Canyon - Devils Hump', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Not Observed', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': '•\tThe morning had broken skies with the occasional sunshine. By noon skies were overcast and by 1400 S-1 to S1 snowfall with elevations above 5500’ favored.•\t1” of new snowfall above 5000’ on our exit and a trace on the Canyon floor.•\tDaytime highs reached the mid-30s °F on the Canyon floor and the low to mid-20s °F above 6000’ elevation.', 'Observation Date': 'Feb 7, 2023', 'Submission Date': 'Feb 7, 2023', 'Observer type': 'public', 'Observation Summary': '•\tNo recent avalanche activity observed.•\tPoor snowpack structure predominantly above 5000’ with weak facets above/below the mid-Jan. crust and a building slab on top. This slab is now 1-2’ thick.•\tSome facets noted on top the late-Dec. crust as well, but these layers were harder and rounding.•\tDespite the poor structure, no signs of instability observed, save for some minor cracking underfoot. We could not release any slabs on small, steep test slopes, nor get any shooting cracks.•\tModerate to strong S-SW winds, predominantly above 5000’ elevation were actively loading slopes just below ridgelines on northerly and easterly aspects.•\tWe stayed down in the middle of the basin and limited our terrain choices to slopes most sheltered from the wind and lower than 35°. Avoided consequential slopes that were steeper than this and had rock outcrops and/or unsupported slopes above cliff bands.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


214
214
{'location': 'Sidecounty east of WMR', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '29 to 33 degrees', 'New or Recent Snowfall (cm)': '2 to 3 inches during the day', 'Rain/Snow Line': "3500' (ish)", 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Moderate winds at the minimal time spent in upper elevations. For most of the day, winds were light at mid-elevations.  Visibility was poor, with obscured skies. Snowfall was light before noon and transitioned to S-1, with bursts of S1.', 'Observation Date': 'Feb 7, 2023 (9:30 - 17:00)', 'Submission Date': 'Feb 8, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'We toured east of WMR to check on the surface snow conditions before the incoming storm.\n\nThe biggest takeaway from today was that the recent (8 to 13 inches) of soft snow rests upon a crust. The density change between the new and crust is a clear sliding surface. New snowfall from Tuesday night\'s storm may be consolidated enough to act as a slab upon this crust.\nBelow the crust, the snowpack consisted of facets layers with varying types of crust.\xa0 We dug into the snow on various sheltered northern slopes, but we did not find the buried surface hoar found on 2/5.\xa0\nWe did not get propagation in our ECT.\xa0\nThe impact of many riders on WMR\'s sidecountry slopes proved to be a unique "micro-climate" of compaction layers observed within the snowpack. Sking on stiffened drifts with variable soft snow layers had us retreating back to the resort. Yes, skiing within the resort was better than the sidecountry.\nReturning to the parking lot, the temp was 33 degrees. During the drive down, the snow turned to rain around 4000 feet.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'On steep slopes, there was some harmless sluffing of the top 3 to 4 inches.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


215
215
{'location': 'John F Stevens', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Feb 6, 2023', 'Submission Date': 'Feb 6, 2023', 'Observer type': 'public', 'Observation Summary': 'Still quite windy at elevation here but we managed to find good snow on east and northeast aspects. Two types of snow pack: 4-6” inch on unreactive wind board or 12-14” on the old rain crust. Mild surface sluffing otherwise no instability.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


216
216
{'location': 'Skiumah: site of 2/5/23 avalanche', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '29 to 32', 'New or Recent Snowfall (cm)': '1 to 2 inches', 'Rain/Snow Line': "3500'", 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Overcast skies', 'Observation Date': 'Feb 6, 2023 (9:00 - 17:00)', 'Submission Date': 'Feb 6, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Today we traveled to the site of the 2/5/2023 avalanche above Skiumah Lake in the Flathead Range.\xa0\xa0\nWe are grateful that no one was seriously hurt and that the reporting party shared information to help the greater snow community.\n\nThe Skiumah Basin had evidence of many generations of avalanche debris that were present on all observed slopes.\nWinds were moderate above 5,000 feet. The 1" to 2" of new snow was redistributed into small drifts over a supportable crust.\nThe D1 avalanche occurred in an isolated, cross-loaded chute that was actively being reloaded by swirling, localized winds within the chute.\nThe avalanche was a 1-finger-hard wind slab, varying in slab depth from 20 to 35cms. It failed on the interface of new snow over a recent knife-hard crust.\nThis avalanche was an example of a relatively small slide that had amplified consequences due to the cliff band below.\nThe slope angle of the crown was observed to be 38 degrees.\xa0\nAs my partner and I traveled on the bed surface, we noted that the underlying crust was intermittently blue ice.\xa0\nAs we cut a small column test, the slab failed upon isolation. Due to the active re-loading and a shooting crack on a small adjacent concave slope, we heeded the snowpack\'s warning and stayed in an area of safety.\nWe did not observe any other signs of instability outside of the isolated cross-loaded chute.\nSkiing was punchy with a wide variety of wind-affected snow surfaces.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Cracking Observed (isolated)', 'Instability Comments': 'Besides the D1 avalanche, we did not observe other signs of instability.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

217
217
{'location': 'Skiumah', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Trail into Skiumah and climbed towards the Western side of the main bowl to the saddle skier right', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'mid 30s', 'New or Recent Snowfall (cm)': '4 variable inches depending on area', 'Rain/Snow Line': 'no rain', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Overcast with light to medium wet snowfall. Winds observed in upper elevation.', 'Observation Date': 'Feb 5, 2023', 'Submission Date': 'Feb 5, 2023', 'Observer type': 'public', 'Observation Summary': 'Lots of small cliffs and trees in the area. Steeper area than was thought from down below. Lots of released avalanches in area. Lots of steep areas surrounding Skiumah lower lake.Lower clouds and could not see the top of the mountains and ridges.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered  Caught in Avalanche', 'Instability Comments': 'Temps in the low 30S.<br>Where the avalanche was trigger was on a hump and stomped on a few times as skier tried to make his way over to the saddle.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


218
218
{'location': 'wmr Bc', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Ghoulies/half moon gully', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Observation Date': 'Feb 5, 2023', 'Submission Date': 'Feb 6, 2023', 'Observer type': 'public', 'Observation Summary': 'Light s1 and fog. What else is new?', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': 'Saw D1 sized debris in half moon as I was cutting across towards slick slot.. doubt it was natural..', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


219
219
{'location': 'Northern Whitefish', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'FAC', 'Activity': 'Snowmobiling/Snowbiking', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Below Freezing', 'New or Recent Snowfall (cm)': '3', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Previous', 'Weather Summary': 'Cloud cover rolled in around noon along with light precipitation. Precipitation rates started to pick up (S1) during our exit around 1530.', 'Observation Date': 'Feb 5, 2023 (7:00 - 18:00)', 'Submission Date': 'Feb 5, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Today we went to the northern Whitefish Range to assess the snowpack structure and visit the area around the Ninko Cabin. We hoped to get some info on wind-slab sensitivity, but this appeared to be a relatively protected area. I found this surprising since Hornett (a weather station nearby) was pumping averages of 25 mph for two consecutive days.\xa0\n- Recent and overnight snow totals increased in depth above 6500 feet. We found 3 to 4 inches of graupel above 4 to 6 inches of stellar dendrites. This made for springy pow skiing on our descent.\n- Upper snowpack structure above roughly 6200 feet is poor. We found a layer of near-surface facets about 12 to 16 inches below the surface. In some areas, this layer was capped with a thin layer of surface hoar.\n- We observed no avalanche activity, no red flags, and had non-propagating scores in snowpit tests.\xa0\n- The snowpack is shallow and weak. We probed a few areas and found average depths of 130 to 150 cm between 7000 and 7500 feet. See snowpit for more info on snowpack.\nWith the lack of red flags and no evidence of wind-drifted snow, we felt comfortable skiing a planar slope at 35 degrees.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'No signs of instability observed.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


220
220
{'location': 'Konaish', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Dug on W facing slope', 'Cloud Cover': 'Obscured (Sky not visible due to fog or non-cloud layer)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'None', 'Weather Summary': 'Rime growing on rime.', 'Observation Date': 'Feb 5, 2023', 'Submission Date': 'Feb 5, 2023', 'Observer type': 'public', 'Observation Summary': 'Great skiing on sheltered slopes. Structure is a bit disconcerting but could get nothing to move on various test slopes. Many clean shears in hand pits on all aspects. All popping on the MLK crust. We chose to stick to slopes below 35°. Had a break in the fog and saw older WL in the Skook Chutes, unsure how old they were, seemed to have ran in the last few days warm up.', 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)', 'Instability Comments': 'Localized cracking around skis', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


221
221
{'location': 'WMR Sidecountry', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Feb 4, 2023', 'Submission Date': 'Feb 4, 2023', 'Observer type': 'public', 'Observation Summary': 'We observed 15-30 cm of nice powder sitting on top of a hard crust. Great riding. Zero wind affected snow observed.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


222
222
{'location': 'Tunnel Ridge', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': "Toured up the Tunnel ridge west of Pinnacle creek east of Tunnel looking for higher elevation terrain where it didn't warm up so much.", 'Cloud Cover': 'Obscured (Sky not visible due to fog or non-cloud layer)', 'Temperature (F)': 'warm', 'New or Recent Snowfall (cm)': '1-2"', 'Rain/Snow Line': '4500', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Intense', 'Weather Summary': 'Warm and windy gloppy up to about 4500-5000 and a little better but quickly warming higher than that. Started colder and light but was heavy by the time we got down.', 'Observation Date': 'Feb 4, 2023', 'Submission Date': 'Feb 4, 2023', 'Observer type': 'public', 'Observation Summary': 'Looked like there was debris from a small slide at the top of the Tunnel Ridge high point.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Cracking Observed (isolated)', 'Instability Comments': 'Cracking on cross-loaded aspects of the ridge', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


223
223
{'location': 'Inspo ridge/lone pine/FAA', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Feb 4, 2023', 'Submission Date': 'Feb 4, 2023', 'Observer type': 'public', 'Observation Summary': 'SS-ASc-R1/D.5-I cornice kicking/ski cuts breaking 6-12 inches and running too to mid path.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered  Cracking Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


224
224
{'location': 'Central Flathead Range', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Feb 4, 2023', 'Submission Date': 'Feb 4, 2023', 'Observer type': 'public', 'Observation Summary': 'Traveled to a northerly, mid-elevation basin and stayed well below ridgetops to try and avoid wind-affected slopes. However, we were surprised with swirling winds that seemed to find their way into every opening between trees. The wind was blustery and strong enough to see swaying trees.Around 5000 ft there was a gradual transition from moist/glommy to dry snow. Observed 2-3mm graupel on the surface from the trailhead up to highest point of travel at 6000 ft. In areas untouched by the wind, there was approx 3-5 inches of graupel. There were a few nice soft turns to be had!Steep convexities that seemed to have soft wind slabs were not reactive.Sky was broken and light graupel fell consistently throughout the day', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

225
225
{'location': 'Jewel Basin', 'Zone / Region': 'Swan Range', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Minimal', 'Rain/Snow Line': '4700’', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': 'Mostly overcast. Some groppel, some snowfall, and something that resembled freezing rain. Some winds strong enough to move trees and lead them to drop their bombs. Sticky snow downlow. 39 degrees at the truck.', 'Observation Date': 'Feb 4, 2023', 'Submission Date': 'Feb 4, 2023', 'Observer type': 'public', 'Observation Summary': 'We observed all the wind things: wind slabs, wind boards, wind scour, wind gusts, wind transport, and wind chimes. Even in fairly protected areas, most trees had lost their snow.', 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)', 'Instability Comments': 'We did observe recent cornice fall on Western aspects that had left debris but not much more in its wake. <br>', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


226
226
{'location': 'John F Stevens Canyon', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': "37 at 4500'", 'New or Recent Snowfall (cm)': '2-3"', 'Rain/Snow Line': "4500'", 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': "Intermittent graupel squalls and rain showers on the valley floor. Pure graupel showers above 5000'. Moderate winds in the morning diminished throughout the day.", 'Observation Date': 'Feb 4, 2023', 'Submission Date': 'Feb 4, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'We traveled to the east end of John F. Stevens Canyon to observe all things related to wind.\n\nIn the morning, we noted wind transport at all elevations, which diminished throughout the day as the winds tapered.\nLarge sections of terrain open to the wind had been affected by recent wind. The snow surface was capped by a 5 cm thick slab that was 1F hard. This layer cracked frequently, but no shooting cracks were observed.\nNew cornice growth was soft and deep and failed under the weight of a skier. Sections of cornice that failed did not exceed the length of my skis. Cornices seem to have gone through a recent growth spurt.\nThere was 5 cm of graupel which fell overnight at 4500 feet. This increased to 8 cm above 6000 feet.\nWe located the mid-January faceted crust responsible for our current Persistent Slab problem. This layer was 45 cm down at 6740 feet but did not propagate in large column tests.', 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)', 'Instability Comments': 'Wind-affected snow had a 5 cm thick surface layer that was 1F hard. This layer cracked under the weight of a skier. Fresh cornices broke easily from the weight of a skier.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


227
227
{'location': 'Essex', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Feb 4, 2023', 'Submission Date': 'Feb 4, 2023', 'Observer type': 'public', 'Observation Summary': 'Intermittent snow and graupel squalls and gusting winds out is the west. Found somewhat reactive wind slabs on due north slope and unreactive wind slab on NW aspect. Best skiing  on NE sheltered aspect. Roller balls started around 5k on the exit ski', 'SIGNS OF INSTABILITY': 'Cracking Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


228
228
{'location': 'N Swans', 'Zone / Region': 'Swan Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Up n down', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'Warm', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Sun in the morning was fortunately covered by clouds around noon and then the winds that eat the snow launched a full scale assault on the western front of the mountain range named after the white birds..if you know what I mean', 'Observation Date': 'Feb 3, 2023', 'Submission Date': 'Feb 3, 2023', 'Observer type': 'public', 'Observation Summary': 'Very variable snow conditions that made for a funtastic day of skiing.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': 'Lots of glide cracks and an old loose dry from maybe …Wednesday in spied her bowl', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


229
229
{'location': 'Swan Range. Jewel Basin', 'Zone / Region': 'Swan Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Skinned up the west slope of the Swan. Skied the skiers left of Crown. Traversed up through picnic notch and skied down to picnic lake.  Skied back down picnic notch and cross courted over to checkerboard.', 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Moderate', 'Weather Summary': 'Some blue sky in the morning. Wind, all day.', 'Observation Date': 'Feb 3, 2023', 'Submission Date': 'Feb 3, 2023', 'Observer type': 'public', 'Observation Summary': 'Wind. Lots of wind and the effects of wind. Also glide cracks on a south facing slope, kind of the opposite side of Spider. And another glide crack in the bowl north of Peters Ridge. Sensitive cornices.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Cracking Observed (isolated)', 'Instability Comments': 'Wind slab, dry snow sluffs, glide cracks', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


230
230
{'location': 'WMR Sidecountry', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': "Skinned up WMR and over to Ghoulies. Skied a south facing run, a north facing run, and then a west facing run in to the SW facing drainage east of ghoulie ridge. Tour went between 4400' and 6700'.", 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': '26-36', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Light', 'Weather Summary': "High clouds that were few at first gradually covered more of the sky as the afternoon went on, although it was generally sunny. Temp at car at 4400' at 11:00 was 26F. Back at the car at 4:30 it was 36F. Wind was calm to light and variable.", 'Observation Date': 'Feb 3, 2023', 'Submission Date': 'Feb 3, 2023', 'Observer type': 'public', 'Observation Summary': "-I toured up in sunshine on a ski trail up to 5800', then left the ski boundary. Between 5800' and 6700' I observed surface hoar growth on the surface of the snowpack, isolated to sheltered areas on W, NW, N, NE slopes.-Snow quality remained excellent above 5500' before my decent around 2pm, still fairly cohesionless considering the sun and warmth. There was some minor wind loading on N through SE aspects.-I saw two very small, recent slides on a S face around 5800' and 5500'. One (5800') was a tiny wind slab that looked to be about 3 inches deep from my vantage point, and ran about 30 feet, not entraining much snow. It looks to have failed on a skin track (see photo), so not sure if intentional or unintentional. By itself it's innocuous, but suggests that larger wind slabs on that aspect may also be easily reactive. The second (5500') was an easily predictable small wet loose slide alongside a cliff band that had been baking in the sun/warmth today. It ran about 80 feet and entrained some snow (see photo).", 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


231
231
{'location': 'Marion Lake', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': '4200', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Previous', 'Weather Summary': "Very strong westerly winds, blowing snow, warming temps. Light snow began 4pm, light rain below 4200' continued all the way down highway 2 to West Glacier", 'Observation Date': 'Feb 3, 2023', 'Submission Date': 'Feb 3, 2023', 'Observer type': 'public', 'Observation Summary': "Significant warming and Crust forming on solar aspects up to 6200'.", 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)', 'Instability Comments': 'Serious wind slabs forming along the lake. Isolated cracking on wind slabs', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

232
232
{'location': 'Big Trees, Canyon Creek', 'Zone / Region': 'Other', 'Activity': 'Skiing/Snowboarding', 'Route': 'Accessed via WMR resort. Then skinned to Big Treed and made three laps.', 'Cloud Cover': 'Few (Mostly Clear, up to 2/8 covered)', 'Temperature (F)': '32', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Observation Date': 'Feb 3, 2023', 'Submission Date': 'Feb 3, 2023', 'Observer type': 'public', 'Observation Summary': 'Only observed wind formations on the ridge from WMR to Big Trees.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'No instability observed.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


233
233
{'location': 'Canyon Creek', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': '27', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': "2500'", 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': 'Mostly clear skies in the morning gave way to partly cloudy conditions in the afternoon. Blustery southwest winds transported snow throughout the day.', 'Observation Date': 'Feb 3, 2023', 'Submission Date': 'Feb 3, 2023', 'Observer type': 'forecaster', 'Observation Summary': "We traveled to the southern Whitefish Range to observe surface conditions and wind transport before an onslaught of users this weekend.\n\n\xa0Moderate southwest winds affected large areas open to the wind above 6000'. Wind transport formed fresh cornices and wind slabs that were reactive to the weight of a skier.\nThursday's warming left a 2 cm thick sun crust on steep southerly slopes at mid-elevations and minor fields of rollerballs.\nFriday's warming was most prevalent at low and mid-elevations. Cool air temperatures and wind kept the snow surface cool above 6000'.\xa0\nRecent low-density snow varied between 20 cm deep on steep southerly slopes to 30 cm in sheltered locations.\nRiding conditions remain good, with no instabilities noted in terrain sheltered from the wind and sun.", 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)', 'Instability Comments': 'We observed cracking in freshly formed wind drifts and cornices. New cornice formation failed from the weight of a skier.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


234
234
{'location': 'Paola Mountain', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Clear (No clouds)', 'Temperature (F)': "low to mid 20's", 'New or Recent Snowfall (cm)': 'Nil', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': '18 in the am at the car, 26 upon return.  Clear skies in the am with increasing high clouds from about 1:30 on.  Variable winds in the am, increasing to moderate with strong gust in the afternoon from the west. The Great Bear Wilderness Divide looked to have strong winds with moderate amounts of snow transport.', 'Observation Date': 'Feb 2, 2023', 'Submission Date': 'Feb 2, 2023', 'Observer type': 'public', 'Observation Summary': 'Riding was good on all aspects down to 5400.  Snow surface on south and west aspects became moist from about 6500 down from solar radiation, developing a crust once shaded. The wind and cool temps helped preserve snow quality at higher elevations.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Isolated developing soft slabs as a result of the increasing winds through out the day. <br><br>Surface cracking in the top 2-4", location dependent.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


235
235
{'location': 'Snowslip Mountain', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'We skinned up the south-facing slope to the west ridge of Snowslip (thanks to whoever set the tracks!), dropped into the southeast basin below the peak, then skied down the southwest slope below the summit.', 'Observation Date': 'Feb 2, 2023', 'Submission Date': 'Feb 2, 2023', 'Observer type': 'public', 'Observation Summary': '- Wind-affected snow on all slope aspects- Crossed soft wind slab pockets on the way up and harder wind slabs near and on ridgelines- Skied great snow on south and southeast aspects from higher to mid-elevations- Encountered a sun-affected zipper crust on a south aspect at lower elevations in the afternoon - Observed active wind transport of snow, most intense on the ridgelines- Saw Roller balls (various sizes ranging from the size of a baseball to larger than a basketball) starting from trees and the base of rock features on south aspects in the afternoon', 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)', 'Instability Comments': 'Isolated cracking around our skis on wind slab pockets<br>', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


236
236
{'location': 'Tranquil', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Skied East and N/NW aspects.', 'Observation Date': 'Feb 2, 2023', 'Submission Date': 'Feb 2, 2023', 'Observer type': 'public', 'Observation Summary': 'The snow surfaces we traveled on were dry upon our exit around 3pm.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered', 'Instability Comments': 'Small Loose Dry on convexity, East aspect at 7k. Rider not caught', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


237
237
{'location': 'Apgnars', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Camas Rd. to Schwack City to "Rubideau."', 'Cloud Cover': 'Clear (No clouds)', 'Temperature (F)': '28', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Light', 'Observation Date': 'Feb 2, 2023', 'Submission Date': 'Feb 2, 2023', 'Observer type': 'public', 'Observation Summary': "- Strongggg solar input on south-facing slopes from 10 a.m. until I bailed at 1, dripping trees, roller balls, etc. ... another fun layer to look forward to!- Westerly 15 mph winds at the ridge top transporting some snow onto east and south faces- Not nearly as much snow as I expected ... it's lowww tide up to 5,400 ft. in the Apgars ... like, even lower than usual for this time of year :/", 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'None.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


238
238
{'location': 'Running Rabbit', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Route': 'Ascend/descend south-facing slopes.', 'Cloud Cover': 'Few (Mostly Clear, up to 2/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '4', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': 'Beautiful day with sun and warm temps.  High cloud began moving in mid-afternoon.', 'Observation Date': 'Feb 2, 2023 (9:30 - 16:00)', 'Submission Date': 'Feb 2, 2023', 'Observer type': 'forecaster', 'Observation Summary': "What a day to be out in the mountains. We enjoyed the sunshine, though it did make for a stick/crusty descent.\xa0\n-Large column tests produced propagating results with moderate force in our test pit.\n-Hand pits during our ascent revealed recent and wind-drifted snow on top of a layer of facets above the mid-January crust.\xa0\n-Winds increased to moderate from the West above 6800'.\xa0\n-We saw light to moderate wind transport in our vicinity, but noticed impressive plumes of snow extending from peaks in the Great Bear Wilderness\n-Found one small natural soft slab avalanche that likely failed yesterday.\xa0\n-Noted debris from two small loose wet avalanches that slid during this afternoon's heat.\xa0\n-Observed isolated cracking in recently wind-drifted snow.\xa0\nWe avoided convex roll-overs on our descent.\xa0 Variable surface conditions made for defensive skiing.", 'SIGNS OF INSTABILITY': 'Avalanches Observed  Cracking Observed (isolated)', 'Instability Comments': 'Cracking in windrifted snow 4-6 inches deep.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

239
239
{'location': 'Alpha/Beta', 'Zone / Region': 'Swan Range', 'Activity': 'Snowmobiling/Snowbiking', 'Observation Date': 'Feb 2, 2023', 'Submission Date': 'Feb 2, 2023', 'Observer type': 'public', 'Observation Summary': 'Wind sheltered terrain held plenty of soft dry snow (20-30cm) but it’s beginning to settle. Open bowls and higher terrain adjacent to ridgelines were heavily wind drifted and winds mid day were blowing 20-30 mph on higher (6800 ft) ridge tops. Interestingly, in some of the higher south facing terrain the recent dry snow had been blown into cross loaded formations, revealing harder wind slabs, presumably from the last NE wind event. Lots of deep drifts on ridgelines. We observed no cracking or movement of snow (besides dry sluffs) where we rode but did not feel confident riding wind affected open terrain. One of the NE facing bowls had experienced several fresh cornice fall avalanches but the slides appeared to have been limited to cornice debris and recent storm snow. (See photos) Super fun day to be out with all the sun and powder.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


240
240
{'location': 'Essex', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Below Freezing', 'New or Recent Snowfall (cm)': '3 inches', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Large Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Observed active transport along the crest of the Flathead Range. Winds gusting into the moderate category.', 'Observation Date': 'Feb 1, 2023 (8:00 - 15:30)', 'Submission Date': 'Feb 1, 2023', 'Observer type': 'forecaster', 'Observation Summary': "We went into the Flathead Range to track storm snow totals and the sensitivity of wind slabs and loose dry avalanches.\n- Storm totals were roughly 6 to 9 inches of snow. There were 3 inches of snow on yesterday's skin track (Tuesday).\xa0\n- We triggered small loose dry and soft wind slab avalanches. These were all harmless in size due to the terrain we were in. The wind slabs we triggered were 6 to 8 inches thick and propagated roughly 30 feet. These were on slopes with small amounts of wind loading.\xa0\n- Observed active wind transport along the crest of the flathead. Winds were out of the south and west.\xa0\n- There is 16 to 20 inches of low-density snow sitting on a slick crust on solar aspects.\xa0\nWe selected south-facing aspects to avoid freshly formed wind slabs. We managed sluff by riding slopes less than 40 degrees. Overall the skiing exceeded expectations.\xa0\nphotos/video soon", 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered  Cracking Observed (isolated)', 'Instability Comments': 'Cracking anywhere winds stiffened the snow surface. Triggered small wind slabs along a lightly wind-loaded ridgeline. Observed a large (D2) crown on Nyack from the road.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


241
241
{'location': 'Cascade', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Up from the Skiumah Trail and back down through the woods (and bush!)', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '21', 'New or Recent Snowfall (cm)': '5-20+ cm', 'Rain/Snow Line': "5600' (Jan 27?)", 'Snow Available For Transport': 'Large Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Calm winds and S-1 to S1 precip during our brief outing.', 'Observation Date': 'Feb 1, 2023', 'Submission Date': 'Feb 1, 2023', 'Observer type': 'public', 'Observation Summary': 'Challenging skinning conditions but pretty good skiing conditions up high. Still quite bushy down low.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Instability was confined to the recent surface snow (Loose Dry) sluffing on old crusts and was easily skier (or treebomb) triggered. More sluffing and longer running higher up and on steep slopes.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


242
242
{'location': 'Sixmile', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Route': 'Ascend southern ridge to subpeak and traverse to summit.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '10 inches', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Large Amounts', 'Wind Loading': 'Light', 'Weather Summary': "Wind began calm, increasing to light above 6500' and gusting to moderate above 7000' with light blowing snow.", 'Observation Date': 'Feb 1, 2023 (9:30 - 16:30)', 'Submission Date': 'Feb 1, 2023', 'Observer type': 'forecaster', 'Observation Summary': "We traveled into the Swan Range to verify recent snow totals and see what effect the wind has had.\n**We found buried surface hoar 1 meter below the surface on a S-SE aspect at 6800 feet.\xa0 This particular spot was not an area I expected surface hoar to survive.\xa0 It isn't particularly well-preserved at this point, but its stil there.\xa0\n-Small and large column tests produced fractures (no propagation) with moderate and hard force at this location.\xa0\xa0\n- We found roughly 10 inches of new snow at upper eleveations. This snow fell on old wind board, wind slab, and-in sheltered areas-dry, unconsolidated snow.\xa0\n-Old wind slabs were masked by the new snow.\xa0 We were able to identify their locations by digging down in areas where our ski penetration decreased.\n-Old wind slabs were generally stubborn to non-reactive.\xa0 They were hard (1F) and 2-8 inches thick in this location.\n-Fresh drifts of snow were up to 2 feet deep.\xa0 These drifts were soft and produced minimal cracking.\xa0 They did, however, slow our skinning/skiing.\xa0\xa0\n-In seltered terrain we saw minimal cracking in the top 3-4 inches of the new snow.\xa0\nWith this information we chose to ski Southeast aspect with slopes generally 30-35 degrees (but some spots exceding 35 degrees). We did travel down the ridge a ways before dropping in to hopefully avoid recently drifted snow.\xa0 We still found pockets that cracked 1 foot deep and extended up to 10 feet but did not slide.\xa0 We rode one at a time and kept eyes on eachother.", 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)  Collapsing Observed (isolated)', 'Instability Comments': 'Collapsing occured when traveling over the edge of old windslabs buried beneath the new snow.  Cracking was minimal where the new snow has been stiffened by wind.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


243
243
{'location': 'Spider Bowl area', 'Zone / Region': 'Swan Range', 'Activity': 'Skiing/Snowboarding', 'Route': "Toured from 3300' to 6600' in the Spider area for a couple of powder laps on a W aspect.", 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '14', 'New or Recent Snowfall (cm)': '4-24"', 'Rain/Snow Line': 'N/A', 'Snow Available For Transport': 'Large Amounts', 'Wind Loading': 'Previous', 'Weather Summary': 'Temperature at trailhead at 9:00am was 14 degrees with little to no wind. The snow fell constantly throughout the day, mostly S1-S2, with brief periods of heavier (estimate up to S4-5, quickly accumulating on hat brims and backpacks) snow. Winds were generally light, from the SE in the morning switching to SW in the afternoon, gusting moderate as the afternoon went on. We noted some new snow had blown off the trees on the windward side on our final descent. Upon returning to the trailhead, about 2" of snow had accumulated on the car. We estimate between 6-10" fell at upper elevations since last night.', 'Observation Date': 'Jan 31, 2023', 'Submission Date': 'Jan 31, 2023', 'Observer type': 'public', 'Observation Summary': 'Enjoyed a great powder day with a plan to avoid the newer thin wind slabs on NW-NE-SE aspects, as well as the surface hoar weak layer potentially lurking on those same aspects. There was about 2-4" of new, cold, dry snow at the trailhead at 3300\' at 9am, and snow fell constantly throughout the day. At ridgeline, and below on a SW-W face we encountered old wind slabs from last week\'s storm with NE winds. Despite some huge whalebacks, all wind slabs we tested proved to be very stiff and very unreactive. In areas sheltered from the wind we enjoyed 18-24" of new snow from the last couple of storms. All the superlatives for fun powder skiing apply here. Snow did stuff quite fast and far (mostly at the surface) in steeper terrain. SE-SW winds were generally light throughout the day, although gusting moderate in the afternoon -- we did note snow had blown off of the windward side of some trees. There is plenty of snow available for transport if winds do pick up.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Older wind slabs caused by last week\'s stormy NE winds were very stiff and very stubborn. 18+" of new cohesionless snow sluffed fairly fast and far on steeper (35-45 degree) terrain, but only superficially.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

244
244
{'location': 'Lost Johnny', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Route': 'Took sleds to the end of the road, skinned up a southeast aspect to the ridge, and skied powder down.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '10', 'New or Recent Snowfall (cm)': 'N/A', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': 'A little sunshine in the morning and then overcast most of the day. Cold temperatures to start, with warmer temperatures (10 degrees) by 1400. Winds were calm, except for a light breeze around 1530.', 'Observation Date': 'Jan 30, 2023 (8:30 - 16:00)', 'Submission Date': 'Jan 30, 2023', 'Observer type': 'forecaster', 'Observation Summary': "We were in the Swan Range today, on the east side of the Swan Crest, in the Lost Johnny drainage.\n\nToday we skied the best powder I've skied all season. The southern-facing slopes we descended were protected from the recent winds of this past weekend's storm.\nOur first snow profile at 6100 feet, was on a southeast aspect and had the multiple crusts we've been tracking (Christmas, \xa0MLK, and 1/18 rime-crust) with 8 inches of new soft snow resting above. We did not get slab propagation in our ECT (see the snowpack section for details).\nAlong the ridge, we observed older, stubborn cornices from typical southwest winds, with pockets of fresh wind drifts from recent northerly winds.\nOur second snow profile at 6800 feet was northwest facing and also had the three identified crusts. We got propagation with hard force (ECTP30) above a crust 90cm below the surface. We found scattered pieces of surface hoar crystals mixed with facets within this weak layer.\nThe thin wind slabs we did observe in upper elevations were at most 1 foot thick. \xa0Besides some isolated cracking around our boards, we did not observe any significant signs of instability on the slopes we traveled.\nThe bumpy sled ride into and out of Lost Johnny was worth the 8 to 11 inches of sheltered powder.", 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)', 'Instability Comments': 'Minimal, isolated cracking was observed around our boards at upper elevations.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


245
245
{'location': 'Noisy Basin/Swan Range', 'Zone / Region': 'Swan Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'We started on Jewel Basin Road, skinned up the FS5392 to then hike up the Switchback trailhead.  Got up to 5,400 ft. Were we saw signs of severe wind loading and instability. We aborted and climbed up to checkered board via camp misery on the second attempt. All aspects we tested were mid/low elevations on SE/SW aspects.', 'Cloud Cover': 'Clear (No clouds)', 'Temperature (F)': '3', 'New or Recent Snowfall (cm)': '3”', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Intense', 'Weather Summary': 'Very cold, clear day. No wind.', 'Observation Date': 'Jan 29, 2023', 'Submission Date': 'Jan 30, 2023', 'Observer type': 'public', 'Observation Summary': 'Cracks on the snow. Unpredictable snow pack. Large snow pillows.', 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)', 'Instability Comments': 'We arrived to an area exposed by Friday/Saturday were the snow started to crack with load.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


246
246
{'location': 'Dorothy', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Jan 29, 2023', 'Submission Date': 'Jan 29, 2023', 'Observer type': 'public', 'Observation Summary': 'What’s harder: skiing inbounds and losing your toes for hours at a time or touring in the cold and trying to sort out the right blend of layers?We opted for the latter. Clear skies and cold. Ridgetops showed signs of wind, but S aspects held the goods below where the wind did its work. Sloughing of new snow was evident in shallow natural releases in the Skook shoots, and we kicked some slough down steeper angles on Dorothy.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


247
247
{'location': 'Running rabbit', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Found warmth and good skiing in the sun today. S facing slopes were the ticket with this weekends storm.', 'Cloud Cover': 'Clear (No clouds)', 'Temperature (F)': '0', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': 'No windBlue skies on the continental divide', 'Observation Date': 'Jan 29, 2023', 'Submission Date': 'Jan 29, 2023', 'Observer type': 'public', 'Observation Summary': "The storm was definitely a dud at lower elevations,  but surprisingly impressive up high. The winds did not effect S facing slopes where we were. Up to 10 inches of new snow from Friday's storm.", 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered', 'Instability Comments': "40 cms of loose snow sitting on top of MLK crust at upper elevations.  1 meter of snow on top of Christmas crust.<br>Dug pit at 6600' SW facing slope<br>Ectn16 40 cms down<br>No other results<br>Heard 1 whumpf entering drainage above creek.<br>No cracking, good bonding of storm snow on S facing slope.<br>Unintentionally Triggered one avalanche at 5800' on descent at the bottom of the run. It was storm snow, loose, dry avalanche. 60 ' wide and ran 300'. Not big enough to bury a person.<br>", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


248
248
{'location': 'Checkerboard', 'Zone / Region': 'Swan Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Skinned the road up to checkerboard and summited peak 6437.', 'Cloud Cover': 'Clear (No clouds)', 'Temperature (F)': '-10', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Moderate', 'Observation Date': 'Jan 29, 2023', 'Submission Date': 'Jan 29, 2023', 'Observer type': 'public', 'Observation Summary': "At 5500' near the NW ridge of checkerboard we experienced shooting cracks and thick wind slabs on the west side of the ridge, indicating the snow transport likely occured recently when the wind was coming from the NE. Evidence of wind transport was widespread with slabs, scoured nodules, and cornices visible throughout the day at all elevations and aspects, even deep in the trees. While at lower elevations, slabs we're observed primarily on NW-S aspects, at higher elevations large cornices and slabs were observed on primarily NE aspects, indicating the wind transport at these elevations was older, from a few days ago when winds were from the SSW. Perhaps the upper elevations had less snow to transport by the time yesterday's gusts came through.The slabs within the forest were very sporadic and varied a lot locally. We dug two pits 15 feet from one another. The top 4 inches of wind slab popped off as soon as we cut it with the cord on one ECT, where the other pit 15' away was ECTX with no wind slab at all.Overall the ski was cold and a bit chunky coming down with thin slabs everywhere, very little powdery snow on top without wind alteration. Really nice day overall.", 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)', 'Instability Comments': 'Experienced localized shooting cracks in wind drifted snow. Cracks never extended beyond ~10 feet.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


249
249
{'location': 'Jewel', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Clear (No clouds)', 'Temperature (F)': 'Below Freezing', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Previous', 'Weather Summary': 'Cold, clear day with calm winds.', 'Observation Date': 'Jan 29, 2023 (9:00 - 16:30)', 'Submission Date': 'Jan 29, 2023', 'Observer type': 'forecaster', 'Observation Summary': "Sunshine! Today we took a trip into the Jewel to assess wind slabs and quickly dig around for buried weak layers.\xa0\n- We observed very little recent avalanche activity. We suspect that most natural activity from the storm quickly got covered with drifting snow.\xa0\n- It is hard to pinpoint the distribution of wind-drifted snow. We found slabs on all aspects above 5000 feet. The softest snow we found was on a south aspect.\xa0\n- A weak layer of buried surface hoar standing upright on north-facing aspects. It is buried between 70 to 90 cm at upper elevations.\xa0\n- We triggered small slabs of drifted snow and one loose dry avalanche. These were all small due to the small (putt putt golf) kind of terrain we were on.\xa0\nThe skiing was honestly mediocre due to the stiff, grabby wind slabs everywhere. I say mediocre, but also hilarious due to the numerous wipeouts it caused. We were extra mindful of the terrain we traveled in once we switched to northerly aspects. A persistent weak layer at 70 to 90 cm isn't something we cared to tango with.", 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered  Cracking Observed (widespread)', 'Instability Comments': 'Isolated cracking around skis. Drummy sounding pillows. Hollow feeling slabs. Human triggered wind slabs (small). All signs of drifting are present. Winds drifted snow on almost every aspect and all elevations.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

250
250
{'location': 'Rescue Crk', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': "Up Rescue Crk to 6600'", 'Observation Date': 'Jan 28, 2023', 'Submission Date': 'Jan 28, 2023', 'Observer type': 'public', 'Observation Summary': 'Warmer, windier, and less accumulated snow than expected. 15F at the hwy with just a dusting of new snow on top of ice and hardpack. Higher up the valley most of the fresh snow appeared to be in the form of wind slab.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Cracking Observed (isolated)', 'Instability Comments': 'Soft 2-6" thick windslab was widespread on North and East facing aspects. Observed some soft D1 slide debris on steep slopes, possibly from 1/27.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


251
251
{'location': 'Flathead Range', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Summer trail', 'Cloud Cover': 'Clear (No clouds)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '6', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': 'Polar air plunging down from the north', 'Observation Date': 'Jan 28, 2023', 'Submission Date': 'Jan 28, 2023', 'Observer type': 'public', 'Observation Summary': 'Dense wind drifts on ridge lines.. stayed away from anything over 30 deg..could have been trouble if you ended up on a west/lee aspect unexpectedly.', 'SIGNS OF INSTABILITY': 'Cracking Observed  Collapsing Observed (isolated)', 'Instability Comments': 'Skinning on mellow ridge line thru dense, hard wind drifts let out a couple good woomphs', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


252
252
{'location': 'JFS Canyon - Running Rabbit Mtn', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Driving', 'Route': 'Road observations from Hwy 2.', 'Cloud Cover': 'Not Observed', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': '•\tAfternoon had partly sunny skies with no precipitation and light to moderate E winds on the Canyon floor and moderate N-NE winds above 6000’.•\tDaytime highs only reaching single-digits °F on the Canyon floor and negative single-digits °F above 6000’ elevation.', 'Observation Date': 'Jan 28, 2023', 'Submission Date': 'Jan 28, 2023', 'Observer type': 'public', 'Observation Summary': 'Two new avalanches that likely ran this morning observed from Hwy 2.The Jan. 26-28 storm was a dud here in JFS Canyon. Canyon floor received 2-3” snowfall with 0.30” water. HST totals at Shed 11 were 10” (suspect some wind-loading) and 4” and Shed 7.Arctic air pushed around 0100 last night with increasing easterly winds and moderate amounts of blowing/drifting snow. Some serious near-surface faceting going on now in the upper 5” of the snowpack.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


253
253
{'location': 'Snowshed', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Up Essex Creek and into the bush!', 'Cloud Cover': 'Few (Mostly Clear, up to 2/8 covered)', 'Temperature (F)': '10', 'New or Recent Snowfall (cm)': '5-20cm', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Temps started at 15*F @ 9am and cooled to 10*F by 2pm in Essex. Winds were generally light and from the NW shifting to NE by our exit - but we were well protected in the woods. Skies cleared up by noon and made for a lovely albeit brisk day!', 'Observation Date': 'Jan 28, 2023', 'Submission Date': 'Jan 28, 2023', 'Observer type': 'public', 'Observation Summary': 'We observed no natural avalanches, no collapsing, and no shooting cracks. We did trigger a variety of inconsequential small avalanches on steep test slopes while descending.We did not find any buried surface hoar despite poking in the snow pretty regularly, but were confined generally to N/NE aspects during our brief tour.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered', 'Instability Comments': 'See avalanches description - we triggered a variety of very small inconsequential storm slab/loose dry avalanches.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


254
254
{'location': 'Dickey Cr', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Jan 28, 2023', 'Submission Date': 'Jan 29, 2023', 'Observer type': 'public', 'Observation Summary': 'Due to life instabilities including a sick toddler and a sick dog, two members of the Dickey Cr Powder Party Posse found themselves still at home yesterday. The remaining two managed to arrive sans either of the two snowmobiles they planned to bring. It started chilly, and just got colder. We traveled on N and NW aspects. The more open the terrain, the more we saw evidence of wind affect, but this mostly manifested as thick (1” or less) wind skins on otherwise dry snow. Wind was moving snow into our skinner between laps. We saw sloughing on steep, sheltered slopes. Winds were light to moderate, higher on the ridgelines. Sky overcast to clear as the day went on.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


255
255
{'location': 'Marion lac', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'S facing runs outta Essex town.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '30', 'New or Recent Snowfall (cm)': '7 inches', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Not a huge storm.Good enough to be skiing fun pow without signs of instabilities.', 'Observation Date': 'Jan 27, 2023', 'Submission Date': 'Jan 27, 2023', 'Observer type': 'public', 'Observation Summary': "At trailhead 0900 it was snowing hard with big wet flakes. We found about 2 inches of overnight snow to start our tour. The storm came and went through the day. Mostly lighty snowing, light winds except for Ridgeline @ 7200' was gusting to moderate. 7 new inches of pow up high by the end of the day. Good day to be skiing S facing runs, with surprisingly little wind affect top to bottom (until tonight....).", 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Did not notice any cracking or whumpfing.<br>1" thick storm slab forming on Ridgeline at 7200\'.<br>Below 5500 the loose snow was sluffing on crust.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


256
256
{'location': 'Checkerboard', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Obscured (Sky not visible due to fog or non-cloud layer)', 'Temperature (F)': '30', 'New or Recent Snowfall (cm)': '7', 'Rain/Snow Line': '3000', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Silver-dollar sized flakes early AM, then most of the day. High intensity (S5 mid morning) with snow piling up on packs and jackets in a few minutes. Some breaks late morning-early afternoon, then steady snow (S1-2). Light winds at ridgeline (6400 ft) but no apparent drifting.', 'Location': 'NESWNWNESESW', 'Distribution': 'IsolatedSpecificWidespread', 'Sensitivity': 'UnreactiveStubbornReactiveTouchy', 'Size': 'D1D2D3D4D5', 'Observation Date': 'Jan 27, 2023 (9:00 - 4:00)', 'Submission Date': 'Jan 27, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Storm day skiing in sheltered, mid elevation terrain, in large part to avoid exposure to developing new snow hazards. No signs of wind drifting in this terrain. Wet day to start, with outer layers soaked first climb. Snowfall intensity diminished early afternoon and dried out. New snow loose with few signs of storm slab development in the terrain we chose. Loose snow sluffs a hazard on very steep slopes.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered', 'Instability Comments': 'Some short cracking at switchback corners and in turns. Seemed more common mid afternoon, after snow settled some.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

257
257
{'location': 'Marion/Dickey', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': "Went to get a fun times tour in pre-storm. Went from the trailhead at 3800' up Marion Creek to the ridge at 6800' and skied a south facing shot, then went back up and skied a northern aspect out Dickey Creek.", 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '27-35', 'New or Recent Snowfall (cm)': 'Tr-6"', 'Rain/Snow Line': 'N/A', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': "From 9:00-11:00 there was occasional snowfall ranging from S-1 - S2 intensity. There were occasional breaks of sun, but mostly overcast. The wind was gusty and variable, with periods of calm followed by airborne rime chunks to the face. The wind became a more consistent westerly flow as the afternoon wore on, mostly moderate winds. Around 14:30 the cloud ceiling lowered to around 7000'.", 'Observation Date': 'Jan 26, 2023', 'Submission Date': 'Jan 26, 2023', 'Observer type': 'public', 'Observation Summary': 'Went out to see what the snow was like before tonight\'s storm. Small snowfall events from the last couple of days left us with a (wet) dust on (stout) crust down low. This new snow was fairly wet and sticky below 5800\' on south aspects and 5300\' on north, leading to some glopping on skins and less-than-ideal skating conditions on the exit. Above those elevations however we enjoyed great soft turns with 3-6" of new dry snow. We observed some blowing snow from gusty variable winds on ridge line, potentially creating some new small slabs about to be buried by tonight/tomorrow\'s snow event.', 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)', 'Instability Comments': "Our main concern with instability was wind loading. We did find wind slabs, particularly near the top of our north facing line with a fair amount of cross loading below the ridge line. I jumped on small wind slabs on SE, N, and NE slopes between 6500-6800' -- most were stubborn and did not fail. Two of the slabs on test slopes on N and NE aspects showed minor cracking, and one released a small slab that ran thirty feet or so below my skis. (see photo)<br><br>We also discussed the day's potential for small wet loose sluffs and avalanches down low. Our observation of this hazard was limited to skier-triggered roller balls on our exit.<br><br>We observed one large old avalanche in a south facing gully across the Dickey drainage from repeater ridge. We were not close enough for good photos or great detail, but it appeared to be a wet slab avalanche that ran over a thousand feet, likely from the Xmas week rain event.", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


258
258
{'location': 'Grants Ridge', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Up Disbrow creek', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '20', 'New or Recent Snowfall (cm)': 'Trace to 4', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': 'Gusting winds transporting snow and light snow throughout the day. Warming below 5,000’ glopping snow.', 'Observation Date': 'Jan 26, 2023', 'Submission Date': 'Jan 27, 2023', 'Observer type': 'public', 'Observation Summary': 'Gusting winds transporting snow and light snow throughout the day. Warming below 5,000’ glopping snow.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


259
259
{'location': 'Lost Johnny', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'FAC', 'Activity': 'Snowmobiling/Snowbiking', 'Observation Date': 'Jan 25, 2023', 'Submission Date': 'Jan 29, 2023', 'Observer type': 'forecaster', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


260
260
{'location': 'Essex', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Obscured (Sky not visible due to fog or non-cloud layer)', 'Temperature (F)': 'Below Freezing', 'New or Recent Snowfall (cm)': 'Trace to 3', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Previous', 'Weather Summary': 'Cloud deck was at roughly 7000 feet. Obscured above that.', 'Observation Date': 'Jan 25, 2023 (9:00 - 16:30)', 'Submission Date': 'Jan 25, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Today we went into upper elevations to look for buried weak layers on wind-sheltered slopes. We also wanted to look at what surfaces new snow will fall on with incoming precipitation.\n- Could not find buried surface hoar at any elevation on north, east, or west aspects above 7k in this area. We found a 2-inch hard wind board with a crust capping it.\xa0\n- We had non-propagating results on extended column tests above the MLK crust.\xa0\n- We initially descended onto a south-facing slope at 7600 feet and found an incredibly rotten snowpack structure. Large depth hoar grains with a stiff slab above them. We tucked in below a rock and decided to boot out.\xa0\nWe found the snowpack structure generally stable on north, east, and west-facing aspects. We felt comfortable skiing steep west-facing terrain after observing no signs of buried weak layers in the upper snowpack. A hard and supportable crust in the upper snowpack also added confidence to our decisions.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


261
261
{'location': 'Stahl Peak', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Route': 'Up the groomed trail until grooming stops, then skin up to the lookout.', 'Cloud Cover': 'Few (Mostly Clear, up to 2/8 covered)', 'Temperature (F)': '25', 'New or Recent Snowfall (cm)': '3', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Gorgeous day.  Sunny and mild temps.  Solar aspects were slightly tacky feeling in the afternoon', 'Observation Date': 'Jan 25, 2023 (9:30 - 16:30)', 'Submission Date': 'Jan 25, 2023', 'Observer type': 'forecaster', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'No instabilities that we noticed today.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


262
262
{'location': 'Devils', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Jan 25, 2023', 'Submission Date': 'Jan 25, 2023', 'Observer type': 'public', 'Observation Summary': 'Minimal evidence of precious days wind transport on west aspect. Very small amount of surface hoar present. Overall found about 15-25 cm of snow sitting on top of MLK crust. No sluffing during skiing. Benign weather. One pit at 6500’. Depth of 180 cm, ectx', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


263
263
{'location': 'Link Mtn', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Obscured (Sky not visible due to fog or non-cloud layer)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '2”', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Cloudy.Temps were colder than they’ve been (20F at the TH) and the air had a bit of a bite to it. Guy’s Marias Pass winds were easily found in the Whitefish Range today: winds were moving trees and definitely strong enough to transport snow. At least 1cm of rime had returned to the weather station overnight. That place got more rimes than Phyllis Diller.', 'Observation Date': 'Jan 23, 2023', 'Submission Date': 'Jan 23, 2023', 'Observer type': 'public', 'Observation Summary': 'A couple of fresh inches (5cm Canadian) of very low density snow had fallen overnight, adding to the pretty decent snowpack near Red Meadow pass. Wind slabs seemed to be the most obvious avalanche problem of the day, which was managed easily by avoiding wind-loaded slopes. The other primary issue of the day was the well-known low viz combo pack of fog-cloud obscura and flat light. We managed this by skiing short pitches and keeping one another in view, especially near tree well hazards and other forms of uncertainty (such as, where is the edge of this ridge, bro?).', 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)', 'Instability Comments': 'Cornice.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

264
264
{'location': 'Southern Whitefish', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Obscured (Sky not visible due to fog or non-cloud layer)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '1', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': 'In and out of obscured and overcast. Light precip throughout the day with short periods of snow showers.', 'Observation Date': 'Jan 23, 2023 (10:00 - 15:00)', 'Submission Date': 'Jan 23, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'I took a quick trip to the southern Whitefish Range to familiarize myself with middle elevations.\n- Observed no signs of instability below 6500 feet.\xa0\n- Found a layer of faceted snow in hand pits roughly 6 to 8 inches below the surface. This layer is roughly 4 inches below the MLK crust.\nBeing that the terrain was nearly bumped out and no signs of instability, we felt very comfortable skiing in steep terrain spaced out.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


265
265
{'location': 'Skyland', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Route': 'Took the logging road behind Challenge cabin.  Then skinned up the ridge to the West.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '28', 'New or Recent Snowfall (cm)': '3 inches', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'None', 'Weather Summary': 'No wind!  Overcast and snowing lightly all day.', 'Observation Date': 'Jan 23, 2023 (17:00 - 15:00)', 'Submission Date': 'Jan 23, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'We took the highway and had a look at the Skyland country today.\n-We had exceptional sking, and felt comfortable stepping into bigger terrain.\n-No cracking, whoomphing or sluffing was observed.\n-Besides the MLK and Dec crusts the snowpack is very upright.\n-The MLK crust was capped by 5 inches of light snow that is very much available for wind transport. \xa0Below this crust is an inch of small facets and below that is a layer of well preserved buried surface hoar. \xa0\n-Suprise of the day was no wind! \xa0A nice treat for being in the Marias Pass country.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'No instabilities in our pits or that we noticed.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


266
266
{'location': 'Rescue Creek Basin', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Route': 'Summer trail into the basin, up to the saddle to our high point of 6800 feet.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '20', 'New or Recent Snowfall (cm)': "3-4 inches at 6800'", 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': 'Overcast most of the day. Moderate winds until 2pm, when winds became calm.', 'Observation Date': 'Jan 23, 2023 (9:00 - 17:00)', 'Submission Date': 'Jan 23, 2023', 'Observer type': 'forecaster', 'Observation Summary': "Glacier's 2023 winter park intern joined me today in the Flathead Range to sample the varied surface conditions\xa0\n\nLow elevations consisted of stout crust that made for some challenging skinning.\nModerate winds from 1000 until 1400. S-1 for 2 hours. We observed snow being actively transported.\n0.5 to 1 inch of new snow at 5k.\nSnowprofile at 6k, HS: 240, ECTX. We observed many crusts, including a layer of broken surface hoar, buried 45cm from the surface.\nSurface snow was highly diverse. We traveled on a slick, supportable, and stout crust that transitioned to semi-supportable, with thin drifts of wind-distributed snow.\xa0\nSkiing above 5600 feet was good. Winds have been redistributing 3-4 inches of low-density snow.\nBy the end of the day, winds were calm.", 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


267
267
{'location': 'Old Man’s Bowl', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Not Observed', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': 'Calm winds, snow was available for transport but didn’t see any transported. Decent visibility until afternoon.', 'Observation Date': 'Jan 22, 2023', 'Submission Date': 'Jan 22, 2023', 'Observer type': 'public', 'Observation Summary': 'Did ECT on NE facing slope - ECTN 18 - 160cm deep in a 190cm pit.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


268
268
{'location': 'Old mans bowl', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Old mans bowl', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '20', 'New or Recent Snowfall (cm)': '1”', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Great day', 'Observation Date': 'Jan 22, 2023', 'Submission Date': 'Jan 22, 2023', 'Observer type': 'public', 'Observation Summary': 'Another 1” of snow, calm conditions, no wind, and fair visibility.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'All good', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


269
269
{'location': 'Cascadilla', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'North and east aspects to mid elevations', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '4 cm', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Previous', 'Observation Date': 'Jan 22, 2023', 'Submission Date': 'Jan 22, 2023', 'Observer type': 'public', 'Observation Summary': 'Several crusts adding strength to the upper snowpack. 2 to 4 cm of new snow with thin drifts up to 15 cm over the most recent rime crust. All very small and harmless.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


270
270
{'location': 'Skook Peak', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '19', 'New or Recent Snowfall (cm)': '1”', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Overcast with occasional light flurry', 'Observation Date': 'Jan 22, 2023', 'Submission Date': 'Jan 22, 2023', 'Observer type': 'public', 'Observation Summary': 'Large cornices on north aspect, multiple rain crusts, small volume of lower density snow on top of snow pack', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'ECT n16 @100 cm from bottom', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


271
271
{'location': 'Link Mountain', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'FAC', 'Activity': 'Snowmobiling/Snowbiking', 'Route': 'Ascended up south facing terrain to ridge and up to peak.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Below Freezing', 'New or Recent Snowfall (cm)': '2 in', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Relatively calm winds and very light precipitation.', 'Observation Date': 'Jan 22, 2023 (9:00 - 15:30)', 'Submission Date': 'Jan 22, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Today our primary goal was to de-rime Link Mountain weather station. That station took first place for the most rimed station I have ever seen.\xa0\n- 1 to 2 inches of new snow overnight. We found roughly 4 to 6 inches of new and recent snow sitting on the MLK crust. This crust is thin and not noticeable while skiing here. We found it up to 7200 feet.\xa0\n- Two different layers of near surface facets were observed. Both had non propagating results in snowpit tests.\xa0\n- Surface snow was almost unneffected by wind in this location.\xa0\n- We observed some impressive debris piles that we suspect occurred during the Christmas rain event.\xa0\nLink Mountain is back in action.', 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)', 'Instability Comments': 'Isolated cracking in small wind drifts near ridgeline.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

272
272
{'location': 'Marion Lake, Dickey Creek', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Essex to Marion Lake, Repeater Ridge, Dickey Creek and back.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '25', 'New or Recent Snowfall (cm)': '1', 'Rain/Snow Line': 'Below TH elevation', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Very light snowfall all day. No significant breaks in the clouds, though you could see them thinning. Ridgeline winds were light from the W.', 'Observation Date': 'Jan 22, 2023', 'Submission Date': 'Jan 22, 2023', 'Observer type': 'public', 'Observation Summary': 'We found generally stable conditions, with very stubborn pockets of wind-deposited snow at upper elevations.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


273
273
{'location': 'Central Flathead Range', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Crustville to Powderton', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '6cm', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'None', 'Weather Summary': "Cool temps and cloudy skies. Light snowfall most of the day with a few burst of S2. Approximately 6cm of new snow fallen at upper elevations by 3pm. Very light/calm winds all day to 6900' on ridgetop.  Climbed to this elevation for 3 laps between noon and 3pm and winds were calm on each climb.", 'Observation Date': 'Jan 22, 2023', 'Submission Date': 'Jan 22, 2023', 'Observer type': 'public', 'Observation Summary': 'Traveled into the Central Flathead Range to continue the hunt for buried surface hoar. We dug one pit on sheltered north facing below a saddle that we deemed a reasonable location for fragile feathers to survive the wind and sun. No luck finding the culprit.We did find high quality riding at upper elevations. 26cm of soft snow above the 1/13 crust. No signs of the 1/19 freezing rain/rime crust here. Winds appear to have been minimal in this drainage as even upper elevation westerlies harbored nice unconsolidated powder up to ridgetop and there was undistrurbed powder in the trees on "windward" slopes as well. Riding conditions were great above 6000\', good down to 5200\', and good enough below that.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Generally good stability. Some sloughing on steep westerlies. Not at much as expected and inconsequential. Hardly worth noting.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


274
274
{'location': 'Marion Creek', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Skiied the first obvious Avi chute north of the trail as you approach Marion lake.', 'Observation Date': 'Jan 21, 2023', 'Submission Date': 'Jan 21, 2023', 'Observer type': 'public', 'Observation Summary': 'We observed some short dry loose sluffs that were harmless at a slope angle of 40 degrees on a SSE aspect beginning at 5500 feet. This was very manageable at our elevation with only 10-15 cm of dry, fresh snow. Cloud level was hanging out around 7k or so all day.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


275
275
{'location': 'Northern Flathead', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Jan 21, 2023', 'Submission Date': 'Jan 21, 2023', 'Observer type': 'public', 'Observation Summary': 'The top 5-10 cm of snow not well bonded to the most recent crust, skiing on steeper slopes caused sluffing to run for a couple hundred feet. Dug one pit at 6400, north facing. Depth of 200 cm. Similar to Marion last weekend, got ectn11 at the layer 20 cm from surface. Slides right off with a light shovel shear. Everything below 4500 is locked up!', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


276
276
{'location': 'Northern Whitefish range', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Skied S, SE, and SW aspects. Spent a little time playing around on flat terrain at 5500’, where the snow was soft but too dense to be the deep fluffy powder we were looking for.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': 'The clouds hovered at about 6800’ all day. Breezy but no gusting on the ridge, and felt calm all day below ridge line.', 'Observation Date': 'Jan 21, 2023', 'Submission Date': 'Jan 21, 2023', 'Observer type': 'public', 'Observation Summary': 'Generally consistent snowpack where we traveled, no cracking. We felt comfortable skiing steeper pitches one at a time with eyes on our partners to manage the fast-moving sluff.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Sluff in the top several inches ran pretty fast and for several hundred feet in steeper zones and gullies', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


277
277
{'location': 'Swan', 'Zone / Region': 'Other', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '30', 'New or Recent Snowfall (cm)': '5', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Normal wx', 'Observation Date': 'Jan 21, 2023', 'Submission Date': 'Jan 21, 2023', 'Observer type': 'public', 'Observation Summary': 'Lots of snow moving.. which was expected but not much room for error.  Risk tolerance is too high :/', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Cracking Observed (isolated)  Collapsing Observed (isolated)', 'Instability Comments': 'Medium loud whumpf then immediate shooting crack from my skiis out into the fog.  Slope was steep enough to slide so I’m not sure why it didn’t… tree anchors?!?  Humbling and unnerving.  Was third in line on the up track;other two in party did not observe/were too far ahead.  NW aspect. 6500 ft.  Northern swan range.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


278
278
{'location': 'John F Stevens Canyon', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Below freezing at all elevations', 'New or Recent Snowfall (cm)': 'Not observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Mild temps and light WSW winds on ridge line .  Skies were overcast throughout our tour, but upon returning to the valley floor around 3pm noticed the clouds breaking/sunny drive home through the Middle Fork Corridor.', 'Observation Date': 'Jan 21, 2023', 'Submission Date': 'Jan 21, 2023', 'Observer type': 'public', 'Observation Summary': 'No avalanche problems observed today.  Rode sustained 35 degree slopes with no concerns.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'No major instability noted.  Some very mild effected snow near ridge lines but nothing of concern.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


279
279
{'location': 'Hay Ck', 'Zone / Region': 'Whitefish Range', 'Activity': 'Snowmobiling/Snowbiking', 'Cloud Cover': 'Obscured (Sky not visible due to fog or non-cloud layer)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Observation Date': 'Jan 21, 2023', 'Submission Date': 'Jan 21, 2023', 'Observer type': 'public', 'Observation Summary': 'Rode up towards the Whitefish Divide. Super crusty low snowpack around Polebridge made for difficult temperature management with the sleds. Snow got much better around 5800 ft and downright fun above 6200 ft to our high point at 7000. Intense fog kept us in the trees and ponds below the main east faces. Sidehill tested  some short 40+ degree slopes and saw no signs of instability. New snow on thin 1/19 rime crust was 10-15cm. Another 15cm soft below that. Great traction with the stiff but edgeable base snow.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

280
280
{'location': 'Jenny Lake', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'FAC', 'Activity': 'Snowmobiling/Snowbiking', 'Cloud Cover': 'Not Observed', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': 'Nice day. Calm.', 'Observation Date': 'Jan 21, 2023', 'Submission Date': 'Jan 22, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Triggered long shooting cracks when on landing snowbike at top of short, steep slope. Cracks extended about 100 feet. Small pocket in one corner released about 2 feet deep. Did not see anything else like this during the day.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered  Cracking Observed (isolated)', 'Instability Comments': 'Cracks occurred on a steep, mid elevation slope that was south-southeast.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


281
281
{'location': 'John F. Stevens Canyon', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': '18', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Two - Two days in one. Foggy and calm until ~1430, with cloud bases below 7000 ft. 1430-1500 Clouds abruptly broke up and skies cleared, with light winds at ridge lines. Gusts just strong enough to move some snow.', 'Location': 'NESWNWNESESW', 'Distribution': 'IsolatedSpecificWidespread', 'Sensitivity': 'UnreactiveStubbornReactiveTouchy', 'Size': 'D1D2D3D4D5', 'Observation Date': 'Jan 21, 2023 (9:30 - 17:00)', 'Submission Date': 'Jan 21, 2023', 'Observer type': 'forecaster', 'Observation Summary': '2-10 cm new/ recent snow on MLK crust. Crust supportable at low elevations, making for slick slick skinning and sometimes teeth-chattering exit. At mid elevations, crust occasionally unsupportable, with some hooky turns. Covered enough at upper elevations to make for good, consistent riding. Some soft, drifted snow on leeward slopes at upper elevations, with light blowing snow after 14:30-15:00.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


282
282
{'location': 'Stahl Peek-a-Boo', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Toured up from Stahl Peak to the lookout.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Observation Date': 'Jan 21, 2023', 'Submission Date': 'Jan 22, 2023', 'Observer type': 'public', 'Observation Summary': 'Foggy and cold below about 7100’ after which we emerged into a world which led us to ask “is that sky particularly blue or have we just not seen it for that long?” Snow skied fast and fun.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Our group noted a fairly well-consolidated snow pack as we conducted moving tests along our route. Dug about 200’ below the summit (in the Sun!) for the curious minds in our group and found a thin crust about 16cm down and a firmer one about 40cm down. Moderate force revealed failure on the layer 40cm down.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


283
283
{'location': 'East of WMR', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '15', 'New or Recent Snowfall (cm)': '2 inches', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Observation Date': 'Jan 20, 2023', 'Submission Date': 'Jan 20, 2023', 'Observer type': 'public', 'Observation Summary': 'Toured from WMR and skied multiple trees and open lines facing between east, south and west, 30-40+ degrees. The 1/19 rime crust was covered with 6-10 cm mid density snow (some grauple mixed in) and 10 cm below that there was another breakable rime crust. On a couple steeper convexities we experienced soft sluffing of the upper 10 cm’s. No cracking or or others signs of instability during skinning or skiing. Super fun turns with nice poppy rebound dynamics. Not deep but fun!', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


284
284
{'location': 'Northern Swan', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Route': 'Ascend/descend NW ridge.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '23', 'New or Recent Snowfall (cm)': '4-6"', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Light wind from SW, S-1 at 1200hrs', 'Observation Date': 'Jan 20, 2023 (8:00 - 14:00)', 'Submission Date': 'Jan 20, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'We chased the surprise storm in the Northern Swan Range to check on the new snow and buried surface hoar:\n***We found two layers of buried surface hoar in the top 50 cm of the snowpack in hand/test pits on W, S, and E aspects at middle and upper elevations.\xa0 These layers were adjacent to\xa0 thin crusts.\xa0\n-Small and large column tests failed with medium and heavy force including a propagating result in our South-facing test pit.\xa0\n-Found 4-6" of recent snow atop a rime/freezing rain crust.\xa0 The storm snow seemed well-adhered to the crust below and we noticed no signs of instability.\n-Observed little sign of wind effect in an area that typically funnels SW winds.\xa0 Current winds were light with no blowing snow.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'No obvious signs of instability', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


285
285
{'location': 'Skiumah creek', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': "Up skiumah to 5200'", 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'None', 'Wind Loading': 'None', 'Weather Summary': 'S-1 to NO during day.  L-SW winds.', 'Observation Date': 'Jan 20, 2023', 'Submission Date': 'Jan 20, 2023', 'Observer type': 'public', 'Observation Summary': "Little haggard down low on trail, but I'll take a supportable crust over an unsupportable one.  Guess the Swan took all the precip this week, unless it stacked up at higher elevations in the Flathead.", 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': 'No signs of instability.  Felt like locked in frozen Low danger in terrain observed.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


286
286
{'location': 'Upper Stillwater drainage', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': "Toured up to 5900' on north, northeast aspects of Herrig Mountain.", 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '23', 'New or Recent Snowfall (cm)': '3', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Wind was calm to 5mph from the West, temperatures were low 20s.', 'Observation Date': 'Jan 20, 2023', 'Submission Date': 'Jan 20, 2023', 'Observer type': 'public', 'Observation Summary': "We dug a pit at 5200', north aspect. 110cm hs, CT23 failed on recent crust layer approximately 12cm down. ECTN26 failed on the same layer. This crust layer was quite supportive, we were able to walk on it without skis/boards in many places. Observed a couple small rollerballs in steeper sections > 30deg", 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


287
287
{'location': 'Mt Baldhead', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Skied three bowls along Mt Baldhead ridge.  Rode sleds up the 25mi rd and skinned up the standard route from the switchback above the cabin one day.  The road was easy sledding so kept going out toward the pass and skinned up the next drainage to the south the other two days.  Skied the north-east facing bowls along the ridge, never summited the peak.', 'Observation Date': 'Jan 20, 2023', 'Submission Date': 'Jan 23, 2023', 'Observer type': 'public', 'Observation Summary': 'We felt good about skiing the steeper glades, so got some sluffing on pitches and roller overs.  There was hour long wind event thrusday night, but no signs of windslab formation.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Experienced some sluffing on steep slopes', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

288
288
{'location': 'Shed 7/Snowslip', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Up ridgeline from Shed 7 pullout, past the weather station and down the Shed 7 W shoulder.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '25', 'New or Recent Snowfall (cm)': '2-10cm', 'Rain/Snow Line': "6300' (last Friday/Saturday)", 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': 'S-1 snowfall throughout tour and light winds with little snow transporting.', 'Observation Date': 'Jan 19, 2023', 'Submission Date': 'Jan 19, 2023', 'Observer type': 'public', 'Observation Summary': "Variable recent snow depths observed throughout tour, especially along the wind-affected ridgeline ascent, with slippery crusts exposed or just under the surface making ascending less than lovely. Recent Jan 13 crust is mostly supportable to ~6300' and thins above that, making for hooky skiing. We found buried decomposing surface hoar on sheltered N and NE aspects at 6800' all the way down to 5500' ~20cm below the surface. We began to trigger small roller balls with our turns below 5000'.", 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'No obvious signs of instability observed today. Stomped small very fresh and touchy cornices near the top of Shed 7 W with no meaningful results.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


289
289
{'location': 'East of WMR', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Route': 'more tracks than the WHitefish railyard.', 'Cloud Cover': 'Obscured (Sky not visible due to fog or non-cloud layer)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '4 cm', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Foggy, slightly less foggy, then more foggy. Fog base about 6000 feet in canyon creek at times. S-1 at times. Calm.', 'Location': 'NESWNWNESESW', 'Distribution': 'IsolatedSpecificWidespread', 'Sensitivity': 'UnreactiveStubbornReactiveTouchy', 'Size': 'D1D2D3D4D5', 'Observation Date': 'Jan 19, 2023 (11:30 - 4:00)', 'Submission Date': 'Jan 19, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'We went hunting for recently buried surface hoar or near-surface facets. Did not find them. There are some weak interfaces in the upper ~75 cm of the snowpack but none propagated in tests.\xa0 We were surprised to trigger several sluffs on very steep, north-facing, mid elevation slopes that involved the 4 cm of new snow. These ran surprisingly far and could be a hazard in areas with more snow above the 1/19 rime crust.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


290
290
{'location': 'East Side Swan Range', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'FAC', 'Activity': 'Snowmobiling/Snowbiking', 'Route': 'Headed up Lost Johnny and over to Wounded Buck and back.', 'Cloud Cover': 'Obscured (Sky not visible due to fog or non-cloud layer)', 'Temperature (F)': 'Below Freezing', 'New or Recent Snowfall (cm)': '3', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Unknown', 'Weather Summary': 'We were in a wet cloud with freezing rain almost the entire day. Visibility was less than a 100 yards. Winds calm until the end of the day.', 'Observation Date': 'Jan 18, 2023 (9:00 - 15:30)', 'Submission Date': 'Jan 18, 2023', 'Observer type': 'forecaster', 'Observation Summary': "Today our only goal was to assess the sensitivity and distribution of persistent weak layers in the upper part of the snowpack. We rode into the Swan Range and tried to cover as much ground as possible on snowmobiles. The snowmobile riding was excellent, but the visibility from icing on goggles was atrocious.\xa0\xa0- We dug 4 pits on northerly and easterly aspects between 6000-6550. All snowpit tests propagated. These all failed on a weak layer of buried surface hoar and near-surface facets.\xa0- We were both surprised to see 2ish feet of snow resting on this weak layer in areas protected by the wind. We quickly wrote off all steep terrain. This included terrain sheltered from the wind, which we didn't suspect to be a problem. Surprise!- Our hopes of looking for any recent avalanche activity was squashed by the thick cloud we were stuck in.- A thin freezing rain crust now blankets the surface.", 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'We were on snowmobiles all day so signs of instability were not as obvious as traveling on skis. We had no views of larger avalanche terrain above 6000 feet.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


291
291
{'location': 'Ten Lakes/Stahl Peak', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': "Multi aspect tour in the Northern Whitefish Range from 3600' to 7000'. We skied mainly NW aspects and dug a pit on that same aspect to test the near surface weak layers we found yesterday.", 'Cloud Cover': 'Obscured (Sky not visible due to fog or non-cloud layer)', 'Temperature (F)': '23', 'New or Recent Snowfall (cm)': '5-8"', 'Rain/Snow Line': 'N/A', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': "Temperatures dropped below freezing at all elevations down to at least 3600' at the trailhead. Temp at 3600' at 9am was 33F, Temp at 2:00 at our pit side at 6464' was 23F. Winds were mostly calm throughout the day, occasionally light and variable. The sky was obscured (fog above 5200'). Occasional snow flurries in the morning. A light freezing rain began at 3pm that quickly froze on goggles, gear, and the 1-2mm thick rime crust that is widespread in this zone at mid to upper elevations.", 'Observation Date': 'Jan 18, 2023', 'Submission Date': 'Jan 18, 2023', 'Observer type': 'public', 'Observation Summary': "The temperatures dropped below freezing at the trailhead, which improved the quality of the snow at lower elevations (hardpack is a huge upgrade over breakable crust). The rime we had observed on the surface of the snow yesterday above 5500' had turned into a 1-2 mm thick rime crust today, increasing in thickness with elevation gain.We dug a pit at 6464' on a NW aspect, and did not get propagating results in the weak layers we found yesterday. CT23 RP failed on a weak layer of facets 26 cm under the snow -- the same layer on which we were able to trigger three slides yesterday on a loaded test slope.At around 3:00 pm a freezing rain began to fall. The air temp and snow surface temp at our test pit less than an hour prior was -5C. It quickly froze on the existing rime crust on the surface of the snow, making the surface crust a little more stout. We experienced freezing rain between 5700' and 6800' and between 3:00 and 5:00 when we descended.The snow quality was soft in sheltered areas without the rime/freezing rain crust, and still fairly enjoyable where the crust was present.", 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


292
292
{'location': 'Flathead Range', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Snowmobiling/Snowbiking', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Below Freezing', 'New or Recent Snowfall (cm)': 'Trace-1 Inch', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Periods of strong winds above 6500 feet. Freezing rain up to 6800 feet. Light snowfall on and off throughout the day (S-1).', 'Observation Date': 'Jan 17, 2023 (9:00 - 17:00)', 'Submission Date': 'Jan 17, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Took a tour into the Flathead Range to verify danger rating and look for any buried persistent weak layers.\n- Wind speeds were stronger than expected. Ridge walking above 6500 feet was comical and painful at times due to gust speeds and blowing snow. Observed very small and isolated slabs of drifted snow. These were unreactive to stomping.\xa0\n- Found surface hoar buried just beneath the surface in all hand pits on northerly aspects an up to 7500 ft. There is currently only 3 to 5 inches of snow resting on top of it.\xa0\xa0\n- Recent melt-freeze crust extends to 6800 feet. Below this elevation, the crust is supportable and slick. Crampons are helpful.\nWe chose to ski a steep northwest-facing run given no signs of instability. The skiing was much better than expected, even despite the freezing rain crust that formed throughout the day.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'No signs of instability.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

293
293
{'location': 'Northern Whitefish Range near Eureka', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': "Toured into Ten Lakes to ski a northern aspect and get eyes on the northern Whitefish range for the first time since the fall. Started at 3600' and toured up to 6500'. Great snow above 5200'. A mixture of grabby, icy, and punch crust below that elevation.", 'Cloud Cover': 'Obscured (Sky not visible due to fog or non-cloud layer)', 'Temperature (F)': '27-34', 'New or Recent Snowfall (cm)': '5-8" above 5200\'; not much below', 'Rain/Snow Line': "4800'", 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': "Valley fog lifted in the early afternoon. We were mostly obscured in fog up above 5600', with occasional breaks. Unsurprisingly (it is the Whitefish range) we noted heavy rime on trees and cliffs, which had blown off or accumulated onto the surface of the snow in some locations. Winds were calm with the exception of ridgeline on the top of the pass where they were light and variable. Last night's rain line we estimated at 4800'.", 'Observation Date': 'Jan 17, 2023', 'Submission Date': 'Jan 17, 2023', 'Observer type': 'public', 'Observation Summary': 'We went out hunting in a favorite zone for surface hoar and wind loading, hoping to ski some steep lines. We did not observe any surface hoar during our tour. We did find moderate wind loading. There was no recent snow below 4800\', about an inch of the heavy wet stuff between 4800\' and 5200\', and substantially more above that elevation line -- roughly the 5-8" reported in the rest of the forecast area.Due to cross loading and wind slabs from a westerly wind in our north facing lines, we chose to ski an adjacent slope that was sheltered from the wind, and enjoyed soft snow free of wind slabs. However, snow nerds are curious, so we traversed out onto a loaded test slope below 35 degrees, and were able to intentionally trigger three small, but propagating slides (see photo).Several quick hand pits between 5700\' and 6500\' reacted with some energy on two weak layers, both thin layers of facets, after exerting moderate force. The first layer we found about 20 cm down under a M-F crust at 5700\' on a W aspect. This weak layer was still present at 6500\' on a N aspect, while the M-F crust was not present. The second layer was roughly 35-40 cm down.Given our findings, we\'re hoping to dig tomorrow and assess the propagation propensity of these near-surface weak layers.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


294
294
{'location': 'JFS Canyon Snowslip Mtn', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': '•\tClimbed the Shed 6/7 ridge to the Shed 7 weather station, then continued up to the Snowslip weather station and descended the Shed 9 path.', 'Cloud Cover': 'Not Observed', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': '•\tOvercast or broken skies with very light snowfall and a trace of accumulation throughout the day.•\tLight SW winds above 5500’ elevation.•\tDaytime highs reached the low-30s °F on the Canyon floor and the mid-20s °F above 6000’ elevation.', 'Observation Date': 'Jan 17, 2023', 'Submission Date': 'Jan 17, 2023', 'Observer type': 'public', 'Observation Summary': '•\tA new crust formed after the recent cool down and extends from the Canyon floor (~1/2” thick) up to about 7000’ (high point of the day) where it’s about eggshell thickness.•\tNew snow depths on top of this latest crust were about 1” on the Canyon floor and 2-4” above 6000’ in non-wind loaded locations.•\tNo wind loading until above 6000’ elevation and then this was minimal. Found some new wind slabs (6-10” thick) near ridge crests on easterly and northerly aspects, but these were unreactive with no shooting cracks from ski cuts.•\tBelow 5500’ the snow is moist between the mid-January crust and the late-Dec/Christmas crust below. By ~6000’ the snow between the two crusts was dry with some notable facet layers but could not find any buried surface hoar. •\tDug a hasty pit in the upper reaches of Shed 9 at 6400’ on a SE aspect. Snow depth was about 47”. Extended Column test yielded some ECTNs right below the mid-Jan crust and then ECTP28 on 1-2 mm facets right above the Christmas crust (~22” below the surface, mostly 1F hard snow save for the newest snow on the surface) with the column sliding into the pit. Did a 2nd test and the same layer failed again only with less force, ECTP13. •\tNo recent avalanche activity observed.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': '<br>', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


295
295
{'location': 'Elk Mountain', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Elk/Shields trailhead to Elk Mountain traveling up SW ridge and yo yo on SW/W face.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '-3 C', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Moderate', 'Observation Date': 'Jan 17, 2023', 'Submission Date': 'Jan 17, 2023', 'Observer type': 'public', 'Observation Summary': 'Temperatures at trailhead were right around freezing.  Area toured had temperatures below freezing all day.  The 1/13 crust was very supportable to 6,300 feet.  Above this elevation it was breaking but still evident to 7,350 feet; where it transitioned near the top of Elk Mountain to old wind crust and large rime.   New snow was 1/2 inch below 5,500 feet and about 1 inch up to around 6,200 feet.  Above this it varied from 1 to 6 inches depending on aspect and wind deposition.  Snow was actively being transported above 6,000 feet.  Refer to snow profile but ECT and CT tests were not very reactive and no notable sluffing or cracking was experienced during skiing.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


296
296
{'location': 'South Whitefish Range', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '21', 'New or Recent Snowfall (cm)': '1in', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'The sky was mostly obscured for the day with periods of moderate S-1 snowfall for 2 hours mid-afternoon. Winds were generally calm out of the SW, gusts produced ridge top transport onto leeward slopes.', 'Observation Date': 'Jan 17, 2023', 'Submission Date': 'Jan 17, 2023', 'Observer type': 'public', 'Observation Summary': 'Wind transported snow deposited into soft pillows on NW-SE aspects. These pockets were not reactive on test slopes. Rollerballs from the warming event earlier in the week were observed on all aspects and were nearly covered up by new snow. Loose snow generated impressive amounts of sluff in steep terrain.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


297
297
{'location': 'Essex Mountain', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Up Marion Creek trail, north-facing laps down to Marion Creek, then egress off Essex Mtn. back to Essex Road.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '28', 'New or Recent Snowfall (cm)': '5 cm', 'Rain/Snow Line': '6000 ft', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': 'No precip today and no wind.', 'Observation Date': 'Jan 16, 2023', 'Submission Date': 'Jan 16, 2023', 'Observer type': 'public', 'Observation Summary': 'Snowpack is fairly solid from 50 cm on down.  Looks like top 50 cm could possibly slide but not in our test and we observed no dry or wet avalanches.  Did see quite a few rollerballs from several days ago on several aspects.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'No signs of instability', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

298
298
{'location': 'Rescue Basin', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Up rescue creek to 5640 ft, N aspect.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '33', 'New or Recent Snowfall (cm)': '3 cm', 'Rain/Snow Line': "5000'", 'Snow Available For Transport': 'None', 'Wind Loading': 'None', 'Weather Summary': 'Calm SW winds, s-1 precip, overcast to sparse moments of broken sky', 'Observation Date': 'Jan 16, 2023', 'Submission Date': 'Jan 16, 2023', 'Observer type': 'public', 'Observation Summary': 'ECTN5 down 5cm below 2cm P hard melt/freeze crust on facets.ECTN15 down 20cm on 1cm K hard melt/freeze crust on small facets.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': 'Few wet loose D1 avalanches observed at low to mid elevations. Most activity consisted of rollerballs and pinwheels triggered from falling snow from trees and shedding rocks/steep aspects above 60 degrees.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


299
299
{'location': 'Northern Whitefish Range, east side', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Obscured (Sky not visible due to fog or non-cloud layer)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '2-6 cm', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Valley fog below about 4800-5000 ft. High stratus above. Calm winds, except for a few brief breezes. S-1 snow shower mid afternoon. Temps above freezing except upper elevations.', 'Location': 'NESWNWNESESW', 'Distribution': 'IsolatedSpecificWidespread', 'Sensitivity': 'UnreactiveStubbornReactiveTouchy', 'Size': 'D1D2D3D4D5', 'Observation Date': 'Jan 16, 2023 (9:00 - 16:30)', 'Submission Date': 'Jan 16, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Holiday explore with a trip plan primed with potential excuses - overheating sleds on frozen roads, creek crossing, mushy snow, doghair wildfire regen. Never took one of the excuses, and found decent conditions up high. However, these deteriorated to knee-wrenching mush at low elevations.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


300
300
{'location': 'Lock Peak', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'WMR- Skook Peak and beyond', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': "<32'", 'New or Recent Snowfall (cm)': '15cm', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Light', 'Weather Summary': 'Only light wind observed throughout the tour. WX conditions generally matched the forecast.', 'Observation Date': 'Jan 16, 2023', 'Submission Date': 'Jan 16, 2023', 'Observer type': 'public', 'Observation Summary': 'A generally stable snowpack with kinda poor structure.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'We did see some (15cm thick) slabs breaking on the new crust on steeper test terrain features, and on steep kick turns. The new 15cm slabs that we observed were fist - 4f hardness. No other obvious signs of instability observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


301
301
{'location': 'Central Flathead Range', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Central Flathead Range via Highway 2', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '10cm', 'Rain/Snow Line': '5500', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Dead calm winds. Broken skies, Inversion sandwich, thick valley fog, and mostly cloudy. No new snow during the day. Temps remained cool all day.', 'Observation Date': 'Jan 16, 2023', 'Submission Date': 'Jan 16, 2023', 'Observer type': 'public', 'Observation Summary': "Traveled into the Central Flathead Range to follow up on FAC's report of buried surface hoar and touchy windslabs in the Swan Range. We were curious to see if similar conditions and structure could be found here. Not quite. We targeted a 6800' peak with a moderate angled NE facing slope as a prime candidate for safely assessing these problems. We were underwhelmed by the amount of recent snow in the area and we also found very little evidence of wind affect and wind slab formation. Winds were dead calm on ridgetop today and appear to have been insignificant in the last 24 hours as well. We were also unsuccessful at locating buried surface hoar. In hindsight, we felt that we should have selected a pit site further below the ridgetop to search for SH. So we dug several quick handpits at middle elevations to continue the hunt and they were not revealing any signs of the weak layer FAC found in the Swan. We skied one lap on NE facing and a second lap on West Facing. Both aspects harbored a thin crust below the recent snow, however the windward westerly slope had a slightly thicker crust that was noticeably more firm and icy. We attribute this difference to the NE slope forming its crust due to warm temps, whereas the westerly slope was subject to both warm temps and sun Jan 12-13. Loose dry snow sloughed easily on this west facing slope. Riding conditions were pretty good at upper elevations and crappy/dangerously challenging below 5500'.", 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': "Not a lot of new snow since the Jan 12-13 warm up. Only 10cm or so available for transport at ridgetop (~6800'), but with no wind present to move anything around. No signs of instability observed. Pit test on NE facing upper elevation slope resulted in ECTX.", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


302
302
{'location': 'Whitefish range', 'Zone / Region': 'Whitefish Range', 'Activity': 'Snowmobiling/Snowbiking', 'Route': 'Sleds from Whitefish to 6000’, skied a SW face up to 7000’', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': '5500', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Observation Date': 'Jan 16, 2023', 'Submission Date': 'Jan 16, 2023', 'Observer type': 'public', 'Observation Summary': 'Flat light made it challenging to observe much on the ridge while stumbling over windlips, but the rime on the ridgetop made the first couple of inches of snow there seem to crack and collapse under our skis, but this disappeared quickly below the ridge. The skiing exceeded our expectations and no stability concerns were noted. The upper cloud deck moved around all day, while we stayed above the valley inversion layer. Descending back into it at the end of the day, it was certainly cooler than the morning, with some flakes swirling in the air, whereas the morning was more like sledding through a cool steam room.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'lots of leftover rollerballs from the trees shedding the day before, which were covered with a couple cm’s of fresh that seemed to keep them from turning into frozen death cookies. No current signs of instability were observed.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


303
303
{'location': 'Noisy Basin', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Route': 'Rode sleds to Camp Misery. Skinned to Noisy Basin SNOTEL. Ascending to Aeneas Ridge weather station.', 'Cloud Cover': 'Obscured (Sky not visible due to fog or non-cloud layer)', 'Temperature (F)': '30', 'New or Recent Snowfall (cm)': '4 to 6 inches', 'Rain/Snow Line': '5500 feet', 'Snow Available For Transport': 'None', 'Wind Loading': 'None', 'Weather Summary': 'Unusually calm winds. Visibility was limited most of the day. At our exit, we rode in S-1 conditions for 20 minutes.', 'Observation Date': 'Jan 16, 2023 (9:00 - 17:00)', 'Submission Date': 'Jan 16, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'We went hunting for buried surface hoar in the Swan Range today, but despite digging all day, we did not find that pesky gray line.\xa0\n\nAs we rode up the Jewel Basin Road on sleds, the slush gradually turned to snow about 5500 feet.\nWe dug pits at all three elevation bands, on different aspects, but we did not find a reactive weak layer of buried surface hoar.\nWe did find a knife-hard, 1 cm, melt-freeze crust buried under the recent snow (10 to 15 cm). This crust extends up to 6700 feet.\nMany of the northeast-facing slopes that we could observe in the fog, had evidence of older roller balls and tree bombs.\nThere was evidence of wind-loading and drifting along the Aeneas Ridge, despite having calm conditions all day.\nCornices along the ridge were sagging. We estimated that some chucks of cornices had failed during the warm temperatures on 1/13/23.\nWe suspected that the buried weak layer found 1/15/23 was destroyed by wind in the area we traveled, as we could only find broken pieces of surface hoar, buried 20 to 35 cm below the surface.', 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)', 'Instability Comments': 'Minimal cracking in wind stiffened drifts. We observed that when we stomped on 8-inch cornices, they failed on the recent melt-freeze crust.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

304
304
{'location': 'Sun Shields', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Standard route up, lap on SW aspect, out NE aspect (skiers right trees to gut)', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '+35-40 F', 'New or Recent Snowfall (cm)': '2” up high', 'Rain/Snow Line': '6500’', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Overcast, broken clouds, fog, no wind. Some snow/rain.', 'Observation Date': 'Jan 15, 2023', 'Submission Date': 'Jan 15, 2023', 'Observer type': 'public', 'Observation Summary': 'No negative feedback, snowing on top raining at the bottom. Old pinwheels under fresh snow. Breakable crust starting at 6200’, supportable above to 6900’. Manky. No concerns about stability unless it gets even warmer.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': 'No negative feedback, snowing on top raining at the bottom. Old pinwheels under fresh snow. Breakable crust starting at 6200’, supportable above to 6900’. Manky. No concerns about stability unless it gets even warmer.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


305
305
{'location': 'Lost Johnny', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Obscured (Sky not visible due to fog or non-cloud layer)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '2 inches', 'Rain/Snow Line': '5000 ft', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Rain up to roughly 5000 feet. Snow showers (periods of S1) above 5500 feet.', 'Observation Date': 'Jan 15, 2023 (9:30 - 15:30)', 'Submission Date': 'Jan 15, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Today we went hunting for buried surface hoar and wind slabs in the Swan Range. We found slabs of drifted snow to be "touchy" where they rested on buried surface hoar. I was quite surprised at how sensitive these slabs were.\xa0\n- Triggered two slab avalanches on a leeward-facing ridgeline above 6500 feet. The first slab we triggered would likely be large enough to bury a person. Both slabs were 1 to 2 feet thick. More info in avalanche section.\xa0\n- We descended down the ridge to search for buried surface hoar beneath 6500 feet. We found faceted snow resting on a crust, but no surface hoar. Although we never triggered anything, the snowpack structure and neighboring avalanches were enough avoid steep slopes on north through east aspects.\xa0\n- There were roughly two inches of new snow on a superficial rain crust at middle elevations.\xa0\nThe obvious red flags we observed made many decisions for us. We turned to windward and solar aspects where no buried surface hoar was observed. Here we felt comfortable skiing steep terrain spaced out. At roughly 5700 feet, the crust became unsupportable and we triggered very small wet loose avalanches in the surface snow. The ski quality went in the dumps at around 5500\'. Above that, quality exceeded expectations.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered  Cracking Observed (isolated)  Collapsing Observed (isolated)', 'Instability Comments': "Remotely triggered one slab avalanche on a northeast facing slope at roughly 6700'. Triggered a second slab avalanche with a cornice fall at roughly 6800'. Both avalanche suspect failed on buried surface hoar, which was found on an adjacet slope. We did not access crowns due to overhead cornice hazards.", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


306
306
{'location': 'Terrain surrounding WMR', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Visited various locations in and around WMR.', 'Cloud Cover': 'Obscured (Sky not visible due to fog or non-cloud layer)', 'Temperature (F)': '<32', 'New or Recent Snowfall (cm)': '2 in throughout the day > 6,000 ft', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Moderate', 'Weather Summary': 'Temps remained at or below freezing above 6,000 ft.', 'Observation Date': 'Jan 15, 2023', 'Submission Date': 'Jan 15, 2023', 'Observer type': 'public', 'Observation Summary': 'Observed fresh soft wind slab formation on lee side of non-forested ridge lines. It appears that all steep terrain in the "Skook Chutes" may have produced wet slides in the last 48 hours. Debris is deposited to and across the lower portion of the summer trail (typical skin track from saddle), and the Canyon Crk road (as was previously reported in another observation).', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'No obvious signs of instability noted.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


307
307
{'location': 'Cascadilla', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': "Cascadilla drainage up to 4000'", 'Cloud Cover': 'Not Observed', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': '4500', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Observation Date': 'Jan 14, 2023', 'Submission Date': 'Jan 14, 2023', 'Observer type': 'public', 'Observation Summary': "New wet slide activity from the last 48 hours observed at all aspects in cascadilla up to 5500'. Slides entrained snow entirely above the Xmas crust. Many slides occured directly on top of the large holiday slide paths, but some slides we're observed on faces that did not look to have slid previously. Some slides ran for 1000 or more vertical feet and had large debris run-outs.We experienced about 8 inches of concrete density wet snow on top of mostly crust but some facets were present underneath as well. This thick concrete was present up to 4500' where we turned around and likely extended much higher, it was really warm. We observed a mix of snow and rain from 4000'-4500' and rain below that. It was a light drizzle for most of the day.", 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': 'New small to medium sized wet slides observed at all aspects.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


308
308
{'location': 'Ghoulies', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Out Ghoulies Ridge from Flower Point to do snow assessments then returned to WMR', 'Cloud Cover': 'Obscured (Sky not visible due to fog or non-cloud layer)', 'Temperature (F)': '-2', 'New or Recent Snowfall (cm)': 'Trace - 2"', 'Rain/Snow Line': "5500'", 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Calm winds today and light snowfall between 2 and 4pm.', 'Observation Date': 'Jan 14, 2023', 'Submission Date': 'Jan 14, 2023', 'Observer type': 'public', 'Observation Summary': 'Calm socked in day out in Ghoulies with quite a few folks out for a rip off the ridge!', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': "No obvious signs of instability observed today, but looking for avalanches wasn't easy with consistent obscured skies and thick fog above 5500' today.", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


309
309
{'location': 'Upper Road/Skook Chutes', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Observation Date': 'Jan 14, 2023', 'Submission Date': 'Jan 14, 2023', 'Observer type': 'public', 'Observation Summary': 'News of wet loose slides definitely reduced use. High elevation in canyon was decent, got heavy and wet near lower elevation.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


310
310
{'location': 'Wounded Buck', 'Zone / Region': 'Swan Range', 'Activity': 'Snowmobiling/Snowbiking', 'Route': 'Took Wounded Buck Road up to "Y" that splits off to the trailhead. Continues left to an opening. Got a report from the public of avalanche debris above our turnaround.', 'Cloud Cover': 'Not Observed', 'Temperature (F)': '35', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Low', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Observation Date': 'Jan 14, 2023', 'Submission Date': 'Jan 14, 2023', 'Observer type': 'public', 'Observation Summary': 'Did a column test northerly slope. Ct of 16 that split across the column at approx 120 cm. Sheer test broke off clean at 100 cm with moderate pulling.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

311
311
{'location': 'Dickey', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Jan 14, 2023', 'Submission Date': 'Jan 14, 2023', 'Observer type': 'public', 'Observation Summary': 'Rain gave way to snow around 5500” and started accumulating above this. About 5 cm of new snow sitting on top of the newest crust at 6900’. Dug one pit on south aspect at 6700’. Depth of 185 cm. On this aspect the crust layer and below is quite uniform and stout! No propagation, but with shovel sheer there was a notable failed 20 cm from surface. Some mild wind, but nevertheless cornices rebuilding and cracking. Saw recent wet slides and plenty of partially re frozen roller balls. Certainly felt winter like above 6k!', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


312
312
{'location': 'Canyon Creek', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Skook face to Eastern border of Skook chutes.', 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': '35?', 'New or Recent Snowfall (cm)': '2', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'None', 'Wind Loading': 'None', 'Weather Summary': 'Party sunny, no wind below the ridges, and above freezing temps.', 'Observation Date': 'Jan 13, 2023', 'Submission Date': 'Jan 13, 2023', 'Observer type': 'public', 'Observation Summary': 'Lots of pinwheels. Loose wet avalanche in Skook chutes that ran to the canyon. Deposited four feet of debris on the upper road.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': 'Hot pow with lots of pinwheels.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


313
313
{'location': 'Strawberry fields for the day', 'Zone / Region': 'Swan Range', 'Activity': 'Skiing/Snowboarding', 'Route': '5390 + 5', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '36', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': '9000', 'Snow Available For Transport': 'None', 'Wind Loading': 'None', 'Weather Summary': 'Looked like March, skiied like April.', 'Observation Date': 'Jan 13, 2023', 'Submission Date': 'Jan 13, 2023', 'Observer type': 'public', 'Observation Summary': 'Above freezing temps all morning combined with mostly cloudy skies turned the atmosphere in a greenhouse.  Easy to make large truck tire sized pinwheels with the toss of a snowball.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Easily could have triggered wet loose slides on open exposed terrain. Rolling baseball sized snowballs off the side of the trail told me all I needed to know..', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


314
314
{'location': 'Southern Whitefish Range', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '32', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': "6000'", 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Warm and humid conditions this morning continued through the afternoon. Fortunately, a thick layer of high clouds limited solar radiation.', 'Observation Date': 'Jan 13, 2023', 'Submission Date': 'Jan 13, 2023', 'Observer type': 'forecaster', 'Observation Summary': "I visited a windy location in the southern Whitefish Range to get a handle on recent wind slab distribution and reactivity. I was also interested in seeing how the former cool, dry snow surface was being affected by overnight warming.\n\nSoutherly winds had drifted recent snow into slabs up to 1 foot thick on northerly slopes. The slabs were generally small, cohesionless, and unreactive to a skier's weight.\nNew cornice growth cracked and failed from the weight of a skier. The new lip was soft, and cracks would travel no further than the length of my skis.\nOvernight warming initiated tree bombs, rollerballs, and two thin Wet, Loose slides. Moist snow extended to ridgeline elevation (up to 6700') on all aspects.\nIt was easy to trigger rollerballs on steep slopes, but none of these initiated a Wet Loose slide.\xa0\nA snowpit at 6650' was dug down to the Christmas Atmospheric River rain crust. See the snowpack section for more details.", 'SIGNS OF INSTABILITY': 'Avalanches Observed  Cracking Observed (isolated)', 'Instability Comments': 'The recent warming triggered two thin wet loose slides in the south-facing Skook Chutes and extensive rollerball activity on all aspects at mid-elevations.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


315
315
{'location': 'Essex: Marion Lake area', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Route': 'Summer trail to Marion Lake to Repeater Ridge.', 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': 'Above freezing', 'New or Recent Snowfall (cm)': 'N/A', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'None', 'Wind Loading': 'None', 'Weather Summary': 'Periods of sunshine with scattered clouds for most of the day. Dark clouds loomed South of our location.', 'Observation Date': 'Jan 13, 2023 (9:30 - 16:00)', 'Submission Date': 'Jan 13, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'We went to slopes above Marion Lake today in search of surface snow conditions and to look for evidence of wind-affected snow.\n\nIt felt like a day in April and not mid-January. Snow was wet and transitioned to moist around 5000 feet.\nThe winds were calm most of the day with only a few wind gusts.\nThe sunshine brought fresh roller balls on both northerly and southerly aspects.\nWe skied slopes that had already been warmed with above-freezing temperatures, experiencing heavy, mash-potato quality turns.\nIn the area that we traveled, the trees were free of snow.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': 'Roller balls observed on all aspects. Trees were clear of snow, with evidence of widespread tree bombs.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


316
316
{'location': 'Snowslip', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Route': 'Ascend southerly aspect to ridge.  Traverse ridge to the west. Descend easterly slide path.', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '28', 'New or Recent Snowfall (cm)': '1 inch', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'S-1 started at 1100', 'Observation Date': 'Jan 12, 2023 (9:30 - 13:30)', 'Submission Date': 'Jan 12, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Teamed up with USGS on a visit to Snowslip:\n-Found a variety of surfaces on the ascent including: breakable sun crust, supportable rain crust, dry faceted snow and wind abused surface hoar.\n-Winds were variable, gusty, and sufficient enough to drift what little loose snow was available.\n-We found isolated pockets of wind drifted snow on Easterly aspects. Generally these were not cohesive enough to produce any cracking.\xa0\nBecause we anticipated potential wind loading at the top of our descent, we chose to ski one at a time as we navigated the entrance to the line.\xa0 After regrouping, we skied the remainder of the line, spacing ourselves out at an interval of roughly 10 seconds.. The skiing on shelterred terrain was much better than anticipated.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'No obvious signs of instability', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


317
317
{'location': 'Sixmile', 'Zone / Region': 'Swan Range', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Not Observed', 'Weather Summary': 'Flurries to light snow for a couple hours starting about 1030 with clearing skies and much better visibility by 1600.', 'Observation Date': 'Jan 12, 2023', 'Submission Date': 'Jan 13, 2023', 'Observer type': 'public', 'Observation Summary': 'Overall fun lower angle turns to be had above 6000 ft on west to east slopes esp. on more sheltered terrain with an icy luge exit. Very thin sun crust on more open south slopes observed on the way up. Moderate winds with high gusts from the west on the ridge transporting the 8+ new inches from Sunday. Ridge line scoured and rimey.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

318
318
{'location': 'Not So Tranquil Basin', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': "Windy multi-aspect tour up to 7600'. We chose to ski a western face to try to avoid our wind slab problem. Great surface snow above 6000' -- snow changed to rain below this elevation in the late afternoon. Swirling winds, blowing snow, and (below 6000') a snowpack that was saturated with small amounts of rain caused instability to rise throughout the day.", 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '27-34', 'New or Recent Snowfall (cm)': '1"', 'Rain/Snow Line': "Rising to 6000'", 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': 'Our weather forecast of "30% chance of everything" delivered and then some. At 1100 hrs at the trailhead at 4200\' it was 27 degrees F with S-1 precip. By 1700 hrs at the same location it was 34 degrees and raining (or "heavily misting"). The cloud cover ranged from broken to overcast to obscured. The snow was on and off throughout our tour and briefly increased to a maximum of around S2 in the early afternoon. By 1530-1600 hrs, the snowfall at our elevation on ridgeline at about 7600\' mixed with wind-driven frozen pellets.The wind and blowing snow was the main story of the day (until we discovered it had rained below 6000\'). It seemed to change slightly from the SW to W at ridgeline throughout the day, consistently moderate gusting to strong as large trees were swaying. However, ascending an east aspect on a southern drainage we noticed that the wind was funneling from the S through the drainage, and swirling at us from the E. We imagine this terrain-enhanced wind swirling occurred in drainages and canyons throughout the area, and would expect to find wind loading in unusual spots, and crossroading near the tops of gullies outside of the normal places to find wind loading with a SW-W wind.', 'Observation Date': 'Jan 12, 2023', 'Submission Date': 'Jan 12, 2023', 'Observer type': 'public', 'Observation Summary': "Went out in the wind and surprisingly stormy weather for a multi-aspect tour up to 7600'. We had multiple ascent/descent options we had discussed, and ended up choosing to ascend and descend a western face after observing moderate to strong W and SW winds transporting snow at ridgeline, as to avoid being on wind loaded slopes in low visibility. Minus the couple hundred feet of wind-scoured-death-ridges down from the summit we were rewarded in our decision making with a long run of great soft surface snow mostly free of wind loading. As the rain line rose to 6000' by 1700 hrs, we observed widespread rollerballs and rising instability as water has been added to our unconsolidated top layer.We observed blowing snow in addition to a small amount of new snowfall throughout the day. While the blowing snow occurring at ridgeline was SW-W, we observed snow being transported by the S to E wind funneling through our drainage. We estimate yesterday's snow available to transport at up to a foot.Due to the wind and time we did not dig a pit today. My partner did note widespread surface hoar on all aspects in the same drainage yesterday. By this afternoon, however, surface hoar only existed on the snow's surface in isolated sheltered areas -- either knocked over by the swirling winds or buried under new/blowing snow. We found an isolated, thin (1mm or less) sun crust around 7000' on a SSW aspect. During our exit from the drainage around 1630 hrs, we noticed glopping on our skis (around 6000'). We were initially befuddled until we looked up and realized that the wind-driven snow had changed to wind-driven rain. We made haste and traveled one at a time through steeper terrain to limit the hazard as the risk for wet loose avalanches rapidly increased. It was a little spooky to be skiing down while rollerballs ran naturally past you. A great ski day, but with a lot going on!", 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'The wind was swirling and being funneled through drainages and terrain features, therefore we expect canyons, creeks, and gullies below ridgeline to have wind slabs and crossloading in unusual areas. We avoided wind loaded slopes on our tour and did not have the opportunity to test the reactivity of any newly formed slabs. My partner had toured in the same drainage the day prior (before today\'s wind event) and noted up to a foot of available snow for transport up high, most of it being faceted "recycled pow." We did not experience cracking, collapsing, or whumpfing.<br><br>By 1700 hrs rain had fallen at up to 6000\'. Rollerballs were happening naturally and were widespread on steeper slopes below 6000\'. I would expect wet loose avalanches ran naturally in areas collecting the most rainfall. We did not dally long enough to take photos of the widespread rollerballs.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


319
319
{'location': 'Southern Flathead Range', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': "Toured to 7200' on east aspect", 'Observation Date': 'Jan 11, 2023', 'Submission Date': 'Jan 12, 2023', 'Observer type': 'public', 'Observation Summary': 'North and east facing snow was faceted and cohesionless with surface hoar on top. Multiple small loose dry avalanches in steep terrain that ran fast. Making sure riders were in safe zones and not stopping in on top of one another was critical.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


320
320
{'location': 'Snowslip', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Toured up the south west slop to top of snowslip', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Light', 'Weather Summary': 'Light winds. Not much of any snow moving around.', 'Observation Date': 'Jan 11, 2023', 'Submission Date': 'Jan 11, 2023', 'Observer type': 'public', 'Observation Summary': 'Snow seemed solid.  Skiing was better than expected as skinning was a struggle guessing due to so much hoar frost.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'No signs', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


321
321
{'location': 'Wildcat', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'FAC', 'Activity': 'Snowmobiling/Snowbiking', 'Observation Date': 'Jan 11, 2023', 'Submission Date': 'Jan 12, 2023', 'Observer type': 'forecaster', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


322
322
{'location': 'Skiumah Lake', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'On Wednesday we reached approx 7200 on a steep protected N-NE aspect. Thursday we reached 6000 on a similar aspect.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': '1/11: no notable weather. Slightly foggy, no sun after the morning1/12: a dusting of new snow. The wind appeared to be swirling around the drainage, had a hard time pin pointing a specific wind direction. NE aspects were actively loading.', 'Observation Date': 'Jan 11, 2023', 'Submission Date': 'Jan 13, 2023', 'Observer type': 'public', 'Observation Summary': 'Went up Skiumah 2 days in a row. Wednesday the riding was great with small pockets of wind slabs on unsheltered NE aspects. Found the supportable Christmas crust underneath the powder up to the top of our line at 7200 feet. Toured up again on Thursday with the plan to drop into the Great Bear creek drainage, but vis was bad and the wind was blowing every direction, so we stuck to sheltered terrain in Skiumah.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Cracking Observed (isolated)', 'Instability Comments': 'Windslabs varying from 2-6” deep with varying levels of reactivity', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

323
323
{'location': 'Cascadilla', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '30-35', 'New or Recent Snowfall (cm)': '3-5”', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Light', 'Observation Date': 'Jan 10, 2023', 'Submission Date': 'Jan 11, 2023', 'Observer type': 'public', 'Observation Summary': 'Rollerballs, large ones, and wet loose avalanches', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Cracking Observed (isolated)', 'Instability Comments': 'Witnessed warming snow beginning to produce large numbers of big rollerballs, and small shooting cracks and slabs forming while creating a skin track on a S/SE facing aspect, saw appx 5 (D2) slides on a high elevation E/NE facing aspect', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


324
324
{'location': 'Essex', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': "Toured to 7200'", 'Observation Date': 'Jan 10, 2023', 'Submission Date': 'Jan 10, 2023', 'Observer type': 'public', 'Observation Summary': "Toured to 7200' hoping to ski a steep alpine SE face higher up. We found it wind-loaded and baking in the sun so we decided to ski a Windward NE aspect. ECTX at 7000' on NE aspect. There was a thin crust above the stout rain crust. Significant sluffing on steep NE aspects made sluff management critical.", 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


325
325
{'location': 'Southern Whitefish Range', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '3 inches', 'Rain/Snow Line': "5500'", 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': 'In an out of the cloud throughout the day. Felt rain on us at roughly 5800 feet for a brief moment.', 'Observation Date': 'Jan 10, 2023 (11:00 - 15:00)', 'Submission Date': 'Jan 10, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Today we investigated a crown of a reported avalanche in the Southern Whitefish Range. See the avalanche section for more information.\n- We found 3 to 5 inches of new snow overnight. This refreshed surfaces and skied quite well.\n- Observed one very small loose dry sluff from steep rocky terrain.\xa0\n- Snow above the December Rain Crust is faceted and weak in sheltered terrain at middle elevations. No signs of cracking or collapsing.\n- Our travels only took us into terrain sheltered from the wind.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


326
326
{'location': 'Southern Flathead Range', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Essex Area', 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '1.5 inches', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': "Winds were calm to light during most of our tour. However, winds were light to moderate out of the SSW on the last 200 feet to our days highpoint (7900'). We were up top at noon. Between 7000' and 7900', west facing slopes were significantly rimed, inhibiting windloading. We enjoyed another day of sunny skies until mid afternoon. By about 2pm skies transitioned to overcast and light flurries began around 530 during the drive home. Temps were cool, but ample sunshine was impacting solar aspects at mid elevations.", 'Observation Date': 'Jan 9, 2023', 'Submission Date': 'Jan 9, 2023', 'Observer type': 'public', 'Observation Summary': "Another good day out in the mountains. Evidence of strong winds last night at all elevations. This unfortunately negatively impacted riding conditions in areas open to the wind. But, on the plus side, there was not significant new snowfall in our drainage last night so fresh windslabs were thin/non-existent at upper elevations. We didn't encounter any windslabs worth noting during our ski off ridgetop onto a ENE slope.", 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': "No recent instability observed. One glide crack found on an east facing slope around 6000'. Most of the major SE facing paths in lower essex creek had cycled during the Santa Soaker. At least two went big and reached the creek bottom. The northwest facing paths on showshed seem to have been quieter during the cycle.", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


327
327
{'location': 'Werner Peak', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'FAC', 'Activity': 'Snowmobiling/Snowbiking', 'Route': 'Rode sleds up to and around Werner Lookout.', 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': 'Below Freezing', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Clear skies became broken after noon. Partly cloudy for the remainder of day. Late morning sun was warm.', 'Observation Date': 'Jan 9, 2023 (10:30 - 14:30)', 'Submission Date': 'Jan 9, 2023', 'Observer type': 'forecaster', 'Observation Summary': "Today we went into the Whitefish Range to hunt persistent weak layers and explore some less frequented ground for us.\xa0\n- Overall observed a shallower snowpack (120-130 cm) than seen throughout the rest of the forecast area. This average was from a couple different probes between 6500 to 6700.\xa0\n- Found pockets of recently formed winds labs. Slabs were 4 to 6 inches thick and relatively firm. These were stubborn to trigger.\xa0\n- Basal snowpack structure is poor. 3 to 5 mm depth hoar with obvious evidence of rounding.\xa0\n- We got propagating pit results on large column tests failing on the Christmas crust.\xa0\nThis is the poorest snowpack structure we've found throughout the forecast area. And shallowest. I would currently be making a lot different decisions if the impenetrable rain crust didn't exist.", 'SIGNS OF INSTABILITY': 'Cracking Observed (isolated)', 'Instability Comments': 'Isolated cracking in snow drifted by wind.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


328
328
{'location': 'Cliffs east of half moon outside WMR boundary', 'Zone / Region': 'Whitefish Range', 'Activity': 'Other', 'Cloud Cover': 'Few (Mostly Clear, up to 2/8 covered)', 'Temperature (F)': '24', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Observation Date': 'Jan 9, 2023', 'Submission Date': 'Jan 9, 2023', 'Observer type': 'public', 'Observation Summary': 'Recent avalanche activity', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


329
329
{'location': 'Mt. Penrose', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Rescue Creek to South face of Penrose', 'Cloud Cover': 'Few (Mostly Clear, up to 2/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Trace', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': "Cleared up around 10:30 then high clouds moved in for the afternoon. Winds above 6500' were SW 5-10", 'Observation Date': 'Jan 9, 2023', 'Submission Date': 'Jan 9, 2023', 'Observer type': 'public', 'Observation Summary': 'On the hike up Rescue Cr. trace amounts of new snow were blown off of melt-freeze crusts into small drifts and the skin track.  Afternoon cloud cover kept the solar intensity down. Variable conditions up high on exposed areas with rime and sun crusts. The sheltered skiing was great!', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


330
330
{'location': 'Essex area', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Route': 'Mostly traveled on N-E-S facing slopes at low and mid elevations.', 'Cloud Cover': 'Few (Mostly Clear, up to 2/8 covered)', 'Temperature (F)': '26', 'New or Recent Snowfall (cm)': '1 cm', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': 'T-1 cm new snow, rimed or graupel. Clear/ few skies in AM, with increasing clouds early afternoon. High overcast by mid afternoon. Winds last night/ early AM left pine needles and other debris on the snow surface. Almost no wind today, however.', 'Observation Date': 'Jan 9, 2023 (9:30 - 2:30)', 'Submission Date': 'Jan 9, 2023', 'Observer type': 'forecaster', 'Observation Summary': 'Day off ski. Mostly found dry snow with no surface crust, no signs of instability except a wee sluff on one turn, and good views. We stayed on sheltered slopes below 6800 feet to avoid any freshly formed wind slabs or freshly imposed wind effects on the surface snow.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

331
331
{'location': 'Mt Penrose', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'From Rescue Creek trail, skinned up to SE saddle of Penrose to the summit. Skied the E face chute back down.', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'N/O', 'New or Recent Snowfall (cm)': 'None', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Clear and sunny day turned to OVC by about 2pm. Good visibility entire day. Temps were moderate and winds were light.', 'Observation Date': 'Jan 9, 2023', 'Submission Date': 'Jan 12, 2023', 'Observer type': 'public', 'Observation Summary': 'Evidence of a melt freeze crust lower in the Penrose bowl (observed up to ~5500ft). No wind slab or scouring was evident until about 6800ft up the ridge and what had formed was very thin. The line we skied on the E face had well preserved light and dry snow that easily sluffed while skiing. As we skied lower we hit the MF crust in patches but did not affect quality of turns. Good day out!', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'No signs of instability observed. Would be curious about facet growth/weak layers forming near Xmas rain crust through time.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


332
332
{'location': 'Dickey creek', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Observation Date': 'Jan 8, 2023', 'Submission Date': 'Jan 8, 2023', 'Observer type': 'public', 'Observation Summary': 'Thin sun crust on exposed south aspects.  Noted thick crust throughout ascent by pole strike at about 5 inches below soft snow.  Evidence at approximately 6300 ft of small roller balls with only one small propagation, likely occurred yesterday.  No roller balls noted above this and none new today as it did not warm enough by the time we exited the south aspect.  The riding quality was excellent until about 4500 feet where it turned to heavy snow on a stout crust.  Did note several small loose dry sluffs in steep upper terrain, did not run far', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'One member of our group reported finding a glide crack that looked like it opened with the rain event, some new snow covering.  Notes on NE/E aspect at approx 6300 ft. We steered well clear of this.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


333
333
{'location': 'Dickey Creek', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Climbed Skiers right of Marian Creek. About .3 miles from Marion Lake, climbed to northern ridge via established skin track. Descended NE Aspect Ridge to Dickey Creek Road', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Moderate', 'Observation Date': 'Jan 8, 2023', 'Submission Date': 'Jan 8, 2023', 'Observer type': 'public', 'Observation Summary': 'Dug pit on NE aspect of slope in Dickey Creek drainage.  Compression test showed no signs of instability. Crust later was well established.  Identified a 50 yard length glide crack upon descent. Appeared to be from rain cycle with new snow accumulation from recent storm cycle. Navigated to a new route clear of avalanche path below crack.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Glide Crack about 6000 to 6500 feet down NW aspect', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


334
334
{'location': 'Furlong', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'Below freezing', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Moderate Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'Just as we began to discuss the solar impact (started to see small tree bombs lead to small roller balls) on a E facing slope in the AM the clouds and wind rolled in and the heater turned off. We observed swirling moderate- strong wind gusts transporting snow at and near ridgelines. These gusts were inconsistent.', 'Observation Date': 'Jan 8, 2023', 'Submission Date': 'Jan 8, 2023', 'Observer type': 'public', 'Observation Summary': 'A generally stable snowpack that matches a recent obs and forecasts.We poked around in steeper rocky terrain above 6800ft. Locations adjacent to rocks in steep terrain did not harbor the Christmas crust and the snowpack is weak, thin, and faceted.We spent extra time discussing our mindset pre tour and throughout our tour we discussed how conditions matched the forecast. We felt confident “stepping out” a bit more as we explored steeper terrain today.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'No signs of instability observed. <br><br>Some loose, cohesiveness snow moved on steeper slopes. It was isolated and non threatening to skiers.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


335
335
{'location': 'Grant Ridge', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Jan 8, 2023', 'Submission Date': 'Jan 8, 2023', 'Observer type': 'public', 'Observation Summary': 'Some may say that the Middle Fork isn’t consistent. The sun was out today, which was confusing. Danger was Low, which seems atypical for early January. Yet despite those wildcards, we still got to schwack up 2000ft feet of crust covered logs and boosh before the snow got better, so it felt just like normal. Nothing much to report on the stability front. Some wind affect up high on E and NE aspects. More sheltered, flatter S aspects were fully slush at the surface around 6k ft, so there’s another crust in the making. Sky was either clear or overcast; no precip; winds were light to moderate on ridge tops.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


336
336
{'location': 'Flathead Range', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Central Flathead Range', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Filtered sunshine until about 1pm. Skies gradually became overcast later in the afternoon with very light snowfall starting around 230pm. Light winds with a few moderate gusts from the southwest during the day.', 'Observation Date': 'Jan 8, 2023', 'Submission Date': 'Jan 8, 2023', 'Observer type': 'public', 'Observation Summary': 'Another nice day to be out. Skied polar aspects up to 40 degrees without signs of instability.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': "Good stability today. Noted some tree plop triggered wet loose on a steep east facing slope @ 6200'. Appeared to have occurred yesterday. The glide on great northern has not increased in size since last obs from Jan 2nd, however bedsurface is now covered by blown in snow.", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


337
337
{'location': 'Skiumah Creek', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Went right up the gut of Skiumah, summited the ridge at the back of the drainage, just above the observation location at 7000 feet.', 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Light', 'Weather Summary': 'Beautiful sunny day with great views all around. Clouds built around 2:30 and very light snow fell from 3:30 to 5:00', 'Observation Date': 'Jan 8, 2023', 'Submission Date': 'Jan 8, 2023', 'Observer type': 'public', 'Observation Summary': 'Variable crust and faceting surface snow at all elevations from the valley to the ridge. Shady areas had drier faceting snow which was great riding. The snow was not as dry and sugary as the earlier season depth hoar we observed. More sun exposed slopes had a thin crust at the surface, approx 0.5 cm thick in most areas where presentAt our NE aspect there was minimal wind loading and minor cornice growth.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'No instability observed.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

338
338
{'location': 'Middle Fork corridor', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Big North facing steeps', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '30', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Moderate', 'Weather Summary': 'Not the best visibility to ski steep North facing slopes, but good enough. Light winds both days with light flurries closing in by the end of the day Sunday.', 'Observation Date': 'Jan 8, 2023', 'Submission Date': 'Jan 9, 2023', 'Observer type': 'public', 'Observation Summary': 'Lots of skers out and about. Met multiple parties skiing in drainages for first time.Skied steep N facing aspects up to 7800 feet on Saturday and Sunday. Trail breaking was easy even on steep terrain. West winds were depositing snow on East facing slopes most of the day Sunday. New drifts were still soft .', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Saw a few old crowns and glide cracks on various slopes above 6 grand', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


339
339
{'location': 'Rescue Creek', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Toured up Rescue Creek to the saddle between Pinrose and Nayak.', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '21', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': '0', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Moderate', 'Weather Summary': 'Broken skies, little to no wind. Overall snow felt stable. Signs of an incoming but delivered nothing, and skies cleared again.', 'Observation Date': 'Jan 8, 2023', 'Submission Date': 'Jan 9, 2023', 'Observer type': 'public', 'Observation Summary': 'Between 6000-6400 ft, shaded snow was soft and loose. Small loose sluffs observed in this zone. From 6000 ft to about 5400 ft there was a significant rime crust at the surface with soft somewhat sugary snow below. The rime crust was easy to punch through. The buried freeze crust seemed solid. From about 5800 ft to roughly 5600 ft the rime crust became very hard and icy. Signs of wind blown snow all over the drainage. Some of that wind blown texturing occurred in the rime/frozen crusts. Overall snow felt stable.', 'SIGNS OF INSTABILITY': 'Collapsing Observed (isolated)', 'Instability Comments': 'Shooting crack in the surface rime/newer snow at about 5400 ft (North aspect - 33 degree slope angle). Crack propagated roughly 40 ft. and was confined above the freeze crust.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


340
340
{'location': 'Skiuma Creek', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': 'Up skiuma creek proper', 'Cloud Cover': 'Scattered (Partly Cloudy,\xa03/8 to 4/8 covered)', 'Temperature (F)': '26', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': '7,000', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': 'started the day under clear cool skies in the teens, around 1 pm dark clouds moved in. Mild to moderate winds out of the south/southwest 5-10MPH', 'Observation Date': 'Jan 8, 2023', 'Submission Date': 'Jan 9, 2023', 'Observer type': 'public', 'Observation Summary': 'beautiful views', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


341
341
{'location': 'Great Northern Powder Guides', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'All over our ski terrain the past few days', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '0 to -4', 'New or Recent Snowfall (cm)': 'trace', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'None', 'Weather Summary': 'warm', 'Observation Date': 'Jan 8, 2023', 'Submission Date': 'Jan 12, 2023', 'Observer type': 'public', 'Observation Summary': 'a stable snowpackmultiple CTN scores in various locations within our terrain', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Really a very stable snowpack overall!<br>Some minor "slow" sloughing in steeper (30-40 degree) northern aspect slopes.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


342
342
{'location': 'North Face Penrose', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Jan 7, 2023', 'Submission Date': 'Jan 7, 2023', 'Observer type': 'public', 'Observation Summary': 'Decided to make a go at the north face of Penrose, thinking it might be a good time.  We hoped the crust would see us through, but ended up in knee deep, drifted snow above the Kristmas Krust around 5800ft and bailed for less complex terrain and flatter angles. Lots of evidence of wind affect and plenty of formerly wet debris making for frozen obstacles at middle elevations. We broke a very small pane while skinning up a windloaded gully later in the day. Sheltered terrain held the best skiing. Sky was partly cloudy, with light winds all day. No precip, and either around or below freezing temperature wise.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


343
343
{'location': 'Diamond Peak', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Skied the northwest face of Diamond peak through the main gut', 'Observation Date': 'Jan 7, 2023', 'Submission Date': 'Jan 7, 2023', 'Observer type': 'public', 'Observation Summary': 'D3 wet slide 2000’ path length. From Christmas. Took down full sized trees. Stretched  almost to valley floor', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


344
344
{'location': 'Essex area', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Jan 7, 2023', 'Submission Date': 'Jan 8, 2023', 'Observer type': 'public', 'Observation Summary': "Our party skied between Essex and the Continental Divide today, on the S side of the highway. We found about 5 cm of this week's new snow along the road, and toured up to 7700'. We found the rain crust at 6400' but didn't try to look for it any higher. Skied glorious soft and smooth snow on a West face. Despite the sunshine the day felt cooler than expected given the light but fairly consistent breeze- never strong enough to transport snow. Surprised by how well preserved this week's snow was, even up high. At the end of the day there were rollerballs from trees shedding, around 6200' and below. I imagine lower S and W faces will have a crust tomorrow after the warmup... before it warms up again.", 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


345
345
{'location': 'Tunnel Creek', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Route': "Up Tunnel Creek to 5400'", 'Cloud Cover': 'Few (Mostly Clear, up to 2/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Observation Date': 'Jan 7, 2023', 'Submission Date': 'Jan 7, 2023', 'Observer type': 'public', 'Observation Summary': 'Lower East slopes of Grant were pretty blown out by the soaker cycle.', 'SIGNS OF INSTABILITY': 'Avalanches Observed', 'Instability Comments': "Roller balls and a small D2 slide observed on a south facing solar aspect at 5500' around noon.", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


346
346
{'location': 'Big Slide', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'WMR to Big slide to Haskill Basin road', 'Cloud Cover': 'Clear (No clouds)', 'Temperature (F)': 'To warm', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': 'Sunny', 'Observation Date': 'Jan 7, 2023', 'Submission Date': 'Jan 7, 2023', 'Observer type': 'public', 'Observation Summary': 'Dreamy, creamy turns. Then endless rollerballs and pinwheels. Real wet and sticky snow continued til approx. 4000ft', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': '11:45 am witnessed a waterfall of rollerballs and pinwheels on the east side of the face, skiers left', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

347
347
{'location': 'Skook shoot not chute', 'Zone / Region': 'Other', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Few (Mostly Clear, up to 2/8 covered)', 'Temperature (F)': 'N/o', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Observation Date': 'Jan 7, 2023', 'Submission Date': 'Jan 7, 2023', 'Observer type': 'public', 'Observation Summary': "Headed up aiming to flirt with the edge of the first skook chute. Quick assessment at 5950' on a SE aspect on 25 degree slope found 160 cm HS and about 40 cm down was the very very stout Christmas crust. Pulled off column at that layer in the shovel sheer and CT27 RP in column test. It was right at noon and light fluff upper snow was fairly unaffected by sun. First time on this side and too early and ended up in elkweed instead of the first chute but okay.", 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


348
348
{'location': 'Tunnel creek', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Jan 7, 2023', 'Submission Date': 'Jan 7, 2023', 'Observer type': 'public', 'Observation Summary': 'Spent the day in the alpine above tunnel. While in rescue yesterday we found multiple breakable crusts in the surface snow but none of this was present here. We did find some wind board on exposed saddles and occasional moderate wind with some transport. Though the majority of east and north slopes are still skiing very well. The ice crust seems to be harder to find above 6k. No surface hoar seen. Impressive seeing the recent wet slide debris. We did not witness any point releases or wet slide.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


349
349
{'location': 'Spider bowl', 'Zone / Region': 'Swan Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Road and trail/some ridge walking', 'Cloud Cover': 'Few (Mostly Clear, up to 2/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Not Observed', 'Weather Summary': 'Below freezing ambient temp until mid morning with a slight inversion.', 'Observation Date': 'Jan 7, 2023', 'Submission Date': 'Jan 7, 2023', 'Observer type': 'public', 'Observation Summary': 'Serious short wave radiation going on until some thin clouds stopped/slowed the tree drippings at mid elevations. Open south facing slopes were getting moist but not too sticky by around 12 pm..  I guess Al Gore was right.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Harder to find than a parking spot in Larch lot', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


350
350
{'location': 'Tunnel Ridge', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Few (Mostly Clear, up to 2/8 covered)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Mostly sunny, calm to light winds.', 'Observation Date': 'Jan 7, 2023', 'Submission Date': 'Jan 7, 2023', 'Observer type': 'public', 'Observation Summary': "Sunshine and calm to light winds made for a great day to get up high. Late Dec. crust was about 35 cm down, 2-3 cm thick, and pencil hard at my high point at about 7500'. Minimal, spotty surface hoar growth, mostly confined to glades above 5000'. Where the snow on top of the late Dec. crust isn't stiffened by the wind it's mostly facets, made for slippery skinning at times but great turns in sheltered areas, especially below 6000'. Wind affected snow showed no signs of instability (cracking).Plenty of D2s and at least three D3s that ran during the Christmas warm-up and rain in Paola Creek. Most of the activity was off the Tunnel Ridge side.", 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'No signs of instability observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


351
351
{'location': 'Elk Mountain - southern Glacier Park', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Few (Mostly Clear, up to 2/8 covered)', 'Temperature (F)': '22', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': "3500'", 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': 'Consistent light to moderate winds but zero wind transport. Warming temperatures and plenty of sunshine.', 'Observation Date': 'Jan 7, 2023 (10:00 - 16:00)', 'Submission Date': 'Jan 7, 2023', 'Observer type': 'forecaster', 'Observation Summary': "We visited a notoriously windy spot just west of Marias Pass to look for evidence of recent or current wind slab formation. No slabs were found, and only small amounts of wind-affected snow were noted on the surface. Excellent visibility provided beautiful views of the surrounding high peaks, where we did not observe any plumes of wind-blown snow. Our other objective was to gather evidence concerning the distribution of the Christmas Crust, which we found extended to at least 7500' in this area.", 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


352
352
{'location': 'Whitefish Range', 'Zone / Region': 'Other', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Jan 6, 2023', 'Submission Date': 'Jan 6, 2023', 'Observer type': 'public', 'Observation Summary': 'South end of the whitefish range, east aspect, 6300’. Large whumpf and shifting felt under foot near edge of the slope.', 'SIGNS OF INSTABILITY': 'Collapsing Observed (isolated)', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


353
353
{'location': 'Great Bear/Rescue Creek', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Obscured (Sky not visible due to fog or non-cloud layer)', 'Temperature (F)': '26', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Previous', 'Weather Summary': 'Gray', 'Observation Date': 'Jan 6, 2023', 'Submission Date': 'Jan 8, 2023', 'Observer type': 'public', 'Observation Summary': 'From digging a pit nearly to ground on a S/SE aspect @ 7,400 ft we found results from an  ICT 17 sliding 85cm below the surface, with an overall depth of 250cm. On this aspect there was a fair amount of wind transport/cross loading creating this substantial slab sitting atop a faceted layer nearly 3ft down. While there was no obvious sign of instability on the surface, the deeper layer issue, and lack of visibility made us rethink our original objective, and go with a safer anchored/sloped pitch.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'Weak layers found lower in the snowpack when tested extensively.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


354
354
{'location': 'Rescue u', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Jan 6, 2023', 'Submission Date': 'Jan 6, 2023', 'Observer type': 'public', 'Observation Summary': 'In the northern Flathead the cloud deck was pretty stubborn at 7k. Between 5500 and 7k we found about 30 cm of snow above the crust with variable breakable crust, which thankfully didn’t affect skiing too much. Minimal sluffing. Minimal wind. No surface hoar. Also notice some really interesting ripples in the snow, as seen in photo', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


355
355
{'location': 'Big Slide', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Obscured (Sky not visible due to fog or non-cloud layer)', 'Temperature (F)': 'Not Observed', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'None', 'Wind Loading': 'None', 'Weather Summary': 'In the ping pong ball much of the day, no new precip, no wind.', 'Observation Date': 'Jan 6, 2023', 'Submission Date': 'Jan 6, 2023', 'Observer type': 'public', 'Observation Summary': 'Went out to big slide to try out a center punch test to report back to Rob. While not a multi day epic in the alpine, “it goes”, as they say. No signs of instability. No precip, no wind, obscured sky. Approx 20-30cm of recent snow atop the supportable crust. Could see old wet loose debris, but nothing recent.', 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

356
356
{'location': 'Sub shields', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': 'Below freezing', 'New or Recent Snowfall (cm)': 'Not Observed', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'Light', 'Weather Summary': 'The clouds never broke. Summit of Elk Mtn remained in clouds throughout the day. Swirling Wind gusts to ~20-30 mph were transporting snow at ridgelines. Wind transport of snow was intermittent with gusts.', 'Observation Date': 'Jan 6, 2023', 'Submission Date': 'Jan 6, 2023', 'Observer type': 'public', 'Observation Summary': 'No signs of instability observed. No signs of slab formation on top of rain crust.', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'No signs of instability observed', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


357
357
{'location': 'WMR', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Route': 'Beacon Park laps  and Canyon Creek', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '24', 'New or Recent Snowfall (cm)': 'Trace', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'Light', 'Weather Summary': 'S-1 began around 1430 hours with cloud deck lowering to the valley bottom. Winds gusted from SW.', 'Observation Date': 'Jan 5, 2023 (1:30 - 3:30)', 'Submission Date': 'Jan 5, 2023', 'Observer type': 'forecaster', 'Observation Summary': "Got into the beacon park at WMR for monthly training.\xa0 Make use of these resources if you haven't yet! There is one located on the summit near the top of Chair 1.\xa0 There is a second park located roughly 2/3 of the way down Grey Wolf on the back side.\xa0 Both are accessible to snowmobiles.\n-Followed training with a quick lap through the canyon to check on surface conditions, sluffing, and usage.\xa0\xa0\n-Found the area well utilized, with any remaining untouched snow sluffing easily on steep slopes.\xa0 However, these were small in size and easy to manage.\n-Did not find surface hoar", 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'No obvious signs of instability.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


358
358
{'location': 'Shed 7/Snowslip', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'FAC', 'Activity': 'Skiing/Snowboarding', 'Cloud Cover': 'Broken (Mostly Cloudy, more than 4/8 but less than 8/8)', 'Temperature (F)': '28', 'New or Recent Snowfall (cm)': '0', 'Rain/Snow Line': "3000'", 'Snow Available For Transport': 'Not Observed', 'Wind Loading': 'None', 'Weather Summary': 'We enjoyed pleasant weather with broken skies, ambient temperatures of -2° C, and calm, gusting, light WSW wind.', 'Observation Date': 'Jan 5, 2023', 'Submission Date': 'Jan 6, 2023', 'Observer type': 'forecaster', 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'We did not observe any obvious signs of instability today aside from some small surface loose snow movement on a wind-loaded loaded steep roll over while descending.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


359
359
{'location': 'Flathead Range & Glacier NP', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Jan 5, 2023', 'Submission Date': 'Jan 6, 2023', 'Observer type': 'public', 'Observation Summary': "Beautiful day in the alpine. No wind. A bit warmer today with high clouds and a couple sunny holes throughout the day. Skied S, W/NW, and NE aspects. Skied NE from our high point of 7700'. All aspects we skied had dense pow ranging from 20-50 cms stuck onto underlying rain crust. Crust became much softer and almost nonexistent at times above 7550' on north face. West aspects had sun crust of variable thickness and hardness. Spotted one glide crack on south face at 6600'. Nothing moving even in steep terrain.", 'SIGNS OF INSTABILITY': 'None Reported', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


360
360
{'location': 'Marion Lake', 'Zone / Region': 'Flathead Range & Glacier NP', 'Activity': 'Skiing/Snowboarding', 'Observation Date': 'Jan 4, 2023', 'Submission Date': 'Jan 4, 2023', 'Observer type': 'public', 'Observation Summary': 'Played the game called "Avoid the Sun Crust" and had some success. We triggered a very small loose dry avalanche running on the rain crust in steep north facing terrain. It was very small due to being in small terrain, I can only assume bigger terrain will run much larger. Besides that, no instabilities to report.', 'SIGNS OF INSTABILITY': 'Avalanches Observed  Avalanches Triggered', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


361
361
{'location': 'Link Mtn.', 'Zone / Region': 'Whitefish Range', 'Activity': 'Skiing/Snowboarding', 'Route': 'Approached on the road from the North Fork.  Ascended the SE ridge.', 'Cloud Cover': 'Overcast (Cloudy, 8/8 covered)', 'Temperature (F)': '22', 'New or Recent Snowfall (cm)': '5', 'Rain/Snow Line': 'Not Observed', 'Snow Available For Transport': 'Small Amounts', 'Wind Loading': 'None', 'Weather Summary': "Grey bird at its best.  You couldn't see the debris piles until you hit them.  No snow or wind.  Pow is aging.", 'Observation Date': 'Jan 4, 2023', 'Submission Date': 'Jan 4, 2023', 'Observer type': 'public', 'Observation Summary': "The skinning was the most laborious part of the day, as the lower elevations had 5-7 inches ontop of a supportable crust.\n-The crust/ice layer was buried by 45 cm of Fist hard pow at 6900'.\n-Just below the summit we found the crown of a D3 size avalanche that had occurred last week. The failure plane was a density change approx 100 cm from the ground and 70 cm from the surface. This was well below the dreaded ice layer from Christmas.\n-Skiing was fantastic, we felt comfortable on steeper and more complex terrain.", 'SIGNS OF INSTABILITY': 'None Reported', 'Instability Comments': 'The stability today was great.  We saw no signs of recent avalanches or instabilities.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

In [239]:
pd.DataFrame(forms).head()

,location,Zone / Region,Activity,Observation Date,Submission Date,Observer Name,Observer type,Observation Summary,SIGNS OF INSTABILITY,Instability Comments,...,New or Recent Snowfall (cm),Rain/Snow Line,Snow Available For Transport,Wind Loading,Location,Distribution,Sensitivity,Size,Route,Weather Summary
0,Little Dog,Other,Skiing/Snowboarding,"Mar 15, 2024","Mar 15, 2024",Anders Soyland,public,"Good freeze last night, there was a bit of a p...",None Reported,Just wet roller balls,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Doris,Swan Range,Snowmobiling/Snowbiking,"Mar 15, 2024","Mar 15, 2024",JBurk,professional,"Rollerballs on solar aspects, propagating frac...",Avalanches Observed,Rollerballs were observed on solar aspects. on...,...,Not Observed,Not Observed,Small Amounts,None,NESWNWNESESW,IsolatedSpecificWidespread,UnreactiveStubbornReactiveTouchy,D1D2D3D4D5,NaN,NaN
2,Hungry Horse Dam,Other,Driving,"Mar 15, 2024 (18:00) - Mar 15, 2024 (19:00)","Mar 15, 2024",Cam Johnson,forecaster,Took a quick drive to the Hungry Horse Dam to ...,Avalanches Observed,NaN,...,Not Observed,Not Observed,Not Observed,Not Observed,NaN,NaN,NaN,NaN,NaN,NaN
3,Skiumah Lake,Flathead Range & Glacier NP,Skiing/Snowboarding,"Mar 15, 2024","Mar 15, 2024",Al Goretex,public,Dry snow at middle and upper elevations on pol...,Avalanches Observed,Saw that crown on the northwest shoulder of Pe...,...,Not Observed,Not Observed,Small Amounts,None,NaN,NaN,NaN,NaN,"Hwy up the summer trail to lake, then reverse.",Too hot for march.
4,Skook Face,Whitefish Range,Skiing/Snowboarding,"Mar 15, 2024 (10:00 - 15:30)","Mar 15, 2024",Mark Dundas,forecaster,We traveled to the southern Whitefish Range to...,Avalanches Observed,Warming temperatures initiated rollerballs and...,...,0,5000,Small Amounts,None,NESWNWNESESW,IsolatedSpecificWidespread,UnreactiveStubbornReactiveTouchy,D1D2D3D4D5,The standard skin track up and down Skook Ridge.,NaN

In [237]:
pd.DataFrame(forms).to_csv('/home/christine/Jupyter/snow/data/fac_observations_2023-11-01_2024-03-16.csv')

# Avalanche

In [274]:
import json
import copy
driver = webdriver.Chrome(service=s)
season = 2023
driver.get(f"https://flatheadavalanche.org/observations/read-observations/#/view/avalanches?startDate=%22{int(season-1)}-11-01%22&endDate=%22{int(season)}-06-16%22&season={int(season)}")

# Wait for the table to load
WebDriverWait(driver, 10).until(
    EC.presence_of_element_located((By.CSS_SELECTOR, ".nac-card.nac-observation-card.nac-card-hover"))
)

rows = driver.find_elements(By.CSS_SELECTOR, ".nac-card.nac-observation-card.nac-card-hover")
rows[0].click()
forms = []
n=0
while(True):
    driver.implicitly_wait(20)
    html = driver.page_source
    soup = BeautifulSoup(html, 'html.parser')
    new_form = get_obs_fields(soup, obs_type = 'Avalanche Occurrence')
    if new_form in forms:
        break
    else:
        forms.append(copy.deepcopy(new_form))
    next_arrow = WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.CSS_SELECTOR, ".nac-btn.nac-btn-primary.nac-next"))
    )
    next_button = driver.find_element(By.CSS_SELECTOR, "a.nac-btn-primary.nac-next")
    next_button.click()
    time.sleep(20)
    n+=1
    print(len(forms))
    print(len(set([json.dumps(elem) for elem in forms])))
    print(new_form)
    print('\n')
pd.DataFrame(forms).to_csv('/home/christine/Jupyter/snow/data/fac_avalanche_2022_2023.csv')

1
1
{'Latitude': '48.402214', 'Longitude': '-114.13365'}


2
2
{'location': 'Rescue Creek - south chutes', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '12', 'Aspect:': 'SE', 'Slope Angle:': '35°', 'Elevation:': '6000 ft', 'Vertical Fall:': '1000 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R2', 'Type:': 'WL-Wet Loose', 'Bed Surface:': 'I-New/Old Interface', 'Width:': '50 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Apr 23, 2023 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Sustained sun and warming intitiated these slides. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


3
3
{'location': 'Rescue Creek - south chutes', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Aspect:': 'SE', 'Slope Angle:': '35°', 'Elevation:': '6200 ft', 'Vertical Fall:': '1200 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R2', 'Type:': 'WL-Wet Loose', 'Bed Surface:': 'I-New/Old Interface', 'Width:': '50 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Apr 23, 2023 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Sustained sun and warming intitiated these slides. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


4
4
{'location': 'Below Crystal Point', 'Zone / Region': 'Other', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Aspect:': 'W', 'Elevation:': '5700 ft', 'Vertical Fall:': '20 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'WL-Wet Loose', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '30 cm (1 ft)', 'Width:': '25 ft', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Apr 20, 2023 (Exact)', 'Occurrence Time': '00:22 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'Small wet loose avalanche(s) triggered over steep rollovers on small test slopes while skiing back to the loop. These avalanches failed predictably on the old snow/new snow interface and moved slowly downhill entraining storm snow until the slope flattened out (picture attached).', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


5
5
{'location': '48.1078N / -113.8832W', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SW', 'Elevation:': '6500 ft', 'Destructive Size:': 'D2', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Apr 11, 2023 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'This slide occurred on a new glide crack that recently opened up above a larger crack first observed in late Feb. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


6
6
{'location': 'Flathead', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'N', 'Elevation:': '6500 ft', 'Destructive Size:': 'D1.5', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '20 cm (0.5 ft)', 'Width:': '100 ft', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Apr 2, 2023 (Exact)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


7
7
{'location': 'Flathead', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'N', 'Slope Angle:': '40°', 'Elevation:': '6300 ft', 'Vertical Fall:': '10 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '30 cm (1 ft)', 'Width:': '25 ft', 'Trigger:': 'N-Naturalc-Intentional', 'Occurrence Date': 'Apr 2, 2023 (Exact)', 'Occurrence Time': '12:12 (Exact)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


8
8
{'location': 'Flathead', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NW', 'Slope Angle:': '38°', 'Elevation:': '6400 ft', 'Vertical Fall:': '800 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '30 cm (1 ft)', 'Width:': '20 ft', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Apr 2, 2023 (Exact)', 'Occurrence Time': '12:19 (Exact)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


9
9
{'location': 'Crystal Creek', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Slope Angle:': '35°', 'Elevation:': '6200 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R2', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '25 cm (1 ft)', 'Width:': '300 ft', 'Trigger:': 'AR-Snowboarderu-Unintentional', 'Occurrence Date': 'Apr 2, 2023 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'Triggered when rider jumped onto slope and fell. Rider able to esape debris.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


10
10
{'location': 'Swan', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Destructive Size:': 'D1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Trigger:': 'AM-Snowmobileu-Unintentional', 'Occurrence Date': 'Apr 2, 2023 (Exact)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


11
11
{'location': 'Heavens Peak - Heavens Gate', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Other', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '4', 'Aspect:': 'E', 'Elevation:': '8200 ft', 'Destructive Size:': 'D2.5', 'Relative Size:': 'R3', 'Type:': 'U-Unknown', 'Bed Surface:': 'U-Unknown', 'Width:': '2000 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Apr 2, 2023 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': "Estimate on date and size, did not get clear view of runouts. Largest continuous crown estimated over 2000' wide on maps in office.", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


12
12
{'location': 'Diamond Peak', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Elevation:': '6700 ft', 'Destructive Size:': 'D1.5', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '50 cm (1.5 ft)', 'Trigger:': 'AM-Snowmobile', 'Occurrence Date': 'Apr 2, 2023 (Exact)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


13
13
{'location': 'Upper Wahoo', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Slope Angle:': '38°', 'Elevation:': '6400 ft', 'Vertical Fall:': '150 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R2', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '30 cm (1 ft)', 'Width:': '50 ft', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Apr 2, 2023 (Exact)', 'Occurrence Time': '00:19 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'Ski cut 38* test slope and triggered a predictable soft wind slab avalanche.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


14
14
{'location': 'Upper Wahoo', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Slope Angle:': '38°', 'Elevation:': '6400 ft', 'Vertical Fall:': '150 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R3', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '40 cm (1.5 ft)', 'Width:': '150 ft', 'Trigger:': 'AR-Snowboarderu-Unintentional', 'Occurrence Date': 'Apr 2, 2023 (Exact)', 'Occurrence Time': '00:20 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'After observing crown of intentionally triggered wind slab listed above, while skiing off of the bed surface of the wind slab avalanche a snowboarder triggered a deeper persistant slab avalanche. The snowboarder was caught and carried ~75ft downhill. The snowboarder came to rest on top of the debris. The avalanche failed on a layer of recently buried near surface facets under recently consolidated surface snow. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

15
15
{'location': 'Upper Wahoo', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Slope Angle:': '35°', 'Elevation:': '6200 ft', 'Vertical Fall:': '200 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R3', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '30 cm (1 ft)', 'Width:': '50 ft', 'Trigger:': 'AR-Snowboarderu-Unintentional', 'Occurrence Date': 'Apr 2, 2023 (Exact)', 'Occurrence Time': '00:20 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'This avalanche was unintentionally triggered at the flank, from a connected lower angle slope while descending. The slab propagated up (well above the rider) and across the small slope. Rider was easily able to avoid getting caught. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


16
16
{'location': 'Flathead', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Slope Angle:': '33°', 'Elevation:': '6500 ft', 'Vertical Fall:': '900 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R3', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '80 cm (2.5 ft)', 'Width:': '600 ft', 'Trigger:': 'AS-Skieru-Unintentional', 'Occurrence Date': 'Apr 2, 2023 (Exact)', 'Occurrence Time': '12:15 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Triggered this while walking a 33 degree ridgeline. This slab wrapped from an east facing aspect all the way around to a west facing aspect. Moving debris pushed me downhill approximately 15 feet. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


17
17
{'location': 'Tranquil Basin', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Elevation:': '6700 ft', 'Vertical Fall:': '300 ft', 'Destructive Size:': 'D2', 'Type:': 'U-Unknown', 'Bed Surface:': 'U-Unknown', 'Width:': '175 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Apr 1, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Released below rocks on leeward slope about 250 ft below ridge. Crown linked across small terrain features.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


18
18
{'location': 'Tranquil Basin', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Elevation:': '6900 ft', 'Vertical Fall:': '300 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'U-Unknown', 'Bed Surface:': 'U-Unknown', 'Width:': '50 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Apr 1, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Small, narrow natural avalanche that broke below rocks on leeward slope. Debris did not trigger slab on slope below.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


19
19
{'location': 'Flathead', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Aspect:': 'SE', 'Slope Angle:': '40°', 'Elevation:': '7000 ft', 'Vertical Fall:': '1500 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R2', 'Type:': 'U-Unknown', 'Bed Surface:': 'U-Unknown', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Apr 1, 2023 (Estimated)', 'Occurrence Time': '23:21 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Saw a few large debris piles that looked like they failed overnight or in the early hours of the morning. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


20
20
{'location': 'Adjacent to WMR', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '8', 'Aspect:': 'SW', 'Destructive Size:': 'D2', 'Type:': 'WL-Wet Loose', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Mar 29, 2023 (Estimated)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


21
21
{'location': 'Within The Bubble marked on Map Location above', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NW', 'Elevation:': '5900 ft', 'Destructive Size:': 'D1', 'Type:': 'L-Dry Loose', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Mar 25, 2023 (Exact)', 'Observer type': 'public', 'Avalanche Summary': "I'd say about 6 inches of new snow slid freely on the smooth icy crust.  The crusts in this area were patchy but were found to be quite hard and supportable a week ago.", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


22
22
{'location': 'Central Whitefish Range', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Slope Angle:': '40°', 'Elevation:': '7000 ft', 'Vertical Fall:': '700 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R3', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '50 cm (1.5 ft)', 'Width:': '60 ft', 'Trigger:': 'AC-Human-caused cornice fallc-Intentional', 'Occurrence Date': 'Mar 22, 2023 (Exact)', 'Occurrence Time': '11:48 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Cornice fall triggered a Hard Slab 2 feet thick. The slope did not have a lot of room for it to propagate widely. Rocky terrain and thin snowpack reduced the likelihood for that. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


23
23
{'location': 'Flathead Range', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Elevation:': '8000 ft', 'Destructive Size:': 'D1.5', 'Type:': 'C-Cornice', 'Occurrence Date': 'Mar 21, 2023 (Exact)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


24
24
{'location': 'Apgars', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Aspect:': 'SW', 'Elevation:': '6400 ft', 'Destructive Size:': 'D2', 'Type:': 'WL-Wet Loose', 'Occurrence Date': 'Mar 19, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Various old piles of wet debris. Unknown date. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


25
25
{'location': 'Red Crow Mountain', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Other', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Elevation:': '7700 ft', 'Vertical Fall:': '800 ft', 'Destructive Size:': 'D2.5', 'Relative Size:': 'R3', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '80 cm (2.5 ft)', 'Width:': '500 ft', 'Trigger:': 'AW-Wildlife', 'Occurrence Date': 'Mar 18, 2023 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': ' ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


26
26
{'location': 'Marion Lake', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '10', 'Aspect:': 'SE', 'Slope Angle:': '40°', 'Elevation:': '7000 ft', 'Vertical Fall:': '1000 ft', 'Destructive Size:': 'D1', 'Type:': 'WL-Wet Loose', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Mar 16, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Suspect the wet loose observed on the high point above marion failed on the first day of solar after a few inches of snow fell. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


27
27
{'location': 'Dickey', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Elevation:': '7400 ft', 'Destructive Size:': 'D2', 'Type:': 'HS-Hard Slab', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Mar 15, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': "I'm guessing it was a hard slab. Failed just below ridgeline. Crown looked crisper than old crowns observed on Cameahwait. ", 'Latitude': '48.402214', 'Longitude': '-114.13365'}

28
28
{'location': 'Swan Lake', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NW', 'Slope Angle:': '35°', 'Elevation:': '7100 ft', 'Vertical Fall:': '100 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'S-New Snow', 'Slab Thickness:': '10 cm (0.5 ft)', 'Width:': '40 ft', 'Trigger:': 'AS-Skiery-Sympathetic', 'Occurrence Date': 'Mar 15, 2023 (Exact)', 'Occurrence Time': '13:45 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Avalanche failed on adjacent slope after intentionally triggering a small avalanche. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


29
29
{'location': 'Swan Lake', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'N', 'Slope Angle:': '35°', 'Elevation:': '7200 ft', 'Vertical Fall:': '200 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'S-New Snow', 'Slab Thickness:': '10 cm (0.5 ft)', 'Width:': '60 ft', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Mar 15, 2023 (Exact)', 'Occurrence Time': '13:45 (Exact)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


30
30
{'location': 'Marion', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Elevation:': '5500 ft', 'Destructive Size:': 'D1.5', 'Type:': 'WL-Wet Loose', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Mar 14, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'A wet loose ran down and touched the marion lake trail. Suspect this failed during rain event? ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


31
31
{'location': "Devil's Hump West", 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'N', 'Elevation:': '7250 ft', 'Destructive Size:': 'D2.5', 'Type:': 'HS-Hard Slab', 'Slab Thickness:': '200 cm (6.5 ft)', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Mar 14, 2023 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': "Large avalanche crown observed (photo attached as well) from Snowslip's E ridge above Shed 7. Estimated date of occurrence given the fresh snow obscuring the debris. The avalanche may have been triggered by a natural smaller slab avalanche above, but it was hard telling from our vantage point..", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


32
32
{'location': 'East face of Elk Mtn', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Elevation:': '6600 ft', 'Vertical Fall:': '1000 ft', 'Destructive Size:': 'D2.5', 'Relative Size:': 'R3', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '150 cm (5 ft)', 'Width:': '200 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Mar 14, 2023 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'Details on elevation and crown dimensions are estimated. Looks to have failed on an old persistent weak layer.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


33
33
{'location': 'Swan Lake', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'S', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R1', 'Type:': 'WL-Wet Loose', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Mar 13, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Debris piled on road. Originated in steep rocky terrain. Could not see start zone.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


34
34
{'location': 'Swan Lake', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'NW', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R1', 'Type:': 'WL-Wet Loose', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Mar 13, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Debris piles on road. Originated in steep rocky terrain. Could not see start zone.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


35
35
{'location': 'Nyack Mountain', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Aspect:': 'NE', 'Elevation:': '7400 ft', 'Destructive Size:': 'D1', 'Type:': 'L-Dry Loose', 'Bed Surface:': 'S-New Snow', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Mar 12, 2023 (Exact)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


36
36
{'location': 'Wahoo Creek', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Aspect:': 'NE', 'Elevation:': '6000 ft', 'Destructive Size:': 'D1', 'Type:': 'L-Dry Loose', 'Bed Surface:': 'S-New Snow', 'Trigger:': 'AS-Skier', 'Occurrence Date': 'Mar 12, 2023 (Exact)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


37
37
{'location': 'Jakes - S face Snowslip Mtn', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'S', 'Slope Angle:': '45°', 'Elevation:': '5000 ft', 'Vertical Fall:': '600 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R3', 'Type:': 'WL-Wet Loose', 'Bed Surface:': 'O-Old Snow', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Mar 12, 2023 (Exact)', 'Occurrence Time': '00:28 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'Initiated in surface wet snow but then gouged down deeper into the snowpack', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


38
38
{'location': 'Apgar Range', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '10', 'Aspect:': 'SE', 'Elevation:': '5500 ft', 'Destructive Size:': 'D1', 'Type:': 'WL-Wet Loose', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Mar 12, 2023 (Exact)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


39
39
{'location': 'Hay Creek', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'S', 'Slope Angle:': '35°', 'Elevation:': '4500 ft', 'Vertical Fall:': '100 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'WL-Wet Loose', 'Bed Surface:': 'S-New Snow', 'Occurrence Date': 'Mar 8, 2023 (Exact)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


40
40
{'location': 'Diamond Peak', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '4', 'Aspect:': 'E', 'Slope Angle:': '40°', 'Elevation:': '7000 ft', 'Vertical Fall:': '200 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'L-Dry Loose', 'Bed Surface:': 'S-New Snow', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Mar 8, 2023 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Several loose dry in steep rocky terrain.  The longest (not pictured) ran ~400 ft.  ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


41
41
{'location': '2', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Slope Angle:': '45°', 'Elevation:': '6800 ft', 'Vertical Fall:': '100 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'WL-Wet Loose', 'Bed Surface:': 'S-New Snow', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Mar 8, 2023 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'A couple loose wet in the sunniest, rockiest terrain. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

42
42
{'location': 'Green Mountain', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Slope Angle:': '38°', 'Elevation:': '7600 ft', 'Vertical Fall:': '800 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R2', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '60 cm (2 ft)', 'Width:': '200 ft', 'Trigger:': 'AM-Snowmobileu-Unintentional', 'Occurrence Date': 'Mar 7, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Original avalanche observation is posted on 3/8/23. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


43
43
{'location': 'Nyack Mountain, northeast face', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Elevation:': '7000 ft', 'Destructive Size:': 'D3', 'Slab Thickness:': '60 cm (2 ft)', 'Trigger:': 'NC-Cornice Fall', 'Occurrence Date': 'Mar 5, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': "Appears to be a cornice fall onto the slope. The crown at the top of the slide seems to be around 5 ft. Did not notice crowns and debris from below, in Rescue Creek. Noticed when dropped into run. Party reports it's possible that they triggered the cornice fall remotely  from opposite side of ridge while ascending. ", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


44
44
{'location': 'Tranquil Creek', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'W', 'Elevation:': '5900 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'U-Unknown', 'Slab Thickness:': '20 cm (0.5 ft)', 'Width:': '10 ft', 'Trigger:': 'AS-Skieru-Unintentional', 'Occurrence Date': 'Mar 3, 2023 (Exact)', 'Occurrence Time': '15:15 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Small soft slab of new/ drifted snow released while cutting across a short, steep slope.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


45
45
{'location': 'Nyack Mountain', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Slope Angle:': '38°', 'Elevation:': '7150 ft', 'Vertical Fall:': '500 ft', 'Destructive Size:': 'D3', 'Relative Size:': 'R4', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '150 cm (5 ft)', 'Width:': '1500 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Mar 2, 2023 (Estimated)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


46
46
{'location': '54-1', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Other', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'N', 'Elevation:': '7000 ft', 'Vertical Fall:': '3300 ft', 'Destructive Size:': 'D3.5', 'Relative Size:': 'R4', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'U-Unknown', 'Width:': '1300 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Mar 2, 2023 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'Best guess for timing is similar to large natural avalanche on Nyak (March 2, 2023) with possible additional more recent avalanche since then as some of the debris appears to be more fresh (less buried in recent snowfall).', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


47
47
{'location': 'Swan', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '4', 'Aspect:': 'E', 'Elevation:': '7100 ft', 'Destructive Size:': 'D1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '30 cm (1 ft)', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Mar 2, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Suspect this failed on on the 2nd when winds increased the day after Noisy basin picked up an inche of water. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


48
48
{'location': 'Hay Creek', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Slope Angle:': '40°', 'Elevation:': '6500 ft', 'Vertical Fall:': '1500 ft', 'Destructive Size:': 'D3', 'Relative Size:': 'R4', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '100 cm (3.5 ft)', 'Width:': '600 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Mar 2, 2023 (Estimated)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


49
49
{'location': 'Garden Wall', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Other', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SW', 'Elevation:': '8000 ft', 'Destructive Size:': 'D2.5', 'Relative Size:': 'R2', 'Type:': 'U-Unknown', 'Bed Surface:': 'U-Unknown', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Mar 2, 2023 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'Best guess for timing is similar to large natural avalanche on Nyak (March 2, 2023) with partially refilled crown and debris covered in recent snowfall.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


50
50
{'location': 'Big Bend', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Other', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'W', 'Elevation:': '7900 ft', 'Destructive Size:': 'D2.5', 'Relative Size:': 'R3', 'Type:': 'U-Unknown', 'Bed Surface:': 'U-Unknown', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Mar 2, 2023 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'Best guess for timing is similar to large natural avalanche on Nyak (March 2, 2023) with partially refilled crown and no view of debris/runout.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


51
51
{'location': 'Skookaleel Creek', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Slope Angle:': '38°', 'Elevation:': '6200 ft', 'Vertical Fall:': '50 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R2', 'Type:': 'WL-Wet Loose', 'Bed Surface:': 'I-New/Old Interface', 'Trigger:': 'AS-Skieru-Unintentional', 'Occurrence Date': 'Mar 1, 2023 (Exact)', 'Occurrence Time': '13:15 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Turns on a short, very steep slope produced a wet loose sluff that quickly entrained the moist surface snow. Had the pitch been continuous, it easily could have grown into a D2 or larger.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


52
52
{'location': 'Elk Moutain - Middle Path', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Other', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Slope Angle:': '40°', 'Elevation:': '6900 ft', 'Vertical Fall:': '1800 ft', 'Destructive Size:': 'D3', 'Relative Size:': 'R3', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'U-Unknown', 'Slab Thickness:': '100 cm (3.5 ft)', 'Width:': '500 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 28, 2023 (Estimated)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


53
53
{'location': 'Elk Mountain - North Path', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Other', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Slope Angle:': '40°', 'Elevation:': '6800 ft', 'Vertical Fall:': '1500 ft', 'Destructive Size:': 'D2.5', 'Relative Size:': 'R3', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'U-Unknown', 'Slab Thickness:': '100 cm (3.5 ft)', 'Width:': '400 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 28, 2023 (Estimated)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

54
54
{'location': 'Elk Moutain - Middle Path', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Other', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Slope Angle:': '40°', 'Elevation:': '6700 ft', 'Vertical Fall:': '1000 ft', 'Destructive Size:': 'D2.5', 'Relative Size:': 'R2', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'U-Unknown', 'Slab Thickness:': '100 cm (3.5 ft)', 'Width:': '250 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 28, 2023 (Estimated)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


55
55
{'location': 'Flattop Mountain', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Other', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'N', 'Elevation:': '6500 ft', 'Destructive Size:': 'D2', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'U-Unknown', 'Slab Thickness:': '60 cm (2 ft)', 'Trigger:': 'NC-Cornice Fall', 'Occurrence Date': 'Feb 27, 2023 (Estimated)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


56
56
{'location': 'Middle Fork', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'N', 'Elevation:': '6000 ft', 'Vertical Fall:': '15 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '15 cm (0.5 ft)', 'Width:': '12 ft', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Feb 26, 2023 (Exact)', 'Occurrence Time': '14:15 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Ski cut produced a small soft slab on the lee side of a mid-elevation ridge. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


57
57
{'location': '48.1072N / -113.8841W', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SW', 'Elevation:': '6500 ft', 'Destructive Size:': 'D2', 'Type:': 'HS-Hard Slab', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 26, 2023 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'Could not see debris field but  guessing HS rather than SS', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


58
58
{'location': 'Whitefish Mountain', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Elevation:': '7100 ft', 'Destructive Size:': 'D2', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 24, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': "Fracture line partially visible midway up west bowl on Whitefish Mountain. Coudn't make out details/ dimensions because of poor visibility and recent and drifted snow.", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


59
59
{'location': 'Upper Whitefish Lake road', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'W', 'Elevation:': '5800 ft', 'Vertical Fall:': '600 ft', 'Destructive Size:': 'D2.5', 'Relative Size:': 'R3', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'U-Unknown', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 24, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': '2 slides across groomed trail (previously reported) that occurred before Sunday (based on convo w NMA). Recent and drifted snow on debris and crown obscured dimensions. Some of crowns still visible; debris ran to creek but not up other side. 6-10 ft debris on road. Uppermost 2 of 3 paths. Passable on sleds thanks to carved out trough. . ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


60
60
{'location': 'Mt. Adams east Face', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Elevation:': '6900 ft', 'Destructive Size:': 'D3.5', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '125 cm (4 ft)', 'Width:': '1500 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 24, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Reported by 2 observers 3/5; a 3rd observer reported seeing the crown on 2/25. Possibly triggered by cornice fall. Runout not visible. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


61
61
{'location': 'Central Whitefish Range', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Elevation:': '5800 ft', 'Destructive Size:': 'D1.5', 'Type:': 'SS-Soft Slab', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 23, 2023 (Estimated)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


62
62
{'location': 'Skiumah', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Elevation:': '6800 ft', 'Destructive Size:': 'D2', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 23, 2023 (Estimated)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


63
63
{'location': 'Marston', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Elevation:': '5400 ft', 'Vertical Fall:': '15 ft', 'Destructive Size:': 'D1', 'Type:': 'C-Cornice', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 23, 2023 (Estimated)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


64
64
{'location': 'Grant Ridge/ S. Fork Tunnel Ridge', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Elevation:': '7600 ft', 'Destructive Size:': 'D3', 'Type:': 'U-Unknown', 'Bed Surface:': 'U-Unknown', 'Width:': '500 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 22, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': "Crown face and bed surface partially filled in. Ran from ridgeline, then broke mmuch wider severl hundred feet down. Couldn't see runout or full extent of fracture line. Guessing hard slab on old snow.", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


65
65
{'location': 'Rescue Creek', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'NE', 'Elevation:': '7000 ft', 'Vertical Fall:': '2500 ft', 'Destructive Size:': 'D3', 'Type:': 'HS-Hard Slab', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 21, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'I did not see the starting zone of either of these avalanches. Therefore I can not fill out all of the data accurately.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


66
66
{'location': 'Rescue Creek', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'SE', 'Elevation:': '6500 ft', 'Vertical Fall:': '2000 ft', 'Destructive Size:': 'D3', 'Type:': 'HS-Hard Slab', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 21, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'I did not see the starting zone of either of these avalanches. Therefore I can not fill out all of the data accurately.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


67
67
{'location': 'Rescue Creek', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '4', 'Aspect:': 'SE', 'Elevation:': '6500 ft', 'Vertical Fall:': '2000 ft', 'Destructive Size:': 'D2', 'Type:': 'SS-Soft Slab', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 21, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'I did not see the starting zone of any of these avalanches. Therefore I can not fill out all of the data accurately.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

68
68
{'location': 'Rescue Creek', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '4', 'Aspect:': 'NE', 'Elevation:': '6500 ft', 'Vertical Fall:': '2000 ft', 'Destructive Size:': 'D2', 'Type:': 'SS-Soft Slab', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 21, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'I did not see the starting zone of any of these avalanches. Therefore I can not fill out all of the data accurately.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


69
69
{'location': 'Flathead Range', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '6', 'Aspect:': 'E', 'Slope Angle:': '40°', 'Elevation:': '6000 ft', 'Vertical Fall:': '100 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R2', 'Type:': 'L-Dry Loose', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Feb 21, 2023 (Exact)', 'Occurrence Time': '12:22 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Another wind drifted test slope had propagation. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


70
70
{'location': 'Cascadilla Creek Nyack Mtn NE face', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '4', 'Aspect:': 'NE', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 21, 2023 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'D2 to D3. Crowns running several hundred feet and ranging from 1-4+ feet thick.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


71
71
{'location': 'SE-facing slopes off the Skiumah/Great Bear divide', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '4', 'Aspect:': 'SE', 'Destructive Size:': 'D2', 'Type:': 'U-Unknown', 'Bed Surface:': 'U-Unknown', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 21, 2023 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': "Several more crowns further up the basin and looker's right", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


72
72
{'location': 'Central Whitefish', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Slope Angle:': '40°', 'Elevation:': '7000 ft', 'Vertical Fall:': '1000 ft', 'Destructive Size:': 'D3', 'Relative Size:': 'R3', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '150 cm (5 ft)', 'Width:': '300 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 21, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Old crown. Appeared 5 feet thick. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


73
73
{'location': 'Slopes to the west above Skiumah Lake', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Elevation:': '5200 ft', 'Vertical Fall:': '800 ft', 'Destructive Size:': 'D2.5', 'Relative Size:': 'R2', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '100 cm (3.5 ft)', 'Width:': '200 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 21, 2023 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'Uncertain bed surface/failure layer and crown length', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


74
74
{'location': 'NE face of Peak 7510', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Elevation:': '6200 ft', 'Vertical Fall:': '1800 ft', 'Destructive Size:': 'D3', 'Relative Size:': 'R3', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '100 cm (3.5 ft)', 'Width:': '700 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 21, 2023 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'Crown details estimated. Thinking this might be a hard slab failing on old PWL', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


75
75
{'location': 'Snowshed Mtn', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Elevation:': '7000 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R2', 'Type:': 'U-Unknown', 'Bed Surface:': 'U-Unknown', 'Slab Thickness:': '100 cm (3.5 ft)', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 21, 2023 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'Observed from Java East along the rail. Could only view part of the crown, D2 at least', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


76
76
{'location': 'Snowshed Mtn', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Elevation:': '6800 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R3', 'Type:': 'U-Unknown', 'Bed Surface:': 'U-Unknown', 'Slab Thickness:': '100 cm (3.5 ft)', 'Width:': '2800 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 21, 2023 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'Observed from Java East along the rail. May be the same avalanche reported on Feb 20th? Could only view part of the crown. D2 at least.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


77
77
{'location': 'NNE face Mt Penrose', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'N', 'Elevation:': '7200 ft', 'Vertical Fall:': '2800 ft', 'Destructive Size:': 'D3', 'Relative Size:': 'R2', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '150 cm (5 ft)', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 21, 2023 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'Looked to be a big hard slab. Visibility limited by fog. Elevation and crown size estimated.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


78
78
{'location': 'Nyack Area', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'E', 'Elevation:': '7000 ft', 'Destructive Size:': 'D2.5', 'Relative Size:': 'R3', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'O-Old Snow', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 21, 2023 (Estimated)', 'Occurrence Time': '01:32 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Rough estimate of the number of avalanches observed not already accounted for. Counted roughly 12 D2 and D3 size avalanches. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


79
79
{'location': 'Noisy', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Aspect:': 'NE', 'Elevation:': '6700 ft', 'Destructive Size:': 'D1.5', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'U-Unknown', 'Slab Thickness:': '40 cm (1.5 ft)', 'Width:': '200 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 21, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Observed three crowns. Appeared to be soft slabs. Varying aspects. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


80
80
{'location': 'Hay Creek', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Slope Angle:': '40°', 'Elevation:': '6500 ft', 'Vertical Fall:': '1200 ft', 'Destructive Size:': 'D3', 'Relative Size:': 'R3', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '100 cm (3.5 ft)', 'Width:': '600 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 21, 2023 (Estimated)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

81
81
{'location': 'Cascadilla', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Elevation:': '6600 ft', 'Vertical Fall:': '500 ft', 'Destructive Size:': 'D3', 'Relative Size:': 'R3', 'Type:': 'HS-Hard Slab', 'Slab Thickness:': '100 cm (3.5 ft)', 'Width:': '600 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 20, 2023 (Estimated)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


82
82
{'location': 'Cascadilla', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Elevation:': '6400 ft', 'Vertical Fall:': '250 ft', 'Destructive Size:': 'D3', 'Relative Size:': 'R2', 'Type:': 'HS-Hard Slab', 'Slab Thickness:': '100 cm (3.5 ft)', 'Width:': '500 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 20, 2023 (Estimated)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


83
83
{'location': 'Cascadilla', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '10', 'Aspect:': 'NW', 'Elevation:': '5200 ft', 'Vertical Fall:': '200 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R2', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '40 cm (1.5 ft)', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 20, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Width varied between 40-150 feet', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


84
84
{'location': 'Cascadilla', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '6', 'Aspect:': 'SE', 'Elevation:': '5800 ft', 'Vertical Fall:': '1300 ft', 'Destructive Size:': 'D2', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 20, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'I could not see the crowns and therefore can not estimate slab characteristics', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


85
85
{'location': 'Northeast-facing slope below Snowshed Mountain.', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Elevation:': '6800 ft', 'Vertical Fall:': '300 ft', 'Destructive Size:': 'D2', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '3 cm (0 ft)', 'Width:': '150 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 20, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'We estimated that the wind loaded the slope to the tipping point. We could not safely access the crown.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


86
86
{'location': 'Flathead Range', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '5', 'Aspect:': 'NE', 'Slope Angle:': '40°', 'Elevation:': '6000 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R3', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '100 cm (3.5 ft)', 'Width:': '500 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 20, 2023 (Exact)', 'Occurrence Time': '23:01 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Observed 5+ D2s or D3s off Mt. Penrose up Chrystal Drainage. Crowns spanned long distances and wrapped around terrain features. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


87
87
{'location': 'Mt Marston', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '4', 'Aspect:': 'SE', 'Elevation:': '6300 ft', 'Vertical Fall:': '10 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'L-Dry Loose', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '30 cm (1 ft)', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 20, 2023 (Estimated)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


88
88
{'location': 'Marston', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'SE', 'Slope Angle:': '35°', 'Elevation:': '6300 ft', 'Vertical Fall:': '10 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '30 cm (1 ft)', 'Width:': '20 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 20, 2023 (Estimated)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


89
89
{'location': 'Marston', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Slope Angle:': '45°', 'Elevation:': '6800 ft', 'Vertical Fall:': '100 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '30 cm (1 ft)', 'Width:': '50 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 20, 2023 (Estimated)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


90
90
{'location': 'Nyack', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'E', 'Destructive Size:': 'D3', 'Relative Size:': 'R2', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'O-Old Snow', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 20, 2023 (Estimated)', 'Occurrence Time': '23:35 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Rough estimate of the number of avalanches observed not already accounted for.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


91
91
{'location': 'Cascadilla', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '5', 'Aspect:': 'NW', 'Elevation:': '5500 ft', 'Vertical Fall:': '1000 ft', 'Destructive Size:': 'D2', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 20, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'I could not see the crowns and therefore can not estimate slab characteristics', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


92
92
{'location': 'Cascadilla', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Elevation:': '5900 ft', 'Vertical Fall:': '1400 ft', 'Destructive Size:': 'D3', 'Type:': 'HS-Hard Slab', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 20, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'I could not see the crowns and therefore can not estimate slab characteristics', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


93
93
{'location': 'Snowshed', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Elevation:': '7000 ft', 'Vertical Fall:': '800 ft', 'Destructive Size:': 'D3', 'Relative Size:': 'R4', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '90 cm (3 ft)', 'Width:': '1800 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 20, 2023 (Estimated)', 'Occurrence Time': '23:36 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'This slab failed on facets just below the mid-January crust. We traced crownline 1200 feet and it conitnued out of site. Visibility was poor. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

94
94
{'location': 'Fern', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Slope Angle:': '32°', 'Elevation:': '6000 ft', 'Vertical Fall:': '250 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R2', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '45 cm (1.5 ft)', 'Width:': '150 ft', 'Trigger:': 'AS-Skieru-Unintentional', 'Occurrence Date': 'Feb 19, 2023 (Exact)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


95
95
{'location': 'Marion', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Elevation:': '6700 ft', 'Destructive Size:': 'D1', 'Type:': 'SS-Soft Slab', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Feb 19, 2023 (Exact)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


96
96
{'location': 'West Side Swan', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NW', 'Slope Angle:': '37°', 'Elevation:': '6550 ft', 'Vertical Fall:': '20 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '45 cm (1.5 ft)', 'Width:': '30 ft', 'Trigger:': 'AS-Skieru-Unintentional', 'Occurrence Date': 'Feb 19, 2023 (Exact)', 'Occurrence Time': '14:12 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Knocked me off my feet. Carried a very short distance before coming to a stop on a small bench. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


97
97
{'location': 'West Side Swan', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '10', 'Aspect:': 'NW', 'Slope Angle:': '38°', 'Elevation:': '6000 ft', 'Vertical Fall:': '30 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'L-Dry Loose', 'Bed Surface:': 'S-New Snow', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Feb 19, 2023 (Exact)', 'Occurrence Time': '12:15 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Muliple loose dry triggered intentionally on descent. Easy to manage. Few cracked and behaved like soft slab. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


98
98
{'location': 'Running Rabbit', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'N', 'Elevation:': '7000 ft', 'Destructive Size:': 'D1', 'Type:': 'SS-Soft Slab', 'Slab Thickness:': '3 cm (0 ft)', 'Trigger:': 'AC-Human-caused cornice fallc-Intentional', 'Occurrence Date': 'Feb 14, 2023 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'Triggered a small soft wind slab avalanche on a north/northeast aspect off running rabbit while traversing a ridgeline. It broke 25-30ft across and ran ~200 vertical feet. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


99
99
{'location': 'Jewel Basin- estimated NE slope', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Slope Angle:': '38°', 'Elevation:': '7000 ft', 'Vertical Fall:': '250 ft', 'Destructive Size:': 'D1.5', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '6 cm (0 ft)', 'Width:': '100 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 12, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'photo taken from 48.18783, -113.94605- standing at 6465 feet. Most of the details unknown. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


100
100
{'location': 'Peak 7,787 (above Marion Lake)', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Slope Angle:': '45°', 'Elevation:': '7750 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R3', 'Type:': 'SS-Soft Slab', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 11, 2023 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'Difficult to see debris. crown evident and observed in "pocket" terrain. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


101
101
{'location': 'Essex Mountain', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NW', 'Slope Angle:': '45°', 'Elevation:': '6000 ft', 'Vertical Fall:': '800 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R3', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'U-Unknown', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 11, 2023 (Estimated)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


102
102
{'location': 'Flathead Range', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'NE', 'Destructive Size:': 'D2', 'Type:': 'HS-Hard Slab', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 10, 2023 (Estimated)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


103
103
{'location': 'South Fork Swan', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Elevation:': '6200 ft', 'Destructive Size:': 'D1.5', 'Trigger:': 'AM-Snowmobileu-Unintentional', 'Occurrence Date': 'Feb 10, 2023 (Exact)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


104
104
{'location': 'Brown Creek', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Elevation:': '6300 ft', 'Vertical Fall:': '750 ft', 'Destructive Size:': 'D3', 'Relative Size:': 'R2', 'Type:': 'WS-Wet Slab', 'Bed Surface:': 'G-Ground', 'Slab Thickness:': '200 cm (6.5 ft)', 'Width:': '200 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 9, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'It ran sometime either this morning (2/9) or last evening after 5pm, when I photographed the glide crack on the left and there was no sign whatsoever of the patch weakening that has now failed on the right.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


105
105
{'location': 'Disbrow', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'SE', 'Slope Angle:': '40°', 'Elevation:': '6000 ft', 'Vertical Fall:': '50 ft', 'Destructive Size:': 'D1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '30 cm (1 ft)', 'Width:': '20 ft', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Feb 8, 2023 (Exact)', 'Occurrence Time': '12:38 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Slabs failed at two interfaces. One is a new/old snow from last night on graupel. The second is on a layer of decomposing stellar dendrites that fell last week.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


106
106
{'location': 'Grant', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Slope Angle:': '40°', 'Elevation:': '6500 ft', 'Vertical Fall:': '1000 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R1', 'Type:': 'SS-Soft Slab', 'Slab Thickness:': '50 cm (1.5 ft)', 'Width:': '100 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 7, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Fairly obscured view, but was able to see crown and debris looking towards the shoulder of grant. This slide was itty bitty relative to the terrain. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

107
107
{'location': 'Blaine', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Elevation:': '7100 ft', 'Vertical Fall:': '1000 ft', 'Destructive Size:': 'D1', 'Type:': 'SS-Soft Slab', 'Occurrence Date': 'Feb 6, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Saw debris from side of Blaine. Unknown type. Possible cornice fall or small wind slab. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


108
108
{'location': 'Doris', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Aspect:': 'NE', 'Slope Angle:': '40°', 'Elevation:': '7000 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R3', 'Type:': 'SS-Soft Slab', 'Slab Thickness:': '40 cm (1.5 ft)', 'Width:': '100 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 5, 2023 (Estimated)', 'Occurrence Time': '16:07 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Observed three wind slabs. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


109
109
{'location': 'Chute above Skiumah Lake', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Slope Angle:': '38°', 'Elevation:': '5125 ft', 'Vertical Fall:': '100 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '35 cm (1 ft)', 'Width:': '30 ft', 'Trigger:': 'AS-Skieru-Unintentional', 'Occurrence Date': 'Feb 5, 2023 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Caught and carried 2 riders over a cliff band.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


110
110
{'location': 'Blaine', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Elevation:': '7000 ft', 'Destructive Size:': 'D1.5', 'Type:': 'SS-Soft Slab', 'Occurrence Date': 'Feb 4, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Unknown type. Guessing soft slab. Blown in crown. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


111
111
{'location': 'Tranquil Basin', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Elevation:': '7000 ft', 'Vertical Fall:': '200 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'L-Dry Loose', 'Bed Surface:': 'S-New Snow', 'Trigger:': 'AS-Skieru-Unintentional', 'Occurrence Date': 'Feb 2, 2023 (Exact)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


112
112
{'location': 'Running Rabbit', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Occurrence Date': 'Feb 2, 2023 (Exact)', 'Occurrence Time': '13:00 (Exact)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


113
113
{'location': 'Flathead Range', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '5', 'Slope Angle:': '40°', 'Elevation:': '7200 ft', 'Vertical Fall:': '60 ft', 'Destructive Size:': 'D1', 'Type:': 'L-Dry Loose', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Feb 1, 2023 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Small loose dry triggered on small rollovers at all elevations. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


114
114
{'location': 'Flathead Range', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '5', 'Aspect:': 'NE', 'Slope Angle:': '40°', 'Elevation:': '7200 ft', 'Vertical Fall:': '100 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '20 cm (0.5 ft)', 'Width:': '30 ft', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Feb 1, 2023 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Found some lightly wind drifted features and freshly wind drifted snow was reactive with ski cuts. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


115
115
{'location': 'Grant Ridge drainage', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Destructive Size:': 'D3', 'Width:': '1500 ft', 'Occurrence Date': 'Feb 1, 2023 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'Guess on size. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


116
116
{'location': 'Running Rabbit', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'SW', 'Slope Angle:': '35°', 'Elevation:': '5400 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1.5', 'Type:': 'WL-Wet Loose', 'Bed Surface:': 'S-New Snow', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 1, 2023 (Exact)', 'Occurrence Time': '13:00 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Recent wet loose debris in path 1163.  Could not see where these started. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


117
117
{'location': 'Swan Range South of Swan Lake', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'NW', 'Slope Angle:': '45°', 'Elevation:': '6800 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '30 cm (1 ft)', 'Width:': '20 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 1, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Small crowns that had drifted back in.  Could not make out track.  Did not approach to look for debris piles.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


118
118
{'location': 'Swan Range South of Swan Lake', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SW', 'Slope Angle:': '45°', 'Elevation:': '4700 ft', 'Vertical Fall:': '15 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '30 cm (1 ft)', 'Width:': '30 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Feb 1, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Small crown on a convexity.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


119
119
{'location': 'Running Rabit', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'S', 'Elevation:': '5800 ft', 'Vertical Fall:': '300 ft', 'Destructive Size:': 'D1', 'Type:': 'SS-Soft Slab', 'Width:': '60 ft', 'Trigger:': 'AS-Skieru-Unintentional', 'Occurrence Date': 'Jan 29, 2023 (Exact)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


120
120
{'location': 'Jewel', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Elevation:': '7000 ft', 'Vertical Fall:': '50 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '20 cm (0.5 ft)', 'Width:': '15 ft', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Jan 29, 2023 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': "One slab was hard. This slab propagated and didn't slide far due to the terrain we were in. ", 'Latitude': '48.402214', 'Longitude': '-114.13365'}

121
121
{'location': 'Jewel Basin', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '4', 'Aspect:': 'W', 'Slope Angle:': '45°', 'Elevation:': '7000 ft', 'Vertical Fall:': '400 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R2', 'Type:': 'L-Dry Loose', 'Bed Surface:': 'S-New Snow', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Jan 28, 2023 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Loose dry on west aspects. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


122
122
{'location': 'Running Rabbit Mtn - S face Path 1163', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'S', 'Destructive Size:': 'D2', 'Bed Surface:': 'I-New/Old Interface', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Jan 28, 2023 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'Only debris in the runout clearly visible. Likely a wind slab. Released in upper part of the path but visibility obscured by fog.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


123
123
{'location': 'Running Rabbit Mtn - SE face Shed 10', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Destructive Size:': 'D2', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Jan 28, 2023 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'Only debris in the runout clearly visible. Likely a wind slab. Released in upper part of the path but visibility obscured by fog.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


124
124
{'location': 'Snowshed', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Aspect:': 'N', 'Vertical Fall:': '50 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '10 cm (0.5 ft)', 'Width:': '20 ft', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Jan 28, 2023 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'Small predictable storm slab avalanches triggered in steeper pockets of rolling terrain.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


125
125
{'location': 'Jewel', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Aspect:': 'N', 'Slope Angle:': '40°', 'Elevation:': '7000 ft', 'Vertical Fall:': '300 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R1', 'Type:': 'SS-Soft Slab', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Jan 27, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'We saw a few chunky piles of debris that had wind blown snow on them. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


126
126
{'location': 'Noisy Basin Pt 6437', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'NE', 'Elevation:': '6200 ft', 'Vertical Fall:': '200 ft', 'Destructive Size:': 'D1', 'Type:': 'L-Dry Loose', 'Bed Surface:': 'S-New Snow', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Jan 27, 2023 (Exact)', 'Occurrence Time': '11:15 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Stomping at the top of very steep slopes produced small but long running sluffs in the new snow.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


127
127
{'location': 'Noisy Basin Pt 6437', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '10', 'Aspect:': 'NE', 'Slope Angle:': '40°', 'Elevation:': '6300 ft', 'Vertical Fall:': '150 ft', 'Destructive Size:': 'D1.5', 'Type:': 'L-Dry Loose', 'Bed Surface:': 'S-New Snow', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Jan 27, 2023 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Small natural sluffs in most very steep (40*) terrain features.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


128
128
{'location': 'Lost Johnny', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Elevation:': '6200 ft', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '50 cm (1.5 ft)', 'Occurrence Date': 'Jan 25, 2023 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Individual mentioned it did not appear to be a windslab. Unknown size. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


129
129
{'location': 'Cascadilla', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Elevation:': '5200 ft', 'Destructive Size:': 'D1', 'Type:': 'SS-Soft Slab', 'Slab Thickness:': '12 cm (0.5 ft)', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Jan 22, 2023 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'Thin wind slab', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


130
130
{'location': 'Lone Pine', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'NE', 'Elevation:': '6700 ft', 'Destructive Size:': 'D1', 'Type:': 'SS-Soft Slab', 'Slab Thickness:': '15 cm (0.5 ft)', 'Width:': '30 ft', 'Trigger:': 'AE-Explosive triggeredc-Intentional', 'Occurrence Date': 'Jan 22, 2023 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Slabs consisted of wind-drifted snow.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


131
131
{'location': 'Start zone ~ 48.0772N / -113.8937W', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'W', 'Elevation:': '6600 ft', 'Destructive Size:': 'D1.5', 'Type:': 'L-Dry Loose', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Jan 21, 2023 (Exact)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


132
132
{'location': 'Crater Mountain, Swan Range', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Aspect:': 'S', 'Elevation:': '6200 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Jan 21, 2023 (Exact)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


133
133
{'location': 'Jenny Lake', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Elevation:': '6300 ft', 'Vertical Fall:': '20 ft', 'Destructive Size:': 'D1', 'Type:': 'SS-Soft Slab', 'Slab Thickness:': '60 cm (2 ft)', 'Trigger:': 'AM-Snowmobiler-Remote', 'Occurrence Date': 'Jan 21, 2023 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Small, steep pocket on larger slope that cracked when snowbiker landed a jump.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


134
134
{'location': 'east of Kona gully', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Aspect:': 'N', 'Slope Angle:': '40°', 'Elevation:': '5500 ft', 'Vertical Fall:': '75 ft', 'Destructive Size:': 'D1', 'Type:': 'L-Dry Loose', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '4 cm (0 ft)', 'Width:': '5 ft', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Jan 19, 2023 (Exact)', 'Occurrence Time': '15:00 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Triggered several very small but long running sluffs on very steep slopes near the canyon floor. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

135
135
{'location': 'N. Whitefish Range', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Destructive Size:': 'D1', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Jan 17, 2023 (Exact)', 'Occurrence Time': '13:31 (Exact)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


136
136
{'location': 'Lost Johnny', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Slope Angle:': '38°', 'Elevation:': '6700 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R2', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '60 cm (2 ft)', 'Width:': '200 ft', 'Trigger:': 'AS-Skierr-Remote', 'Occurrence Date': 'Jan 15, 2023 (Exact)', 'Occurrence Time': '12:45 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Walked up to the ridgeline and gave one soft stomp and triggered the first slab. This slab failed between two naturals that must have ran a few days ago. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


137
137
{'location': 'Lost Johnny', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Slope Angle:': '38°', 'Elevation:': '6800 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R2', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '30 cm (1 ft)', 'Width:': '100 ft', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Jan 15, 2023 (Exact)', 'Occurrence Time': '13:48 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Slab failed at a convexity from a falling cornice that we triggered. Again, this slab also failed between two other naturals. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


138
138
{'location': 'Penrose N path', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'N', 'Elevation:': '4500 ft', 'Destructive Size:': 'D2.5', 'Type:': 'WL-Wet Loose', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Jan 15, 2023 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': "Looked like 6'+ debris and 150' wide.  Unsure of elevation of start zone.  Fresh from last warm period, distinct from other N aspect loose wet debris from Santa Soaker.  ", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


139
139
{'location': 'Cascadilla Creek', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '10', 'Aspect:': 'NE', 'Type:': 'WL-Wet Loose', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Jan 14, 2023 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'Recent wet slides observed at all aspects', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


140
140
{'location': 'Hay Creek', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Destructive Size:': 'D2', 'Relative Size:': 'R2', 'Occurrence Date': 'Jan 13, 2023 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Older debris pile.  Possible loose wet from mid-January warming.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


141
141
{'location': 'Skook chute', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Elevation:': '6200 ft', 'Destructive Size:': 'D2', 'Type:': 'WL-Wet Loose', 'Slab Thickness:': '35 cm (1 ft)', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Jan 13, 2023 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'Terminus at 48.51310, -114.31549 piled up around 120 cm depth, overflowed road and small amount of debris ran to lower road. Path as high as can see, assume full distance but did not appear to step down. Snow pit obs next to road here.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


142
142
{'location': 'Sheep Mt.', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Destructive Size:': 'D2', 'Occurrence Date': 'Jan 13, 2023 (Estimated)', 'Occurrence Time': '10:06 (Estimated)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


143
143
{'location': 'Lost Johnny', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '10', 'Elevation:': '5500 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R2', 'Type:': 'WL-Wet Loose', 'Occurrence Date': 'Jan 13, 2023 (Estimated)', 'Occurrence Time': '16:50 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': "General summary of avalanches we observed from Friday's warmup. Saw roughly 10 wet loose avalanches on all aspects at middle elevation. Most were small/medium in size.", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


144
144
{'location': 'North Dickey', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'SE', 'Elevation:': '5600 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R2', 'Type:': 'U-Unknown', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '60 cm (2 ft)', 'Width:': '200 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Jan 13, 2023 (Estimated)', 'Occurrence Time': '18:02 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Vague details. Observed from a long ways away. Crown appeared fairly recent. Best guess of timing would be during recent warming and rain. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


145
145
{'location': 'SE Steep chutes above Dickie Creek', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Aspect:': 'SE', 'Slope Angle:': '40°', 'Elevation:': '6200 ft', 'Vertical Fall:': '300 ft', 'Destructive Size:': 'D1', 'Type:': 'WL-Wet Loose', 'Bed Surface:': 'U-Unknown', 'Width:': '50 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Jan 13, 2023 (Estimated)', 'Occurrence Time': '12:00 (Estimated)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


146
146
{'location': 'Lost Johnny', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Slope Angle:': '40°', 'Elevation:': '6000 ft', 'Vertical Fall:': '1000 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R2', 'Type:': 'WL-Wet Loose', 'Occurrence Date': 'Jan 13, 2023 (Estimated)', 'Occurrence Time': '15:53 (Estimated)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


147
147
{'location': 'Skinny skook chute 1', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Elevation:': '6200 ft', 'Destructive Size:': 'D1.5', 'Type:': 'WL-Wet Loose', 'Slab Thickness:': '35 cm (1 ft)', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Jan 13, 2023 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'Terminus at 48.51177, -114.31392 deposited estimated 60 cm on upper Rd. Appeared to squiggle through woods. Did not step down to lower layers, ran on Xmas crust', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


148
148
{'location': 'Skook Chutes', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'S', 'Slope Angle:': '40°', 'Elevation:': '6000 ft', 'Vertical Fall:': '300 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R1', 'Type:': 'WL-Wet Loose', 'Bed Surface:': 'S-New Snow', 'Width:': '20 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Jan 12, 2023 (Estimated)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

149
149
{'location': 'Wildcat Mountain', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Elevation:': '6200 ft', 'Vertical Fall:': '400 ft', 'Destructive Size:': 'D2', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '30 cm (1 ft)', 'Width:': '100 ft', 'Trigger:': 'AM-Snowmobiler-Remote', 'Occurrence Date': 'Jan 11, 2023 (Exact)', 'Occurrence Time': '12:00 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Dry snow moving on rain crust. Remote triggered. No riders injured.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


150
150
{'location': 'Cascadilla', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '5', 'Aspect:': 'E', 'Elevation:': '7200 ft', 'Destructive Size:': 'D2', 'Type:': 'WL-Wet Loose', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Jan 10, 2023 (Exact)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


151
151
{'location': 'Marion Lake North Aspect', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'N', 'Elevation:': '6600 ft', 'Destructive Size:': 'D1', 'Type:': 'L-Dry Loose', 'Trigger:': 'AS-Skieru-Unintentional', 'Occurrence Date': 'Jan 4, 2023 (Exact)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


152
152
{'location': 'Skiumah Lake', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Elevation:': '7000 ft', 'Destructive Size:': 'D2', 'Type:': 'SS-Soft Slab', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Jan 4, 2023 (Estimated)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


153
153
{'location': "Great Northern Sub Peak 8508'", 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Elevation:': '7800 ft', 'Destructive Size:': 'D3', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'G-Ground', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Jan 2, 2023 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'Deep Slab/Glide. Bed surface is a smooth polished slab of bedrock.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


154
154
{'location': 'Disbrow Creek', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Elevation:': '7000 ft', 'Destructive Size:': 'D1.5', 'Type:': 'L-Dry Loose', 'Trigger:': 'NC-Cornice Fall', 'Occurrence Date': 'Dec 31, 2022 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'Failed within recent storm snow', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


155
155
{'location': 'Shed 7 West', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Elevation:': '5600 ft', 'Destructive Size:': 'D1', 'Type:': 'SS-Soft Slab', 'Slab Thickness:': '15 cm (0.5 ft)', 'Trigger:': 'AS-Skier', 'Occurrence Date': 'Dec 30, 2022 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'On a steep sidewall of the gully in the bottom of the path', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


156
156
{'location': 'East of WMR, near “half moon”', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SW', 'Elevation:': '5800 ft', 'Trigger:': 'U-Unknown', 'Occurrence Date': 'Dec 29, 2022 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'Photo was sent to me by a friend… I encouraged him to submit an observation w/ more details', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


157
157
{'location': "10' cut banks by road", 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'NE', 'Elevation:': '6400 ft', 'Vertical Fall:': '10 ft', 'Destructive Size:': 'D1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '40 cm (1.5 ft)', 'Trigger:': 'AK-Snowcatu-Unintentional', 'Occurrence Date': 'Dec 28, 2022 (Exact)', 'Occurrence Time': '00:25 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'Fracturing below moist snow 12/23', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


158
158
{'location': 'Skook Ridge', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Elevation:': '6800 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '20 cm (0.5 ft)', 'Width:': '20 ft', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Dec 28, 2022 (Exact)', 'Occurrence Time': '14:10 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': "Another slide triggered with a cornice drop that didn't involve as much debris.", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


159
159
{'location': 'Skook Ridge', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'NE', 'Elevation:': '6800 ft', 'Vertical Fall:': '125 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R2', 'Type:': 'C-Cornice', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '25 cm (1 ft)', 'Width:': '70 ft', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Dec 28, 2022 (Exact)', 'Occurrence Time': '14:15 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Triggered two soft slabs of drifted snow with cornice drops from the ridge. Car-sized cunks of cornice, though actual slab debris was more like D1.5.  Bed surface seemed to be older wind slab.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


160
160
{'location': 'Grant Ridge (Disbrow High Point)', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Elevation:': '6200 ft', 'Destructive Size:': 'D3', 'Type:': 'WL-Wet Loose', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 28, 2022 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'Observed from ridgeline on the other side of the drainage. Flat light/moderately poor visibility. Confidence poor on initiation/crown location/s, but significant debris filling the gully was apparent. Estimated size 3 given the path characteristics and other recent activity reported. Would need a better look for a more accurate report on this slide.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


161
161
{'location': 'Rescue', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Slope Angle:': '45°', 'Elevation:': '5500 ft', 'Vertical Fall:': '600 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R2', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'G-Ground', 'Slab Thickness:': '100 cm (3.5 ft)', 'Width:': '80 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 28, 2022 (Estimated)', 'Occurrence Time': '17:43 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Appeared to be a Glide Avalanche. See Photos. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


162
162
{'location': 'Penrose East Face', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Slope Angle:': '45°', 'Elevation:': '7500 ft', 'Vertical Fall:': '2000 ft', 'Destructive Size:': 'D2.5', 'Relative Size:': 'R3', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'U-Unknown', 'Width:': '300 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 28, 2022 (Estimated)', 'Occurrence Time': '17:45 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Observed from a distance. Upper face of Penrose appeared to have numerous crowns stretch most of the east face. Some looked to go down to the rock. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

163
163
{'location': 'Path 1163 S face Running Rabbit Mtn', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Slope Angle:': '40°', 'Elevation:': '6000 ft', 'Vertical Fall:': '1400 ft', 'Destructive Size:': 'D2.5', 'Relative Size:': 'R2', 'Type:': 'WL-Wet Loose', 'Bed Surface:': 'O-Old Snow', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 27, 2022 (Exact)', 'Occurrence Time': '00:08 (Exact)', 'Observer type': 'public', 'Avalanche Summary': "Main gully on looker's left headwall. Gouged down to the ground in track and runout entraining all the snow (photo)", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


164
164
{'location': 'Just south of Blue Rock cut', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Aspect:': 'E', 'Elevation:': '3700 ft', 'Destructive Size:': 'D2', 'Type:': 'WL-Wet Loose', 'Bed Surface:': 'G-Ground', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 27, 2022 (Exact)', 'Occurrence Time': '02:06 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Stopped in highway ditch. Damaged some vegetation. Gouged to the ground. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


165
165
{'location': 'Shed 6 E face Snowslip Mtn', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Slope Angle:': '40°', 'Elevation:': '4500 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R2', 'Type:': 'U-Unknown', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '75 cm (2.5 ft)', 'Width:': '30 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 27, 2022 (Exact)', 'Occurrence Time': '00:20 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'The only crown observed today not associated with a wet loose (photo). Mostly obscured from view, details lacking', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


166
166
{'location': 'Blue Rock cut, between Crystal and Stanton Creeks on US Highway 2', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '10', 'Aspect:': 'E', 'Slope Angle:': '3650°', 'Elevation:': '3500 ft', 'Destructive Size:': 'D1.5', 'Type:': 'WL-Wet Loose', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 27, 2022 (Exact)', 'Occurrence Time': '01:30 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Debris from 4 of the slides blocked the eastbound lane of US Highway 2. Debris 3-4 ft deep and 20-30 ft wide. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


167
167
{'location': 'Cascadilla S Side', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Slope Angle:': '40°', 'Elevation:': '5800 ft', 'Vertical Fall:': '1500 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R3', 'Type:': 'WL-Wet Loose', 'Bed Surface:': 'U-Unknown', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 27, 2022 (Estimated)', 'Occurrence Time': '20:59 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Assume this slide ran later in the storm since wet debris overran smoother looking debris. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


168
168
{'location': 'Red Meadow', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Destructive Size:': 'D3', 'Occurrence Date': 'Dec 26, 2022 (Estimated)', 'Occurrence Time': '19:22 (Estimated)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


169
169
{'location': 'Nyack', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'NE', 'Slope Angle:': '40°', 'Elevation:': '7000 ft', 'Vertical Fall:': '2000 ft', 'Destructive Size:': 'D3', 'Relative Size:': 'R3', 'Type:': 'U-Unknown', 'Bed Surface:': 'U-Unknown', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 26, 2022 (Estimated)', 'Occurrence Time': '20:22 (Estimated)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


170
170
{'location': 'Essex Creek', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '10', 'Aspect:': 'S', 'Elevation:': '6700 ft', 'Destructive Size:': 'D3', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 26, 2022 (Estimated)', 'Occurrence Time': '18:21 (Estimated)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


171
171
{'location': 'Grant', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Aspect:': 'E', 'Slope Angle:': '40°', 'Elevation:': '7500 ft', 'Vertical Fall:': '3000 ft', 'Destructive Size:': 'D3.5', 'Occurrence Date': 'Dec 26, 2022 (Estimated)', 'Occurrence Time': '22:15 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'Information based on photos and description. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


172
172
{'location': 'N. Dickey', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'SE', 'Destructive Size:': 'D3', 'Occurrence Date': 'Dec 26, 2022 (Estimated)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


173
173
{'location': 'Southern Whitefish Range', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Slope Angle:': '45°', 'Elevation:': '6000 ft', 'Vertical Fall:': '200 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R4', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '60 cm (2 ft)', 'Width:': '200 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 26, 2022 (Estimated)', 'Occurrence Time': '21:49 (Estimated)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


174
174
{'location': 'Steeps above road', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Aspect:': 'NE', 'Slope Angle:': '38°', 'Elevation:': '5400 ft', 'Vertical Fall:': '300 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R2', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '30 cm (1 ft)', 'Width:': '50 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 26, 2022 (Exact)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


175
175
{'location': 'Road cuts adjacent to the North Fork road', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Other', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '10', 'Aspect:': 'E', 'Slope Angle:': '35°', 'Elevation:': '3500 ft', 'Vertical Fall:': '40 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1.5', 'Type:': 'WL-Wet Loose', 'Bed Surface:': 'I-New/Old Interface', 'Width:': '10 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 26, 2022 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'These were noted on steep road cuts and cutbanks adjacent to the North Fork river. Aspects included both east and west. Vertical fall varied between 20-80 feet.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


176
176
{'location': 'Shed 7 West SE face Snowslip Mtn', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Slope Angle:': '35°', 'Elevation:': '6800 ft', 'Vertical Fall:': '1600 ft', 'Destructive Size:': 'D2.5', 'Relative Size:': 'R2', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '50 cm (1.5 ft)', 'Width:': '400 ft', 'Trigger:': 'NC-Cornice Fall', 'Occurrence Date': 'Dec 26, 2022 (Exact)', 'Occurrence Time': '00:13 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'Looks to have run on the Dec 20 storm interface. (photo)', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

177
177
{'location': 'Path 1163 S face Running Rabbit Mtn', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'S', 'Slope Angle:': '40°', 'Elevation:': '7000 ft', 'Vertical Fall:': '2000 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R1', 'Type:': 'WL-Wet Loose', 'Bed Surface:': 'I-New/Old Interface', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 26, 2022 (Exact)', 'Occurrence Time': '00:13 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'Could not see uppermost starting zone and uncertain if this may have been a slab?', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


178
178
{'location': 'SE face Mount Shields above Shields Ck', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'SE', 'Slope Angle:': '40°', 'Elevation:': '6800 ft', 'Vertical Fall:': '1500 ft', 'Destructive Size:': 'D2.5', 'Relative Size:': 'R2', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '50 cm (1.5 ft)', 'Width:': '300 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 26, 2022 (Exact)', 'Occurrence Time': '00:13 (Exact)', 'Observer type': 'public', 'Avalanche Summary': '2 separate avalanches D2-2.5. Could not see debris terminus (photo)', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


179
179
{'location': 'Shed 4D Cutbank E face of Snowslip Mtn', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Slope Angle:': '40°', 'Elevation:': '4600 ft', 'Vertical Fall:': '150 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R2', 'Type:': 'WL-Wet Loose', 'Bed Surface:': 'G-Ground', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 26, 2022 (Exact)', 'Occurrence Time': '00:25 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'Reported by work train crew. Debris stopped just short of the rail. Looks to have gouged to the ground. (photo)', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


180
180
{'location': 'West Side Road', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Slope Angle:': '45°', 'Elevation:': '4500 ft', 'Vertical Fall:': '50 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R3', 'Type:': 'WL-Wet Loose', 'Bed Surface:': 'G-Ground', 'Width:': '50 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 26, 2022 (Estimated)', 'Occurrence Time': '08:13 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Broke at ground. Entrained a quite the debris for such a little slope. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


181
181
{'location': 'Stryker Ridge', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Aspect:': 'E', 'Elevation:': '6300 ft', 'Destructive Size:': 'D2', 'Type:': 'U-Unknown', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 26, 2022 (Estimated)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


182
182
{'location': 'Elk', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Elevation:': '7000 ft', 'Vertical Fall:': '2500 ft', 'Destructive Size:': 'D3', 'Relative Size:': 'R3', 'Type:': 'WL-Wet Loose', 'Occurrence Date': 'Dec 26, 2022 (Estimated)', 'Occurrence Time': '18:04 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Observed a number of debris piles down into Dickey. All covered in recent snow. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


183
183
{'location': 'Dickey Creek', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Aspect:': 'S', 'Elevation:': '6700 ft', 'Vertical Fall:': '2000 ft', 'Destructive Size:': 'D3', 'Relative Size:': 'R3.5', 'Type:': 'WS-Wet Slab', 'Bed Surface:': 'O-Old Snow', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 26, 2022 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': '3 large debris piles in main fork of Dickey Creek. Debris included trees up to 12" diameter, was 3m+ deep in places and showed evidence of one path repeating during the storm with a wet pathway through the original debris pile! Could not clearly see crowns but am banking on WS given amount of the debris and adjacent wet slab crowns seen.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


184
184
{'location': 'Elk Mountain', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Elevation:': '7000 ft', 'Vertical Fall:': '1500 ft', 'Destructive Size:': 'D2.5', 'Relative Size:': 'R2', 'Type:': 'WL-Wet Loose', 'Bed Surface:': 'I-New/Old Interface', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 26, 2022 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'Only could see the debris piles in the runouts, but they were quite large for not having obvious crown lines (hard to see at distance).', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


185
185
{'location': 'Road cuts adjacent to the North Fork road', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Other', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '8', 'Aspect:': 'E', 'Slope Angle:': '35°', 'Elevation:': '3500 ft', 'Vertical Fall:': '60 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R2', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '40 cm (1.5 ft)', 'Width:': '40 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 26, 2022 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'These were noted on steep road cuts and cutbanks adjacent to the North Fork river. Aspects included both east and west. Vertical fall varied between 40-80 feet.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


186
186
{'location': 'Upper Dickey Creek', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'S', 'Elevation:': '5700 ft', 'Vertical Fall:': '1000 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R2', 'Type:': 'WS-Wet Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '125 cm (4 ft)', 'Width:': '50 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 26, 2022 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'Estimated slab depth and width from a distance, but saw definitive crownline and assume that it broke in the old persistent weak snow.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


187
187
{'location': 'Flathead Range (Tunnel Ridge)', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '7', 'Aspect:': 'S', 'Elevation:': '6700 ft', 'Vertical Fall:': '2000 ft', 'Destructive Size:': 'D2', 'Type:': 'WL-Wet Loose', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 26, 2022 (Estimated)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


188
188
{'location': 'SE side of Cascadilla', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'SE', 'Slope Angle:': '40°', 'Elevation:': '6000 ft', 'Vertical Fall:': '2000 ft', 'Destructive Size:': 'D2.5', 'Relative Size:': 'R3', 'Type:': 'U-Unknown', 'Bed Surface:': 'U-Unknown', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 26, 2022 (Estimated)', 'Occurrence Time': '20:25 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': '1 slide appeared to have descended a fairly long way down the valley in the gully. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

189
189
{'location': 'Cascadilla N Side', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'N', 'Slope Angle:': '40°', 'Elevation:': '5500 ft', 'Vertical Fall:': '1000 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R3.5', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '40 cm (1.5 ft)', 'Width:': '200 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 26, 2022 (Estimated)', 'Occurrence Time': '20:27 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Upper crown appeared to be a dry slab. Lower crown looked more like it failed as a wet slab given the jagged nature of the crown line. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


190
190
{'location': 'Red Meadow', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '5', 'Occurrence Date': 'Dec 25, 2022 (Estimated)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


191
191
{'location': 'Path 1163 Headwall S face Running Rabbit Mtn', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SW', 'Slope Angle:': '40°', 'Elevation:': '5500 ft', 'Vertical Fall:': '1100 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '50 cm (1.5 ft)', 'Width:': '100 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 25, 2022 (Exact)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


192
192
{'location': 'Jakes S Face Snowslip Mtn', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'S', 'Slope Angle:': '40°', 'Elevation:': '4800 ft', 'Vertical Fall:': '600 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R2', 'Type:': 'WL-Wet Loose', 'Bed Surface:': 'I-New/Old Interface', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 25, 2022 (Exact)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


193
193
{'location': 'Highway 2 Cutbanks near Skyland TH', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '5', 'Aspect:': 'SE', 'Slope Angle:': '40°', 'Elevation:': '5000 ft', 'Vertical Fall:': '50 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R3', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '15 cm (0.5 ft)', 'Width:': '50 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 24, 2022 (Exact)', 'Occurrence Time': '00:28 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'Some looked to have been snowmobile triggered. But at last two were naturals that occurred between 1800-1900 hrs. (photo)', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


194
194
{'location': 'Rescue Creek', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '20', 'Aspect:': 'W', 'Slope Angle:': '35°', 'Elevation:': '4000 ft', 'Vertical Fall:': '6 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '8 cm (0.5 ft)', 'Width:': '10 ft', 'Trigger:': 'AS-Skieru-Unintentional', 'Occurrence Date': 'Dec 23, 2022 (Exact)', 'Occurrence Time': '15:35 (Exact)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


195
195
{'location': 'BNSF/ Highway 2 right of way', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'S', 'Elevation:': '4075 ft', 'Vertical Fall:': '80 ft', 'Destructive Size:': 'D1.5', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '40 cm (1.5 ft)', 'Width:': '75 ft', 'Trigger:': 'AV-Vehicle', 'Occurrence Date': 'Dec 22, 2022 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Triggered by plowing debris from railroad. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


196
196
{'location': 'Shed 5 path, Snowslip Mountain', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Elevation:': '5700 ft', 'Destructive Size:': 'D1.5', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '80 cm (2.5 ft)', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 21, 2022 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Bed surface looked close to ground, with little snow or blowing snow obscuring crown. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


197
197
{'location': 'Great Bear Creek', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Slope Angle:': '40°', 'Elevation:': '6600 ft', 'Destructive Size:': 'D2.5', 'Type:': 'U-Unknown', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '75 cm (2.5 ft)', 'Width:': '600 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 21, 2022 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': "Crown on ESE-facing burn just below ridgeline. Wrapped across several terrain features and through burned snags. Couldn't see runout of debris.Date, slab thickness and width estimates. ", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


198
198
{'location': 'Broken Bridge Bowl, Mt. Furlong', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'NW', 'Slope Angle:': '38°', 'Elevation:': '7200 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R2', 'Type:': 'U-Unknown', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '100 cm (3.5 ft)', 'Occurrence Date': 'Dec 21, 2022 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Higher, more recent-looking slide on skiers right at top, at typical entry to bowl. Thick crown but not wide. Similar sized slide ~300 ft lower and further skiers left in bowl. More debris on bed surface.  ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


199
199
{'location': 'Running rabbit mountain', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Other', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Occurrence Date': 'Dec 20, 2022 (Exact)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


200
200
{'location': 'Infinity Path, Snowslip Mountain', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'S', 'Elevation:': '6050 ft', 'Vertical Fall:': '1500 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R2', 'Width:': '150 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 20, 2022 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Crown mostly blown in. Extent of debris visible from highway.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


201
201
{'location': 'East face, Mt. Cameahwait', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Aspect:': 'E', 'Elevation:': '7200 ft', 'Destructive Size:': 'D3', 'Type:': 'HS-Hard Slab', 'Slab Thickness:': '100 cm (3.5 ft)', 'Width:': '500 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 20, 2022 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Two wide crowns visible skiers below ridge extending south from Mt. Cameahwait. Not in main bowl, as is typical. Both seemed large and likely the result of wind loading on steep, unsuppported face, though southern crown wrapped around a nose/ sub ridge.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

202
202
{'location': 'SE face of Running Rabbit Mtn - Railroad Shed 10 feeder path', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Destructive Size:': 'D2', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '100 cm (3.5 ft)', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 20, 2022 (Exact)', 'Observer type': 'public', 'Avalanche Summary': "Runout was at least to 5400', likely further, but out of view. Likely this failed on Nov. facets given the slab thickness.", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


203
203
{'location': 'South face of Running Rabbit Mtn - Railroad Path 1163', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'S', 'Elevation:': '7100 ft', 'Vertical Fall:': '2500 ft', 'Destructive Size:': 'D2.5', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'U-Unknown', 'Slab Thickness:': '60 cm (2 ft)', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 20, 2022 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'Crown was mostly drifted in. Dimensions are rough estimates. Debris ran to 4600 ft. Uncertain if this failed on Nov. facets.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


204
204
{'location': 'Cascadilla Creek', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Elevation:': '5800 ft', 'Destructive Size:': 'D2', 'Type:': 'U-Unknown', 'Bed Surface:': 'U-Unknown', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 20, 2022 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Crown in sparse trees on northeast facing slope above lake.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


205
205
{'location': 'East Face of Nyack Mountain, Cascadilla Creek', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '4', 'Aspect:': 'E', 'Slope Angle:': '45°', 'Elevation:': '6700 ft', 'Destructive Size:': 'D2', 'Type:': 'U-Unknown', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 20, 2022 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': "At least 3 partially filled crowns on the east face of Nyack Mountain above Cascadilla Creek. Generally at base of steepest terrain. Highest about 7000 ft. Possibly triggered by sluffing. Couldn't tell extent of runout; whole apron rough with debris.", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


206
206
{'location': 'Essex High Rustler/ Backdoor Chute/ Gunbarrel', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Elevation:': '6250 ft', 'Destructive Size:': 'D2', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 20, 2022 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': "Crown mostly blown in except skiers right side. Ran from top, just below trees. Couldn't see extent of runout.", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


207
207
{'location': 'Crystal Creek', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Elevation:': '6800 ft', 'Destructive Size:': 'D3', 'Type:': 'U-Unknown', 'Slab Thickness:': '150 cm (5 ft)', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 20, 2022 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'On apron below headwall. Deep crown, possibly because slope filled with sluff debris. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


208
208
{'location': 'South face of Snowslip Mtn - Railroad Shed 7 West', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'S', 'Elevation:': '6200 ft', 'Destructive Size:': 'D2', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '75 cm (2.5 ft)', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 20, 2022 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'Crown drifted back in, dimensions are rough estimates. Thinking this likely failed on Nov. facets given the crown and visible ground features. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


209
209
{'location': 'Highway 2 corridor', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '4', 'Elevation:': '4100 ft', 'Destructive Size:': 'D1', 'Type:': 'SS-Soft Slab', 'Slab Thickness:': '12 cm (0.5 ft)', 'Width:': '15 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 20, 2022 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'several small soft slabs failing in the storm snow on steep cut banks above the Hwy. These were 3-5" thick and mostly only propagated 20-30" but a few pushing 50\'.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


210
210
{'location': 'Stryker Loop', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Destructive Size:': 'D2', 'Slab Thickness:': '60 cm (2 ft)', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 20, 2022 (Estimated)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


211
211
{'location': 'No name peak N side Noisy Creek', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'S', 'Elevation:': '5500 ft', 'Destructive Size:': 'D1', 'Type:': 'SS-Soft Slab', 'Slab Thickness:': '30 cm (1 ft)', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 18, 2022 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': "N R3 D1 at 5500' S above cliff supported slope.     N R1 D1 at 6200' S, small part of larger bowl.", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


212
212
{'location': 'Apgars', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'SE', 'Slope Angle:': '38°', 'Elevation:': '5500 ft', 'Vertical Fall:': '20 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'L-Dry Loose', 'Bed Surface:': 'S-New Snow', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Dec 18, 2022 (Exact)', 'Occurrence Time': '13:19 (Exact)', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


213
213
{'location': 'Apgar Range', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'N', 'Elevation:': '5800 ft', 'Destructive Size:': 'D1', 'Type:': 'SS-Soft Slab', 'Slab Thickness:': '8 cm (0.5 ft)', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Dec 18, 2022 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'See details above. Would have run further downslope if slope angle were steeper.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


214
214
{'location': 'WMR', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Elevation:': '6400 ft', 'Destructive Size:': 'D1.5', 'Slab Thickness:': '30 cm (1 ft)', 'Trigger:': 'AE-Explosive triggeredc-Intentional', 'Occurrence Date': 'Dec 11, 2022 (Exact)', 'Occurrence Time': '10:30 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Results from avalanche mitigation with explosives.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

215
215
{'location': 'Shed 7 Ridge (BNSF test slopes)', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'NE', 'Elevation:': '6100 ft', 'Vertical Fall:': '50 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R2', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '30 cm (1 ft)', 'Width:': '30 ft', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Dec 9, 2022 (Exact)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


216
216
{'location': 'Slopes above the Beaver pond', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Slope Angle:': '40°', 'Elevation:': '6500 ft', 'Vertical Fall:': '100 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R2.5', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '45 cm (1.5 ft)', 'Width:': '40 ft', 'Trigger:': 'U-Unknown', 'Occurrence Date': 'Dec 4, 2022 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'It is unknown if it was skier-triggered or remote-triggered avalanche.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


217
217
{'location': 'Shed 7 West Snowslip Mtn', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'NE', 'Elevation:': '6800 ft', 'Vertical Fall:': '100 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '50 cm (1.5 ft)', 'Width:': '25 ft', 'Trigger:': 'NC-Cornice Fall', 'Occurrence Date': 'Dec 3, 2022 (Estimated)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


218
218
{'location': 'Whitefish Mountain', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'N', 'Elevation:': '7200 ft', 'Destructive Size:': 'D2', 'Type:': 'U-Unknown', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 3, 2022 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'Seen from distance; size and date guesstimated.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


219
219
{'location': 'Crown Bowl Avalanche', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'NE', 'Slope Angle:': '39°', 'Elevation:': '6600 ft', 'Vertical Fall:': '600 ft', 'Destructive Size:': 'D2', 'Type:': 'SS-Soft Slab', 'Slab Thickness:': '40 cm (1.5 ft)', 'Width:': '100 ft', 'Trigger:': 'U-Unknown', 'Occurrence Date': 'Dec 3, 2022 (Estimated)', 'Occurrence Time': '10:44 (Estimated)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


220
220
{'location': 'Mt. Aeneas', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'N', 'Elevation:': '7400 ft', 'Destructive Size:': 'D1.5', 'Type:': 'U-Unknown', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 2, 2022 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'Seen 12/4/22; date estimated from other recent activity', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


221
221
{'location': "Cal's", 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'S', 'Elevation:': '6200 ft', 'Vertical Fall:': '50 ft', 'Destructive Size:': 'D1', 'Type:': 'SS-Soft Slab', 'Slab Thickness:': '30 cm (1 ft)', 'Width:': '30 ft', 'Trigger:': 'AE-Explosive triggered', 'Occurrence Date': 'Dec 2, 2022 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Pocket of drifted snow at top of slope.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


222
222
{'location': 'Snowshed Mtn', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Elevation:': '6800 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R2', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '75 cm (2.5 ft)', 'Width:': '100 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 2, 2022 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'Looks like this was reported in an earlier observation too', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


223
223
{'location': 'Haskill', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SW', 'Elevation:': '6000 ft', 'Vertical Fall:': '15 ft', 'Destructive Size:': 'D1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '35 cm (1 ft)', 'Width:': '10 ft', 'Trigger:': 'AS-Skierr-Remote', 'Occurrence Date': 'Dec 2, 2022 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Triggered remotely by slope cut above. Steep, convex, unsupported knob', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


224
224
{'location': 'Snowshed Mtn SE face above Sheep Ck', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Elevation:': '7300 ft', 'Destructive Size:': 'D3', 'Relative Size:': 'R4', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '100 cm (3.5 ft)', 'Width:': '700 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 2, 2022 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'Could not view the runout', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


225
225
{'location': 'Mt. Cameahwait', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Elevation:': '7300 ft', 'Destructive Size:': 'D2.5', 'Relative Size:': 'R2', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '100 cm (3.5 ft)', 'Width:': '400 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 2, 2022 (Estimated)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


226
226
{'location': 'WMR', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Elevation:': '6700 ft', 'Vertical Fall:': '5 ft', 'Destructive Size:': 'D1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '35 cm (1 ft)', 'Width:': '15 ft', 'Trigger:': 'AS-Skieru-Unintentional', 'Occurrence Date': 'Dec 2, 2022 (Exact)', 'Occurrence Time': '14:05 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Triggered by skier cutting down steep slope onto cat track. Slab thinner, with pronounced depth hoar in failure layer.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


227
227
{'location': 'WMR - Haskill Slide (closed)', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Slope Angle:': '38°', 'Elevation:': '5900 ft', 'Vertical Fall:': '400 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R2', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'O-Old Snow', 'Trigger:': 'AS-Skierr-Remote', 'Occurrence Date': 'Dec 2, 2022 (Exact)', 'Occurrence Time': '08:30 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'Witnessed by skiers on East route skinning up. Rider skied out of moving debris or powder cloud.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


228
228
{'location': 'Mt. Aeneas', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'N', 'Elevation:': '7400 ft', 'Destructive Size:': 'D2', 'Type:': 'U-Unknown', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 2, 2022 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'Seen 12/4/22; guessing it ran sometime late in this last storm cycle.   It had some fresh snow on top of it, but was still fairly visible. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

229
229
{'location': 'test', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Occurrence Date': 'Dec 1, 2022 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'test', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


230
230
{'location': '48.0N -113.0W', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'S', 'Elevation:': '5000 ft', 'Vertical Fall:': '500 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '100 cm (3.5 ft)', 'Width:': '50 ft', 'Trigger:': 'U-Unknownc-Intentional', 'Occurrence Date': 'Dec 1, 2022 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'text text text  more text text', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


231
231
{'location': '48.0n -0113.0W', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Elevation:': '5500 ft', 'Destructive Size:': 'D5', 'Type:': 'R-Roof', 'Slab Thickness:': '50 cm (1.5 ft)', 'Trigger:': 'N-Naturalc-Intentional', 'Occurrence Date': 'Dec 1, 2022 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'text', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


232
232
{'location': 'Central Whitefish Range', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Destructive Size:': 'D1.5', 'Type:': 'SS-Soft Slab', 'Slab Thickness:': '50 cm (1.5 ft)', 'Trigger:': 'AS-Skierr-Remote', 'Occurrence Date': 'Dec 1, 2022 (Exact)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


233
233
{'location': 'E face of Peak 6437', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'E', 'Elevation:': '6000 ft', 'Destructive Size:': 'D1', 'Type:': 'L-Dry Loose', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 1, 2022 (Estimated)', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


234
234
{'location': 'Misery Cabin area', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Elevation:': '5800 ft', 'Destructive Size:': 'D1', 'Type:': 'SS-Soft Slab', 'Slab Thickness:': '40 cm (1.5 ft)', 'Trigger:': 'AM-Snowmobilec-Intentional', 'Occurrence Date': 'Nov 30, 2022 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'Short road cut that produced large amounts of debris', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


235
235
{'location': 'test chrome', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Elevation:': '3000 ft', 'Destructive Size:': 'D2', 'Type:': 'SS-Soft Slab', 'Slab Thickness:': '100 cm (3.5 ft)', 'Trigger:': 'AU-Unknown artificial triggeru-Unintentional', 'Occurrence Date': 'Nov 29, 2022 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'test chrome', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


236
236
{'location': 'Near Ghoulies Point', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'E', 'Slope Angle:': '37°', 'Elevation:': '6400 ft', 'Vertical Fall:': '125 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R2', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '1 cm (0 ft)', 'Width:': '15 ft', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Nov 28, 2022 (Exact)', 'Occurrence Time': '15:00 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'Very soft surface slab which limited propagation.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


237
237
{'location': 'Ghoulie to Beaver Ponds', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Slope Angle:': '38°', 'Elevation:': '6500 ft', 'Vertical Fall:': '100 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R2', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '35 cm (1 ft)', 'Width:': '20 ft', 'Trigger:': 'AS-Skieru-Unintentional', 'Occurrence Date': 'Nov 27, 2022 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'Slide was 12-16 inches deep and about 20 feet wide consisting of loose and unstable snow collected during the Sunday morning storm cycle, likely wind transported. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


238
238
{'location': 'Near Ghoulie Point', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'E', 'Slope Angle:': '37°', 'Elevation:': '6300 ft', 'Vertical Fall:': '125 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '1 cm (0 ft)', 'Width:': '15 ft', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Nov 27, 2022 (Exact)', 'Occurrence Time': '15:00 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'The surface slab was a bit too soft to propagate.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


239
239
{'location': 'Shed 7 West', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Elevation:': '6700 ft', 'Vertical Fall:': '50 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'C-Cornice', 'Width:': '15 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Nov 26, 2022 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'Very small (D1 size) cornice-fall observed in Shed 7 West, at least a couple days old. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


240
240
{'location': '34.33N 120.0W', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'S', 'Slope Angle:': '40°', 'Elevation:': '3000 ft', 'Vertical Fall:': '1000 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'U-Unknown', 'Bed Surface:': 'U-Unknown', 'Slab Thickness:': '100 cm (3.5 ft)', 'Width:': '100 ft', 'Trigger:': 'U-Unknownc-Intentional', 'Occurrence Date': 'Nov 25, 2022 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'test', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


241
241
{'location': 'Noisy Basin Road', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Elevation:': '5400 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '15 cm (0.5 ft)', 'Width:': '20 ft', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Nov 23, 2022 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'I approached the edge of the road and sent cracks from about 8ft back out to the edge, which then triggered a small section about 6-8” deep, and probably 20ft across to release. This was on a north-eastern aspect off the roadside and was probably between 30-40°.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


242
242
{'location': 'Crown Bowl, Jewel Basin', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NW', 'Destructive Size:': 'D1.5', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'O-Old Snow', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Nov 23, 2022 (Estimated)', 'Occurrence Time': '10:00 (Estimated)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Observed debris at the base of Crown Bowl.  Could not see track or start zone due to poor visability. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

243
243
{'location': 'Jewel Basin', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Slope Angle:': '45°', 'Elevation:': '6000 ft', 'Vertical Fall:': '10 ft', 'Destructive Size:': 'D1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '20 cm (0.5 ft)', 'Width:': '30 ft', 'Trigger:': 'N-Naturalr-Remote', 'Occurrence Date': 'Nov 23, 2022 (Exact)', 'Occurrence Time': '16:15 (Exact)', 'Observer type': 'forecaster', 'Avalanche Summary': 'Small slab on the lee side of a short, steep rollover.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


244
244
{'location': 'test firefox', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SW', 'Elevation:': '3000 ft', 'Destructive Size:': 'D2.5', 'Type:': 'U-Unknown', 'Slab Thickness:': '100 cm (3.5 ft)', 'Trigger:': 'U-Unknownc-Intentional', 'Occurrence Date': 'Nov 8, 2022 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'test firefox', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


245
245
{'location': 'Whitefish Mountain', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'N', 'Elevation:': '7200 ft', 'Destructive Size:': 'D2', 'Type:': 'U-Unknown', 'Slab Thickness:': '35 cm (1 ft)', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Nov 5, 2022 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'Date estimated', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


246
246
{'location': 'Crown Bowl', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'fac', 'Associated Observation': 'View Observation', '# Avalanches:': '5', 'Aspect:': 'W', 'Elevation:': '6900 ft', 'Destructive Size:': 'D1.5', 'Type:': 'SS-Soft Slab', 'Slab Thickness:': '25 cm (1 ft)', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Nov 4, 2022 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'Triggered by ski cuts', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

In [280]:
pd.DataFrame(forms).to_csv('/home/christine/Jupyter/snow/data/fac_avalanche_2022_2023.csv')

In [276]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)

In [270]:
while(True):
    driver.implicitly_wait(20)
    html = driver.page_source
    soup = BeautifulSoup(html, 'html.parser')
    new_form = get_obs_fields(soup, obs_type = 'Avalanche Occurrence')
    if new_form in forms:
        break
    else:
        forms.append(copy.deepcopy(new_form))
    next_arrow = WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.CSS_SELECTOR, ".nac-btn.nac-btn-primary.nac-next"))
    )
    next_button = driver.find_element(By.CSS_SELECTOR, "a.nac-btn-primary.nac-next")
    next_button.click()
    time.sleep(20)
    n+=1
    print(len(forms))
    print(len(set([json.dumps(elem) for elem in forms])))
    print(new_form)
    print('\n')

188
188
{'location': 'Snowlip Mtn Shed 6 avalanche path', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'BNSF Avalanche Safety', 'Observation Date': 'Jan 10, 2024', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Slope Angle:': '45°', 'Elevation:': '4600 ft', 'Vertical Fall:': '100 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R1', 'Type:': 'SS-Soft Slab', 'Problem Type:': 'Persistent Slab', 'Bed Surface:': 'G-Ground', 'Weak Layer Grain Type:': 'DH-Depth Hoar', 'Slab Thickness:': '25 cm (1 ft)', 'Width:': '75 ft', 'Trigger:': 'N-Natural', 'Terminus:': 'BP - Bottom of Path', 'Occurrence Date': 'Jan 10, 2024 (Estimated)', 'Occurrence Time': '06:00 (Estimated)', 'Observer Name': 'Adam Clark', 'Observer type': 'professional', 'Avalanche Summary': 'Observed around daybreak from Hwy. Investigated the crown around 1600 today', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


189
189
{'location': 'Small cut bank just east of Marias Pass along Hwy 2', 'Zone / Region': 'Other', 'Observer Affiliation': 'BNSF Avalanche Safety', 'Observation Date': 'Jan 10, 2024', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'N', 'Slope Angle:': '45°', 'Elevation:': '5200 ft', 'Vertical Fall:': '50 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'G-Ground', 'Slab Thickness:': '30 cm (1 ft)', 'Width:': '40 ft', 'Trigger:': 'U-Unknown', 'Occurrence Date': 'Jan 10, 2024 (Estimated)', 'Occurrence Time': '06:00 (Estimated)', 'Observer Name': 'Adam Clark', 'Observer type': 'professional', 'Avalanche Summary': 'Observed from Hwy around 0900. May have been triggered by plow debris?', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


190
190
{'location': 'Ghoulies Ridge', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Jan 10, 2024', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Elevation:': '6450 ft', 'Vertical Fall:': '150 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R4', 'Type:': 'SS-Soft Slab', 'Problem Type:': 'Persistent Slab', 'Bed Surface:': 'O-Old Snow', 'Weak Layer Grain Type:': 'FC-Faceted Crystals', 'Slab Thickness:': '80 cm (2.5 ft)', 'Width:': '150 ft', 'Trigger:': 'U-Unknown', 'Terminus:': 'U - Unknown', 'Occurrence Date': 'Jan 10, 2024 (Estimated)', 'Observer Name': 'blase reardon', 'Observer type': 'public', 'Avalanche Summary': "Crown and debris noted from uptrack to Ghoulie Point. Tracks to skier's left (North) so unclear if triggered or natural. Given location on typical lee side of ridge, slab may have been comprised of wind-stiffened and wind-thickened snow. ", 'Latitude': '48.402214', 'Longitude': '-114.13365'}


191
191
{'location': 'Beta Lakes Road', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Jan 10, 2024', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Aspect:': 'SE', 'Aspect Range:': 'SE, E', 'Elevation:': '5000 ft', 'Vertical Fall:': '10 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R2', 'Type:': 'SS-Soft Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '20 cm (0.5 ft)', 'Width:': '40 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Jan 9, 2024 (Estimated)', 'Observer Name': 'blase reardon', 'Observer type': 'forecaster', 'Avalanche Summary': 'Several small soft slabs on cutbanks above Beta Lakes road. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


192
192
{'location': 'Lost Johnny', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Jan 8, 2024', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Slope Angle:': '38°', 'Elevation:': '6300 ft', 'Vertical Fall:': '30 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R3', 'Type:': 'SS-Soft Slab', 'Problem Type:': 'Storm Slab', 'Bed Surface:': 'I-New/Old Interface', 'Weak Layer Grain Type:': 'FC-Faceted Crystals', 'Slab Thickness:': '60 cm (2 ft)', 'Width:': '90 ft', 'Trigger:': 'AS-Skieru-Unintentional', 'Occurrence Date': 'Jan 8, 2024 (Exact)', 'Observer Name': 'Cam Johnson', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


193
193
{'location': 'Mt. Barnaby', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Jan 7, 2024', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Aspect Range:': 'E, SE, S', 'Elevation:': '6000 ft', 'Vertical Fall:': '200 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R2', 'Type:': 'L-Dry Loose', 'Problem Type:': 'Dry Loose', 'Bed Surface:': 'S-New Snow', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Jan 7, 2024 (Exact)', 'Occurrence Time': '11:45 (Exact)', 'Observer Name': 'blase reardon', 'Observer type': 'forecaster', 'Avalanche Summary': 'Watched a natural sluff pour off cliffs onto apron below. Did not trigger a slab.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


194
194
{'location': 'Mt. Barnaby', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Jan 7, 2024', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Aspect Range:': 'NE', 'Elevation:': '6500 ft', 'Vertical Fall:': '125 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R2', 'Type:': 'SS-Soft Slab', 'Problem Type:': 'Storm Slab', 'Trigger:': 'N-Natural', 'Terminus:': 'BP - Bottom of Path', 'Occurrence Date': 'Jan 7, 2024 (Estimated)', 'Observer Name': 'blase reardon', 'Observer type': 'forecaster', 'Avalanche Summary': 'Soft slab of new and recent snow that wrapped around the base of a rock buttress. Probably triggered by sluff from above. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


195
195
{'location': 'Lost Johnny', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Jan 8, 2024', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Slope Angle:': '40°', 'Elevation:': '7000 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R2', 'Type:': 'SS-Soft Slab', 'Problem Type:': 'Wind Slab', 'Bed Surface:': 'U-Unknown', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Jan 7, 2024 (Estimated)', 'Observer Name': 'Cam Johnson', 'Observer type': 'forecaster', 'Avalanche Summary': 'Plus or minus a day with occurrence date. Assuming it was a wind slab due to its location being directly beneath a cornice.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


196
196
{'location': '6 Mile', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Jan 7, 2024', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Aspect:': 'SW', 'Aspect Range:': 'N, NE, E, SE, S, SW, W, NW', 'Elevation:': '6200 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R1', 'Type:': 'SS-Soft Slab', 'Problem Type:': 'Storm Slab', 'Bed Surface:': 'I-New/Old Interface', 'Weak Layer Grain Type:': 'MF-Melt Forms', 'Weak Layer Burial Date:': 'Jan 22, 2024', 'Slab Thickness:': '30 cm (1 ft)', 'Width:': '35 ft', 'Trigger:': 'AM-Snowmobileu-Unintentional', 'Occurrence Date': 'Jan 7, 2024 (Estimated)', 'Observer Name': 'guy zoellner', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


197
197
{'location': 'Mt. Barnaby', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Jan 7, 2024', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'N', 'Elevation:': '6675 ft', 'Vertical Fall:': '150 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R2', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'O-Old Snow', 'Weak Layer Burial Date:': 'Dec 31, 2023', 'Slab Thickness:': '85 cm (3 ft)', 'Width:': '100 ft', 'Trigger:': 'N-Natural', 'Terminus:': 'BP - Bottom of Path', 'Occurrence Date': 'Jan 7, 2024 (Estimated)', 'Occurrence Time': '02:00 (Estimated)', 'Observer Name': 'blase reardon', 'Observer type': 'forecaster', 'Avalanche Summary': 'Large hard slab composed mostly of accumulated sluff debris from slopes above.  Looked to be triggered by sluff from above. Slab ranged from 60-110 cm thick at crown face. Failed about 20 cm above most recent MFcr. Weak layer not distinct - perhaps small facets buried 1/31 (just under thin, almost indistinguishable rime crust). 7-10 cm of fresh snow on debris. Guestimating time as early AM on 1/7 based on snowfall at Stahl Peak SNOTEL ~ 1 mi away. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

198
198
{'location': 'Gibralter Ridge', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Jan 7, 2024', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'W', 'Elevation:': '6250 ft', 'Vertical Fall:': '150 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R2', 'Type:': 'HS-Hard Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '70 cm (2.5 ft)', 'Width:': '88 ft', 'Trigger:': 'N-Natural', 'Terminus:': 'BP - Bottom of Path', 'Occurrence Date': 'Jan 7, 2024 (Estimated)', 'Observer Name': 'blase reardon', 'Observer type': 'forecaster', 'Avalanche Summary': 'Crown and debris from large hard slab visible on apron below steep slopes. Guessing this slab occurred about the same time as one on Barnaby and involved slab composed of sluff debris. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


199
199
{'location': 'Skook Chutes', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Jan 8, 2024', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SW', 'Aspect Range:': 'W, SW, S', 'Slope Angle:': '42°', 'Elevation:': '6200 ft', 'Vertical Fall:': '275 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R2', 'Type:': 'SS-Soft Slab', 'Problem Type:': 'Storm Slab', 'Bed Surface:': 'I-New/Old Interface', 'Slab Thickness:': '25 cm (1 ft)', 'Width:': '350 ft', 'Trigger:': 'N-Natural', 'Terminus:': 'BP - Bottom of Path', 'Occurrence Date': 'Jan 6, 2024 (Estimated)', 'Observer Name': 'blase reardon', 'Observer type': 'forecaster', 'Avalanche Summary': 'Wide but shallow crown visible from canyon floor. Bed surface covered with 15-20 cm recent snow. Estimating it ran during period of high snowfall intensity on Jan. 6. Weak layer not readily apparent in profile at one part of crown. Suspect mid-storm density change. Crown wrapped all the way across the bowl, including in very steep rocks above main face. Debris piles 3-6 feet deep on uphill sides of trees below. Did not hit Canyon Creek trail.  Crown deepesst on northern flank, near bottom. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


200
200
{'location': 'Skook skin track', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Jan 8, 2024', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'SW', 'Aspect Range:': 'W', 'Slope Angle:': '41°', 'Elevation:': '5900 ft', 'Vertical Fall:': '50 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R2', 'Type:': 'SS-Soft Slab', 'Problem Type:': 'Storm Slab', 'Width:': '100 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Jan 6, 2024 (Estimated)', 'Observer Name': 'blase reardon', 'Observer type': 'forecaster', 'Avalanche Summary': 'Shallow crown(s) visible at convexity above skin track leading from notch to Skook. Also multiple debris piles. Fresh snow on both crowns and debris piles. Suspect soft slab failing mid storm during period of high snowfall intensity on 1/6. Debris partially covered roadbed where uptrack traverses out of the notch in piles 4-5 feet deep. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


201
201
{'location': 'Sixmile', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Jan 10, 2024', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'E', 'Slope Angle:': '35°', 'Elevation:': '6200 ft', 'Vertical Fall:': '60 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R2', 'Type:': 'HS-Hard Slab', 'Problem Type:': 'Wind Slab', 'Bed Surface:': 'O-Old Snow', 'Slab Thickness:': '40 cm (1.5 ft)', 'Width:': '50 ft', 'Trigger:': 'NC-Cornice Fall', 'Terminus:': 'BP - Bottom of Path', 'Occurrence Date': 'Jan 6, 2024 (Estimated)', 'Observer Name': 'Rob Millspaugh', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


202
202
{'location': 'SW face of GN', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observation Date': 'Jan 3, 2024', 'Associated Observation': 'View Observation', '# Avalanches:': '6', 'Aspect:': 'SW', 'Slope Angle:': '35°', 'Elevation:': '7000 ft', 'Vertical Fall:': '300 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R1', 'Type:': 'WL-Wet Loose', 'Problem Type:': 'Wet Loose', 'Bed Surface:': 'I-New/Old Interface', 'Trigger:': 'N-Natural', 'Terminus:': 'BP - Bottom of Path', 'Occurrence Date': 'Jan 2, 2024 (Exact)', 'Occurrence Time': '16:00 (Estimated)', 'Observer Name': 'Jeff Metsky', 'Observer type': 'public', 'Avalanche Summary': 'PM warming on SW faces triggered these slides on areas near rock bands.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


203
203
{'location': 'Great Northern', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Dec 30, 2023', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'W', 'Elevation:': '7500 ft', 'Destructive Size:': 'D1.5', 'Type:': 'WL-Wet Loose', 'Problem Type:': 'Wet Loose', 'Trigger:': 'AS-Skier', 'Occurrence Date': 'Dec 30, 2023 (Estimated)', 'Observer Name': 'Cam Johnson', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


204
204
{'location': 'Jewel Basin', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Dec 25, 2023', 'Associated Observation': 'View Observation', '# Avalanches:': '4', 'Aspect:': 'E', 'Aspect Range:': 'NE, E, SE', 'Elevation:': '6850 ft', 'Vertical Fall:': '100 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R1', 'Type:': 'L-Dry Loose', 'Problem Type:': 'Dry Loose', 'Bed Surface:': 'S-New Snow', 'Trigger:': 'AS-Skier', 'Occurrence Date': 'Dec 25, 2023 (Exact)', 'Observer Name': 'emily carino', 'Observer type': 'public', 'Avalanche Summary': 'Kicked off some sizeable sluff on a previously non-skied slope, and some more sluff skiing it a 2nd time. No sluff on run 3. No sluff on previously skied slopes.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


205
205
{'location': '10 lakes', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Dec 24, 2023', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'N', 'Slope Angle:': '40°', 'Elevation:': '6975 ft', 'Vertical Fall:': '150 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'L-Dry Loose', 'Problem Type:': 'Dry Loose', 'Bed Surface:': 'I-New/Old Interface', 'Weak Layer Grain Type:': 'DF-Decomposing and Fragmented Particles', 'Weak Layer Burial Date:': 'Dec 22, 2023', 'Trigger:': 'AS-Skierc-Intentional', 'Terminus:': 'MP - Middle of Path', 'Occurrence Date': 'Dec 24, 2023 (Exact)', 'Occurrence Time': '13:30 (Exact)', 'Observer Name': 'blase reardon', 'Observer type': 'forecaster', 'Avalanche Summary': 'Triggered D1 sluff while descendng steep, northerly slope. Good runout so not conesequential.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


206
206
{'location': 'Diorite Sill', 'Zone / Region': 'Other', 'Observation Date': 'Dec 27, 2023', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Aspect:': 'SE', 'Slope Angle:': '40°', 'Elevation:': '8300 ft', 'Vertical Fall:': '25 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'HS-Hard Slab', 'Problem Type:': 'Wind Slab', 'Bed Surface:': 'I-New/Old Interface', 'Weak Layer Grain Type:': 'DF-Decomposing and Fragmented Particles', 'Slab Thickness:': '12 cm (0.5 ft)', 'Width:': '10 ft', 'Trigger:': 'N-Natural', 'Terminus:': 'BP - Bottom of Path', 'Occurrence Date': 'Dec 24, 2023 (Estimated)', 'Occurrence Time': '15:00 (Estimated)', 'Observer Name': 'Jeff Metsky', 'Observer type': 'public', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


207
207
{'location': '10 lakes', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Dec 24, 2023', 'Associated Observation': 'View Observation', '# Avalanches:': '12', 'Aspect:': 'NE', 'Aspect Range:': 'E, NE, N', 'Elevation:': '6800 ft', 'Vertical Fall:': '150 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R2', 'Type:': 'L-Dry Loose', 'Problem Type:': 'Dry Loose', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 23, 2023 (Estimated)', 'Observer Name': 'blase reardon', 'Observer type': 'forecaster', 'Avalanche Summary': 'Numerous natural loose snow avalanches below cliffs. Probably ran during or shortly after snow fall ended. Perhaps with gusty winds that followed. Not obscured buy new snow. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

208
208
{'location': 'Mt. Brown NW face gullies', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Dec 23, 2023', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NW', 'Aspect Range:': 'W, NW, N', 'Elevation:': '6900 ft', 'Vertical Fall:': '2000 ft', 'Destructive Size:': 'D2.5', 'Type:': 'U-Unknown', 'Trigger:': 'N-Natural', 'Terminus:': 'MP - Middle of Path', 'Occurrence Date': 'Dec 23, 2023 (Exact)', 'Occurrence Time': '15:00 (Exact)', 'Observer Name': 'blase reardon', 'Observer type': 'forecaster', 'Avalanche Summary': 'Six natural avalanches observed in relatively short time, with largest overrunning and injuring one member of a climbing team. Probably dry loose slides, though party was well below release area. Elevation, aspect, vertical fall estimated from reports. Map location marks where party was caught, not start of slides. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


209
209
{'location': 'Mt. Brown NW face gullies', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Dec 23, 2023', 'Associated Observation': 'View Observation', '# Avalanches:': '5', 'Aspect:': 'NW', 'Aspect Range:': 'W, NW, N', 'Elevation:': '6900 ft', 'Vertical Fall:': '2000 ft', 'Destructive Size:': 'D2', 'Type:': 'U-Unknown', 'Trigger:': 'N-Natural', 'Terminus:': 'MP - Middle of Path', 'Occurrence Date': 'Dec 23, 2023 (Estimated)', 'Occurrence Time': '15:15 (Estimated)', 'Observer Name': 'blase reardon', 'Observer type': 'forecaster', 'Avalanche Summary': 'Six natural avalanches observed in relatively short time, with largest overrunning and injuring one member of a climbing team. Probably dry loose slides, though party was well below release area. Elevation, aspect, vertical fall estimated from reports. Map location marks where party was caught, not start of slides. The 5 smaller slides may not have involved that much snow, but the confined, very steep terrain channeled the debris and they likely packed the destructive force of D2 slides. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


210
210
{'location': 'Upper Paola', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observation Date': 'Dec 29, 2023', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Elevation:': '7200 ft', 'Destructive Size:': 'D2', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 23, 2023 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'Observed one crown from last Saturdays "sneaker-storm" in the alpine terrain of Paola Creek at 7200\' on a NE aspect. On 12/23 Tunnel Ridge Snow recorded 11" of snow (one 3"/hour rate). Given the partially filled in crown I would estimate the release to have occurred during this storm. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


211
211
{'location': 'Barnaby Peak', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Dec 23, 2023', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Elevation:': '6300 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'SS-Soft Slab', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 22, 2023 (Estimated)', 'Observer Name': 'blase reardon', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


212
212
{'location': 'Skook Chutes', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Dec 22, 2023', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SW', 'Aspect Range:': 'SW, S', 'Slope Angle:': '38°', 'Elevation:': '6000 ft', 'Vertical Fall:': '200 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R1', 'Type:': 'WL-Wet Loose', 'Problem Type:': 'Wet Loose', 'Bed Surface:': 'O-Old Snow', 'Width:': '20 ft', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 20, 2023 (Estimated)', 'Observer Name': 'Mark Dundas', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


213
213
{'location': 'Skook Chutes', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Dec 22, 2023', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SW', 'Aspect Range:': 'SW, S', 'Slope Angle:': '38°', 'Elevation:': '6250 ft', 'Vertical Fall:': '400 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R1', 'Type:': 'WL-Wet Loose', 'Problem Type:': 'Wet Loose', 'Bed Surface:': 'G-Ground', 'Width:': '20 ft', 'Trigger:': 'N-Natural', 'Terminus:': 'MP - Middle of Path', 'Occurrence Date': 'Dec 20, 2023 (Estimated)', 'Observer Name': 'Mark Dundas', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


214
214
{'location': 'WMR ski area', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'WMR ski patrol', 'Observation Date': 'Dec 15, 2023', '# Avalanches:': '3', 'Aspect:': 'S', 'Aspect Range:': 'SE, SW', 'Elevation:': '6200 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'WL-Wet Loose', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 15, 2023 (Exact)', 'Observer Name': 'WMR Patrol', 'Observer type': 'professional', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


215
215
{'location': 'Crown Bowl', 'Zone / Region': 'Swan Range', 'Observation Date': 'Dec 14, 2023', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NW', 'Elevation:': '6800 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'HS-Hard Slab', 'Problem Type:': 'Wind Slab', 'Slab Thickness:': '20 cm (0.5 ft)', 'Width:': '20 ft', 'Trigger:': 'AS-Skieru-Unintentional', 'Occurrence Date': 'Dec 14, 2023 (Exact)', 'Occurrence Time': '04:15 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'D1 Wind Slab Avalanche was triggered by the second skier on the slope. Slope was a steep NW aspect on skier\'s left just shy of the top of Crown Bowl. The Wind Slab was not present at top of the line but was present about half way down (approx 6700-6800\'). Crown depth estimated 6-12". Propagated 20-30 feet wide and a foot or two above Skier 2. While we didn\'t have time to assess the crown(avalanche happened at 4:15pm), we assume it was a hard wind slab on lower density snow but not on any persistent weak layer. We believe this gully to have been cross-loaded by the wind. Skier 2 was carried 5 feet, skied left and came to rest as the avalanche washed over the skier\'s legs and down slope. Skier 2\'s final position was about 20\' below the crown. Snow covered to the top of the boots of skier 2 who was able to self extricate and ski the remainder of the slope.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


216
216
{'location': 'Skook', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'WMR Patrol', 'Observation Date': 'Dec 13, 2023', '# Avalanches:': '1', 'Aspect:': 'SW', 'Aspect Range:': 'S, W, SW', 'Elevation:': '6000 ft', 'Destructive Size:': 'D1.5', 'Type:': 'L-Dry Loose', 'Bed Surface:': 'O-Old Snow', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 13, 2023 (Exact)', 'Observer Name': 'Jamie Burkholder', 'Observer type': 'professional', 'Avalanche Summary': 'Small loose snow avalanche visible in the Skook Chutes 1/13. Noted by WMR patrol ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


217
217
{'location': 'Upper Snyder Creek', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'Flathead Nordic Backcountry Patrol', 'Observation Date': 'Dec 15, 2023', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SE', 'Slope Angle:': '40°', 'Elevation:': '6500 ft', 'Vertical Fall:': '900 ft', 'Destructive Size:': 'D2.5', 'Relative Size:': 'R4', 'Type:': 'WL-Wet Loose', 'Problem Type:': 'Wet Loose', 'Bed Surface:': 'O-Old Snow', 'Weak Layer Grain Type:': 'MF-Melt Forms', 'Weak Layer Burial Date:': 'Dec 7, 2023', 'Slab Thickness:': '40 cm (1.5 ft)', 'Width:': '100 ft', 'Trigger:': 'U-Unknown', 'Terminus:': 'MP - Middle of Path', 'Occurrence Date': 'Dec 13, 2023 (Estimated)', 'Observer Name': 'Jackson George', 'Observer type': 'public', 'Avalanche Summary': 'Two old skier tracks lead directly to the top of this avalanche. The upper portion of the slide looked like it may have began as a slab avalanche, with a few large broken pockets rather than one distinct crown line (regrettably did not take photos of the start zone). It quickly turned into a loose wet slide removing all of the recent snow since Dec 7th and gliding on a stout raincrust. This is also the only exit gully for this run, so it may just be a coincidence that the ski tracks lead directly to a fractured pocket. There is a large wall with many hanging ice features directly above this gully as well, so a natural trigger would not be surprising here. Pretty confident that this occurred some time Wednesday.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

218
218
{'location': 'Flathead Range', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Dec 13, 2023', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Aspect:': 'SE', 'Aspect Range:': 'W, S, SE', 'Elevation:': '7000 ft', 'Destructive Size:': 'D1', 'Type:': 'L-Dry Loose', 'Problem Type:': 'Dry Loose', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 11, 2023 (Estimated)', 'Observer Name': 'Cam Johnson', 'Observer type': 'forecaster', 'Avalanche Summary': 'Saw a few loose dry sluffs that I am guessing occurred in the last couple days. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


219
219
{'location': 'east of WMR', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Dec 6, 2023', 'Associated Observation': 'View Observation', '# Avalanches:': '8', 'Aspect:': 'SW', 'Aspect Range:': 'W, SW, S, SE', 'Elevation:': '6000 ft', 'Vertical Fall:': '300 ft', 'Destructive Size:': 'D1.5', 'Type:': 'WL-Wet Loose', 'Bed Surface:': 'O-Old Snow', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 5, 2023 (Estimated)', 'Observer Name': 'blase reardon', 'Observer type': 'forecaster', 'Avalanche Summary': 'Debris from several wet snow slides visible in the Skook Chutes, possibly Half Moon and Big Slide', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


220
220
{'location': 'Crown Bowl', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Dec 7, 2023', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NW', 'Slope Angle:': '45°', 'Elevation:': '6900 ft', 'Vertical Fall:': '400 ft', 'Destructive Size:': 'D1.5', 'Relative Size:': 'R2', 'Type:': 'U-Unknown', 'Trigger:': 'U-Unknown', 'Terminus:': 'BP - Bottom of Path', 'Occurrence Date': 'Dec 5, 2023 (Estimated)', 'Observer Name': 'Rob Millspaugh', 'Observer type': 'forecaster', 'Avalanche Summary': 'Wet debris in the bottom of Crown Bowl.  Could not see much of the track or start zone with poor visibility.  Uncertain if this initiated as point release or slab. Elevation of origin and vertical fall are estimated guesses.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


221
221
{'location': '6437', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Dec 7, 2023', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'NE', 'Slope Angle:': '38°', 'Elevation:': '6200 ft', 'Vertical Fall:': '500 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'U-Unknown', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 5, 2023 (Estimated)', 'Observer Name': 'Rob Millspaugh', 'Observer type': 'forecaster', 'Avalanche Summary': 'Narrow and thin track leaving exposed rock.  Could not see origin or debris pile. Wet Loose or Wet Slab.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


222
222
{'location': 'Liebig', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Dec 18, 2023', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'E', 'Aspect Range:': 'NE, E', 'Elevation:': '7800 ft', 'Destructive Size:': 'D2', 'Relative Size:': 'R2', 'Type:': 'U-Unknown', 'Bed Surface:': 'U-Unknown', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 5, 2023 (Estimated)', 'Observer Name': 'Cam Johnson', 'Observer type': 'forecaster', 'Avalanche Summary': 'Observed two large debris piles off the crest of the Flathead. These appeared old. I suspect these failed during the warm atmospheric river in early December. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


223
223
{'location': 'Mt Penrose', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Dec 24, 2023', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'N', 'Aspect Range:': 'N, NE', 'Slope Angle:': '38°', 'Elevation:': '7000 ft', 'Vertical Fall:': '1500 ft', 'Destructive Size:': 'D2.5', 'Relative Size:': 'R2', 'Type:': 'U-Unknown', 'Trigger:': 'N-Natural', 'Terminus:': 'MP - Middle of Path', 'Occurrence Date': 'Dec 5, 2023 (Estimated)', 'Observer Name': 'Mark Dundas', 'Observer type': 'forecaster', 'Avalanche Summary': 'These avalanches occurred around 18-19 days ago and are adjacent to each other. The starting zone has been filled in with snow and wind-blown snow, and no crown line was visible. The debris was wet and likely triggered by rain, but it is impossible to tell if the slide was a Persistent Slab. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


224
224
{'location': 'WMR', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Dec 3, 2023', 'Associated Observation': 'View Observation', '# Avalanches:': '5', 'Aspect:': 'NE', 'Aspect Range:': 'E, N, S, W', 'Slope Angle:': '35°', 'Elevation:': '6800 ft', 'Destructive Size:': 'D1', 'Type:': 'SS-Soft Slab', 'Problem Type:': 'Storm Slab', 'Bed Surface:': 'I-New/Old Interface', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Dec 3, 2023 (Estimated)', 'Observer Name': 'Cam Johnson', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


225
225
{'location': 'Southern Whitefish Range', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Dec 2, 2023', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Aspect:': 'NE', 'Aspect Range:': 'N, E', 'Elevation:': '6500 ft', 'Destructive Size:': 'D1.5', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Dec 2, 2023 (Estimated)', 'Observer Name': 'Cam Johnson', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


226
226
{'location': 'Noisy', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Dec 2, 2023', 'Associated Observation': 'View Observation', '# Avalanches:': '3', 'Aspect:': 'NE', 'Aspect Range:': 'E, N', 'Elevation:': '6400 ft', 'Destructive Size:': 'D1', 'Type:': 'SS-Soft Slab', 'Problem Type:': 'Storm Slab', 'Trigger:': 'U-Unknown', 'Occurrence Date': 'Dec 2, 2023 (Estimated)', 'Observer Name': 'Cam Johnson', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


227
227
{'location': 'WMR', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Dec 2, 2023', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'SW', 'Elevation:': '6400 ft', 'Destructive Size:': 'D1.5', 'Type:': 'SS-Soft Slab', 'Problem Type:': 'Storm Slab', 'Trigger:': 'AS-Skier', 'Occurrence Date': 'Dec 2, 2023 (Estimated)', 'Observer Name': 'Cam Johnson', 'Observer type': 'forecaster', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


228
228
{'location': 'Fault 1', 'Zone / Region': 'Whitefish Range', 'Observer Affiliation': 'WMR Patrol', 'Observation Date': 'Dec 2, 2023', 'Associated Observation': 'View Observation', 'Occurrence Date': 'Dec 2, 2023 (Estimated)', 'Occurrence Time': '14:00 (Exact)', 'Observer type': 'professional', 'Avalanche Summary': 'SS-ASr-R3-D2-S', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


229
229
{'location': 'McDonald Valley', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Nov 18, 2023', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'S', 'Elevation:': '7000 ft', 'Vertical Fall:': '800 ft', 'Destructive Size:': 'D1', 'Type:': 'L-Dry Loose', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Nov 18, 2023 (Exact)', 'Observer type': 'public', 'Avalanche Summary': 'two natural point releases in the new snow that ran 800’.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

230
230
{'location': 'Great Northern', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observation Date': 'Nov 18, 2023', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'SW', 'Elevation:': '8000 ft', 'Destructive Size:': 'D1.5', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Nov 18, 2023 (Estimated)', 'Occurrence Time': '14:00 (Estimated)', 'Observer type': 'public', 'Avalanche Summary': 'Observed numerous wet loose slides that ran a long distance down solar faces on Great Northern. See photo. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


231
231
{'location': 'Noisy Basin', 'Zone / Region': 'Swan Range', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Nov 17, 2023', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'SW', 'Slope Angle:': '40°', 'Elevation:': '6500 ft', 'Vertical Fall:': '30 ft', 'Destructive Size:': 'D1', 'Relative Size:': 'R1', 'Type:': 'WL-Wet Loose', 'Problem Type:': 'Wet Loose', 'Bed Surface:': 'S-New Snow', 'Weak Layer Grain Type:': 'MF-Melt Forms', 'Width:': '10 ft', 'Trigger:': 'AS-Skierc-Intentional', 'Occurrence Date': 'Nov 17, 2023 (Estimated)', 'Occurrence Time': '14:34 (Estimated)', 'Observer Name': 'Cam Johnson', 'Observer type': 'forecaster', 'Avalanche Summary': 'Intentionally triggered two small wet loose avalanches. Both were harmless in size. These occurred on solar aspects in the afternoon. We observed natural roller balls prior to human triggers. ', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


232
232
{'location': 'Great Northern Peak', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observation Date': 'Nov 17, 2023', 'Associated Observation': 'View Observation', '# Avalanches:': '2', 'Aspect:': 'N', 'Aspect Range:': 'NE, N', 'Elevation:': '8500 ft', 'Destructive Size:': 'D1.5', 'Type:': 'SS-Soft Slab', 'Slab Thickness:': '25 cm (1 ft)', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Nov 15, 2023 (Estimated)', 'Observer Name': 'Adam Clark', 'Observer type': 'professional', 'Avalanche Summary': 'Observed a few old crowns (D1.5) on steep, unsupported northerly slopes between 6500-7500\'. These crowns were about 10" thick and likely failed during the storm on Wednesday.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}


233
233
{'location': 'Mt. Brown', 'Occurrence Time': 'Not Reported', 'Zone / Region': 'Flathead Range & Glacier NP', 'Observer Affiliation': 'Flathead Avalanche Center', 'Observation Date': 'Nov 28, 2023', 'Associated Observation': 'View Observation', '# Avalanches:': '1', 'Aspect:': 'N', 'Aspect Range:': 'NW, N', 'Elevation:': '6500 ft', 'Vertical Fall:': '1200 ft', 'Destructive Size:': 'D2', 'Trigger:': 'N-Natural', 'Occurrence Date': 'Nov 15, 2023 (Estimated)', 'Observer Name': 'Kevin Oberholser', 'Observer type': 'public', 'Avalanche Summary': 'North facing slope had released naturally, must have run about 1000+. Debris above waterfall @5000 ft.', 'Latitude': '48.402214', 'Longitude': '-114.13365'}

In [271]:
pd.DataFrame(forms).to_csv('/home/christine/Jupyter/snow/data/fac_avalanche_2023-11-01_2024-03-16.csv')